---
permalink: try/task_use_demonode.html 
sidebar: sidebar 
keywords: element demo node, virtual machine, element software, element api, vmware deployment 
summary: Element Demo Node는 Element 소프트웨어의 VMware 가상 머신 버전으로, NetApp HCI 및 SolidFire 제품의 주요 스토리지 기능을 쉽게 시연할 수 있습니다. 
---
= Element Demo Node를 사용하여 스토리지 기능을 사용해 보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://mysupport.netapp.com/site/tools/tool-eula/element-demonode/download["요소 데모 노드"^] 는 Element 소프트웨어의 VMware 가상 머신(VM) 버전이며, NetApp HCI 및 SolidFire 제품의 주요 스토리지 기능을 쉽게 시연할 수 있습니다. 데모 노드를 사용하면 개발자가 물리적 하드웨어 없이도 Element API를 기준으로 코드를 작성할 수 있습니다. OVA 파일로 패키징되어 VMware를 손쉽게 구축할 수 있습니다.



== 지원되는 기능:

Element Demo Node는 데모 및 개발 도구로만 사용할 수 있습니다. 데모 노드를 사용하기 전에 다음과 같은 기능 제한 사항을 숙지하십시오.

* Element Demo Node는 클러스터링을 지원하지 않습니다. 단일 노드 클러스터로만 작동합니다.
* Element 업그레이드는 지원하지 않습니다. 최신 버전의 Element를 시연하려면 새 데모 노드 VM을 설치해야 합니다.
* 이 문서는 스토리지 성능을 입증하기 위한 용도가 아닙니다. 데모 노드에서 관찰된 성능은 물리적 클러스터의 성능을 나타내는 것이 아닙니다.
* NetApp HCI 또는 SolidFire 클러스터에는 데모 노드를 추가할 수 없습니다.
* VRF VLAN은 지원되지 않습니다(표준 태그 VLAN이 지원됨).
* 다중 드라이브 슬라이스 서비스(MDSS)는 지원되지 않습니다.
* Element Demo Node는 VMFS 데이터 저장소에서만 지원됩니다. VVOL은 지원되지 않습니다.
* 하드웨어 기반 구성 및 모니터링 기능은 데모 노드에서 작동하지 않습니다.
* 볼륨당 최대 10개의 스냅샷을 지원합니다.
* 노드/클러스터당 최대 20개의 계정을 지원합니다.
* 계정당 최대 100개의 볼륨을 지원합니다.
* 계정당 최대 200VVol을 지원합니다.
* 최대 볼륨 크기 100GiB를 지원합니다.
* 3000IOPS의 일관된 클러스터 제한을 지원합니다.



NOTE: 기타 모든 Element 소프트웨어 제한 사항이 적용됩니다. 자세한 내용은 최신 Element 소프트웨어 릴리스 노트를 참조하십시오.



== VM 요구 사항

* 총 240GB 용량(VM의 가상 디스크 크기 및 수는 변경할 수 없습니다. 하이퍼바이저를 통해 제공되는 추가 스토리지는 게스트 OS에서 무시됩니다.)
* 60GB 루트 디스크
* 일반 프로비저닝/Eager 제로화(30GB 메타데이터 드라이브 1개 또는 50GB 블록 드라이브 3개) 또는 씬 프로비저닝/Eager 제로화(권장 *)(30GB 메타데이터 드라이브 1개 또는 50GB 블록 드라이브 3개)
* vCPU 2개(전체 예약)
* 16GB RAM(완전 예약)
* 모든 디스크에 단일 HBA, LSI Logic Parallel
* vNIC 2개, 두 vmxnet3(관리 1개, 스토리지 1개)




== 호스트 요구 사항

* Element Demo Node 11.7 VM용 ESXi 6.0 또는 6.5
* Element Demo Node 12.0 및 12.2개의 VM용 ESXi 6.5
* Element Demo Node 12.5 VM용 ESXi 6.7 및 7.0
* 멀티코어 64비트 인텔 ® 아키텍처




== Element 데모 노드를 다운로드합니다

Element Demo Node 소프트웨어는 .ova 파일로 패키지된 VMware 파일 집합입니다.



== VMware ESXi에 Element Demo Node를 설치합니다

VMware ESXi에 Element Demo Node를 설치하는 작업은 다음과 같습니다.

* <<Configure network interfaces>>
* <<Register the demo node on an ESXi server>>
* <<Start the demo node on an ESXi server>>




=== 네트워크 인터페이스를 구성합니다

Element Demo Node에는 두 개의 개별 가상 머신 네트워크가 필요합니다. 하나는 스토리지 트래픽이고 다른 하나는 관리 트래픽입니다. 점보 프레임을 지원하도록 스토리지 네트워크를 구성해야 합니다.



=== ESXi 서버에 데모 노드를 등록합니다

ESXi 서버에 Element Demo Node를 등록하려면 vSphere Client를 사용하여 데모 node.ova 파일을 배포해야 합니다.

.단계
. vSphere Client에 로그인하고 인벤토리 패널에서 ESXi 호스트를 선택합니다.
. File * > * Deploy OVF Template * 을 선택합니다.
+
Deploy OVF Template Wizard가 시작됩니다.

. Select template * 페이지에서 다운로드한 OVA 파일을 찾아 * Open * 을 선택합니다.
. 다음 * 을 선택합니다.
. 이름 및 위치 * 페이지에서 배포된 템플릿의 이름과 위치를 지정한 후 * 다음 * 을 선택합니다.
. 리소스 선택 * 페이지에서 템플릿을 실행할 위치를 찾아 * 다음 * 을 선택합니다.
. 세부 정보를 확인하고 * 다음 * 을 선택합니다.
. 스토리지 선택 페이지에서 가상 머신 파일을 저장할 위치를 선택한 후 * 다음 * 을 선택합니다.
. 네트워크 선택 * 페이지에서 OVA 파일에 사용된 네트워크를 인벤토리에 있는 두 개의 개별 가상 시스템 네트워크에 매핑하고 * 다음 * 을 선택합니다.
. 완료 준비 완료 * 페이지에서 생성 중인 가상 머신에 대한 세부 정보를 확인한 다음 * 마침 * 을 선택합니다.



NOTE: 데모 노드 구축을 완료하는 데 몇 분 정도 걸릴 수 있습니다.



=== ESXi 서버에서 데모 노드를 시작합니다

VMware ESXi 콘솔을 통해 Element에 액세스하려면 데모 노드 VM을 시작해야 합니다.

.단계
. vSphere Client에서 생성한 데모 노드 VM을 선택합니다.
. 이 VM에 대한 세부 정보를 보려면 * 요약 * 탭을 선택하십시오.
. VM을 시작하려면 * Power On * 을 선택합니다.
. 웹 콘솔 시작 * 을 선택합니다.
. TUI를 사용하여 데모 노드를 구성합니다. 자세한 내용은 을 참조하십시오 link:../setup/concept_setup_configure_a_storage_node.html["스토리지 노드를 구성합니다"^].




== 지원을 받는 방법

Element Demo Node는 자원 봉사자 단위로 이용할 수 있습니다. 지원을 받으려면 에 질문을 게시하십시오 https://community.netapp.com/t5/Simulator-Discussions/bd-p/simulator-discussions["Element 데모 노드 포럼"^].



== 자세한 내용을 확인하십시오

* https://www.netapp.com/data-storage/solidfire/documentation/["SolidFire All-Flash 스토리지 리소스 페이지를 참조하십시오"^]
* https://mysupport.netapp.com/site/tools/tool-eula/element-demonode/download["Element Demo Node 다운로드 페이지(로그인 필요)"^]

