---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: 이 섹션에서는 NetApp SolidFire All-Flash 스토리지 시스템의 구성 요소에 대한 권장 업그레이드 순서를 소개합니다. 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= 업그레이드 개요
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: solidfire, cloud, onprem, documentation, help


[role="lead"]
이 섹션에서는 NetApp SolidFire All-Flash 스토리지 시스템의 구성 요소에 대한 권장 업그레이드 순서를 소개합니다. ​



== 시스템 업그레이드 순서

시스템 업그레이드 순서 내용에서는 SolidFire All-Flash 스토리지 시스템의 업그레이드를 완료하는 데 필요한 작업에 대해 설명합니다. 이러한 절차는 격리가 아닌 더 큰 업그레이드 순서의 일부로 수행하는 것이 이상적입니다. 구성 요소 기반 업그레이드 또는 업데이트가 필요한 경우 추가 복잡성을 해결하기 위한 절차 필수 구성 요소를 참조하십시오.

Element 12.3.x용 NetApp SolidFire All-Flash 스토리지 시스템을 업그레이드하려면 다음 순서를 사용하십시오.

* link:task_sf_upgrade_all.html["Element 12.3.x를 위해 NetApp SolidFire All-Flash 스토리지 시스템을 업그레이드하십시오"].




== vCenter Server용 Element 플러그인을 포함한 vSphere 업그레이드 시퀀스

vCenter Server용 Element Plug-in 컨텐츠를 포함한 vSphere 업그레이드 시퀀스에서는 vCenter Server용 Element 플러그인을 다시 설치하는 데 필요한 추가 사전 및 사후 업그레이드 단계에 대해 설명합니다.

vCenter Server용 Element 플러그인을 사용하여 NetApp SolidFire All-Flash 스토리지 시스템에서 vSphere 구성요소를 업그레이드하려면 다음 단계를 따르십시오.

* link:task_sf_upgrade_all_vsphere.html["vCenter Server용 Element 플러그인을 사용하여 NetApp SolidFire 스토리지 시스템용 vSphere 구성요소를 업그레이드하십시오"].


[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

