---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: 모든 NetApp 스토리지 구성요소를 업그레이드하여 구축 후 SolidFire Element 스토리지 시스템을 최신 상태로 유지할 수 있습니다. 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= 업그레이드 순서 개요
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: solidfire, cloud, onprem, documentation, help


[role="lead"]
모든 NetApp 스토리지 구성요소를 순차적으로 업그레이드하여 구축 후 SolidFire Element 스토리지 시스템을 최신 상태로 유지할 수 있습니다.

이러한 구성 요소에는 관리 서비스, HealthTools, NetApp 하이브리드 클라우드 제어, Element 소프트웨어, 관리 노드 및 vCenter Server용 Element 플러그인(설치에 따라 다름)이 포함됩니다.

를 클릭합니다 <<sys_upgrade,시스템 업그레이드 순서>> 내용 은 SolidFire All-Flash 스토리지 시스템 업그레이드를 완료하는 데 필요한 작업에 대해 설명합니다. 이러한 절차는 격리가 아닌 더 큰 업그레이드 순서의 일부로 수행하는 것이 이상적입니다. 구성 요소 기반 업그레이드 또는 업데이트가 필요한 경우 추가 복잡성을 해결하기 위한 절차 필수 구성 요소를 참조하십시오.

를 클릭합니다 link:task_sf_upgrade_all_vsphere.html["vSphere 업그레이드 시퀀스"] vCenter Server용 Element 플러그인 포함 에서는 vCenter Server용 Element 플러그인을 다시 설치하는 데 필요한 추가 사전 및 사후 업그레이드 단계에 대해 설명합니다.

.무엇을 &#8217;필요로 할거야
* 관리 노드 11.3 이상을 실행하고 있습니다. 최신 버전의 관리 노드에는 개별 서비스를 제공하는 모듈식 아키텍처가 있습니다.
+

TIP: 버전을 확인하려면 관리 노드에 로그인하고 로그인 배너에서 Element 버전 번호를 확인합니다. 11.3이 없는 경우 를 참조하십시오 link:task_hcc_upgrade_management_node.html["관리 노드를 업그레이드합니다"].

* 관리 서비스를 버전 2.1.326으로 업그레이드했습니다.
+
NetApp 하이브리드 클라우드 제어를 사용하는 업그레이드는 이전 서비스 번들 버전에서 사용할 수 없습니다.

* 모든 노드의 시스템 시간이 동기화되고 스토리지 클러스터 및 노드에 대해 NTP가 올바르게 구성되었는지 확인했습니다. 각 노드는 시간편중과 관련된 해결되지 않은 클러스터 장애가 없는 노드별 웹 UI('https://[IP address]:442')에서 DNS 이름 서버로 구성되어야 합니다.




== 시스템 업그레이드 순서

Element 12.3.x의 NetApp SolidFire All-Flash 스토리지 시스템을 업그레이드할 때 다음 순서를 사용할 수 있습니다

.단계
. link:task_hcc_update_management_services.html["하이브리드 클라우드 제어에서 관리 서비스를 업데이트합니다"].
+

IMPORTANT: 관리 서비스를 버전 2.16 이상으로 업데이트하고 관리 노드 11.3에서 11.8을 실행 중인 경우 관리 서비스를 업데이트하기 전에 관리 노드 VM의 RAM을 늘려야 합니다.

+

IMPORTANT: Element 소프트웨어를 업그레이드하기 전에 최신 관리 서비스 번들로 업데이트해야 합니다.

. link:task_upgrade_element_latest_healthtools.html["(선택 사항) 최신 HealthTools로 업그레이드하십시오"].
+

NOTE: HealthTools 업그레이드는 실행 중인 관리 노드 및 Element 소프트웨어가 11.1 이전 버전인 경우에만 필요합니다. NetApp 하이브리드 클라우드 제어를 사용하여 Element 업그레이드를 수행하는 데 HealthTools가 필요하지 않습니다.

. link:task_hcc_upgrade_element_prechecks.html["스토리지를 업그레이드하기 전에 Element 스토리지 상태 점검을 실행합니다"].
. link:task_hcc_upgrade_element_software.html["Element 소프트웨어 및 스토리지 펌웨어를 업그레이드합니다"].
. link:task_hcc_upgrade_storage_firmware.html["(선택 사항) Element 스토리지 펌웨어만 업그레이드합니다"].
+

NOTE: 주요 릴리즈 외부에서 새 스토리지 펌웨어를 업그레이드할 수 있는 경우 이 작업을 수행할 수 있습니다.

. link:task_hcc_upgrade_management_node.html["(선택 사항) 관리 노드를 업그레이드합니다"].
+

NOTE: 스토리지 클러스터에서 Element 소프트웨어를 업그레이드하는 데 관리 노드 운영 체제를 더 이상 업그레이드할 필요가 없습니다. 관리 노드가 버전 11.3 이상인 경우 NetApp 하이브리드 클라우드 제어를 사용하여 관리 서비스를 최신 버전으로 업그레이드하여 Element 업그레이드를 수행할 수 있습니다. 보안 문제 해결과 같은 다른 이유로 관리 노드 운영 체제를 업그레이드하려면 시나리오에 따라 관리 노드 업그레이드 절차를 따르십시오.

. link:task_vcp_upgrade_plugin.html["vCenter Server용 Element 플러그인을 업그레이드합니다"].


[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]

