---
permalink: concepts/concept_intro_clusters.html 
sidebar: sidebar 
keywords: element, solidfire, cluster, what is, authoritative  cluster, rule of thirds, stranded capacity, storage efficiency, storage cluster quorum 
summary: 클러스터는 SolidFire 스토리지 시스템의 허브이며 노드 모음으로 구성됩니다. SolidFire 스토리지 효율성을 실현하려면 하나의 클러스터에 최소 4개의 노드가 있어야 합니다. 클러스터는 네트워크에 단일 논리 그룹으로 표시되며, 블록 스토리지로 액세스할 수 있습니다. 
---
= 클러스터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터는 SolidFire 스토리지 시스템의 허브이며 노드 모음으로 구성됩니다. SolidFire 스토리지 효율성을 실현하려면 하나의 클러스터에 최소 4개의 노드가 있어야 합니다. 클러스터는 네트워크에 단일 논리 그룹으로 표시되며, 블록 스토리지로 액세스할 수 있습니다.

새 클러스터를 생성하면 클러스터의 통신 소유자로 노드가 초기화되고 클러스터의 각 노드에 대한 네트워크 통신이 설정됩니다. 이 프로세스는 각 새 클러스터에 대해 한 번만 수행됩니다. Element UI 또는 API를 사용하여 클러스터를 생성할 수 있습니다.

노드를 추가하여 클러스터를 확장할 수 있습니다. 새 노드를 추가할 경우 서비스가 중단되지 않으며 클러스터는 새 노드의 성능과 용량을 자동으로 사용합니다.

관리자와 호스트는 가상 IP 주소를 사용하여 클러스터에 액세스할 수 있습니다. 클러스터의 모든 노드에서 가상 IP 주소를 호스팅할 수 있습니다. MVIP(Management Virtual IP)를 사용하면 1GbE 연결을 통해 클러스터를 관리할 수 있고 SVIP(Storage Virtual IP)를 통해 10GbE 연결을 통해 스토리지에 대한 호스트 액세스가 가능합니다. 이러한 가상 IP 주소는 SolidFire 클러스터의 크기나 구성과 상관없이 일관된 연결을 지원합니다. 가상 IP 주소를 호스팅하는 노드에 장애가 발생하면 클러스터의 다른 노드에서 가상 IP 주소를 호스팅하기 시작합니다.


NOTE: Element 버전 11.0부터는 노드의 관리 네트워크에 대해 IPv4, IPv6 또는 두 주소를 모두 사용하여 노드를 구성할 수 있습니다. IPv6을 지원하지 않는 관리 노드 11.3 이상을 제외하고 스토리지 노드와 관리 노드 모두에 적용됩니다. 클러스터를 생성할 때 단일 IPv4 또는 IPv6 주소만 MVIP에 사용할 수 있으며 모든 노드에서 해당 주소 유형을 구성해야 합니다.

.클러스터에 추가 정보
* <<Authoritative storage clusters>>
* <<Rule of thirds>>
* <<Stranded capacity>>
* <<Storage efficiency>>
* <<Storage cluster quorum>>




== 권한 있는 스토리지 클러스터

신뢰할 수 있는 스토리지 클러스터는 NetApp 하이브리드 클라우드 제어에서 사용자를 인증하는 데 사용하는 스토리지 클러스터입니다.

관리 노드에 스토리지 클러스터가 하나만 있는 경우 신뢰할 수 있는 클러스터입니다. 관리 노드에 둘 이상의 스토리지 클러스터가 있는 경우 이러한 클러스터 중 하나가 권한 있는 클러스터로 할당되고 해당 클러스터의 사용자만 NetApp 하이브리드 클라우드 제어에 로그인할 수 있습니다. 어느 클러스터가 권위 있는 클러스터인지 확인하려면 Get/mnode/about API를 사용할 수 있습니다. 이에 대한 응답으로 token_url 필드의 IP 주소는 권한 있는 스토리지 클러스터의 관리 가상 IP 주소(MVIP)입니다. NetApp 하이브리드 클라우드 제어에 권한 있는 클러스터에 없는 사용자로 로그인하려고 하면 로그인 시도가 실패합니다.

많은 NetApp 하이브리드 클라우드 제어 기능은 여러 스토리지 클러스터에서 작동하도록 설계되었지만 인증과 권한 부여에는 제한이 있습니다. 인증 및 권한 부여에 대한 제한 사항은 권한 있는 클러스터의 사용자가 다른 스토리지 클러스터의 사용자가 아니더라도 NetApp 하이브리드 클라우드 제어에 연결된 다른 클러스터에 대한 작업을 실행할 수 있다는 것입니다. 여러 스토리지 클러스터를 관리하기 전에 권한 있는 클러스터에 정의된 사용자가 동일한 권한을 가진 다른 모든 스토리지 클러스터에 정의되어 있는지 확인해야 합니다.

여러 스토리지 클러스터를 관리하기 전에 권한 있는 클러스터에 정의된 사용자가 동일한 권한을 가진 다른 모든 스토리지 클러스터에 정의되어 있는지 확인해야 합니다. 에서 사용자를 관리할 수 있습니다 link:../storage/concept_system_manage_manage_cluster_administrator_users.html["Element 소프트웨어 사용자 인터페이스"].

을 참조하십시오 link:../mnode/task_mnode_manage_storage_cluster_assets.html["스토리지 클러스터 자산을 생성하고 관리합니다"] 관리 노드 스토리지 클러스터 자산을 사용하는 방법에 대한 자세한 내용은 섹션을 참조하십시오.



== 3분의 규칙

NetApp SolidFire 스토리지 클러스터에서 스토리지 노드 유형을 혼합하여 사용할 경우 단일 스토리지 노드에 총 스토리지 클러스터 용량의 33% 이상을 포함할 수 없습니다.



== 고립된 용량

새로 추가된 노드가 전체 클러스터 용량의 50% 이상을 차지하는 경우 이 노드의 일부 용량을 사용할 수 없게 되어 용량 규칙을 준수합니다("고립됨"). 이는 스토리지 용량이 더 추가될 때까지 유지됩니다. 용량 규칙에 불복종하는 매우 큰 노드가 추가되면 이전에 고립된 노드는 더 이상 고립되지 않고 새로 추가된 노드는 고립됩니다. 이러한 상황이 발생하지 않도록 용량을 항상 쌍으로 추가해야 합니다. 노드가 고립되면 적절한 클러스터 장애가 throw됩니다.



== 스토리지 효율성

NetApp SolidFire 스토리지 클러스터는 중복제거, 압축 및 씬 프로비저닝을 사용하여 볼륨 저장에 필요한 물리적 스토리지 양을 줄입니다.

* * 압축 *
+
압축은 압축 그룹에 데이터 블록을 결합하여 볼륨에 필요한 물리적 스토리지의 양을 줄이며, 각 블록이 단일 블록으로 저장됩니다.

* * 데이터 중복 제거 *
+
중복 제거는 중복 데이터 블록을 제거하여 볼륨에 필요한 물리적 스토리지 양을 줄입니다.

* * 씬 프로비저닝 *
+
씬 프로비저닝된 볼륨 또는 LUN은 스토리지가 미리 예약되지 않은 볼륨입니다. 대신 필요에 따라 스토리지가 동적으로 할당됩니다. 볼륨 또는 LUN의 데이터가 삭제되면 사용 가능한 공간이 스토리지 시스템으로 다시 해제됩니다





== 스토리지 클러스터 쿼럼입니다

Element 소프트웨어는 선택한 노드에서 스토리지 클러스터를 생성하며, 이 노드는 클러스터 구성의 복제된 데이터베이스를 유지 관리합니다. 클러스터 복원력을 위해 쿼럼을 유지하려면 클러스터 앙상블에 최소한 3개의 노드가 필요합니다.
