---
permalink: concepts/concept_solidfire_concepts_nodes.html 
sidebar: sidebar 
keywords: what is, node, management node, storage node, fibre channel, state, pending, active 
summary: 노드는 블록 스토리지 또는 컴퓨팅 리소스로 액세스할 수 있도록 클러스터로 그룹화된 하드웨어입니다. 
---
= 노드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드는 블록 스토리지 및 컴퓨팅 기능을 제공하기 위해 클러스터로 그룹화된 하드웨어 또는 가상 리소스입니다.

NetApp Element 소프트웨어는 클러스터에 대한 다양한 노드 역할을 정의합니다. 노드 역할의 유형은 다음과 같습니다.

* <<관리 노드>>
* <<스토리지 노드>>
* <<Fibre Channel 노드>>


<<노드 작업 상태입니다,노드 상태>> 클러스터 연결에 따라 다릅니다.



== 관리 노드

관리 노드는 모니터링 및 원격 측정을 포함하여 시스템 서비스를 업그레이드 및 제공하고, 클러스터 자산 및 설정을 관리하고, 시스템 테스트 및 유틸리티를 실행하고, 문제 해결을 위해 NetApp Support 액세스를 지원하는 데 사용되는 가상 머신입니다.link:../concepts/concept_intro_management_node.html["자세한 정보"]



== 스토리지 노드

SolidFire 스토리지 노드는 Bond10G 네트워크 인터페이스를 통해 서로 통신하는 드라이브 모음이 포함된 서버입니다. 노드의 드라이브에는 데이터 스토리지 및 데이터 관리를 위한 블록 및 메타데이터 공간이 포함되어 있습니다. 각 노드에는 NetApp Element 소프트웨어의 출하 시 이미지가 포함되어 있습니다.

스토리지 노드의 특징은 다음과 같습니다.

* 각 노드의 이름은 고유합니다. 관리자가 노드 이름을 지정하지 않은 경우 기본적으로 SF-XXXX가 사용됩니다. 여기서 XXXX는 시스템에서 생성되는 4개의 임의 문자입니다.
* 각 노드에는 전반적인 시스템 성능을 향상시키고 쓰기 지연 시간을 줄이기 위해 고유한 고성능 비휘발성 랜덤 액세스 메모리(NVRAM) 쓰기 캐시가 있습니다.
* 각 노드는 이중화 및 성능을 위한 2개의 독립적인 링크가 있는 스토리지 및 관리 라는 2개의 네트워크에 연결됩니다. 각 노드에는 각 네트워크의 IP 주소가 필요합니다.
* 새 스토리지 노드로 클러스터를 생성하거나 기존 클러스터에 스토리지 노드를 추가하여 스토리지 용량과 성능을 높일 수 있습니다.
* 서비스를 중단하지 않고 언제든지 클러스터에서 노드를 추가하거나 제거할 수 있습니다.




== Fibre Channel 노드

SolidFire 파이버 채널 노드는 파이버 채널 클라이언트에 연결할 수 있는 파이버 채널 스위치에 대한 연결을 제공합니다. 파이버 채널 노드는 파이버 채널과 iSCSI 프로토콜 간 프로토콜 변환기 역할을 합니다. 이를 통해 새로운 또는 기존 SolidFire 클러스터에 파이버 채널 연결을 추가할 수 있습니다.

Fibre Channel 노드의 특징은 다음과 같습니다.

* 파이버 채널 스위치는 패브릭의 상태를 관리하여 최적화된 상호 연결을 제공합니다.
* 두 포트 간의 트래픽은 스위치만 통과하며 다른 포트로 전송되지 않습니다.
* 포트 장애는 격리되며 다른 포트의 작동에 영향을 주지 않습니다.
* 여러 포트 쌍이 Fabric에서 동시에 통신할 수 있습니다.




== 노드 작업 상태입니다

[role="lead"]
노드는 구성 수준에 따라 여러 상태 중 하나일 수 있습니다.

* * 이용 가능 *
+
노드에 연결된 클러스터 이름이 없으며 아직 클러스터의 일부가 아닙니다.

* * 보류 중 *
+
노드가 구성되고 지정된 클러스터에 추가될 수 있습니다.

+
노드를 액세스하는 데 인증이 필요하지 않습니다.

* * 보류 중 활성 *
+
시스템이 노드에 호환되는 Element 소프트웨어를 설치하는 중입니다. 완료되면 노드가 활성 상태로 이동합니다.

* * 활성 *
+
노드가 클러스터에 사용되고 있습니다.

+
노드를 수정하려면 인증이 필요합니다.



이러한 각 상태에서 일부 필드는 읽기 전용입니다.

[discrete]
== 자세한 내용을 확인하십시오

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

