---
permalink: concepts/concept_solidfire_concepts_security.html 
sidebar: sidebar 
keywords: solidfire security, element security, encryption at rest, software encryption at rest, external key management, fips 140-2, mfa 
summary: NetApp Element 소프트웨어를 사용하면 업계 표준 보안 프로토콜을 통해 데이터가 보호됩니다. 
---
= 보안
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire All-Flash 스토리지 시스템을 사용하면 업계 표준 보안 프로토콜을 통해 데이터가 보호됩니다.



== 유휴 데이터 암호화(하드웨어)

스토리지 노드의 모든 드라이브는 드라이브 레벨에서 AES 256비트 암호화를 사용하여 암호화할 수 있습니다. 각 드라이브에는 드라이브가 처음 초기화될 때 생성되는 자체 암호화 키가 있습니다. 암호화 기능을 활성화하면 클러스터 전체의 암호가 생성되고 암호 청크가 클러스터의 모든 노드에 분산됩니다. 전체 암호를 저장하는 단일 노드는 없습니다. 그런 다음 암호를 사용하여 드라이브에 대한 모든 액세스를 암호로 보호합니다. 드라이브 잠금을 해제하려면 암호가 필요하며 드라이브에서 전원을 제거하거나 드라이브가 잠겨 있지 않는 한 필요하지 않습니다.

link:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["저장된 하드웨어 암호화 기능 활성화"^] 클러스터의 성능 또는 효율에는 영향을 미치지 않습니다. Element API 또는 Element UI를 사용하여 클러스터 구성에서 암호화 지원 드라이브 또는 노드를 제거하면 드라이브에서 유휴 암호화가 비활성화됩니다. 드라이브를 제거한 후에는 'ecureEraseDrives' API 방식을 사용하여 드라이브를 안전하게 지울 수 있습니다. 물리적 드라이브 또는 노드가 강제로 제거되면 데이터가 클러스터 전체 암호와 드라이브의 개별 암호화 키에 의해 보호됩니다.



== 유휴 데이터 암호화(소프트웨어)

또 다른 유형의 유휴 암호화 소프트웨어 암호화 기능으로 스토리지 클러스터의 SSD에 기록된 모든 데이터를 암호화할 수 있습니다. link:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["활성화 시"^], 기록된 모든 데이터를 암호화하고 소프트웨어에서 자동으로 읽은 모든 데이터를 해독합니다. 저장된 소프트웨어 암호화는 SED(Self-Encrypting Drive) 구현을 하드웨어에 미러링하여 SED가 없는 경우 데이터 보안을 제공합니다.


NOTE: 모든 SolidFire 엔터프라이즈 SDS 노드에서 유휴 소프트웨어 암호화가 기본적으로 설정됩니다. 저장 시 소프트웨어 암호화는 SED(자체 암호화 드라이브)가 포함되지 않은 SolidFire 엔터프라이즈 SDS 노드에서 데이터 보안 암호화의 기본 소프트웨어 계층을 제공합니다.


WARNING: SolidFire All-Flash 스토리지 클러스터의 경우, 클러스터 생성 중에 유휴 소프트웨어 암호화를 활성화해야 하며, 클러스터를 생성한 후에는 비활성화할 수 없습니다.

소프트웨어 및 하드웨어 기반의 유휴 암호화 모두 독립적으로 사용하거나 함께 사용할 수 있습니다.



== 외부 키 관리

타사 KMIP 호환 키 관리 서비스(KMS)를 사용하여 스토리지 클러스터 암호화 키를 관리하도록 Element 소프트웨어를 구성할 수 있습니다. 이 기능을 활성화하면 스토리지 클러스터의 클러스터 전체 드라이브 액세스 암호 암호화 키가 사용자가 지정한 KMS에 의해 관리됩니다.

요소는 다음과 같은 주요 관리 서비스를 사용할 수 있습니다.

* Gemalto SafeNet KeySecure를 참조하십시오
* SafeNet AT KeySecure
* HyTrust 키컨트롤
* Vormetric Data Security Manager를 참조하십시오
* IBM Security Key Lifecycle Manager를 참조하십시오


외부 키 관리 구성에 대한 자세한 내용은 을 참조하십시오 link:../storage/concept_system_manage_key_get_started_with_external_key_management.html["외부 키 관리를 시작합니다"] 문서화:



== 다중 요소 인증

다중 요소 인증(MFA)을 사용하면 사용자가 로그인할 때 NetApp Element 웹 UI 또는 스토리지 노드 UI를 사용하여 인증하기 위해 여러 유형의 증거를 제시하도록 할 수 있습니다. 기존 사용자 관리 시스템 및 ID 공급자와 통합되는 로그인에 대해 다중 요소 인증만 허용하도록 Element를 구성할 수 있습니다. 기존 SAML 2.0 ID 공급자와 통합되도록 Element를 구성할 수 있습니다. 이 공급자는 암호 및 텍스트 메시지, 암호 및 전자 메일 메시지 또는 기타 방법과 같은 여러 인증 체계를 적용할 수 있습니다.

다중 요소 인증을 ADFS(Microsoft Active Directory Federation Services) 및 Shibboleth와 같은 일반적인 SAML 2.0 호환 ID 공급자(IdP)와 페어링할 수 있습니다.

MFA를 구성하려면 를 참조하십시오 link:../storage/concept_system_manage_mfa_enable_multi_factor_authentication.html["다중 요소 인증을 사용합니다"] 문서화:



== FIPS 140-2 - HTTPS 및 유휴 데이터 암호화를 지원합니다

NetApp SolidFire 스토리지 클러스터는 암호화 모듈에 대한 FIPS(Federal Information Processing Standard) 140-2 요구사항을 준수하는 암호화를 지원합니다. SolidFire 클러스터에서 FIPS 140-2 규정 준수를 활성화하여 HTTPS 통신과 드라이브 암호화를 둘 다 사용할 수 있습니다.

클러스터에서 FIPS 140-2 운영 모드를 활성화하면 클러스터는 NetApp CSM(Cryptographic Security Module)을 활성화하고 HTTPS를 통해 NetApp Element UI 및 API에 연결되는 모든 통신에 FIPS 140-2 Level 1 인증 암호화를 사용합니다. FIPS 140-2 HTTPS 암호화를 사용하려면 "EnableFeature" Element API와 함께 "FIPS" 매개 변수를 사용합니다. FIPS 호환 하드웨어가 있는 스토리지 클러스터에서 "FipsDrives" 매개 변수가 있는 "EnableFeature" Element API를 사용하여 유휴 데이터에 대해 FIPS 드라이브 암호화를 설정할 수도 있습니다.

FIPS 140-2 암호화를 위한 새 스토리지 클러스터를 준비하는 방법에 대한 자세한 내용은 을 참조하십시오 link:../storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["FIPS 드라이브를 지원하는 클러스터를 생성합니다"].

미리 준비된 기존 클러스터에서 FIPS 140-2 를 사용하도록 설정하는 방법에 대한 자세한 내용은 을(를) 참조하십시오 link:../api/reference_element_api_enablefeature.html["EnableFeature 요소 API입니다"].



== 를 참조하십시오

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

