---
permalink: storage/concept_prereq_switch_configuration_for_solidfire_clusters.html 
sidebar: sidebar 
keywords: cluster switch configuration, best practices for switch configuration, optimal storage performance, node hardware, traffic, cluster, Element software, best practices, switches, switch requirements, storage, performance, storage performance 
summary: NetApp Element 소프트웨어 시스템에는 최적의 스토리지 성능을 위한 특정 스위치 요구사항 및 모범 사례가 있습니다. 
---
= Element 소프트웨어를 실행하는 클러스터의 스위치 구성
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element 소프트웨어 시스템에는 최적의 스토리지 성능을 위한 특정 스위치 요구사항 및 모범 사례가 있습니다.

스토리지 노드에는 iSCSI 스토리지 서비스 및 노드 내부 클러스터 서비스 통신을 위해 특정 노드 하드웨어에 따라 10 또는 25GbE 이더넷 스위치가 필요합니다. 1GbE 스위치는 다음과 같은 트래픽 유형에 사용할 수 있습니다.

* 클러스터 및 노드 관리
* 노드 간 클러스터 내 관리 트래픽
* 클러스터 노드와 관리 노드 가상 머신 간의 트래픽입니다


|===


 a| 
* 모범 사례: * 클러스터 트래픽에 대한 이더넷 스위치를 구성할 때 다음 모범 사례를 구현해야 합니다.

* 클러스터의 비스토리지 트래픽의 경우 고가용성 및 로드 공유를 제공하기 위해 1GbE 스위치 쌍을 구축합니다.
* 스토리지 네트워크 스위치에서 스위치를 쌍으로 구축하고 점보 프레임(MTU 크기 9216바이트)을 구성 및 활용합니다. 이렇게 하면 설치가 성공적으로 이루어지므로 조각화된 패킷으로 인한 스토리지 네트워크 오류가 제거됩니다.


|===
요소 배포에는 다음 트래픽 유형에 대해 하나 이상의 네트워크 세그먼트가 필요합니다.

* 관리
* 스토리지/데이터


NetApp H 시리즈 스토리지 노드 모델 및 계획된 케이블 연결 구성에 따라 별도의 스위치를 사용하여 이러한 네트워크를 물리적으로 분리하거나 VLAN을 사용하여 네트워크를 논리적으로 분리할 수 있습니다. 그러나 대부분의 구축 환경에서는 VLAN을 사용하여 이러한 네트워크를 논리적으로 분리해야 합니다.

스토리지 노드는 구축 전, 구축 중, 구축 후 통신할 수 있어야 합니다.

스토리지 노드에 대해 별도의 관리 네트워크를 구축하는 경우 이러한 관리 네트워크 간에 네트워크 경로가 있는지 확인하십시오. 이러한 네트워크에는 게이트웨이가 할당되어 있어야 하며 게이트웨이 사이에 경로가 있어야 합니다. 각 새 노드에 노드와 관리 네트워크 간의 통신을 용이하게 하기 위한 게이트웨이가 할당되어 있는지 확인합니다.

NetApp Element의 요구 사항은 다음과 같습니다.

* NetApp H 시리즈 스토리지 노드에 연결된 모든 스위치 포트는 스패닝 트리 에지 포트로 구성되어야 합니다.
+
** Cisco 스위치에서 스위치 모델, 소프트웨어 버전 및 포트 유형에 따라 다음 명령 중 하나를 사용하여 이 작업을 수행할 수 있습니다.
+
*** 패닝 트리 포트형 모서리
*** 패닝 트리 포트형 에지 트렁크
*** 패닝 트리 portfast
*** 패닝 트리 portfast 트렁크


** Mellanox 스위치에서 '패닝 트리 포트 유형 에지' 명령을 사용하여 이 작업을 수행할 수 있습니다.


* 스토리지 트래픽을 처리하는 스위치는 포트당 10GbE 이상의 속도를 지원해야 합니다(포트당 최대 25GbE 지원).
* 관리 트래픽을 처리하는 스위치는 포트당 1GbE 이상의 속도를 지원해야 합니다.
* 스토리지 트래픽을 처리하는 스위치 포트에서 점보 프레임을 구성해야 합니다. 호스트가 성공적인 설치를 위해 9000바이트 패킷을 엔드투엔드로 보낼 수 있어야 합니다.
* 모든 스토리지 노드 간 왕복 네트워크 지연 시간이 2ms를 초과해서는 안 됩니다.


일부 노드는 전용 관리 포트를 통해 추가적인 대역외 관리 기능을 제공합니다. NetApp H300S, H500S 및 H700S 노드도 포트 A를 통해 IPMI에 액세스할 수 있습니다 모범 사례로서, 사용자 환경의 모든 노드에 대해 대역외 관리를 구성하여 원격 관리를 용이하게 해야 합니다.



== 를 참조하십시오

* https://docs.netapp.com/us-en/hci/docs/hci_prereqs_network_switch.html["NetApp HCI 네트워크 및 스위치 요구 사항"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

