---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: SolidFire 스토리지 시스템의 클러스터 관리자 계정을 관리할 수 있습니다. 사용 가능한 클러스터 관리자 관리 기능에는 클러스터 관리자 계정 생성, 삭제 및 편집, 클러스터 관리자 암호 변경, 사용자에 대한 시스템 액세스 관리를 위한 LDAP 설정 구성 등이 있습니다. 
---
= 클러스터 관리자 사용자 계정을 관리합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 스토리지 시스템의 클러스터 관리자 계정은 클러스터 관리자 계정을 생성, 삭제 및 편집하고, 클러스터 관리자 암호를 변경하고, 사용자에 대한 시스템 액세스를 관리하도록 LDAP 설정을 구성하여 관리할 수 있습니다.



== 스토리지 클러스터 관리자 계정 유형입니다

NetApp Element 소프트웨어를 실행하는 스토리지 클러스터에 존재할 수 있는 관리자 계정은 운영 클러스터 관리자 계정과 클러스터 관리자 계정 두 가지입니다.

* * 기본 클러스터 관리자 계정 *
+
이 관리자 계정은 클러스터를 생성할 때 생성됩니다. 이 계정은 클러스터에 대한 최고 수준의 액세스 권한을 가진 기본 관리 계정입니다. 이 계정은 Linux 시스템의 루트 사용자와 유사합니다. 이 관리자 계정의 암호를 변경할 수 있습니다.

* * 클러스터 관리자 계정 *
+
클러스터 관리자 계정에 제한된 범위의 관리 액세스 권한을 부여하여 클러스터 내에서 특정 작업을 수행할 수 있습니다. 각 클러스터 관리자 계정에 할당된 자격 증명은 스토리지 시스템 내에서 API 및 Element UI 요청을 인증하는 데 사용됩니다.




NOTE: 노드별 UI를 통해 클러스터의 활성 노드에 액세스하려면 로컬(LDAP가 아닌) 클러스터 관리자 계정이 필요합니다. 아직 클러스터에 속하지 않은 노드에 액세스하려면 계정 자격 증명이 필요하지 않습니다.



== 클러스터 관리자의 세부 정보를 봅니다

. 클러스터 전체(LDAP가 아닌) 클러스터 관리자 계정을 생성하려면 다음 작업을 수행합니다.
+
.. 사용자 * > * 클러스터 관리자 * 를 클릭합니다.


. 사용자 탭의 클러스터 관리자 페이지에서 다음 정보를 볼 수 있습니다.
+
** * ID *: 클러스터 관리자 계정에 할당된 순차 번호입니다.
** * 사용자 이름 *: 클러스터 관리자 계정을 만들 때 지정한 이름입니다.
** * 액세스 *: 사용자 계정에 할당된 사용자 권한. 가능한 값:
+
*** 읽기
*** 보고
*** 노드
*** 드라이브
*** 볼륨
*** 계정
*** 클러스터 관리자
*** 관리자




+

NOTE: 모든 권한은 관리자 액세스 유형에 사용할 수 있습니다.

+
** * 유형 *: 클러스터 관리자의 유형입니다. 가능한 값:
+
*** 클러스터
*** LDAP를 지원합니다


** * 특성 *: 클러스터 관리자 계정이 Element API를 사용하여 생성된 경우 이 열에는 해당 방법을 사용하여 설정된 모든 이름 값 쌍이 표시됩니다.
+
을 참조하십시오 link:../api/index.html["NetApp Element 소프트웨어 API 참조서"].







== 클러스터 관리자 계정을 생성합니다

스토리지 시스템의 특정 영역에 대한 액세스를 허용하거나 제한할 수 있는 권한이 있는 새 클러스터 관리자 계정을 생성할 수 있습니다. 클러스터 관리자 계정 권한을 설정하면 시스템은 클러스터 관리자에게 할당하지 않은 모든 권한에 대해 읽기 전용 권한을 부여합니다.

LDAP 클러스터 관리자 계정을 생성하려면 시작하기 전에 클러스터에 LDAP가 구성되어 있는지 확인하십시오.

link:task_system_manage_enable_ldap_authentication.html["Element 사용자 인터페이스를 사용하여 LDAP 인증을 설정합니다"]

나중에 보고, 노드, 드라이브, 볼륨, 계정 및 클러스터 레벨 액세스를 지원합니다. 사용 권한을 설정하면 시스템에서 해당 수준에 대한 쓰기 권한을 할당합니다. 시스템은 사용자가 선택하지 않은 수준에 대해 관리자 사용자에게 읽기 전용 액세스 권한을 부여합니다.

나중에 시스템 관리자가 생성한 모든 클러스터 관리자 사용자 계정을 제거할 수도 있습니다. 클러스터를 생성할 때 생성한 운영 클러스터 관리자 계정은 제거할 수 없습니다.

. 클러스터 전체(LDAP가 아닌) 클러스터 관리자 계정을 생성하려면 다음 작업을 수행합니다.
+
.. 사용자 * > * 클러스터 관리자 * 를 클릭합니다.
.. Create Cluster Admin * 을 클릭합니다.
.. Cluster * 사용자 유형을 선택합니다.
.. 계정의 사용자 이름과 암호를 입력하고 암호를 확인합니다.
.. 계정에 적용할 사용자 권한을 선택합니다.
.. 최종 사용자 사용권 계약에 동의하려면 확인란을 선택합니다.
.. Create Cluster Admin * 을 클릭합니다.


. LDAP 디렉토리에 클러스터 관리자 계정을 생성하려면 다음 작업을 수행하십시오.
+
.. Cluster * > * LDAP * 를 클릭합니다.
.. LDAP 인증이 활성화되어 있는지 확인합니다.
.. 사용자 인증 테스트 * 를 클릭하고 사용자에게 표시되는 고유 이름 또는 사용자가 구성원인 그룹 중 하나를 복사하여 나중에 붙여 넣을 수 있습니다.
.. 사용자 * > * 클러스터 관리자 * 를 클릭합니다.
.. Create Cluster Admin * 을 클릭합니다.
.. LDAP 사용자 유형을 선택합니다.
.. 고유 이름 필드에서 텍스트 상자의 예제를 따라 사용자 또는 그룹의 전체 고유 이름을 입력합니다. 또는 이전에 복사한 고유 이름에서 붙여 넣습니다.
+
고유 이름이 그룹의 일부인 경우 LDAP 서버에서 해당 그룹의 구성원인 사용자는 이 admin 계정의 권한을 갖게 됩니다.

+
LDAP 클러스터 관리자 사용자 또는 그룹을 추가하려면 사용자 이름의 일반 형식은 ""LDAP:<전체 고유 이름>""입니다.

.. 계정에 적용할 사용자 권한을 선택합니다.
.. 최종 사용자 사용권 계약에 동의하려면 확인란을 선택합니다.
.. Create Cluster Admin * 을 클릭합니다.






== 클러스터 관리자 권한을 편집합니다

보고, 노드, 드라이브, 볼륨, 계정 및 클러스터 레벨 액세스를 지원합니다. 사용 권한을 설정하면 시스템에서 해당 수준에 대한 쓰기 권한을 할당합니다. 시스템은 사용자가 선택하지 않은 수준에 대해 관리자 사용자에게 읽기 전용 액세스 권한을 부여합니다.

. 사용자 * > * 클러스터 관리자 * 를 클릭합니다.
. 편집할 클러스터 관리자의 작업 아이콘을 클릭합니다.
. 편집 * 을 클릭합니다.
. 계정에 적용할 사용자 권한을 선택합니다.
. 변경 내용 저장 * 을 클릭합니다.




== 클러스터 관리자 계정의 암호를 변경합니다

Element UI를 사용하여 클러스터 관리자 암호를 변경할 수 있습니다.

. 사용자 * > * 클러스터 관리자 * 를 클릭합니다.
. 편집할 클러스터 관리자의 작업 아이콘을 클릭합니다.
. 편집 * 을 클릭합니다.
. 암호 변경 필드에 새 암호를 입력하고 확인합니다.
. 변경 내용 저장 * 을 클릭합니다.




== 자세한 내용을 확인하십시오

* link:task_system_manage_enable_ldap_authentication.html["Element 사용자 인터페이스를 사용하여 LDAP 인증을 설정합니다"]
* link:concept_system_manage_manage_ldap.html["LDAP를 해제합니다"]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

