---
permalink: storage/concept_troubleshoot_drives.html 
sidebar: sidebar 
keywords: troubleshoot, drives, ssd, swappable, solid-state drives 
summary: '장애가 발생한 SSD\(Solid State Drive)를 교체 드라이브로 교체할 수 있습니다. SolidFire 스토리지 노드용 SSD는 핫 스왑이 가능합니다. SSD에 장애가 발생했다고 의심되는 경우 NetApp 지원 팀에 문의하여 장애를 확인하고 적절한 해결 절차를 안내합니다. NetApp Support는 또한 귀사와 협력하여 서비스 수준 계약에 따라 교체 드라이브를 제공합니다.' 
---
= 드라이브 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
오류가 발생한 SSD(Solid-State Drive)를 교체 드라이브로 교체할 수 있습니다. SolidFire 스토리지 노드용 SSD는 핫 스왑이 가능합니다. SSD에 장애가 발생했다고 의심되는 경우 NetApp 지원 팀에 문의하여 장애를 확인하고 적절한 해결 절차를 안내합니다. NetApp Support는 또한 귀사와 협력하여 서비스 수준 계약에 따라 교체 드라이브를 제공합니다.

이 경우 어떻게 스왑이 가능하면 활성 노드에서 장애가 발생한 드라이브를 제거하고 NetApp에서 새 SSD 드라이브로 교체할 수 있습니다. 활성 클러스터에서 장애가 발생하지 않은 드라이브를 제거하는 것은 권장되지 않습니다.

장애가 발생할 경우 드라이브를 즉시 교체할 수 있도록 NetApp Support에서 제안한 현장 예비 부품을 유지보수해야 합니다.


NOTE: 테스트를 위해 노드에서 드라이브를 잡아당겨 드라이브 장애를 시뮬레이트하는 경우 드라이브를 드라이브 슬롯에 다시 삽입하기 전에 30초 정도 기다려야 합니다.

드라이브에 장애가 발생하면 이중 Helix는 클러스터의 나머지 노드에 데이터를 재배포합니다. Element 소프트웨어는 동일한 노드에 있는 두 개의 데이터 복사본을 보호하므로 동일한 노드에서 여러 드라이브 장애가 발생해도 문제가 되지 않습니다. 드라이브 장애가 발생하면 다음과 같은 이벤트가 발생합니다.

* 데이터가 드라이브에서 마이그레이션됩니다.
* 전체 클러스터 용량은 드라이브 용량에 따라 감소합니다.
* 이중 Helix 데이터 보호로 2개의 유효한 데이터 복사본이 보장됩니다.



IMPORTANT: SolidFire 스토리지 시스템은 데이터를 마이그레이션할 스토리지 양이 부족한 경우 드라이브 제거를 지원하지 않습니다.



== 를 참조하십시오

* xref:task_troubleshoot_remove_failed_drives.adoc[클러스터에서 장애가 발생한 드라이브를 제거합니다]
* xref:concept_troubleshoot_basic_mdss_drive_troubleshooting.adoc[기본 MDSS 드라이브 문제 해결]
* xref:task_troubleshoot_remove_mdss_drives.adoc[MDSS 드라이브를 제거합니다]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2844771["SolidFire 스토리지 노드의 드라이브 교체"]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2846859["H600S 시리즈 스토리지 노드의 드라이브 교체"]
* link:../hardware/concept_h410s_h610s_info.html["H410S 및 H610S 하드웨어 정보"]
* link:../hardware/concept_sfseries_info.html["SF-시리즈 하드웨어 정보"]

