---
permalink: storage/concept_data_manage_vvol_work_virtual_volumes.html 
sidebar: sidebar 
keywords: virtual volume, configure vvols, use UI to manage 
summary: Element UI를 사용하여 가상 볼륨 및 관련 스토리지 컨테이너, 프로토콜 엔드포인트, 바인딩 및 호스트에 대한 정보를 보고 작업을 수행할 수 있습니다. 
---
= 가상 볼륨 작업
:icons: font
:imagesdir: ../media/


[role="lead"]
Element UI를 사용하여 가상 볼륨 및 관련 스토리지 컨테이너, 프로토콜 엔드포인트, 바인딩 및 호스트에 대한 정보를 보고 작업을 수행할 수 있습니다.

NetApp Element 소프트웨어 스토리지 시스템은 VVOL(가상 볼륨) 기능을 비활성화한 상태로 제공됩니다. Element UI를 통해 vSphere VVol 기능을 수동으로 활성화하는 일회성 작업을 수행해야 합니다.

VVOL 기능을 활성화하면 VVOL 관련 모니터링 및 제한된 관리 옵션을 제공하는 사용자 인터페이스에 VVol 탭이 나타납니다. 또한 VASA Provider라고 하는 스토리지 측 소프트웨어 구성 요소는 vSphere에 대한 스토리지 인식 서비스 역할을 합니다. VVOL 생성, 클론 복제 및 편집과 같은 대부분의 VVOL 명령은 vCenter Server 또는 ESXi 호스트에서 시작되며 VASA Provider가 Element 소프트웨어 스토리지 시스템의 Element API로 변환합니다. 스토리지 컨테이너를 생성, 삭제 및 관리하고 가상 볼륨을 삭제하는 명령은 Element UI를 사용하여 시작할 수 있습니다.

Element 소프트웨어 스토리지 시스템에서 가상 볼륨 기능을 사용하는 데 필요한 대부분의 구성은 vSphere에서 이루어집니다. VMware vSphere Virtual Volumes for SolidFire Storage 구성 가이드 _ 를 참조하여 vCenter에 VASA Provider를 등록하고, VVOL 데이터 저장소를 생성 및 관리하고, 정책에 따라 스토리지를 관리하십시오.


NOTE: vCenter에 VASA 공급자를 이미 등록한 경우 여러 vCenter에 대한 VASA 지원을 업그레이드 패치로 사용할 수 있습니다. 설치하려면 에서 VASA39 .tar.gz 파일을 다운로드하십시오 https://mysupport.netapp.com/products/element_software/VASA39/index.html["NetApp 소프트웨어 다운로드"] 사이트를 방문하여 매니페스트의 지침을 따르십시오. NetApp Element VASA 공급자는 NetApp 인증서를 사용합니다. 이 패치를 사용하면 vCenter에서 인증서를 수정하지 않고 사용하여 VASA 및 VVol 사용을 위한 여러 vCenter를 지원합니다. 인증서를 수정하지 마십시오. 사용자 지정 SSL 인증서는 VASA에서 지원되지 않습니다.



== 자세한 내용을 확인하십시오

* xref:task_data_manage_vvol_enable_virtual_volumes.adoc[가상 볼륨을 설정합니다]
* xref:task_data_manage_vvol_view_virtual_volume_details.adoc[가상 볼륨 세부 정보를 봅니다]
* xref:task_data_manage_vvol_delete_a_virtual_volume.adoc[가상 볼륨을 삭제합니다]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[스토리지 컨테이너를 생성합니다]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[저장소 컨테이너를 편집합니다]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[저장소 컨테이너를 삭제합니다]
* xref:concept_data_manage_vvol_protocol_endpoints.adoc[프로토콜 엔드포인트]
* xref:concept_data_manage_vvol_bindings.adoc[바인딩]
* xref:reference_data_manage_vvol_host_details.adoc[호스트 세부 정보입니다]

