---
permalink: storage/concept_system_manage_cluster_terms_manage_the_terms_of_use_banner.html 
sidebar: sidebar 
keywords: element, terms of use, banner, config, edit, terms of use, disable, enable 
summary: 사용자에 대한 메시지가 포함된 배너를 설정, 편집 또는 구성할 수 있습니다. 
---
= 이용 약관 배너를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자에 대한 메시지가 포함된 배너를 설정, 편집 또는 구성할 수 있습니다.

 the Terms of Use banner
 the Terms of Use banner
 the Terms of Use banner



== 사용 약관 배너를 활성화합니다

사용자가 Element UI에 로그인할 때 표시되는 사용 약관 배너를 활성화할 수 있습니다. 사용자가 배너를 클릭하면 클러스터에 대해 구성한 메시지가 포함된 텍스트 대화 상자가 나타납니다. 배너는 언제든지 해제할 수 있습니다.

사용 약관 기능을 활성화하려면 클러스터 관리자 권한이 있어야 합니다.

. 사용자 * > * 이용 약관 * 을 클릭합니다.
. [사용 약관] * 양식에서 [사용 약관] 대화상자에 표시할 텍스트를 입력합니다.
+

NOTE: 4096자를 초과하지 마십시오.

. 사용 * 을 클릭합니다.




== 이용 약관 배너를 편집합니다

사용자가 이용 약관 로그인 배너를 선택하면 표시되는 텍스트를 편집할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 사용 약관을 구성하려면 클러스터 관리자 권한이 있어야 합니다.
* 사용 약관 기능이 활성화되어 있는지 확인합니다.


.단계
. 사용자 * > * 이용 약관 * 을 클릭합니다.
. 사용 약관 * 대화 상자에서 표시할 텍스트를 편집합니다.
+

NOTE: 4096자를 초과하지 마십시오.

. 변경 내용 저장 * 을 클릭합니다.




== 사용 약관 배너를 사용하지 않도록 설정합니다

이용 약관 배너를 사용하지 않도록 설정할 수 있습니다. 배너가 비활성화된 경우 사용자는 더 이상 Element UI를 사용할 때 사용 약관에 동의하도록 요청되지 않습니다.

.무엇을 &#8217;필요로 할거야
* 사용 약관을 구성하려면 클러스터 관리자 권한이 있어야 합니다.
* 사용 약관이 활성화되어 있는지 확인합니다.


.단계
. 사용자 * > * 이용 약관 * 을 클릭합니다.
. 비활성화 * 를 클릭합니다.

