---
permalink: storage/concept_data_manage_vol_access_group_work_with_volume_access_groups_and_initiators.html 
sidebar: sidebar 
keywords: volume access groups, initiators, working with, chap, fc, iscsi 
summary: iSCSI 이니시에이터 또는 Fibre Channel 이니시에이터를 사용하여 볼륨 액세스 그룹 내에 정의된 볼륨에 액세스할 수 있습니다. 
---
= 볼륨 액세스 그룹 및 이니시에이터와 작업합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 이니시에이터 또는 Fibre Channel 이니시에이터를 사용하여 볼륨 액세스 그룹 내에 정의된 볼륨에 액세스할 수 있습니다.

볼륨 컬렉션에 iSCSI 이니시에이터 IQN 또는 파이버 채널 WWPN을 매핑하여 액세스 그룹을 생성할 수 있습니다. 액세스 그룹에 추가하는 각 IQN은 CHAP 인증 없이 그룹의 각 볼륨에 액세스할 수 있습니다.

CHAP 인증 방법에는 두 가지가 있습니다.

* 계정 수준 CHAP 인증: 계정에 CHAP 인증을 할당할 수 있습니다.
* 이니시에이터 수준 CHAP 인증: 단일 계정의 단일 CHAP에 바인딩되지 않고 특정 이니시에이터에 대한 고유 CHAP 대상 및 암호를 할당할 수 있습니다. 이 이니시에이터 레벨 CHAP 인증은 계정 레벨 자격 증명을 대체합니다.


필요에 따라 이니시에이터당 CHAP를 사용하여 이니시에이터 인증 및 이니시에이터당 CHAP 인증을 적용할 수 있습니다. 이러한 옵션은 이니시에이터별로 정의할 수 있으며 액세스 그룹에는 다양한 옵션이 있는 여러 이니시에이터가 포함될 수 있습니다.

액세스 그룹에 추가하는 각 WWPN은 액세스 그룹의 볼륨에 대한 파이버 채널 네트워크 액세스를 설정합니다.


NOTE: 볼륨 액세스 그룹은 다음과 같은 제한 사항이 있습니다.

* 액세스 그룹에는 최대 64개의 IQN 또는 WWPN이 허용됩니다.
* 액세스 그룹은 최대 2000개의 볼륨으로 구성할 수 있습니다.
* IQN 또는 WWPN은 하나의 액세스 그룹에만 속할 수 있습니다.
* 단일 볼륨은 최대 4개의 액세스 그룹에 속할 수 있습니다.




== 자세한 내용을 확인하십시오

* xref:task_data_manage_vol_access_group_create_a_volume_access_group.adoc[볼륨 액세스 그룹을 생성합니다]
* xref:task_data_manage_vol_access_group_add_volumes.adoc[액세스 그룹에 볼륨을 추가합니다]
* xref:task_data_manage_vol_access_group_remove_volumes.adoc[액세스 그룹에서 볼륨을 제거합니다]
* xref:task_data_manage_vol_access_group_create_an_initiator.adoc[이니시에이터를 생성합니다]
* xref:task_data_manage_vol_access_group_edit_an_initiator.adoc[이니시에이터를 편집합니다]
* xref:task_data_manage_vol_access_group_add_a_single_initiator.adoc[볼륨 액세스 그룹에 단일 이니시에이터를 추가합니다]
* xref:task_data_manage_vol_access_group_add_multiple_initiators.adoc[볼륨 액세스 그룹에 여러 이니시에이터를 추가합니다]
* xref:task_data_manage_vol_access_group_remove_initiators_from_an_access_group.adoc[액세스 그룹에서 이니시에이터를 제거합니다]
* xref:task_data_manage_vol_access_group_delete.adoc[액세스 그룹을 삭제합니다]
* xref:task_data_manage_vol_access_group_delete_an_initiator.adoc[이니시에이터를 삭제합니다]

