---
permalink: storage/concept_system_manage_key_get_started_with_external_key_management.html 
sidebar: sidebar 
keywords: kmip, master key, key management, encryption at rest, software encryption at rest, ekm, ak, eks, seds 
summary: '외부 키 관리\(EKM\)는 외부 클러스터 외부 키 서버\(EKS\)와 함께 보안 인증 키\(AK\) 관리를 제공합니다. AK는 클러스터에서 저장된 암호화(Encryption at Rest)가 활성화된 경우 SED(자체 암호화 드라이브)를 잠그거나 잠금 해제하는 데 사용됩니다.' 
---
= 외부 키 관리를 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EKM(외부 키 관리)은 외부 클러스터 EKS(외부 키 서버)와 함께 AK(보안 인증 키) 관리를 제공합니다. AK는 SED(자체 암호화 드라이브)를 잠그거나 잠금 해제하는 데 사용됩니다 link:../concepts/concept_solidfire_concepts_security.html["유휴 데이터 암호화"] 클러스터에서 가 활성화됩니다. EKS는 AK의 안전한 생성 및 저장 기능을 제공합니다. 클러스터는 OASIS에서 정의한 표준 프로토콜인 KMIP(Key Management Interoperability Protocol)를 사용하여 EKS와 통신합니다.

* link:task_system_manage_key_set_up_external_key_management.html["외부 관리를 설정합니다"]
* link:task_system_manage_rekey_software_ear_master_key.html["소프트웨어 암호화 유휴 마스터 키를 다시 입력하다"]
* link:concept_system_manage_key_recover_inaccessible_or_invalid_authentication_keys["액세스할 수 없거나 잘못된 인증 키를 복구합니다"]
* link:concept_system_manage_key_external_key_management_api_commands.html["외부 키 관리 API 명령"]


[discrete]
== 자세한 내용을 확인하십시오

* link:../api/reference_element_api_createcluster.html["저장된 소프트웨어 암호화를 활성화하는 데 사용할 수 있는 CreateCluster API"]
* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 리소스 페이지 를 참조하십시오"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

