---
permalink: storage/concept_data_manage_volumes_quality_of_service_policies.html 
sidebar: sidebar 
keywords: qos policies, manage, volumes, create, edit, delete 
summary: '서비스 품질\(QoS\) 정책을 사용하면 여러 볼륨에 적용할 수 있는 표준화된 서비스 품질 설정을 만들어 저장할 수 있습니다. 관리 탭의 QoS 정책 페이지에서 QoS 정책을 생성, 편집 및 삭제할 수 있습니다.' 
---
= 서비스 품질 정책 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
서비스 품질(QoS) 정책을 사용하면 여러 볼륨에 적용할 수 있는 표준화된 서비스 품질 설정을 생성하여 저장할 수 있습니다. 관리 탭의 QoS 정책 페이지에서 QoS 정책을 생성, 편집 및 삭제할 수 있습니다.


NOTE: QoS 정책을 사용하는 경우 볼륨에 대해 사용자 지정 QoS를 사용하지 마십시오. 사용자 지정 QoS는 볼륨 QoS 설정에 대한 QoS 정책 값을 재정의하고 조정합니다.

https://www.youtube.com/embed/q9VCBRDtrnI?rel=0["NetApp 비디오: SolidFire 서비스 품질 정책"]

을 참조하십시오 link:../concepts/concept_data_manage_volumes_solidfire_quality_of_service.html["성능 및 서비스 품질"].

* QoS 정책을 생성합니다
* QoS 정책을 편집합니다
* QoS 정책을 삭제합니다




== QoS 정책을 생성합니다

볼륨을 생성할 때 QoS 정책을 생성하고 적용할 수 있습니다.

. Management * > * QoS Policies * 를 선택합니다.
. QoS 정책 생성 * 을 클릭합니다.
. 정책 이름 * 을 입력합니다.
. 최소 IOPS**, * 최대 IOPS * 및 * 버스트 IOPS * 값을 입력합니다.
. QoS 정책 생성 * 을 클릭합니다.




== QoS 정책을 편집합니다

기존 QoS 정책의 이름을 변경하거나 정책과 연결된 값을 편집할 수 있습니다. QoS 정책을 변경하면 정책에 연결된 모든 볼륨에 영향을 줍니다.

. Management * > * QoS Policies * 를 선택합니다.
. 편집할 QoS 정책의 작업 아이콘을 클릭합니다.
. 결과 메뉴에서 ** 편집**을 선택합니다.
. QoS 정책 편집 * 대화 상자에서 필요에 따라 다음 속성을 수정합니다.
+
** 정책 이름
** 최소 IOPS
** 최대 IOPS
** 버스트 IOPS


. 변경 내용 저장 * 을 클릭합니다.




== QoS 정책을 삭제합니다

QoS 정책이 더 이상 필요하지 않은 경우 삭제할 수 있습니다. QoS 정책을 삭제할 경우 정책에 연결된 모든 볼륨은 QoS 설정을 유지하지만 정책과 연결되지 않습니다.


NOTE: 대신 QoS 정책에서 볼륨을 연결 해제하려는 경우 해당 볼륨의 QoS 설정을 사용자 지정으로 변경할 수 있습니다.

. Management * > * QoS Policies * 를 선택합니다.
. 삭제할 QoS 정책에 대한 작업 아이콘을 클릭합니다.
. 결과 메뉴에서 * 삭제 * 를 선택합니다.
. 작업을 확인합니다.




== 자세한 내용을 확인하십시오

* link:task_data_manage_volumes_remove_a_qos_policy_association_of_a_volume.html["볼륨의 QoS 정책 연결을 제거합니다"]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

