---
permalink: storage/concept_data_manage_volumes_solidfire_quality_of_service.html 
sidebar: sidebar 
keywords: qos policies, iops 
summary: 'SolidFire 스토리지 클러스터에는 볼륨별로 QoS\(서비스 품질) 매개 변수를 제공할 수 있는 기능이 있습니다. QoS를 정의하는 세 가지 구성 가능한 매개 변수(최소 IOPS, 최대 IOPS 및 버스트 IOPS)를 사용하여 초당 입력 및 출력(IOPS\)으로 측정한 클러스터 성능을 보장할 수 있습니다.' 
---
= 서비스 품질
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 스토리지 클러스터에는 볼륨 기준에 따라 서비스 품질(QoS) 매개 변수를 제공할 수 있는 기능이 있습니다. QoS를 정의하는 세 가지 구성 가능한 매개 변수(최소 IOPS, 최대 IOPS 및 버스트 IOPS)를 사용하여 초당 입력 및 출력(IOPS)으로 측정한 클러스터 성능을 보장할 수 있습니다.


NOTE: SolidFire Active IQ에는 QoS 설정 및 최적의 구성에 대한 조언을 제공하는 QoS 권장 사항 페이지가 있습니다.

IOPS 매개 변수는 다음과 같은 방법으로 정의됩니다.

* * 최소 IOPS *
+
스토리지 클러스터가 볼륨에 제공하는 최소 유지 IOPS(초당 입출력) 수입니다. 볼륨에 대해 구성된 최소 IOPS는 볼륨의 보장된 성능 수준입니다. 성능이 이 수준 아래로 떨어지지 않습니다.

* * 최대 IOPS *
+
스토리지 클러스터가 볼륨에 제공하는 최대 지속 IOPS 수입니다. 클러스터 IOPS 레벨이 매우 높을 경우 이 IOPS 성능 레벨이 초과하지 않습니다.

* * 버스트 IOPS *
+
짧은 버스트 시나리오에서 허용되는 최대 IOPS 수입니다. 볼륨이 최대 IOPS 미만으로 실행 중인 경우 버스트 크레딧이 누적됩니다. 성능 수준이 매우 높고 최대 수준으로 푸시되면 볼륨에 대해 짧은 IOPS 버스트가 허용됩니다.

+
Element 소프트웨어는 클러스터가 낮은 클러스터 IOPS 사용률로 실행 중일 때 버스트 IOPS를 사용합니다.

+
단일 볼륨에서 버스트 IOPS를 늘리고 크레딧을 사용하여 설정된 "버스트 기간"에 대해 최대 IOPS 레벨까지 버스트 IOPS를 초과하는 성능을 높일 수 있습니다. 클러스터에 최대 60초 동안 연속 데이터 증가를 수용할 수 있는 용량이 있는 경우 볼륨이 폭발할 수 있습니다.

+
볼륨은 최대 IOPS 한도 미만으로 실행되는 초당 1초의 버스트 크레딧(최대 60초)을 누적합니다.

+
버스트 IOPS는 두 가지 방법으로 제한됩니다.

+
** 볼륨은 볼륨이 누적된 버스트 크레딧 수와 동일한 몇 초 동안 최대 IOPS 이상으로 급증할 수 있습니다.
** 볼륨이 최대 IOPS 설정 이상으로 급증하면 버스트 IOPS 설정에 의해 제한됩니다. 따라서 버스트 IOPS는 볼륨에 대한 버스트 IOPS 설정을 초과하지 않는다.


* * 유효 최대 대역폭 *
+
최대 대역폭은 IOPS 수(QoS 곡선 기준)에 IO 크기를 곱하여 계산합니다.

+
예:

+
100분 IOPS, 1000 Max IOPS, 1500 Burst IOP의 QoS 매개 변수 설정은 성능 품질에 다음과 같은 영향을 미칩니다.

+
** 클러스터에서 IOPS에 대한 워크로드 경합이 뚜렷해질 때까지 워크로드가 최대 1000 IOPS에 도달하고 이를 유지할 수 있습니다. 그런 다음 모든 볼륨의 IOPS가 지정된 QoS 범위 내에 있고 성능 경합이 완화될 때까지 IOPS가 점진적으로 감소합니다.
** 모든 볼륨의 성능은 최소 IOPS 100으로 푸시됩니다. 레벨은 최소 IOPS 설정 아래로 떨어지지 않지만 워크로드 경합이 완화될 때 100 IOPS를 초과할 수 있습니다.
** 성능이 1000 IOPS를 넘지 않거나 유지 기간 동안 100 IOPS를 넘지 않습니다. 1500 IOPS(버스트 IOPS)의 성능은 허용되지만, 최대 IOPS 미만으로 실행하여 버스트 크레딧을 계산한 볼륨에 대해서만 짧은 시간 동안만 허용됩니다. 버스트 레벨은 절대 지속되지 않습니다.



