---
permalink: storage/concept_troubleshoot_basic_mdss_drive_troubleshooting.html 
sidebar: sidebar 
keywords: mdss drives, troubleshoot, multi-drive slice service 
summary: '하나 또는 두 메타데이터 드라이브 모두에 장애가 발생할 경우 메타데이터 드라이브(또는 슬라이스\)를 클러스터에 다시 추가하여 복구할 수 있습니다. 노드에서 MDSS 기능이 이미 활성화된 경우 NetApp Element UI에서 복구 작업을 수행할 수 있습니다.' 
---
= 기본 MDSS 드라이브 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하나 또는 두 메타데이터 드라이브 모두에 장애가 발생할 경우 메타데이터(또는 슬라이스) 드라이브를 클러스터에 다시 추가하여 복구할 수 있습니다. 노드에서 MDSS 기능이 이미 활성화된 경우 NetApp Element UI에서 복구 작업을 수행할 수 있습니다.

노드의 메타데이터 드라이브 중 하나 또는 둘 다에 장애가 발생하면 슬라이스 서비스가 종료되고 두 드라이브의 데이터가 노드의 다른 드라이브에 백업됩니다.

다음 시나리오는 발생 가능한 실패 시나리오를 설명하고 문제를 해결하기 위한 기본 권장 사항을 제공합니다.



== 시스템 슬라이스 드라이브가 작동하지 않습니다

* 이 시나리오에서는 슬롯 2가 확인되어 사용 가능한 상태로 돌아갑니다.
* 슬라이스 서비스를 다시 온라인으로 전환하기 전에 시스템 슬라이스 드라이브를 다시 채워야 합니다.
* 시스템 슬라이스 드라이브를 교체해야 합니다. 시스템 슬라이스 드라이브를 사용할 수 있게 되면 드라이브와 슬롯 2 드라이브를 동시에 추가해야 합니다.



NOTE: 슬롯 2의 드라이브는 메타데이터 드라이브로 추가할 수 없습니다. 두 드라이브를 동시에 노드에 다시 추가해야 합니다.



== 슬롯 2에 장애가 있습니다

* 이 시나리오에서는 시스템 슬라이스 드라이브를 확인하고 사용 가능한 상태로 돌아갑니다.
* 슬롯 2를 스페어로 교체해야 합니다. 슬롯 2를 사용할 수 있게 되면 시스템 슬라이스 드라이브와 슬롯 2 드라이브를 동시에 추가합니다.




== 시스템 슬라이스 드라이브 및 슬롯 2에 장애가 있습니다

* 시스템 슬라이스 드라이브와 슬롯 2를 모두 스페어 드라이브로 교체해야 합니다. 두 드라이브를 모두 사용할 수 있게 되면 시스템 슬라이스 드라이브와 슬롯 2 드라이브를 동시에 추가합니다.




== 작업 순서

* 장애가 발생한 하드웨어 드라이브를 스페어 드라이브로 교체합니다(둘 다 장애가 발생한 경우 두 드라이브를 모두 교체합니다).
* 드라이브가 다시 채워지고 사용 가능 상태가 되면 클러스터에 다시 드라이브를 추가합니다.




== 작업을 확인합니다

* 슬롯 0(또는 내부) 및 슬롯 2의 드라이브가 활성 드라이브 목록에서 메타데이터 드라이브로 식별되는지 확인합니다.
* 모든 슬라이스 균형 조정이 완료되었는지 확인합니다(이벤트 로그에 최소 30분 동안 더 이상 슬라이스 이동 메시지가 없습니다).




== 를 참조하십시오

xref:task_troubleshoot_add_mdss_drives.adoc[MDSS 드라이브를 추가합니다]
