---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: 'Element 소프트웨어를 실행하는 클러스터는 클러스터 장애를 생성하여 클러스터 용량이 부족해지면 스토리지 관리자에게 경고합니다. 세 가지 수준의 클러스터 충만도가 있으며 모두 NetApp Element UI에 표시됩니다(경고, 오류 및 위험).' 
---
= 클러스터 전체 수준 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element 소프트웨어를 실행하는 클러스터는 클러스터 장애를 생성하여 클러스터 용량이 부족해지면 스토리지 관리자에게 경고합니다. 세 가지 수준의 클러스터 충만도가 있으며 모두 NetApp Element UI에 표시됩니다(경고, 오류 및 위험).

시스템은 BlockClusterFull 오류 코드를 사용하여 클러스터 블록 스토리지 충만성에 대해 경고합니다. Element UI의 Alerts 탭에서 클러스터의 전체 심각도 수준을 볼 수 있습니다.

다음 목록에는 BlockClusterFull 심각도 수준에 대한 정보가 포함되어 있습니다.

* * 경고 *
+
클러스터의 블록 용량이 오류 심각도 수준에 접근하고 있을 때 표시되는 고객 구성 가능 경고입니다. 기본적으로 이 수준은 오류 수준에서 3%로 설정되며 Element UI 및 API를 통해 조정할 수 있습니다. 용량을 추가하거나 가능한 한 빨리 용량을 확보하십시오.

* * 오류 *
+
클러스터가 이 상태일 때 노드가 손실된 경우 이중 Helix 데이터 보호를 재구축하기에 충분한 용량이 클러스터에 없습니다. 클러스터가 이 상태인 동안에는 새 볼륨 생성, 클론 및 스냅샷이 모두 차단됩니다. 이 상태는 클러스터에 대한 안전 또는 권장 상태가 아닙니다. 용량을 추가하거나 즉시 용량을 확장해야 합니다.

* * 심각 *
+
이 심각한 오류는 클러스터가 100% 사용되었기 때문에 발생했습니다. 읽기 전용 상태이며 클러스터에 새 iSCSI 연결을 설정할 수 없습니다. 이 단계에 도달하면 즉시 용량을 확보하거나 추가해야 합니다.



시스템은 MetadataClusterFull 오류 코드를 사용하여 클러스터 메타데이터 스토리지 충만성에 대해 경고합니다. Element UI의 Reporting(보고) 탭의 Overview(개요) 페이지에 있는 Cluster Capacity(클러스터 용량) 섹션에서 클러스터 메타데이터 스토리지 충만 을 볼 수 있습니다.

다음 목록에는 MetadataClusterFull 심각도 수준에 대한 정보가 포함되어 있습니다.

* * 경고 *
+
이 경고는 클러스터의 메타데이터 용량이 오류 심각도 수준에 접근하고 있을 때 고객이 구성할 수 있는 경고입니다. 기본적으로 이 수준은 오류 수준에서 3%로 설정되며 Element API를 통해 조정할 수 있습니다. 용량을 추가하거나 가능한 한 빨리 용량을 확보하십시오.

* * 오류 *
+
클러스터가 이 상태일 때 노드가 손실된 경우 이중 Helix 데이터 보호를 재구축하기에 충분한 용량이 클러스터에 없습니다. 클러스터가 이 상태인 동안에는 새 볼륨 생성, 클론 및 스냅샷이 모두 차단됩니다. 이 상태는 클러스터에 대한 안전 또는 권장 상태가 아닙니다. 용량을 추가하거나 즉시 용량을 확장해야 합니다.

* * 심각 *
+
이 심각한 오류는 클러스터가 100% 사용되었기 때문에 발생했습니다. 읽기 전용 상태이며 클러스터에 새 iSCSI 연결을 설정할 수 없습니다. 이 단계에 도달하면 즉시 용량을 확보하거나 추가해야 합니다.




NOTE: 다음은 2노드 클러스터 임계값에 적용되는 사항입니다.

* 메타데이터 충만 오류는 위험 보다 20% 낮습니다.
* 블록 충만 오류는 1개 블록 드라이브(고립된 용량 포함)가 중요 오류 보다 낮다는 의미입니다. 즉, 2개 블록 드라이브에서 용량이 중요 용량보다 더 적다는 의미입니다.

