---
permalink: storage/concept_intro_custom_protection_domains.html 
sidebar: sidebar 
keywords: Protection Domain layout,user-defined,custom layout 
summary: 사용자 지정 보호 도메인 레이아웃을 정의할 수 있습니다. 여기서 각 노드는 1개 및 1개의 사용자 지정 보호 도메인에만 연결됩니다. 기본적으로 각 노드는 동일한 기본 사용자 지정 보호 도메인에 할당됩니다. 
---
= 사용자 지정 보호 도메인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 섀시 및 노드 레이아웃과 일치하는 사용자 지정 보호 도메인 레이아웃을 정의할 수 있습니다.

사용자 지정 보호 도메인이 할당되지 않은 경우:

* 클러스터 작업은 영향을 받지 않습니다.
* 사용자 지정 수준은 허용 또는 회복성이 없습니다.


클러스터에 대한 사용자 지정 보호 도메인을 구성하는 경우 다음과 같은 세 가지 수준의 보호가 가능합니다. Element 웹 UI 대시보드에서 볼 수 있습니다.

* 보호되지 않음: 스토리지 클러스터가 사용자 지정 보호 도메인 중 하나의 오류로부터 보호되지 않습니다. 이 문제를 해결하려면 클러스터에 스토리지 용량을 추가하거나 클러스터의 사용자 지정 보호 도메인을 다시 구성하여 데이터 손실로부터 클러스터를 보호합니다.
* 내결함성: 스토리지 클러스터에 사용자 지정 보호 도메인 중 하나에 장애가 발생한 후 데이터 손실을 방지할 수 있는 충분한 가용 용량이 있습니다.
* 장애 복구: 스토리지 클러스터는 사용자 지정 보호 도메인 중 하나에 장애가 발생한 후 자가 복구가 가능한 충분한 가용 용량을 제공합니다. 복구 프로세스가 완료된 후 추가 도메인에 장애가 발생하면 클러스터가 데이터 손실로부터 보호됩니다.


사용자 지정 보호 도메인이 두 개 이상 할당된 경우 각 하위 시스템은 개별 사용자 지정 보호 도메인에 중복된 항목을 할당합니다. 이것이 가능하지 않으면 중복 항목을 별도의 노드에 할당하는 것으로 되돌아갑니다. 각 하위 시스템(예: 투출구, 슬라이스, 프로토콜 엔드포인트 공급자 및 앙상블)은 이를 독립적으로 수행합니다.

Element UI를 사용하여 에 대한 작업을 수행할 수 있습니다 link:task_data_protection_configure_custom_protection_domains.html["사용자 지정 보호 도메인을 구성합니다"^]또는 다음 API 메소드를 사용할 수 있습니다.

* link:../api/reference_element_api_getprotectiondomainlayout.html["GetProtectionDomainLayout 을 참조하십시오"^] - 각 노드가 속한 섀시와 사용자 지정 보호 도메인을 표시합니다.
* link:../api/reference_element_api_setprotectiondomainlayout.html["SetProtectionDomainLayout 을 참조하십시오"^] - 각 노드에 사용자 지정 보호 도메인을 할당할 수 있습니다.




== 자세한 내용을 확인하십시오

link:../api/index.html["Element API를 사용하여 스토리지를 관리합니다"^]
