---
permalink: storage/concept_data_manage_vvol_manage_storage_containers.html 
sidebar: sidebar 
keywords: storage container, storage containers, about storage containers, cluster, vvols, create, view details, chap, edit, delete 
summary: 스토리지 컨테이너는 Element 소프트웨어를 실행하는 클러스터에서 생성된 vSphere 데이터 저장소 표현입니다. 
---
= 스토리지 컨테이너 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 컨테이너는 Element 소프트웨어를 실행하는 클러스터에서 생성된 vSphere 데이터 저장소 표현입니다.

스토리지 컨테이너는 NetApp Element 계정에 생성되고 연결되어 있습니다. Element 스토리지에 생성된 스토리지 컨테이너는 vCenter 및 ESXi에서 vSphere 데이터 저장소로 표시됩니다. 스토리지 컨테이너는 Element 스토리지에 공간을 할당하지 않습니다. 가상 볼륨을 논리적으로 연결하는 데 사용됩니다.

클러스터당 최대 4개의 스토리지 컨테이너가 지원됩니다. VVOL 기능을 활성화하려면 최소 하나의 스토리지 컨테이너가 필요합니다.



== 스토리지 컨테이너를 생성합니다

Element UI에서 스토리지 컨테이너를 생성하고 vCenter에서 검색할 수 있습니다. VVOL 지원 가상 머신 프로비저닝을 시작하려면 하나 이상의 스토리지 컨테이너를 생성해야 합니다.

시작하기 전에 클러스터의 Element UI에서 VVOL 기능을 활성화합니다.

.단계
. VVol * > * Storage Containers * 를 선택합니다.
. Create Storage Containers * 버튼을 클릭합니다.
. Create a New Storage Container * (새 저장소 컨테이너 생성 *) 대화 상자에 저장소 컨테이너 정보를 입력합니다.
+
.. 저장소 컨테이너의 이름을 입력합니다.
.. CHAP에 대한 이니시에이터 및 타겟 암호를 구성합니다.
+

TIP: CHAP 설정 필드를 비워 두면 자동으로 암호가 생성됩니다.

.. Create Storage Container * 버튼을 클릭합니다.


. 새 저장소 컨테이너가 * 저장소 컨테이너 * 하위 탭의 목록에 나타나는지 확인합니다.
+

NOTE: NetApp Element 계정 ID는 자동으로 생성되어 저장소 컨테이너에 할당되므로 계정을 수동으로 생성할 필요가 없습니다.





== 저장소 컨테이너 세부 정보를 봅니다

VVol 탭의 Storage Containers 페이지에서 클러스터의 모든 활성 저장소 컨테이너에 대한 정보를 볼 수 있습니다.

* * 계정 ID *: 저장소 컨테이너와 연결된 NetApp Element 계정의 ID입니다.
* * 이름 *: 저장소 컨테이너의 이름입니다.
* * 상태 *: 저장소 컨테이너의 상태입니다. 가능한 값:
+
** Active(활성): 저장소 컨테이너가 사용 중입니다.
** 잠김: 저장소 컨테이너가 잠겨 있습니다.


* * PE 유형 *: 프로토콜 엔드포인트 유형(SCSI는 Element 소프트웨어에 대해 사용 가능한 유일한 프로토콜입니다).
* * 저장소 컨테이너 ID *: 가상 볼륨 저장소 컨테이너의 UUID
* * 활성 가상 볼륨 *: 스토리지 컨테이너와 연결된 활성 가상 볼륨의 수입니다.




== 개별 저장소 컨테이너 세부 정보를 봅니다

VVol 탭의 Storage Containers(저장소 컨테이너) 페이지에서 선택하여 개별 저장소 컨테이너의 저장소 컨테이너 정보를 볼 수 있습니다.

* * 계정 ID *: 저장소 컨테이너와 연결된 NetApp Element 계정의 ID입니다.
* * 이름 *: 저장소 컨테이너의 이름입니다.
* * 상태 *: 저장소 컨테이너의 상태입니다. 가능한 값:
+
** Active(활성): 저장소 컨테이너가 사용 중입니다.
** 잠김: 저장소 컨테이너가 잠겨 있습니다.


* * CHAP 초기자 암호 *: 초기자에 대한 고유한 CHAP 암호입니다.
* * CHAP 대상 암호 *: 타겟의 고유한 CHAP 암호입니다.
* * 저장소 컨테이너 ID *: 가상 볼륨 저장소 컨테이너의 UUID
* * Protocol Endpoint Type * : 프로토콜 엔드포인트 유형을 나타냅니다(SCSI는 유일한 사용 가능 프로토콜입니다).




== 저장소 컨테이너를 편집합니다

Element UI에서 스토리지 컨테이너 CHAP 인증을 수정할 수 있습니다.

. VVol * > * Storage Containers * 를 선택합니다.
. 편집할 저장 컨테이너의 * 작업 * 아이콘을 클릭합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. CHAP 설정 에서 인증에 사용되는 초기자 암호 및 대상 암호 자격 증명을 편집합니다.
+

TIP: CHAP 설정 자격 증명을 변경하지 않으면 자격 증명은 그대로 유지됩니다. 자격 증명 필드를 비워 두면 시스템에서 자동으로 새 암호를 생성합니다.

. 변경 내용 저장 * 을 클릭합니다.




== 저장소 컨테이너를 삭제합니다

Element UI에서 스토리지 컨테이너를 삭제할 수 있습니다.

.필요한 것
모든 가상 머신이 VVol 데이터 저장소에서 제거되었는지 확인합니다.

.단계
. VVol * > * Storage Containers * 를 선택합니다.
. 삭제할 저장소 컨테이너의 * 작업 * 아이콘을 클릭합니다.
. 결과 메뉴에서 * 삭제 * 를 선택합니다.
. 작업을 확인합니다.
. 저장소 컨테이너 * 하위 탭의 저장소 컨테이너 목록을 새로 고쳐 저장소 컨테이너가 제거되었는지 확인합니다.

