---
permalink: storage/concept_troubleshoot_nodes.html 
sidebar: sidebar 
keywords: troubleshoot, nodes removing 
summary: 유지보수 또는 교체를 위해 클러스터에서 노드를 제거할 수 있습니다. 노드를 오프라인으로 전환하기 전에 NetApp Element UI 또는 API를 사용하여 노드를 제거해야 합니다. 
---
= 노드 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
유지보수 또는 교체를 위해 클러스터에서 노드를 제거할 수 있습니다. 노드를 오프라인으로 전환하기 전에 NetApp Element UI 또는 API를 사용하여 노드를 제거해야 합니다.

스토리지 노드를 제거하는 절차는 다음과 같습니다.

* 클러스터에 노드에서 데이터 복사본을 생성할 수 있는 충분한 용량이 있는지 확인합니다.
* UI 또는 RemoveDrives API 메소드를 사용하여 클러스터에서 드라이브를 제거합니다.
+
따라서 시스템이 노드의 드라이브에서 클러스터의 다른 드라이브로 데이터를 마이그레이션합니다. 이 프로세스에 걸리는 시간은 마이그레이션해야 하는 데이터의 양에 따라 달라집니다.

* 클러스터에서 노드를 제거합니다.


노드 전원을 끄기 전에 다음 사항을 고려하십시오.

* 노드 및 클러스터의 전원을 끄는 것은 올바르게 수행되지 않을 경우 위험이 수반됩니다.
+
노드의 전원을 끄는 작업은 NetApp Support의 지시에 따라 수행해야 합니다.

* 어떤 유형의 종료 조건에서든 노드가 5.5분 이상 중단된 경우, 이중 Helix 데이터 보호는 복제된 단일 블록을 다른 노드에 작성하여 데이터를 복제하는 작업을 시작합니다. 이 경우 NetApp Support에 문의하여 장애 노드 분석에 대한 도움을 받으십시오.
* 노드를 안전하게 재부팅하거나 전원을 끄기 위해 Shutdown API 명령을 사용할 수 있습니다.
* 노드가 중단 상태이거나 꺼짐 상태인 경우 온라인 상태로 되돌리기 전에 NetApp 지원에 문의해야 합니다.
* 노드가 다시 온라인 상태가 된 후 서비스 제공 기간에 따라 드라이브를 클러스터에 다시 추가해야 합니다.




== 를 참조하십시오

https://library.netapp.com/ecm/ecm_download_file/ECMLP2844772["장애가 발생한 SolidFire 섀시 교체"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2846861["장애가 발생한 H600S 시리즈 노드 교체"]
