---
permalink: storage/concept_intro_solidfire_software_interfaces.html 
sidebar: sidebar 
keywords: interfaces, integration, user interface, Plug-in, vCenter, API, node UIs, command line, snapshots, shadow copies, Element software, Element, Element UI, UI, manage storage, utilities, integration utilities 
summary: NetApp Element 소프트웨어 인터페이스 및 통합 유틸리티를 사용하여 SolidFire 스토리지 시스템을 관리할 수 있습니다. 
---
= SolidFire 소프트웨어 인터페이스
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element 소프트웨어 인터페이스 및 통합 유틸리티를 사용하여 SolidFire 스토리지 시스템을 관리할 수 있습니다.

* * NetApp Element 소프트웨어 사용자 인터페이스 *
+
멀티 테넌트(multi-tenant) 인프라에서 SolidFire 스토리지를 설정하고, 클러스터 용량과 성능을 모니터링하고, 스토리지 작업을 관리할 수 있습니다. 요소는 SolidFire 클러스터의 중심에 있는 스토리지 운영 체제입니다. Element 소프트웨어는 클러스터의 모든 노드에서 독립적으로 실행되며 클러스터 노드가 리소스를 결합하여 단일 스토리지 시스템으로 외부 클라이언트에 제공할 수 있도록 합니다. Element 소프트웨어는 시스템 전체의 모든 클러스터 조정, 확장 및 관리를 책임집니다. 소프트웨어 인터페이스는 Element API를 기반으로 구축됩니다.

* * vCenter Server * 용 NetApp Element 플러그인
+
Element 소프트웨어를 실행하는 스토리지 클러스터를 구성하고 관리할 수 있습니다. 이 플러그인은 VMware vSphere 내의 Element UI에 대한 대체 인터페이스를 제공합니다.

* * NetApp Element 소프트웨어 API *
+
일련의 오브젝트, 방법 및 루틴을 사용하여 SolidFire 스토리지를 관리할 수 있습니다. Element API는 HTTPS를 통한 JSON-RPC 프로토콜을 기반으로 합니다. API 로그를 활성화하여 Element UI에서 API 작업을 모니터링할 수 있습니다. 이렇게 하면 시스템에 실행 중인 메서드를 볼 수 있습니다. 요청과 응답을 모두 활성화하여 시스템이 실행된 메서드에 응답하는 방법을 확인할 수 있습니다.

* * 관리 노드 UI *
+
관리 노드에는 REST 기반 서비스를 관리하기 위한 UI와 네트워크 및 클러스터 설정과 운영 체제 테스트 및 유틸리티를 관리하기 위한 노드별 UI의 두 가지 UI가 포함되어 있습니다. REST API UI에서 관리 노드의 관리 서비스를 제어하는 서비스 관련 API 메뉴에 액세스할 수 있습니다.





== 추가 통합 유틸리티 및 툴

일반적으로 NetApp Element, NetApp Element API 및 vCenter Server용 NetApp Element 플러그인을 사용하여 스토리지를 관리하지만 추가 유틸리티 및 툴을 사용할 수 있습니다.

* https://mysupport.netapp.com/products/p/vro.html["NetApp 다운로드: SolidFire vRO"]
+
SolidFire API를 사용하여 VMware vRealize Orchestrator ™ 를 사용하여 SolidFire 스토리지 시스템을 관리하는 편리한 방법을 제공합니다.

* https://mysupport.netapp.com/products/p/elementsdk.html["NetApp 다운로드: Element SDK"]
+
다음 툴을 사용하여 SolidFire 클러스터를 관리할 수 있습니다.

+
** SolidFire 명령줄
** SolidFire Postman API 테스트 제품군: 프로그래머가 SolidFire API 호출을 테스트하는 Postman 함수의 컬렉션을 사용할 수 있습니다.
** SolidFire PowerShell: 프로그래머가 SolidFire API를 사용하여 SolidFire 스토리지 시스템을 관리하는 Microsoft ® Windows ® PowerShell ® 기능의 컬렉션을 사용할 수 있습니다.
** SolidFire SDK Java: 프로그래머가 SolidFire API를 Java 프로그래밍 언어와 통합할 수 있습니다.
** SolidFire SDK .NET: 프로그래머가 SolidFire API를 .NET 프로그래밍 플랫폼과 통합할 수 있습니다.
** SolidFire SDK Python: 프로그래머가 SolidFire API를 Python™ 프로그래밍 언어와 통합할 수 있습니다.


* https://mysupport.netapp.com/products/p/elementsra.html["NetApp 다운로드: SolidFire 스토리지 복제 어댑터"]
+
VMware® Site Recovery Manager™(SRM)와 통합하여 복제된 SolidFire 스토리지 클러스터(어레이)와의 통신을 지원하고 지원되는 워크플로우를 실행합니다.

* https://mysupport.netapp.com/products/p/elementvss.html["NetApp 다운로드: SolidFire VSS 공급자"]
+
VSS 섀도우 복제본을 SolidFire 스냅샷 및 클론과 통합합니다.


