---
permalink: storage/reference_snapmirror_relationship_actions.html 
sidebar: sidebar 
keywords: element, ui, relationships, snapmirror, actions, configure 
summary: 데이터 보호 탭의 SnapMirror 관계 페이지에서 관계를 구성할 수 있습니다. 작업 아이콘의 옵션은 여기에 설명되어 있습니다. 
---
= SnapMirror 관계 동작
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 보호 탭의 SnapMirror 관계 페이지에서 관계를 구성할 수 있습니다. 작업 아이콘의 옵션은 여기에 설명되어 있습니다.

* * 편집 *: 관계에 사용되는 정책이나 일정을 편집합니다.
* * 삭제 *: SnapMirror 관계를 삭제합니다. 이 기능은 대상 볼륨을 삭제하지 않습니다.
* * Initialize *(초기화 *): 첫 번째 초기 데이터 베이스라인 전송을 수행하여 새 관계를 설정합니다.
* * 업데이트 *: 대상에 대한 마지막 업데이트 이후 포함된 새 데이터와 스냅샷 복사본을 복제하여 필요에 따라 관계를 업데이트합니다.
* * 정지 *: 관계에 대한 추가 업데이트를 방지합니다.
* * Resume *: 중지된 관계를 재개합니다.
* * Break *: 대상 볼륨을 읽기-쓰기로 설정하고 현재 및 미래의 모든 전송을 중지합니다. 역방향 재동기화 작업으로 인해 원본 소스 볼륨이 읽기 전용이 되므로 클라이언트가 원본 소스 볼륨을 사용하지 않는지 확인합니다.
* * 재동기화 *: 파손되기 전에 동일한 방향으로 끊어진 관계를 다시 설정합니다.
* * 역방향 재동기화 *: 반대 방향으로 새 관계를 만들고 초기화하는 데 필요한 단계를 자동화합니다. 이 작업은 기존 관계가 끊어진 상태인 경우에만 수행할 수 있습니다. 이 작업은 현재 관계를 삭제하지 않습니다. 원래 소스 볼륨은 가장 최근의 공통 스냅샷 복사본으로 되돌려져서 대상과 재동기화됩니다. 마지막으로 성공한 SnapMirror 업데이트 이후 원래 소스 볼륨에 대한 모든 변경 사항이 손실됩니다. 변경된 내용 또는 현재 대상 볼륨에 기록된 새 데이터는 원래 소스 볼륨으로 다시 전송됩니다.
* * Abort * (중단 *): 진행 중인 현재 전송을 취소합니다. 중단된 관계에 대해 SnapMirror 업데이트가 실행되면 중단이 발생하기 전에 생성된 마지막 재시작 체크포인트에서 마지막 전송을 통해 관계가 계속됩니다.

