---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: SSL 암호화는 호스트가 보안 통신을 설정하는 데 사용하는 암호화 알고리즘입니다. FIPS 140-2 모드가 활성화된 경우 Element 소프트웨어가 지원하는 표준 암호와 비표준 암호가 있습니다. 
---
= SSL 암호
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSL 암호화는 호스트가 보안 통신을 설정하는 데 사용하는 암호화 알고리즘입니다. FIPS 140-2 모드가 활성화된 경우 Element 소프트웨어가 지원하는 표준 암호와 비표준 암호가 있습니다.

다음 목록은 Element 소프트웨어에서 지원되는 표준 SSL(Secure Socket Layer) 암호와 FIPS 140-2 모드가 활성화된 경우 지원되는 SSL 암호를 제공합니다.

* * FIPS 140-2 비활성화 *
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(DH 2048)-A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(DH 2048)-A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(DH 2048)-A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(DH 2048)-A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(secp256r1)-A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(secp256r1)-A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(secp256r1)-A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(secp256r1)-A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA(RSA 2048)-C

+
TLS_RSA_WITED_AES_128_CBC_SHA(RSA 2048)-A

+
TLS_RSA_WITED_AES_128_CBC_SHA256(RSA 2048)-A

+
TLS_RSA_with_AES_128_GCM_SHA256(RSA 2048)-A

+
TLS_RSA_WITED_AES_256_CBC_SHA(RSA 2048)-A

+
TLS_RSA_WITED_AES_256_CBC_SHA256(RSA 2048)-A

+
TLS_RSA_WITED_AES_256_GCM_SHA384(RSA 2048)-A

+
tls_rsa_with_camellia_128_CBC_SHA(RSA 2048) -A

+
tls_rsa_with_camellia_256_CBC_SHA(RSA 2048) -A

+
tls_rsa_with_Idea_cbc_SHA(RSA 2048) -a

+
TLS_RSA_WITED_RC4_128_MD5(RSA 2048)-C

+
TLS_RSA_WITED_RC4_128_SHA(RSA 2048)-C

+
TLS_RSA_WITED_SEED_CBC_SHA(RSA 2048)-A

* * FIPS 140-2 활성화 *
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(DH 2048)-A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(DH 2048)-A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(DH 2048)-A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(DH 2048)-A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(sect571r1)-A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(secp256r1)-A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(secp256r1)-A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(sect571r1)-A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(sect571r1)-A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(secp256r1)-A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(secp256r1)-A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(sect571r1)-A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA(RSA 2048)-C

+
TLS_RSA_WITED_AES_128_CBC_SHA(RSA 2048)-A

+
TLS_RSA_WITED_AES_128_CBC_SHA256(RSA 2048)-A

+
TLS_RSA_with_AES_128_GCM_SHA256(RSA 2048)-A

+
TLS_RSA_WITED_AES_256_CBC_SHA(RSA 2048)-A

+
TLS_RSA_WITED_AES_256_CBC_SHA256(RSA 2048)-A

+
TLS_RSA_WITED_AES_256_GCM_SHA384(RSA 2048)-A





== 자세한 내용을 확인하십시오

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[클러스터에서 HTTPS에 FIPS 140-2를 사용하도록 설정합니다]
