---
permalink: storage/reference_per_node_network_settings_details.html 
sidebar: sidebar 
keywords: network settings, per-node UI, storage node, ui 
summary: 스토리지 노드 네트워크 설정을 변경하여 노드에 새 네트워크 속성 세트를 제공할 수 있습니다. 
---
= 노드별 UI에서 네트워크 설정 세부 정보
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드 네트워크 설정을 변경하여 노드에 새 네트워크 속성 세트를 제공할 수 있습니다.

노드에 로그인하면 * 네트워크 설정 * 페이지에서 스토리지 노드에 대한 네트워크 설정을 확인할 수 있습니다 (https://<node[] IP>:442/HCC/노드/네트워크 설정). Bond1G * (관리) 또는 * Bond10G * (스토리지) 설정을 선택할 수 있습니다. 다음 목록에서는 스토리지 노드가 사용 가능, 보류 중 또는 활성 상태일 때 수정할 수 있는 설정을 설명합니다.


NOTE: SolidFire 엔터프라이즈 SDS 클러스터를 실행 중인 경우 노드를 구축한 후에는 노드별 UI의 대부분의 네트워킹 설정을 수정할 수 없습니다.

* * 방법 *
+
인터페이스를 구성하는 데 사용되는 방법입니다. 가능한 방법:

+
** Loopback: IPv4 루프백 인터페이스를 정의하는 데 사용됩니다.
** Manual(수동): 기본적으로 구성이 수행되지 않는 인터페이스를 정의하는 데 사용됩니다.
** DHCP: DHCP를 통해 IP 주소를 가져오는 데 사용됩니다.
** 정적: 정적으로 할당된 IPv4 주소를 사용하여 이더넷 인터페이스를 정의하는 데 사용됩니다.


* * 링크 속도 *
+
가상 NIC가 협상하는 속도입니다.

* * IPv4 주소 *
+
eth0 네트워크의 IPv4 주소입니다.

* * IPv4 서브넷 마스크 *
+
IPv4 네트워크의 주소 부분.

* * IPv4 게이트웨이 주소 *
+
로컬 네트워크 외부로 패킷을 전송하기 위한 라우터 네트워크 주소입니다.

* * IPv6 주소 *
+
eth0 네트워크의 IPv6 주소입니다.

* * IPv6 게이트웨이 주소 *
+
로컬 네트워크 외부로 패킷을 전송하기 위한 라우터 네트워크 주소입니다.

* * MTU *
+
네트워크 프로토콜이 전송할 수 있는 최대 패킷 크기입니다. 1500보다 크거나 같아야 합니다. 두 번째 스토리지 NIC를 추가하는 경우 값은 9000이어야 합니다.

* DNS 서버 *
+
클러스터 통신에 사용되는 네트워크 인터페이스입니다.

* * 검색 도메인 *
+
시스템에서 사용할 수 있는 추가 MAC 주소를 검색합니다.

* * 본드 모드 *
+
다음 모드 중 하나일 수 있습니다.

+
** ActivePassive(기본값)
** ALB를 클릭합니다
** LACP


* * 상태 *
+
가능한 값:

+
** 업그레이드 실행
** 아래로
** 위로


* * 가상 네트워크 태그 *
+
가상 네트워크를 생성할 때 할당된 태그입니다.

* * 루트 *
+
연결된 인터페이스를 통해 특정 호스트 또는 네트워크에 대한 정적 라우트는 사용하도록 구성됩니다.


