---
permalink: storage/reference_per_node_cluster_settings_details.html 
sidebar: sidebar 
keywords: nodes, changing cluster settings, per-node UI 
summary: 클러스터 구성 후 스토리지 노드에 대한 클러스터 설정을 확인하고 노드 호스트 이름을 수정할 수 있습니다. 
---
= 노드별 UI에서 클러스터 설정 세부 정보
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 구성 후 스토리지 노드에 대한 클러스터 설정을 확인하고 노드 호스트 이름을 수정할 수 있습니다.

다음 목록에서는 노드별 UI의 * 클러스터 설정 * 페이지에 표시된 스토리지 노드에 대한 클러스터 설정을 설명합니다 (https://<node[] IP>:442/HCC/노드/클러스터 설정).


NOTE: SolidFire 엔터프라이즈 SDS 클러스터를 실행 중인 경우 노드를 구축한 후에는 노드별 UI의 대부분의 네트워킹 설정을 수정할 수 없습니다.

* * 역할 *
+
클러스터에서 노드의 역할 가능한 값:

+
** 스토리지: 스토리지 또는 Fibre Channel 노드
** 관리: 노드는 관리 노드입니다.


* * 호스트 이름 *
+
노드의 이름입니다.

* * 클러스터 *
+
클러스터의 이름입니다.

* * 클러스터 구성원 *
+
노드의 상태입니다. 가능한 값:

+
** 사용 가능: 노드에 연결된 클러스터 이름이 없으며 아직 클러스터의 일부가 아닙니다.
** 보류 중: 노드가 구성되었으며 지정된 클러스터에 추가할 수 있습니다. 노드를 액세스하는 데 인증이 필요하지 않습니다.
** PendingActive: 시스템이 노드에 호환되는 소프트웨어를 설치하는 중입니다. 완료되면 노드가 활성 상태로 이동합니다.
** Active(활성): 노드가 클러스터에 참여하고 있습니다. 노드를 수정하려면 인증이 필요합니다.


* * 버전 *
+
노드에서 실행되는 Element 소프트웨어의 버전입니다.

* * 통합 *
+
데이터베이스 앙상블의 일부인 노드입니다.

* * 노드 ID *
+
노드가 클러스터에 추가될 때 할당되는 ID입니다.

* * 클러스터 인터페이스 *
+
클러스터 통신에 사용되는 네트워크 인터페이스입니다.

* * 관리 인터페이스 *
+
관리 네트워크 인터페이스. 이 기본값은 Bond1G이지만 Bond10G도 사용할 수 있습니다.

* * 스토리지 인터페이스 *
+
Bond10G를 사용하는 스토리지 네트워크 인터페이스.

* * 암호화 가능 *
+
노드가 드라이브 암호화를 지원하는지 여부를 나타냅니다.


