---
permalink: storage/reference_monitor_volume_performance_details.html 
sidebar: sidebar 
keywords: volume performance 
summary: 'Element UI의 Reporting(보고) 탭에 있는 Volume Performance(볼륨 성능) 페이지에서 볼륨의 성능 통계를 볼 수 있습니다.' 
---
= 볼륨 성능 세부 정보입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element UI의 Reporting(보고) 탭에 있는 Volume Performance(볼륨 성능) 페이지에서 볼륨의 성능 통계를 볼 수 있습니다.

다음 목록에서는 사용 가능한 세부 사항을 설명합니다.

* * ID *
+
볼륨에 대한 시스템 생성 ID입니다.

* * 이름 *
+
볼륨을 생성할 때 볼륨에 지정한 이름입니다.

* * 계정 *
+
볼륨에 할당된 계정의 이름입니다.

* * 액세스 그룹 *
+
볼륨이 속한 볼륨 액세스 그룹 또는 그룹의 이름입니다.

* * 볼륨 활용률 *
+
클라이언트가 볼륨을 얼마나 사용하고 있는지 설명하는 백분율 값입니다.

+
가능한 값:

+
** 0 = 클라이언트가 볼륨을 사용하고 있지 않습니다
** 100 = 클라이언트가 최대값을 사용 중입니다
** 100 초과 = 클라이언트가 버스트를 사용 중입니다


* * 총 IOPS *
+
해당 볼륨에 대해 현재 실행 중인 총 IOPS(읽기 및 쓰기) 수입니다.

* * 읽기 IOPS *
+
해당 볼륨에 대해 현재 실행 중인 총 읽기 IOPS 수입니다.

* * 쓰기 IOPS *
+
해당 볼륨에 대해 현재 실행 중인 총 쓰기 IOPS 수입니다.

* * 총 처리량 *
+
현재 볼륨에 대해 실행 중인 총 처리량(읽기 및 쓰기)입니다.

* * 읽기 처리량 *
+
해당 볼륨에 대해 현재 실행 중인 총 읽기 처리량입니다.

* * 쓰기 처리량 *
+
해당 볼륨에 대해 현재 실행 중인 총 쓰기 처리량입니다.

* * 총 지연 시간 *
+
볼륨에 대한 읽기 및 쓰기 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다.

* * 읽기 지연 시간 *
+
마지막 500밀리초 동안 볼륨에 대한 읽기 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다.

* * 쓰기 지연 시간 *
+
마지막 500밀리초 동안 볼륨에 대한 쓰기 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다.

* * 대기열 길이 *
+
볼륨에 대한 미해결 읽기 및 쓰기 작업 수입니다.

* * 평균 IO 크기 *
+
최근 500밀리초 동안 볼륨에 대한 최근 I/O의 평균 크기(바이트)입니다.


