---
permalink: storage/reference_monitor_event_types.html 
sidebar: sidebar 
keywords: event types, monitor, event log 
summary: 시스템은 여러 유형의 이벤트를 보고합니다. 각 이벤트는 시스템이 완료한 작업입니다. 이벤트는 일상적인 이벤트, 정상적인 이벤트 또는 관리자 주의가 필요한 이벤트일 수 있습니다. 이벤트 로그 페이지의 이벤트 유형 열은 이벤트가 발생한 시스템의 일부를 나타냅니다. 
---
= 이벤트 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템은 여러 유형의 이벤트를 보고합니다. 각 이벤트는 시스템이 완료한 작업입니다. 이벤트는 일상적인 이벤트, 정상적인 이벤트 또는 관리자 주의가 필요한 이벤트일 수 있습니다. 이벤트 로그 페이지의 이벤트 유형 열은 이벤트가 발생한 시스템의 일부를 나타냅니다.


NOTE: 시스템은 이벤트 로그에 읽기 전용 API 명령을 기록하지 않습니다.

다음 목록에서는 이벤트 로그에 나타나는 이벤트 유형을 설명합니다.

* * apiEvent *
+
설정을 수정하는 API 또는 웹 UI를 통해 사용자가 시작한 이벤트입니다.

* * binAssignmentEvent *
+
데이터 저장소 할당과 관련된 이벤트입니다. 빈은 기본적으로 데이터를 보관하며 클러스터 전체에 매핑된 컨테이너입니다.

* * binSyncEvent *
+
블록 서비스 간의 데이터 재할당과 관련된 시스템 이벤트입니다.

* * bsCheckEvent *
+
Block 서비스 검사와 관련된 시스템 이벤트입니다.

* * bsKillEvent *
+
Block 서비스 종료와 관련된 시스템 이벤트입니다.

* * bulkOpEvent *
+
백업, 복원, 스냅샷 또는 클론과 같은 전체 볼륨에서 수행된 작업과 관련된 이벤트입니다.

* * cloneEvent *
+
볼륨 클론 생성과 관련된 이벤트입니다.

* * 클러스터 마스터 이벤트 *
+
클러스터 초기화 시 또는 노드 추가 또는 제거와 같은 클러스터 구성 변경 시 나타나는 이벤트입니다.

* [[csum_event]] * cSumEvent *
+
전체 체크섬 검증 중에 체크섬 불일치를 감지하는 것과 관련된 이벤트입니다.

+
체크섬 불일치를 감지하는 서비스는 자동으로 중지되며 이 이벤트를 생성한 후 다시 시작되지 않습니다.

* * 데이터 이벤트 *
+
데이터 읽기 및 쓰기와 관련된 이벤트입니다.

* * dbEvent *
+
클러스터의 앙상블 노드에 의해 유지되는 글로벌 데이터베이스와 관련된 이벤트입니다.

* * 드라이브 이벤트 *
+
드라이브 작업과 관련된 이벤트입니다.

* * encryptionAtRestEvent *
+
클러스터의 암호화 프로세스와 관련된 이벤트입니다.

* * ensembleEvent *
+
앙상블의 노드 수를 늘리거나 줄이는 것과 관련된 이벤트입니다.

* * 광섬유 채널 이벤트 *
+
노드의 구성 및 연결과 관련된 이벤트입니다.

* * gcEvent *
+
프로세스와 관련된 이벤트는 60분마다 실행되어 블록 드라이브에서 스토리지를 재확보할 수 있습니다. 이 프로세스를 가비지 수집이라고도 합니다.

* * ieEvent *
+
내부 시스템 오류입니다.

* * 설치 이벤트 *
+
자동 소프트웨어 설치 이벤트. 소프트웨어가 보류 중인 노드에 자동으로 설치됩니다.

* * iSCSIEvent *
+
시스템의 iSCSI 문제와 관련된 이벤트입니다.

* * limitEvent *
+
계정 또는 클러스터에 있는 볼륨 또는 가상 볼륨의 수가 허용되는 최대값에 근접하는 것과 관련된 이벤트입니다.

* *유지 관리 모드 이벤트*
+
노드 비활성화 등과 같은 노드 유지보수 모드와 관련된 이벤트입니다.

* [[network_event]] * networkEvent *
+
각 물리적 NIC(네트워크 인터페이스 카드) 인터페이스에 대한 네트워크 오류 보고와 관련된 이벤트입니다.

+
이러한 이벤트는 인터페이스에 대한 오류 수가 10분 모니터링 간격 동안 기본 임계값 1000을 초과할 때 트리거됩니다. 이러한 이벤트는 수신된 오류, 순환 중복 검사(CRC) 오류, 길이 오류, 오버런 오류 및 프레임 오류와 같은 네트워크 오류에 적용됩니다.

* * platformHardwareEvent *
+
하드웨어 장치에서 감지된 문제와 관련된 이벤트입니다.

* * 원격 클러스터 이벤트 *
+
원격 클러스터 페어링과 관련된 이벤트입니다.

* * 일정 이벤트 *
+
예약된 스냅샷과 관련된 이벤트입니다.

* 서비스 이벤트 *
+
시스템 서비스 상태와 관련된 이벤트입니다.

* * 슬라이스 이벤트 *
+
메타데이터 드라이브 또는 볼륨 제거와 같은 슬라이스 서버와 관련된 이벤트입니다.

+
볼륨이 할당된 서비스에 대한 정보를 포함하는 3가지 유형의 슬라이스 재할당 이벤트가 있습니다.

+
** 대칭 이동: 기본 서비스를 새 기본 서비스로 변경합니다
+
[listing]
----
sliceID oldPrimaryServiceID->newPrimaryServiceID
----
** 이동: 2차 서비스를 새 2차 서비스로 변경
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}->{newSecondaryServiceID(s)}
----
** 잘라내기: 서비스 집합에서 볼륨 제거
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}
----


* * snmpTrapEvent *
+
SNMP 트랩과 관련된 이벤트입니다.

* 상태 이벤트 *
+
시스템 통계와 관련된 이벤트입니다.

* * 이벤트 *
+
시스템 전송 서비스와 관련된 이벤트입니다.

* * 예기치 않은 예외 *
+
예기치 않은 시스템 예외와 관련된 이벤트입니다.

* * ureEvent *
+
스토리지 디바이스에서 읽는 동안 발생하는 복구할 수 없는 읽기 오류와 관련된 이벤트입니다.

* * 혈관 제공자 이벤트 *
+
VASA(vSphere APIs for Storage Awareness) Provider와 관련된 이벤트입니다.


