---
permalink: storage/task_per_node_run_system_tests.html 
sidebar: sidebar 
keywords: storage nodes, running system tests,s ystem tests, network settings, testing changes 
summary: 네트워크 구성에 변경한 후 네트워크 설정에 대한 변경 사항을 테스트할 수 있습니다. 테스트를 실행하여 스토리지 노드가 안정적이며 문제 없이 온라인 상태가 될 수 있는지 확인할 수 있습니다. 
---
= 노드별 UI를 사용하여 시스템 테스트를 실행합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크 구성에 변경한 후 네트워크 설정에 대한 변경 사항을 테스트할 수 있습니다. 테스트를 실행하여 스토리지 노드가 안정적이며 문제 없이 온라인 상태가 될 수 있는지 확인할 수 있습니다.

스토리지 노드의 노드별 UI에 로그인했습니다.

. 시스템 테스트 * 를 클릭합니다.
. 실행하려는 테스트 옆에 있는 * 테스트 실행 * 을 클릭하거나 * 모든 테스트 실행 * 을 선택합니다.
+

NOTE: 모든 테스트 작업을 실행하려면 시간이 오래 걸릴 수 있으며 NetApp Support 부서의 지시에 따라서만 수행해야 합니다.

+
** * 연결된 통합 테스트 *
+
데이터베이스 앙상블에 대한 연결을 테스트하고 확인합니다. 기본적으로 이 테스트에서는 노드가 연결된 클러스터에 대해 앙상블을 사용합니다. 또는 다른 앙상블을 제공하여 연결을 테스트할 수도 있습니다.

** * Mvip 연결 테스트 *
+
지정된 관리 가상 IP(MVIP) 주소를 ping하여 MVIP에 대한 간단한 API 호출을 실행하여 연결을 확인합니다. 기본적으로 이 테스트에서는 노드가 연결된 클러스터에 MVIP를 사용합니다.

** * 테스트 연결 Svip *
+
네트워크 어댑터에 설정된 MTU(Maximum Transmission Unit) 크기와 일치하는 ICMP(Internet Control Message Protocol) 패킷을 사용하여 지정된 SVIP(Storage Virtual IP) 주소를 ping합니다. 그런 다음 SVIP에 iSCSI 이니시에이터로 연결합니다. 기본적으로 이 테스트에서는 노드가 연결된 클러스터에 대해 SVIP를 사용합니다.

** * 하드웨어 구성 테스트 *
+
모든 하드웨어 구성이 올바른지 테스트하고, 펌웨어 버전이 올바른지 확인하고, 모든 드라이브가 설치되어 올바르게 실행 중인지 확인합니다. 이는 공장 테스트와 동일합니다.

+

NOTE: 이 테스트는 리소스 집약적이며 NetApp Support에서 요청한 경우에만 실행해야 합니다.

** * 로컬 연결 테스트 *
+
각 노드의 CIP(클러스터 IP)에 대해 Ping을 수행하여 클러스터의 다른 모든 노드에 대한 연결을 테스트합니다. 이 테스트는 노드가 액티브 클러스터의 일부인 경우에만 노드에 표시됩니다.

** * 테스트 찾기 클러스터 *
+
노드에서 클러스터 구성에 지정된 클러스터를 찾을 수 있는지 확인합니다.

** * 네트워크 구성 테스트 *
+
구성된 네트워크 설정이 시스템에서 사용 중인 네트워크 설정과 일치하는지 확인합니다. 이 테스트는 노드가 클러스터에 적극적으로 참여하는 경우 하드웨어 장애를 감지하기 위한 것이 아닙니다.

** * Ping 테스트 *
+
지정된 호스트 목록을 ping합니다. 지정된 호스트가 없으면 클러스터에 등록된 모든 노드 목록을 동적으로 구축하고 각 노드를 ping하여 간단한 접속으로 구성합니다.

** * 원격 연결 테스트 *
+
각 노드의 CIP(클러스터 IP)를 Ping하여 원격으로 연결된 클러스터의 모든 노드에 대한 연결을 테스트합니다. 이 테스트는 노드가 액티브 클러스터의 일부인 경우에만 노드에 표시됩니다.




