---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source, volume, snapmirror, dr, disaster, recovery 
summary: NetApp Element UI를 사용하여 원본 소스 볼륨을 재동기화하고 페일백할 수 있습니다. 이 섹션은 원래 소스 볼륨이 손실되었지만 원래 클러스터가 그대로 유지되는 시나리오에 적용됩니다. 새 클러스터로 복원하는 방법에 대한 자세한 내용은 NetApp Support 사이트 설명서를 참조하십시오. 
---
= 소스 볼륨이 더 이상 존재하지 않는 경우 장애 복구를 수행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element UI를 사용하여 원본 소스 볼륨을 재동기화하고 페일백할 수 있습니다. 이 섹션은 원래 소스 볼륨이 손실되었지만 원래 클러스터가 그대로 유지되는 시나리오에 적용됩니다. 새 클러스터로 복원하는 방법에 대한 자세한 내용은 NetApp Support 사이트 설명서를 참조하십시오.

.필요한 것
* Element 및 ONTAP 볼륨 간에 분리된 복제 관계가 있습니다.
* Element 볼륨이 복구할 수 없는 손실입니다.
* 원래 볼륨 이름이 찾을 수 없음 으로 표시됩니다.


.단계
. Element UI에서 페일오버를 수행하기 위해 끊은 관계를 찾습니다.
+
* 모범 사례: * SnapMirror 정책을 기록하고 원래의 부분 신뢰 관계에 대한 세부 사항을 예약합니다. 이 정보는 관계를 다시 생성할 때 필요합니다.

. Actions * 아이콘을 클릭하고 * Reverse Resync * 를 클릭합니다.
. 작업을 확인합니다.
+

NOTE: 역방향 재동기화 작업은 원래 소스 볼륨과 대상 볼륨의 역할이 반전되는 새 관계를 생성합니다. 이로 인해 원래 관계가 유지됨에 따라 두 개의 관계가 형성됩니다. 원래 볼륨이 더 이상 존재하지 않기 때문에 시스템은 원래 소스 볼륨과 동일한 볼륨 이름 및 볼륨 크기의 새로운 Element 볼륨을 생성합니다. 새 볼륨에는 SM-RECOVERY라는 기본 QoS 정책이 할당되며 SM-RECOVERY라는 기본 계정과 연결됩니다. 또한, SnapMirror에서 생성된 모든 볼륨의 계정 및 QoS 정책을 수동으로 편집하여 제거된 원래 소스 볼륨을 대체할 수 있습니다.

+
역방향 재동기화 작업의 일부로 최신 스냅샷의 데이터가 새 볼륨으로 전송됩니다. 대상 측의 활성 볼륨에 계속 액세스하여 데이터를 쓸 수 있지만 모든 호스트의 액티브 볼륨 연결을 끊고 SnapMirror 업데이트를 수행한 후에 원래 기본 관계를 이후의 단계에서 복구해야 합니다. 역방향 재동기화를 완료하고 대상 측의 볼륨에 연결된 활성 세션이 없는지, 그리고 최신 데이터가 원래 운영 볼륨에 있는지 확인한 후 다음 단계를 계속 수행하여 페일백을 완료하고 원래 운영 볼륨을 다시 활성화합니다.

. 역재동기화 작업 중에 생성된 역관계의 * 작업 * 아이콘을 클릭하고 * 중단 * 을 클릭합니다.
. 원본 볼륨이 없는 원본 관계의 * 작업 * 아이콘을 클릭하고 * 삭제 * 를 클릭합니다.
. 4단계에서 깬 역관계의 * 작업 * 아이콘을 클릭하고 * 역재동기화 * 를 클릭합니다.
. 이렇게 하면 소스 및 대상이 반전되고 원래 관계와 동일한 볼륨 소스 및 볼륨 대상과 관계가 형성됩니다.
. 작업 * 아이콘과 * 편집 * 을 클릭하여 이 관계를 원래의 QoS 정책 및 일정 설정과 함께 업데이트합니다.
. 이제 6단계에서 다시 동기화한 역 관계를 삭제하는 것이 안전합니다.




== 자세한 내용을 확인하십시오

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror 페일백 시나리오]
