---
permalink: storage/task_data_protection_edit_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, edit, modify 
summary: 기존 스냅샷 스케줄을 수정할 수 있습니다. 수정 후 다음 번에 스케줄이 실행될 때 업데이트된 속성이 사용됩니다. 원래 스케줄에 의해 생성된 모든 스냅샷은 스토리지 시스템에 남아 있습니다. 
---
= 스냅샷 스케줄을 편집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 스냅샷 스케줄을 수정할 수 있습니다. 수정 후 다음 번에 스케줄이 실행될 때 업데이트된 속성이 사용됩니다. 원래 스케줄에 의해 생성된 모든 스냅샷은 스토리지 시스템에 남아 있습니다.

.단계
. 데이터 보호 * > * 스케줄 * 을 클릭합니다.
. 변경할 일정에 대한 * 작업 * 아이콘을 클릭합니다.
. 결과 메뉴에서 * 편집 * 을 클릭합니다.
. 볼륨 ID CSV * 필드에서 스냅샷 작업에 현재 포함되어 있는 단일 볼륨 ID 또는 쉼표로 구분된 볼륨 ID 목록을 수정합니다.
. 일정을 일시 중지하거나 다시 시작하려면 다음 옵션 중에서 선택합니다.
+
** 활성 일정을 일시 중지하려면 * 수동 일정 일시 중지 * 목록에서 * 예 * 를 선택합니다.
** 일시 중지된 일정을 다시 시작하려면 * 수동 일정 일시 중지 * 목록에서 * 아니요 * 를 선택합니다.


. 원하는 경우 * New Schedule Name * (새 일정 이름 *) 필드에 일정에 대한 다른 이름을 입력합니다.
. 주별 또는 월의 다른 요일에 실행되도록 스케줄을 변경하려면 * Schedule Type * 을 선택하고 제공된 옵션에서 스케줄을 변경합니다.
. * 선택 사항: * 반복 일정 * 을 선택하여 스냅샷 일정을 무한정 반복합니다.
. * 선택 사항: * 새 스냅샷 이름 * 필드에 새 스냅샷의 이름을 입력하거나 수정합니다.
+
필드를 비워 두면 스냅샷 생성 날짜와 시간이 이름으로 사용됩니다.

. * 선택 사항: * 부모 볼륨이 페어링될 때 복제에 스냅샷이 캡처되도록 하려면 * 쌍으로 된 경우 복제에 스냅샷 포함 * 확인란을 선택합니다.
. 보존 설정을 변경하려면 다음 옵션 중에서 선택합니다.
+
** 영구 유지 * 를 클릭하여 시스템에 스냅샷을 무한정 유지합니다.
** 보존 기간 설정 * 을 클릭하고 날짜 스핀 상자를 사용하여 시스템에서 스냅샷을 보존할 기간을 선택합니다.


. 변경 내용 저장 * 을 클릭합니다.

