---
permalink: storage/task_system_manage_rekey_software_ear_master_key.html 
sidebar: sidebar 
keywords: element, rekey, encryption at rest, rekey master, replace key 
summary: Element API를 사용하여 기존 키를 다시 입력할 수 있습니다. 이 프로세스는 외부 키 관리 서버에 대한 새 대체 마스터 키를 만듭니다. 
---
= 소프트웨어 암호화 유휴 마스터 키를 다시 입력하다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element API를 사용하여 기존 키를 다시 입력할 수 있습니다. 이 프로세스는 외부 키 관리 서버에 대한 새 대체 마스터 키를 만듭니다. 마스터 키는 항상 새 마스터 키로 대체되며 복제 또는 덮어쓰기가 되지 않습니다.

다음 절차 중 하나로 키를 다시 입력하다

* 내부 키 관리에서 외부 키 관리로 변경 작업의 일부로 새 키를 만듭니다.
* 보안 관련 이벤트에 대한 대응 또는 보호 기능으로 새 키를 생성합니다.



NOTE: 이 프로세스는 비동기식이며 키를 다시 입력하다 를 사용할 수 있습니다 link:../api/reference_element_api_getasyncresult.html["GetAsyncResult 를 참조하십시오"] 프로세스가 완료된 시점을 확인하기 위해 시스템을 폴링하는 방법입니다.

.무엇을 &#8217;필요로 할거야
* 를 사용하여 저장 시 소프트웨어 암호화를 활성화했습니다 link:../api/reference_element_api_createcluster.html["클러스터 생성"] 볼륨에 포함되어 있지 않고 I/O가 없는 새 클러스터의 방법입니다 사용 link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["9510c8e68784d05acbae2e947dde3cd8"] 계속하기 전에 상태가 '활성화됨'인지 확인합니다.
* 있습니다 link:../storage/task_system_manage_key_set_up_external_key_management.html["트러스트 관계를 설정했습니다"] SolidFire 클러스터와 EKS(외부 키 서버) 간. 를 실행합니다 link:../api/reference_element_api_testkeyserverkmip.html["TestKeyProviderKmip 을 참조하십시오"] 키 공급자에 대한 연결이 설정되었는지 확인하는 방법입니다.


.단계
. 를 실행합니다 link:../api/reference_element_api_listkeyserverskmip.html["ListKeyProvidersKmip 을 참조하십시오"] 키 공급자 ID('keyProviderID')를 명령 및 복사합니다.
. 를 실행합니다 link:../api/reference_element_api_rekeysoftwareencryptionatrestmasterkey.html["RekeySoftwareEncryptionAtRestMasterKey를 참조하십시오"] 이전 단계에서 키 공급자의 ID 번호로 keyManagementType 매개 변수를 external로, keyProviderID로 사용:
+
[listing]
----
{
 "method": "rekeysoftwareencryptionatrestmasterkey",
 "params": {
   "keyManagementType": "external",
   "keyProviderID": "<ID number>"
 }
}
----
. RekeySoftwareEncryptionAtRestMasterKey 명령 응답에서 asyncHandle 값을 복사합니다.
. 를 실행합니다 link:../api/reference_element_api_getasyncresult.html["GetAsyncResult 를 참조하십시오"] 이전 단계의 asyncHandle 값을 사용하여 명령을 실행하여 구성 변경을 확인합니다. 명령 응답에서 이전 마스터 키 구성이 새 키 정보로 업데이트되었음을 확인할 수 있습니다. 나중에 사용할 수 있도록 새 키 공급자 ID를 복사합니다.
+
[listing]
----
{
   "id": null,
   "result": {
     "createTime": "2021-01-01T22:29:18Z",
     "lastUpdateTime": "2021-01-01T22:45:51Z",
     "result": {
       "keyToDecommission": {
         "keyID": "<value>",
         "keyManagementType": "internal"
     },
     "newKey": {
       "keyID": "<value>",
       "keyManagementType": "external",
       "keyProviderID": <value>
     },
     "operation": "Rekeying Master Key. Master Key management being transferred from Internal Key Management to External Key Management with keyProviderID=<value>",
     "state": "Ready"
   },
   "resultType": "RekeySoftwareEncryptionAtRestMasterKey",
   "status": "complete"
}
----
. GetSoftwareEncryptionatRestInfo 명령을 실행하여 keyProviderID를 포함한 새 키 세부 정보가 업데이트되었는지 확인합니다.
+
[listing]
----
{
   "id": null,
   "result": {
     "masterKeyInfo": {
       "keyCreatedTime": "2021-01-01T22:29:18Z",
       "keyID": "<updated value>",
       "keyManagementType": "external",
       "keyProviderID": <value>
     },
     "rekeyMasterKeyAsyncResultID": <value>
     "status": "enabled",
     "version": 1
   },
}
----


[discrete]
== 자세한 내용을 확인하십시오

* link:../api/concept_element_api_about_the_api.html["Element API를 사용하여 스토리지를 관리합니다"]
* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 리소스 페이지 를 참조하십시오"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

