---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: 보안 액세스를 위해 이니시에이터를 볼륨 컬렉션에 매핑하여 볼륨 액세스 그룹을 생성할 수 있습니다. 그런 다음 계정 CHAP 이니시에이터 암호 및 대상 암호를 사용하여 그룹의 볼륨에 대한 액세스 권한을 부여할 수 있습니다. 
---
= 볼륨 액세스 그룹을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 액세스를 위해 이니시에이터를 볼륨 컬렉션에 매핑하여 볼륨 액세스 그룹을 생성할 수 있습니다. 그런 다음 계정 CHAP 이니시에이터 암호 및 대상 암호를 사용하여 그룹의 볼륨에 대한 액세스 권한을 부여할 수 있습니다.

이니시에이터 기반 CHAP를 사용하는 경우 볼륨 액세스 그룹의 단일 이니시에이터에 대한 CHAP 자격 증명을 추가하여 보안을 강화할 수 있습니다. 따라서 이미 존재하는 볼륨 액세스 그룹에 이 옵션을 적용할 수 있습니다.

.단계
. 관리 * > * 액세스 그룹 * 을 클릭합니다.
. Create Access Group * 을 클릭합니다.
. 이름 * 필드에 볼륨 액세스 그룹의 이름을 입력합니다.
. 다음 방법 중 하나로 볼륨 액세스 그룹에 이니시에이터를 추가합니다.
+
[cols="25,75"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
Fibre Channel 이니시에이터 추가
 a| 
.. 이니시에이터 추가 아래의 Unbound Fibre Channel 이니시에이터 목록에서 기존 Fibre Channel 이니시에이터를 선택합니다.
.. FC 이니시에이터 추가 * 를 클릭합니다.
+

NOTE: 이 단계에서 * 이니시에이터 생성 * 링크를 클릭하고 이니시에이터 이름을 입력한 다음 * 생성 * 을 클릭하면 이니시에이터를 생성할 수 있습니다. 이니시에이터 목록을 생성하면 이니시에이터가 자동으로 이니시에이터 목록에 추가됩니다.



형식의 예는 다음과 같습니다.

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
iSCSI 이니시에이터 추가
 a| 
이니시에이터 추가 아래의 이니시에이터 목록에서 기존 이니시에이터를 선택합니다. * 참고: * 이 단계에서 * 이니시에이터 생성 * 링크를 클릭하고 이니시에이터 이름을 입력한 다음 * 생성 * 을 클릭하면 이니시에이터를 생성할 수 있습니다. 이니시에이터 목록을 생성하면 이니시에이터가 자동으로 이니시에이터 목록에 추가됩니다.

형식의 예는 다음과 같습니다.

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: Management * > * Volumes * > * Active * 목록의 볼륨에 대한 Actions 메뉴에서 * View Details * 를 선택하여 각 볼륨의 이니시에이터 IQN을 찾을 수 있습니다.

이니시에이터를 수정할 때 requiredCHAP 속성을 True로 전환하면 타겟 이니시에이터 암호를 설정할 수 있습니다. 자세한 내용은 ModifyInitiator API 메서드에 대한 API 정보를 참조하십시오.

link:../api/index.html["Element API를 사용하여 스토리지를 관리합니다"]

|===
. * 선택 사항: * 필요에 따라 이니시에이터를 더 추가합니다.
. Add Volumes 아래의 * Volumes * 목록에서 볼륨을 선택합니다.
+
볼륨이 * Attached Volumes * 목록에 나타납니다.

. * 선택 사항: * 필요에 따라 볼륨을 더 추가합니다.
. Create Access Group * 을 클릭합니다.




== 자세한 내용을 확인하십시오

xref:task_data_manage_vol_access_group_add_volumes.adoc[액세스 그룹에 볼륨을 추가합니다]
