---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: 원격 클러스터에 대한 클러스터 관리자 자격 증명이 있는 경우 원격 클러스터의 다른 볼륨과 볼륨을 페어링할 수 있습니다. 
---
= 볼륨 ID를 사용하여 볼륨을 페어링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 클러스터에 대한 클러스터 관리자 자격 증명이 있는 경우 원격 클러스터의 다른 볼륨과 볼륨을 페어링할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 볼륨이 포함된 클러스터가 페어링되었는지 확인합니다.
* 원격 클러스터에 새 볼륨을 생성합니다.
+

NOTE: 페어링 프로세스 후 복제 소스와 타겟을 할당할 수 있습니다. 복제 소스 또는 타겟은 볼륨 쌍의 볼륨일 수 있습니다. 데이터를 포함하지 않고 볼륨의 크기, 블록 크기 설정(512e 또는 4K) 및 QoS 구성과 같은 소스 볼륨의 정확한 특성을 가진 타겟 볼륨을 생성해야 합니다. 기존 볼륨을 복제 타겟으로 할당할 경우 해당 볼륨의 데이터를 덮어씁니다. 타겟 볼륨의 크기는 소스 볼륨과 같거나 더 클 수 있지만 크기는 작을 수 없습니다.

* 타겟 볼륨 ID를 확인합니다.


.단계
. Management * > * Volumes * 를 선택합니다.
. 페어링할 볼륨의 * 작업 * 아이콘을 클릭합니다.
. 페어링 * 을 클릭합니다.
. 볼륨 페어링 * 대화 상자에서 * 페어링 시작 * 을 선택합니다.
. 원격 클러스터에 액세스할 수 있음을 나타내려면 * I DO * 를 선택합니다.
. 목록에서 * 복제 모드 * 를 선택합니다.
+
** * 실시간(비동기식) *: 소스 클러스터에서 커밋된 쓰기가 클라이언트에 확인됩니다.
** * 실시간(동기식) *: 쓰기가 소스 및 타겟 클러스터 모두에서 커밋된 후 클라이언트에 인식됩니다.
** * 스냅샷만 *: 소스 클러스터에서 생성된 스냅샷만 복제됩니다. 소스 볼륨의 활성 쓰기는 복제되지 않습니다.


. 목록에서 원격 클러스터를 선택합니다.
. 원격 볼륨 ID를 선택합니다.
. 페어링 시작 * 을 클릭합니다.
+
시스템에서 원격 클러스터의 Element UI에 연결되는 웹 브라우저 탭을 엽니다. 클러스터 관리자 자격 증명을 사용하여 원격 클러스터에 로그온해야 할 수 있습니다.

. 원격 클러스터의 Element UI에서 * Complete Pairing * 을 선택합니다.
. 볼륨 페어링 확인 * 에서 세부 정보를 확인합니다.
. 페어링 완료 * 를 클릭합니다.
+
페어링을 확인한 후 두 클러스터는 페어링을 위해 볼륨을 연결하는 프로세스를 시작합니다. 페어링 프로세스 중에 * 볼륨 쌍 * 창의 * 볼륨 상태 * 열에 메시지가 표시됩니다. 볼륨 쌍 소스와 타겟이 할당될 때까지 볼륨 페어에 PausedMisconfigured가 표시됩니다.

+
페어링을 완료한 후 볼륨 테이블을 새로 고쳐 페어링된 볼륨에 대한 * Actions * 목록에서 * Pair * 옵션을 제거하는 것이 좋습니다. 테이블을 새로 고치지 않으면 * Pair * 옵션을 선택할 수 있습니다. Pair * 옵션을 다시 선택하면 새 탭이 열리고 볼륨이 이미 페어링된 것이므로 Element UI 페이지의 * Pair Volume * (볼륨 페어링 *) 창에 '스타볼륨 페어링 실패: xVolumeAlreadyPagitting' 오류 메시지가 표시됩니다.





== 자세한 내용을 확인하십시오

* xref:reference_replication_volume_pairing_messages.adoc[볼륨 페어링 메시지]
* xref:reference_replication_volume_pairing_warnings.adoc[볼륨 페어링 경고]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[복제 소스와 타겟을 페어링된 볼륨에 할당합니다]

