---
permalink: storage/task_snapmirror_create_an_endpoint.html 
sidebar: sidebar 
keywords: endpoints, create, snapmirror, ui 
summary: 관계를 만들려면 NetApp Element UI에서 SnapMirror 끝점을 만들어야 합니다. 
---
= SnapMirror 끝점을 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관계를 만들려면 NetApp Element UI에서 SnapMirror 끝점을 만들어야 합니다.

SnapMirror 엔드포인트는 Element 소프트웨어를 실행하는 클러스터의 복제 타겟 역할을 하는 ONTAP 클러스터입니다. SnapMirror 관계를 생성하기 전에 먼저 SnapMirror 끝점을 만듭니다.

Element 소프트웨어를 실행하는 스토리지 클러스터에서 SnapMirror 엔드포인트를 최대 4개 생성하고 관리할 수 있습니다.


NOTE: 기존 끝점이 원래 API를 사용하여 생성되었고 자격 증명이 저장되지 않은 경우 요소 UI에서 끝점을 보고 그 존재를 확인할 수 있지만 Element UI를 사용하여 관리할 수는 없습니다. 그런 다음 이 끝점은 Element API를 통해서만 관리할 수 있습니다.

API 메소드에 대한 자세한 내용은 를 참조하십시오 link:../api/index.html["Element API를 사용하여 스토리지를 관리합니다"].

.무엇을 &#8217;필요로 할거야
* 스토리지 클러스터의 Element UI에서 SnapMirror를 사용하도록 설정해야 합니다.
* 끝점에 대한 ONTAP 자격 증명을 알고 있습니다.


.단계
. 데이터 보호 * > * SnapMirror 엔드포인트 * 를 클릭합니다.
. 끝점 만들기 * 를 클릭합니다.
. 새 엔드포인트 생성 * 대화 상자에서 ONTAP 시스템의 클러스터 관리 IP 주소를 입력합니다.
. 끝점과 연결된 ONTAP 관리자 자격 증명을 입력합니다.
. 추가 세부 정보 검토:
+
** LIF: Element와 통신하는 데 사용되는 ONTAP 인터클러스터 논리 인터페이스를 나열합니다.
** 상태: SnapMirror 끝점의 현재 상태를 표시합니다. 가능한 값은 연결, 연결 해제 및 관리되지 않는 값입니다.


. 끝점 만들기 * 를 클릭합니다.

