---
permalink: storage/task_monitor_system_alerts.html 
sidebar: sidebar 
keywords: system alerts, view, cluster faults, system errors 
summary: 시스템의 클러스터 장애 또는 오류에 대한 알림을 볼 수 있습니다. 경고는 정보, 경고 또는 오류일 수 있으며 클러스터의 실행 상태를 나타내는 좋은 지표입니다. 대부분의 오류는 자동으로 해결됩니다. 
---
= 시스템 경고를 봅니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템의 클러스터 장애 또는 오류에 대한 알림을 볼 수 있습니다. 경고는 정보, 경고 또는 오류일 수 있으며 클러스터의 실행 상태를 나타내는 좋은 지표입니다. 대부분의 오류는 자동으로 해결됩니다.

ListClusterFats API 메서드를 사용하여 경고 모니터링을 자동화할 수 있습니다. 이렇게 하면 발생한 모든 경고에 대한 알림을 받을 수 있습니다.

. Element UI에서 * Reporting * > * Alerts * 를 선택합니다.
+
시스템은 30초마다 페이지의 경고를 새로 고칩니다.

+
모든 이벤트에 대해 다음 정보가 표시됩니다.

+
|===


| 항목 | 설명 


 a| 
ID입니다
 a| 
클러스터 경고와 관련된 고유 ID입니다.



 a| 
심각도입니다
 a| 
알림의 중요도입니다. 가능한 값:

** 경고: 곧 주의가 필요할 수 있는 사소한 문제입니다. 시스템 업그레이드는 여전히 허용됩니다.
** 오류: 성능 저하 또는 고가용성(HA)을 잃을 수 있는 장애입니다. 그렇지 않으면 오류는 서비스에 영향을 주지 않습니다.
** 위험: 서비스에 영향을 미치는 심각한 장애입니다. 시스템에서 API 또는 클라이언트 I/O 요청을 처리할 수 없습니다. 이 상태에서 작동하면 데이터가 손실될 수 있습니다.
** 모범 사례: 권장되는 시스템 구성 모범 사례는 사용되지 않습니다.




 a| 
유형
 a| 
고장이 영향을 미치는 구성 요소입니다. 노드, 드라이브, 클러스터, 서비스 또는 볼륨일 수 있습니다.



 a| 
노드
 a| 
이 장애가 참조하는 노드의 노드 ID입니다. 노드 및 드라이브 장애에 대해 포함되며, 그렇지 않을 경우 -(대시)로 설정됩니다.



 a| 
드라이브 ID입니다
 a| 
이 결함이 참조하는 드라이브의 드라이브 ID입니다. 드라이브 고장에 대해 포함되며, 그렇지 않으면 -(대시)로 설정됩니다.



 a| 
오류 코드
 a| 
고장의 원인을 나타내는 설명 코드입니다.



 a| 
세부 정보
 a| 
고장에 대한 설명과 추가 세부 정보



 a| 
날짜
 a| 
고장이 기록된 날짜 및 시간입니다.

|===
. 개별 경고에 대한 정보를 보려면 * 세부 정보 표시 * 를 클릭합니다.
. 페이지에 있는 모든 경고의 세부 정보를 보려면 자세히 열을 클릭합니다.
+
시스템에서 경고를 해결한 후에는 해결된 날짜를 포함한 모든 경고 정보가 해결된 영역으로 이동됩니다.





== 자세한 내용을 확인하십시오

* xref:reference_monitor_cluster_fault_codes.adoc[클러스터 고장 코드]
* link:../api/index.html["Element API를 사용하여 스토리지를 관리합니다"]

