---
permalink: storage/task_system_manage_fips_identify_nodes_ready_for_fips_drives.html 
sidebar: sidebar 
keywords: fips, security, federal information processing standards, 140-2 
summary: NetApp Element 소프트웨어 GetFipsReport API 메서드를 사용하여 스토리지 클러스터의 모든 노드가 FIPS 드라이브를 지원할 준비가 되었는지 확인해야 합니다. 
---
= 노드가 FIPS 드라이브 기능을 지원할 수 있는지 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element 소프트웨어 GetFipsReport API 메서드를 사용하여 스토리지 클러스터의 모든 노드가 FIPS 드라이브를 지원할 준비가 되었는지 확인해야 합니다.

결과 보고서에는 다음 상태 중 하나가 표시됩니다.

* 없음: 노드가 FIPS 드라이브 기능을 지원할 수 없습니다.
* 부분: 노드가 FIPS를 지원하지만 모든 드라이브가 FIPS 드라이브는 아닙니다.
* 준비됨: 노드가 FIPS를 지원하며 모든 드라이브가 FIPS 드라이브로 장착되거나 드라이브가 없습니다.


.단계
. Element API를 사용하여 스토리지 클러스터의 노드와 드라이브가 다음을 입력하여 FIPS 드라이브를 사용할 수 있는지 확인합니다.
+
게피프스보고서

. Ready(준비) 상태가 표시되지 않은 노드를 확인하여 결과를 검토합니다.
. Ready 상태가 표시되지 않은 노드의 경우 드라이브가 FIPS 드라이브 기능을 지원할 수 있는지 확인합니다.
+
** Element API를 사용하여 'GetHardwareList'를 입력합니다
** DriveEncryptionCapabilityType * 의 값을 확인합니다. "FIPS"인 경우 하드웨어에서 FIPS 드라이브 기능을 지원할 수 있습니다.
+
자세한 내용을 확인하세요 `GetFipsReport` 또는 `ListDriveHardware` 에서 link:../api/concept_element_api_about_the_api.html["요소 API 참조입니다"].



. 드라이브가 FIPS 드라이브 기능을 지원할 수 없는 경우 하드웨어를 FIPS 하드웨어(노드 또는 드라이브)로 교체합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

