---
permalink: storage/task_system_manage_nodes_adding_a_node_to_a_cluster.html 
sidebar: sidebar 
keywords: nodes, add, config, cluster, pending, pairs, capacity, rule 
summary: 더 많은 스토리지가 필요하거나 클러스터를 생성한 후에 클러스터에 노드를 추가할 수 있습니다. 노드의 전원을 처음 켤 때는 초기 구성이 필요합니다. 노드가 구성되면 보류 중인 노드 목록에 나타나고 클러스터에 추가할 수 있습니다. 
---
= 클러스터에 노드를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
더 많은 스토리지가 필요하거나 클러스터를 생성한 후에 클러스터에 노드를 추가할 수 있습니다. 노드의 전원을 처음 켤 때는 초기 구성이 필요합니다. 노드가 구성되면 보류 중인 노드 목록에 나타나고 클러스터에 추가할 수 있습니다.

클러스터의 각 노드에 있는 소프트웨어 버전이 호환되어야 합니다. 클러스터에 노드를 추가하면 클러스터는 필요에 따라 새 노드에 NetApp Element 소프트웨어의 클러스터 버전을 설치합니다.

기존 클러스터에 용량을 작거나 큰 노드를 추가할 수 있습니다. 클러스터에 더 큰 노드 용량을 추가하여 용량을 확장할 수 있습니다. 더 작은 노드를 포함하는 클러스터에 더 큰 노드를 쌍으로 추가해야 합니다. 따라서 큰 노드 중 하나에 장애가 발생할 경우 이중 Helix가 데이터를 이동할 수 있는 충분한 공간이 확보됩니다. 더 작은 노드 용량을 더 큰 노드 클러스터에 추가하여 성능을 향상할 수 있습니다.


NOTE: 새로 추가된 노드가 전체 클러스터 용량의 50% 이상을 차지하는 경우 이 노드의 일부 용량을 사용할 수 없게 되어 용량 규칙을 준수합니다("고립됨"). 이는 더 많은 스토리지가 추가될 때까지 유지됩니다. 용량 규칙에 불복종하는 매우 큰 노드가 추가되면 이전에 고립된 노드는 더 이상 고립되지 않고 새로 추가된 노드는 고립됩니다. 이러한 상황이 발생하지 않도록 용량을 항상 쌍으로 추가해야 합니다. 노드가 고립되면 strandedCapacity 클러스터 장애가 throw됩니다.

https://www.youtube.com/embed/2smVHWkikXY?rel=0["NetApp 비디오: 기업 요건에 맞게 확장: SolidFire 클러스터 확장"^]

NetApp HCI 어플라이언스에 노드를 추가할 수 있습니다.

.단계
. 클러스터 * > * 노드 * 를 선택합니다.
. 보류 중인 노드 목록을 보려면 * Pending * (보류 중 *)을 클릭합니다.
+
노드 추가 프로세스가 완료되면 활성 노드 목록에 나타납니다. 그 때까지 보류 중인 노드가 보류 중인 활성 목록에 나타납니다.

+
SolidFire는 클러스터에 추가할 때 보류 중인 노드에 클러스터의 Element 소프트웨어 버전을 설치합니다. 이 작업은 몇 분 정도 걸릴 수 있습니다.

. 다음 중 하나를 수행합니다.
+
** 개별 노드를 추가하려면 추가할 노드에 대한 * 작업 * 아이콘을 클릭합니다.
** 여러 노드를 추가하려면 추가할 노드의 확인란을 선택한 다음 * 대량 작업 * 을 선택합니다. * 참고: * 추가하려는 노드에 클러스터에서 실행 중인 버전과 다른 버전의 Element 소프트웨어가 있는 경우 클러스터는 노드를 클러스터 마스터에서 실행 중인 Element 소프트웨어 버전으로 비동기식으로 업데이트합니다. 노드가 업데이트되면 자동으로 클러스터에 추가됩니다. 이 비동기 프로세스 중에 노드는 pendingActive 상태가 됩니다.


. 추가 * 를 클릭합니다.
+
노드가 활성 노드 목록에 나타납니다.





== 자세한 내용을 확인하십시오

xref:concept_system_manage_nodes_node_versioning_and_compatibility.adoc[노드 버전 관리 및 호환성]
