---
permalink: storage/task_data_manage_vvol_enable_virtual_volumes.html 
sidebar: sidebar 
keywords: virtual volumes, enable, functionality on the cluster, vvols 
summary: 'NetApp Element 소프트웨어를 통해 VVol(vSphere Virtual Volumes) 기능을 수동으로 활성화해야 합니다. Element 소프트웨어 시스템에는 기본적으로 VVOL 기능이 비활성화되어 있으며 새 설치 또는 업그레이드의 일부로 자동 활성화되지 않습니다. VVOL 기능을 활성화하는 것은 일회성 구성 작업입니다.' 
---
= 가상 볼륨을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element 소프트웨어를 통해 VVOL(vSphere 가상 볼륨) 기능을 수동으로 활성화해야 합니다. Element 소프트웨어 시스템에는 기본적으로 VVOL 기능이 비활성화되어 있으며 새 설치 또는 업그레이드의 일부로 자동 활성화되지 않습니다. VVOL 기능을 활성화하는 것은 일회성 구성 작업입니다.

.필요한 것
* 클러스터는 Element 9.0 이상을 실행해야 합니다.
* 클러스터는 VVol과 호환되는 ESXi 6.0 이상 환경에 연결되어야 합니다.
* Element 11.3 이상을 사용하는 경우 클러스터가 ESXi 6.0 업데이트 3 이상 환경에 연결되어 있어야 합니다.



IMPORTANT: vSphere 가상 볼륨 기능을 활성화하면 Element 소프트웨어 구성이 영구적으로 변경됩니다. 클러스터가 VMware ESXi VVol 호환 환경에 연결된 경우에만 VVol 기능을 활성화해야 합니다. 시스템에서 모든 데이터를 삭제하는 공장 출하 시 이미지로 클러스터를 되돌리시기만 하면 VVOL 기능을 비활성화하고 기본 설정을 복원할 수 있습니다.

.단계
. 클러스터 * > * 설정 * 을 선택합니다.
. 가상 볼륨에 대한 클러스터별 설정을 찾습니다.
. Enable Virtual Volumes * 를 클릭합니다.
. Yes * 를 클릭하여 가상 볼륨 구성 변경을 확인합니다.
+
요소 UI에 * VVol * 탭이 나타납니다.

+

NOTE: VVOL 기능이 활성화되면 SolidFire 클러스터가 VASA Provider를 시작하고, VASA 트래픽에 대해 포트 8444를 열고, vCenter 및 모든 ESXi 호스트에서 검색할 수 있는 프로토콜 엔드포인트를 생성합니다.

. 클러스터 * > * 설정 * 의 가상 볼륨(VVol) 설정에서 VASA Provider URL을 복사합니다. 이 URL을 사용하여 vCenter에 VASA Provider를 등록합니다.
. VVol * > * Storage Containers * 에서 저장소 컨테이너를 만듭니다.
+

NOTE: VM을 VVOL 데이터 저장소에 프로비저닝할 수 있도록 스토리지 컨테이너를 하나 이상 생성해야 합니다.

. VVol * > * Protocol Endpoints * 를 선택합니다.
. 클러스터의 각 노드에 대해 프로토콜 엔드포인트가 생성되었는지 확인합니다.
+

NOTE: vSphere에 추가 구성 작업이 필요합니다. VMware vSphere Virtual Volumes for SolidFire Storage 구성 가이드 _ 를 참조하여 vCenter에 VASA Provider를 등록하고, VVOL 데이터 저장소를 생성 및 관리하고, 정책에 따라 스토리지를 관리하십시오.





== 자세한 내용을 확인하십시오

https://www.netapp.com/pdf.html?item=/media/10516-tr4642pdf.pdf["SolidFire 스토리지용 VMware vSphere 가상 볼륨 구성 가이드 를 참조하십시오"^]
