---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: '노드에 대한 원격 IPMI 액세스 권한이 있는 즉시 기본 IPMI(Intelligent Platform Management Interface) 관리자 암호를 변경할 수 있습니다. 설치 업데이트가 있는 경우 이 작업을 수행할 수 있습니다.' 
---
= 노드의 기본 IPMI 암호를 변경합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
노드에 대한 원격 IPMI 액세스 권한이 있는 즉시 기본 IPMI(Intelligent Platform Management Interface) 관리자 암호를 변경할 수 있습니다. 설치 업데이트가 있는 경우 이 작업을 수행할 수 있습니다.

노드에 대한 IPM 액세스 구성에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["각 노드에 대해 IPMI를 구성합니다"^].

다음 노드의 IPM 암호를 변경할 수 있습니다.

* H410S 노드
* H610S 노드




== H410S 노드의 기본 IPMI 암호를 변경합니다

IPMI 네트워크 포트를 구성하는 즉시 각 스토리지 노드에서 IPMI 관리자 계정의 기본 암호를 변경해야 합니다.

각 스토리지 노드에 대해 IPMI IP 주소를 구성해야 합니다.

.단계
. IPMI 네트워크에 연결할 수 있는 컴퓨터에서 웹 브라우저를 열고 해당 노드의 IPMI IP 주소를 찾습니다.
. 로그인 프롬프트에 사용자 이름 admin과 암호 admin을 입력합니다.
. 로그인 시 * 구성 * 탭을 클릭합니다.
. 사용자 * 를 클릭합니다.
. 'admin' 사용자를 선택하고 'Modify User'를 클릭합니다.
. 암호 변경 * 확인란을 선택합니다.
. 암호 * 및 * 암호 확인 * 필드에 새 암호를 입력합니다.
. 수정 * 을 클릭한 다음 * 확인 * 을 클릭합니다.
. 기본 IPMI 암호가 있는 다른 H410S 노드에 대해 이 절차를 반복합니다.




== H610S 노드의 기본 IPMI 암호를 변경합니다

IPMI 네트워크 포트를 구성하는 즉시 각 스토리지 노드에서 IPMI 관리자 계정의 기본 암호를 변경해야 합니다.

각 스토리지 노드에 대해 IPMI IP 주소를 구성해야 합니다.

.단계
. IPMI 네트워크에 연결할 수 있는 컴퓨터에서 웹 브라우저를 열고 해당 노드의 IPMI IP 주소를 찾습니다.
. 로그인 프롬프트에 root라는 사용자 이름과 암호 calvin을 입력합니다.
. 로그인하면 페이지 왼쪽 상단의 메뉴 탐색 아이콘을 클릭하여 측면 표시줄 서랍을 엽니다.
. 설정 * 을 클릭합니다.
. 사용자 관리 * 를 클릭합니다.
. 목록에서 * Administrator * 사용자를 선택합니다.
. 암호 변경 * 확인란을 활성화합니다.
. 암호 * 및 * 암호 확인 * 필드에 강력한 새 암호를 입력합니다.
. 페이지 하단의 * 저장 * 을 클릭합니다.
. 기본 IPMI 암호가 있는 다른 H610S 노드에 대해 이 절차를 반복합니다.




== 자세한 내용을 확인하십시오

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

