---
permalink: storage/task_system_manage_cluster_ntp_configure.html 
sidebar: sidebar 
keywords: ntp, cluster, query, fqdn, dns server 
summary: '클러스터의 각 노드에 업데이트를 위해 NTP(Network Time Protocol) 서버를 쿼리하도록 지시할 수 있습니다. 클러스터가 구성된 서버에만 접속하여 NTP 정보를 요청합니다.' 
---
= 쿼리할 클러스터에 대한 네트워크 시간 프로토콜 서버를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 각 노드에 업데이트를 위해 NTP(Network Time Protocol) 서버를 쿼리하도록 지정할 수 있습니다. 클러스터가 구성된 서버에만 접속하여 NTP 정보를 요청합니다.

로컬 NTP 서버를 가리키도록 클러스터의 NTP를 구성합니다. IP 주소 또는 FQDN 호스트 이름을 사용할 수 있습니다. 클러스터 생성 시 기본 NTP 서버가 us.pool.ntp.org 으로 설정되지만 SolidFire 클러스터의 물리적 위치에 따라 이 사이트에 연결할 수 없는 경우도 있습니다.

FQDN 사용은 개별 스토리지 노드의 DNS 설정이 제대로 설정되어 있고 작동 중인지 여부에 따라 달라집니다. 이렇게 하려면 모든 스토리지 노드에서 DNS 서버를 구성하고 네트워크 포트 요구 사항 페이지를 검토하여 포트가 열려 있는지 확인합니다.

최대 5개의 서로 다른 NTP 서버를 입력할 수 있습니다.


NOTE: IPv4와 IPv6 주소를 모두 사용할 수 있습니다.

.필요한 것
이 설정을 구성하려면 클러스터 관리자 권한이 있어야 합니다.

.단계
. 서버 설정에서 IP 및/또는 FQDN 목록을 구성합니다.
. DNS가 노드에 올바르게 설정되었는지 확인합니다.
. Cluster * > * Settings * 를 클릭합니다.
. Network Time Protocol Settings(네트워크 시간 프로토콜 설정)에서 표준 NTP 구성을 사용하는 * No *(아니요 *)를 선택합니다.
. 변경 내용 저장 * 을 클릭합니다.




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

