---
permalink: storage/task_data_manage_vol_access_group_add_a_single_initiator.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add single initiator, create initiator 
summary: 기존 볼륨 액세스 그룹에 이니시에이터를 추가할 수 있습니다. 
---
= 볼륨 액세스 그룹에 단일 이니시에이터를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 볼륨 액세스 그룹에 이니시에이터를 추가할 수 있습니다.

볼륨 액세스 그룹에 이니시에이터를 추가하면 해당 이니시에이터는 해당 볼륨 액세스 그룹의 모든 볼륨에 액세스할 수 있습니다.


TIP: 작업 아이콘을 클릭한 다음 활성 볼륨 목록에서 볼륨에 대해 * 세부 정보 보기 * 를 선택하면 각 볼륨의 이니시에이터를 찾을 수 있습니다.

이니시에이터 기반 CHAP를 사용하는 경우 볼륨 액세스 그룹의 단일 이니시에이터에 대한 CHAP 자격 증명을 추가하여 보안을 강화할 수 있습니다. 따라서 이미 존재하는 볼륨 액세스 그룹에 이 옵션을 적용할 수 있습니다.

.단계
. 관리 * > * 액세스 그룹 * 을 클릭합니다.
. 편집할 액세스 그룹의 * 작업 * 아이콘을 클릭합니다.
. 편집 * 을 클릭합니다.
. 볼륨 액세스 그룹에 Fibre Channel 이니시에이터를 추가하려면 다음 단계를 수행하십시오.
+
.. 이니시에이터 추가 아래의 * Unbound Fibre Channel Initiators * 목록에서 기존 Fibre Channel 이니시에이터를 선택합니다.
.. FC 이니시에이터 추가 * 를 클릭합니다.
+

NOTE: 이 단계에서 * 이니시에이터 생성 * 링크를 클릭하고 이니시에이터 이름을 입력한 다음 * 생성 * 을 클릭하면 이니시에이터를 생성할 수 있습니다. 이니시에이터를 생성하면 * Initiators * 목록에 자동으로 추가됩니다.

+
형식의 예는 다음과 같습니다.



+
[listing]
----
5f:47:ac:c0:5c:74:d4:02
----
. iSCSI 이니시에이터를 볼륨 액세스 그룹에 추가하려면 이니시에이터 추가 아래의 * 이니시에이터 * 목록에서 기존 이니시에이터를 선택합니다.
+

NOTE: 이 단계에서 * 이니시에이터 생성 * 링크를 클릭하고 이니시에이터 이름을 입력한 다음 * 생성 * 을 클릭하면 이니시에이터를 생성할 수 있습니다. 이니시에이터를 생성하면 * Initiators * 목록에 자동으로 추가됩니다.

+
이니시에이터 IQN에서 허용되는 형식은 iqn.yyyy-mm이며, 여기서 y와 m은 숫자이고, 그 뒤에 숫자, 소문자 알파벳 문자, 마침표(.), 콜론(:) 또는 대시(-)만 포함되어야 하는 텍스트가 옵니다.

+
형식의 예는 다음과 같습니다.

+
[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
+

TIP: Actions 아이콘을 클릭한 다음 볼륨에 대해 * View Details * 를 선택하여 * Management * > * Volumes * Active Volumes 페이지에서 각 볼륨의 이니시에이터 IQN을 찾을 수 있습니다.

. 변경 내용 저장 * 을 클릭합니다.

