---
permalink: storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html 
sidebar: sidebar 
keywords: enable, disable, encryption at rest, cluster, sed, hardware-based, encryption settings, software-based 
summary: SolidFire 클러스터를 사용하면 저장된 소프트웨어 또는 하드웨어 기반 암호화를 사용하여 클러스터에 저장된 모든 데이터를 암호화할 수 있습니다. 
---
= 클러스터의 유휴 데이터 암호화를 설정 및 해제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 클러스터를 사용하면 클러스터 드라이브에 저장된 모든 유휴 데이터를 암호화할 수 있습니다. 또는 을 사용하여 SED(자체 암호화 드라이브)의 클러스터 전체 보호를 활성화할 수 있습니다 link:../concepts/concept_solidfire_concepts_security.html["하드웨어 또는 소프트웨어 기반의 유휴 암호화"].

Element UI 또는 API를 사용하여 유휴 하드웨어 암호화를 활성화할 수 있습니다. 하드웨어 유휴 암호화 기능을 활성화해도 클러스터의 성능이나 효율에는 영향을 주지 않습니다. 사용되지 않는 소프트웨어 암호화는 Element API만 사용하여 활성화할 수 있습니다.

사용되지 않는 하드웨어 기반 암호화는 기본적으로 클러스터 생성 중에 활성화되지 않으며 Element UI에서 활성화 및 비활성화할 수 있습니다.


WARNING: SolidFire All-Flash 스토리지 클러스터의 경우, 클러스터 생성 중에 유휴 소프트웨어 암호화를 활성화해야 하며, 클러스터를 생성한 후에는 비활성화할 수 없습니다.

.필요한 것
* 암호화 설정을 활성화하거나 변경할 수 있는 클러스터 관리자 권한이 있습니다.
* 저장된 하드웨어 기반 암호화의 경우 암호화 설정을 변경하기 전에 클러스터가 정상 상태인지 확인했습니다.
* 암호화를 사용하지 않도록 설정하는 경우 드라이브에서 암호화를 해제하려면 두 노드가 클러스터에 참여하고 있어야 합니다.




== 저장된 암호화 상태를 확인하십시오

유휴 상태의 암호화 및/또는 클러스터의 유휴 상태의 소프트웨어 암호화를 확인하려면 를 사용합니다 link:../api/reference_element_api_getclusterinfo.html["GetClusterInfo 를 참조하십시오"^] 방법. 를 사용할 수 있습니다 link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["GetSoftwareEncryptionAtRestInfo 를 참조하십시오"^] 클러스터에서 유휴 데이터를 암호화하는 데 사용하는 정보를 가져오는 방법입니다.


NOTE: https://<MVIP>/` 의 Element 소프트웨어 UI 대시보드는 현재 하드웨어 기반 암호화에 대한 저장된 암호화 상태만 표시합니다.

.옵션
* <<하드웨어 기반의 유휴 암호화 활성화>>
* <<유휴 상태의 소프트웨어 기반 암호화 사용>>
* <<저장된 하드웨어 기반 암호화를 비활성화합니다>>




== 하드웨어 기반의 유휴 암호화 활성화


NOTE: 외부 키 관리 구성을 사용하여 유휴 데이터 암호화를 활성화하려면 를 통해 유휴 상태의 암호화를 활성화해야 합니다 link:../api/reference_element_api_enableencryptionatrest.html["API를 참조하십시오"]. 기존 Element UI 버튼을 사용하여 활성화하면 내부적으로 생성된 키를 사용하는 것으로 되돌아갑니다.

. Element UI에서 * Cluster * > * Settings * 를 선택합니다.
. 저장 시 암호화 사용 * 을 선택합니다.




== 유휴 상태의 소프트웨어 기반 암호화 사용


NOTE: 클러스터에서 소프트웨어 암호화를 사용하도록 설정한 후에는 사용되지 않는 소프트웨어 암호화를 해제할 수 없습니다.

. 클러스터를 생성하는 동안 를 실행합니다 link:../api/reference_element_api_createcluster.html["클러스터 생성 방법"] enableSoftwareEncryptionAtRest가 true로 설정되어 있습니다.




== 저장된 하드웨어 기반 암호화를 비활성화합니다

. Element UI에서 * Cluster * > * Settings * 를 선택합니다.
. 저장 시 암호화 비활성화 * 를 선택합니다.


[discrete]
== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

