---
permalink: storage/task_replication_pair_cluster_using_pairing_key.html 
sidebar: sidebar 
keywords: remote replication, pairing key, pairing clusters 
summary: 원격 클러스터가 아닌 로컬 클러스터에 대한 클러스터 관리자 액세스 권한이 있는 경우 페어링 키를 사용하여 클러스터를 페어링할 수 있습니다. 로컬 클러스터에서 페어링 키가 생성된 후 원격 사이트의 클러스터 관리자에게 안전하게 전송되어 연결을 설정하고 실시간 복제를 위해 클러스터 페어링을 완료합니다. 
---
= 페어링 키를 사용하여 클러스터를 페어링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 클러스터가 아닌 로컬 클러스터에 대한 클러스터 관리자 액세스 권한이 있는 경우 페어링 키를 사용하여 클러스터를 페어링할 수 있습니다. 로컬 클러스터에서 페어링 키가 생성된 후 원격 사이트의 클러스터 관리자에게 안전하게 전송되어 연결을 설정하고 실시간 복제를 위해 클러스터 페어링을 완료합니다.

. 로컬 클러스터에서 * 데이터 보호 * > * 클러스터 쌍 * 을 선택합니다.
. 클러스터 페어링 * 을 클릭합니다.
. 페어링 시작 * 을 클릭하고 * 아니요 * 를 클릭하여 원격 클러스터에 액세스할 수 없음을 표시합니다.
. 키 생성 * 을 클릭합니다.
+

NOTE: 이렇게 하면 페어링을 위한 텍스트 키가 생성되고 로컬 클러스터에 구성되지 않은 클러스터 쌍이 생성됩니다. 이 절차를 완료하지 않으면 클러스터 쌍을 수동으로 삭제해야 합니다.

. 클러스터 페어링 키를 클립보드에 복사합니다.
. 원격 클러스터 사이트의 클러스터 관리자가 페어링 키를 액세스할 수 있도록 합니다.
+

NOTE: 클러스터 페어링 키에는 원격 복제를 위한 볼륨 연결을 허용하는 MVIP 버전, 사용자 이름, 암호 및 데이터베이스 정보가 포함되어 있습니다. 이 키는 안전한 방식으로 취급해야 하며 사용자 이름 또는 암호에 우발적이거나 안전하지 않은 액세스를 허용하는 방식으로 저장되지 않아야 합니다.

+

IMPORTANT: 페어링 키의 문자를 수정하지 마십시오. 키를 수정하면 키가 무효화됩니다.

. 원격 클러스터에서 * 데이터 보호 * > * 클러스터 쌍 * 을 선택합니다.
. 클러스터 페어링 * 을 클릭합니다.
. 페어링 완료 * 를 클릭하고 * 페어링 키 * 필드에 페어링 키를 입력합니다(붙여넣기가 권장 방법임).
. 페어링 완료 * 를 클릭합니다.




== 자세한 내용을 확인하십시오

* xref:task_replication_pair_cluster_using_mvip.adoc[MVIP를 사용하여 클러스터를 페어링합니다]
* https://www.youtube.com/watch?v=1ljHAd1byC8&feature=youtu.be["클러스터 페어링 키를 사용하여 클러스터 페어링(비디오)"]

