---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: SolidFire 시스템은 볼륨을 사용하여 스토리지를 프로비저닝합니다. 볼륨은 iSCSI 또는 파이버 채널 클라이언트가 네트워크를 통해 액세스하는 블록 디바이스입니다. 
---
= 볼륨 관리
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 시스템은 볼륨을 사용하여 스토리지를 프로비저닝합니다. 볼륨은 iSCSI 또는 파이버 채널 클라이언트가 네트워크를 통해 액세스하는 블록 디바이스입니다.

관리 탭의 볼륨 페이지에서 노드에서 볼륨을 생성, 수정, 클론 복제 및 삭제할 수 있습니다.



== 볼륨을 생성합니다

볼륨을 생성하고 해당 볼륨을 지정된 계정에 연결할 수 있습니다. 모든 볼륨은 계정과 연결되어 있어야 합니다. 이 연결은 CHAP 자격 증명을 사용하여 iSCSI 초기자를 통해 볼륨에 대한 액세스 권한을 계정에 부여합니다.

생성 중에 볼륨의 QoS 설정을 지정할 수 있습니다.

. Management * > * Volumes * 를 선택합니다.
. Create Volume * 을 클릭합니다.
. 새 볼륨 만들기 * 대화 상자에서 * 볼륨 이름 * 을 입력합니다.
. 볼륨의 총 크기를 입력합니다.
+

NOTE: 기본 볼륨 크기 선택은 GB입니다. GB 또는 GiB 단위로 측정된 크기를 사용하여 볼륨을 생성할 수 있습니다.

+
** 1GB = 1,000,000바이트
** 1GiB = 1 073 741 824바이트


. 볼륨의 * 블록 크기 * 를 선택합니다.
. 계정 * 드롭다운 목록을 클릭하고 볼륨에 액세스할 수 있는 계정을 선택합니다.
+
계정이 없는 경우 * 계정 만들기 * 링크를 클릭하고 새 계정 이름을 입력한 다음 * 만들기 * 를 클릭합니다. 계정이 생성되고 새 볼륨과 연결됩니다.

+

NOTE: 계정이 50개를 초과하는 경우 목록이 나타나지 않습니다. 입력을 시작하면 자동 완성 기능에 선택 가능한 값이 표시됩니다.

. 서비스 품질 * 을 설정하려면 다음 중 하나를 수행합니다.
+
.. 정책 * 에서 기존 QoS 정책을 선택할 수 있습니다(사용 가능한 경우).
.. 사용자 지정 설정 * 에서 IOPS에 대한 사용자 지정 최소, 최대 및 버스트 값을 설정하거나 기본 QoS 값을 사용합니다.
+
최대 또는 버스트 IOPS 값이 20,000 IOPS 이상인 볼륨은 단일 볼륨에서 이러한 IOPS 수준을 달성하기 위해 큐 길이가 크거나 여러 세션이 필요할 수 있습니다.



. Create Volume * 을 클릭합니다.




== 볼륨 세부 정보를 봅니다

. Management * > * Volumes * 를 선택합니다.
. 세부 정보를 검토합니다.
+
** * ID *: 볼륨에 대해 시스템에서 생성한 ID입니다.
** * 이름 *: 볼륨을 생성할 때 볼륨에 지정된 이름입니다.
** * 계정 *: 볼륨에 할당된 계정의 이름입니다.
** * 액세스 그룹 *: 볼륨이 속한 볼륨 액세스 그룹 또는 그룹의 이름입니다.
** * 액세스 *: 볼륨을 생성할 때 볼륨에 할당된 액세스 유형입니다. 가능한 값:
+
*** 읽기/쓰기: 모든 읽기 및 쓰기가 허용됩니다.
*** 읽기 전용: 모든 읽기 작업이 허용되며 쓰기가 허용되지 않습니다.
*** 잠김: 관리자 액세스만 허용됩니다.
*** ReplicationTarget: 복제된 볼륨 쌍의 타겟 볼륨으로 지정됩니다.


** * used * (사용 *): 볼륨에서 사용된 공간의 비율입니다.
** * 크기 *: 볼륨의 총 크기(GB)입니다.
** * 스냅샷 *: 볼륨에 대해 생성된 스냅샷의 수입니다.
** * QoS 정책 *: 사용자 정의 QoS 정책에 대한 이름 및 링크입니다.
** * 최소 IOPS *: 볼륨에 대해 보장된 최소 IOPS 수입니다.
** * 최대 IOPS *: 볼륨에 허용되는 최대 IOPS 수입니다.
** * 버스트 IOPS *: 짧은 기간 동안 볼륨에 허용되는 최대 IOPS 수입니다. 기본값 = 15,000.
** * 특성 *: API 메서드를 통해 볼륨에 키/값 쌍으로 할당된 특성
** * 512e *: 볼륨에서 512e가 활성화되었는지 여부를 나타냅니다. 가능한 값:
+
*** 예
*** 아니요


** * Created on *(생성 날짜): 볼륨이 생성된 날짜 및 시간입니다.






== 개별 볼륨 세부 정보를 봅니다

개별 볼륨의 성능 통계를 볼 수 있습니다.

. 보고 * > * 볼륨 성능 * 을 선택합니다.
. 볼륨 목록에서 볼륨에 대한 작업 아이콘을 클릭합니다.
. 세부 정보 보기 * 를 클릭합니다.
+
용지 맨 아래에 용적에 대한 일반 정보가 들어 있는 용지함이 나타납니다.

. 볼륨에 대한 자세한 정보를 보려면 * 자세한 정보 보기 * 를 클릭하십시오.
+
볼륨에 대한 성능 그래프와 자세한 정보가 표시됩니다.





== 활성 볼륨을 편집합니다

QoS 값, 볼륨 크기 및 바이트 값이 계산되는 측정 단위와 같은 볼륨 특성을 수정할 수 있습니다. 복제 사용에 대한 계정 액세스를 수정하거나 볼륨에 대한 액세스를 제한할 수도 있습니다.

다음 조건에서 클러스터에 공간이 충분할 때 볼륨 크기를 조정할 수 있습니다.

* 정상 작동 조건.
* 볼륨 오류 또는 오류가 보고됩니다.
* 볼륨을 클론 복제 중입니다.
* 볼륨이 재동기화 중입니다.


.단계
. Management * > * Volumes * 를 선택합니다.
. Active * (활성 *) 창에서 편집할 볼륨의 Actions (동작) 아이콘을 클릭합니다.
. 편집 * 을 클릭합니다.
. * 선택 사항: * 볼륨의 총 크기를 변경합니다.
+
** 볼륨 크기를 늘릴 수 있지만 줄일 수는 없습니다. 단일 크기 조정 작업에서만 볼륨 크기를 조정할 수 있습니다. 가비지 수집 작업 및 소프트웨어 업그레이드로 크기 조정 작업이 중단되지 않습니다.
** 복제를 위해 볼륨 크기를 조정하는 경우 먼저 복제 대상으로 할당된 볼륨의 크기를 늘려야 합니다. 그런 다음 소스 볼륨의 크기를 조정할 수 있습니다. 타겟 볼륨의 크기는 소스 볼륨과 같거나 더 클 수 있지만 크기는 작을 수 없습니다.


+
기본 볼륨 크기 선택은 GB입니다. GB 또는 GiB 단위로 측정된 크기를 사용하여 볼륨을 생성할 수 있습니다.

+
** 1GB = 1,000,000바이트
** 1GiB = 1 073 741 824바이트


. * 선택 사항: * 다음 중 하나의 다른 계정 액세스 수준을 선택하십시오.
+
** 읽기 전용
** 읽기/쓰기
** 잠금
** 복제 타겟


. * 선택 사항: * 볼륨에 액세스할 수 있는 계정을 선택합니다.
+
계정이 없는 경우 * 계정 만들기 * 링크를 클릭하고 새 계정 이름을 입력한 다음 * 만들기 * 를 클릭합니다. 계정이 생성되고 볼륨과 연결됩니다.

+

NOTE: 계정이 50개를 초과하는 경우 목록이 나타나지 않습니다. 입력을 시작하면 자동 완성 기능에 선택 가능한 값이 표시됩니다.

. * 선택 사항: * 서비스 품질 * 에서 선택 사항을 변경하려면 다음 중 하나를 수행합니다.
+
.. 정책 * 에서 기존 QoS 정책을 선택할 수 있습니다(사용 가능한 경우).
.. 사용자 지정 설정 * 에서 IOPS에 대한 사용자 지정 최소, 최대 및 버스트 값을 설정하거나 기본 QoS 값을 사용합니다.
+

NOTE: 볼륨에 QoS 정책을 사용하는 경우 사용자 지정 QoS를 설정하여 볼륨에 대한 QoS 정책 가입을 제거할 수 있습니다. 사용자 지정 QoS는 볼륨 QoS 설정에 대한 QoS 정책 값을 재정의하고 조정합니다.

+

TIP: IOPS 값을 변경할 때는 수십 또는 수백 단위로 증분해야 합니다. 입력 값에는 유효한 정수가 필요합니다.

+

TIP: 매우 높은 버스트 값으로 볼륨을 구성합니다. 따라서 시스템에서 가끔 발생하는 대규모 블록 순차적 워크로드를 더 빠르게 처리하는 동시에 볼륨에 대해 일관된 IOPS를 유지할 수 있습니다.



. 변경 내용 저장 * 을 클릭합니다.




== 볼륨을 삭제합니다

Element 스토리지 클러스터에서 하나 이상의 볼륨을 삭제할 수 있습니다.

시스템은 삭제된 볼륨을 즉시 제거하지 않으며, 볼륨은 약 8시간 동안 계속 사용할 수 있습니다. 시스템이 볼륨을 제거하기 전에 볼륨을 복원하면 볼륨이 다시 온라인 상태가 되고 iSCSI 연결이 복원됩니다.

스냅샷을 생성하는 데 사용된 볼륨이 삭제되면 연결된 스냅샷이 비활성화됩니다. 삭제된 소스 볼륨이 제거되면 연결된 비활성 스냅샷도 시스템에서 제거됩니다.


IMPORTANT: 설치 또는 업그레이드 중에 관리 서비스와 연결된 영구 볼륨이 생성되고 새 계정에 할당됩니다. 영구 볼륨을 사용하는 경우 볼륨이나 연결된 계정을 수정하거나 삭제하지 마십시오.

.단계
. Management * > * Volumes * 를 선택합니다.
. 단일 볼륨을 삭제하려면 다음 단계를 수행하십시오.
+
.. 삭제할 볼륨의 작업 아이콘을 클릭합니다.
.. 결과 메뉴에서 * 삭제 * 를 클릭합니다.
.. 작업을 확인합니다.


+
시스템이 볼륨을 * Volumes * 페이지의 * Deleted * (삭제됨 *) 영역으로 이동합니다.

. 여러 볼륨을 삭제하려면 다음 단계를 수행하십시오.
+
.. 볼륨 목록에서 삭제할 볼륨 옆의 확인란을 선택합니다.
.. 대량 작업 * 을 클릭합니다.
.. 결과 메뉴에서 * 삭제 * 를 클릭합니다.
.. 작업을 확인합니다.
+
볼륨이 * Volumes * 페이지의 * Deleted * (삭제됨 *) 영역으로 이동합니다.







== 삭제된 볼륨을 복원합니다

삭제되었으나 아직 제거되지 않은 경우 시스템의 볼륨을 복원할 수 있습니다. 시스템은 삭제된 후 약 8시간 후에 자동으로 볼륨을 삭제합니다. 시스템에서 볼륨을 제거한 경우에는 복원할 수 없습니다.

. Management * > * Volumes * 를 선택합니다.
. 삭제된 볼륨 목록을 보려면 * Deleted * (삭제됨 *) 탭을 클릭합니다.
. 복원하려는 볼륨의 작업 아이콘을 클릭합니다.
. 결과 메뉴에서 * 복원 * 을 클릭합니다.
. 작업을 확인합니다.
+
볼륨은 * 활성 * 볼륨 목록에 배치되고 볼륨에 대한 iSCSI 연결이 복원됩니다.





== 볼륨을 제거합니다

볼륨이 제거되면 시스템에서 영구적으로 제거됩니다. 볼륨의 모든 데이터가 손실됩니다.

삭제 8시간 후 시스템에서 삭제된 볼륨을 자동으로 삭제합니다. 그러나 예약된 시간 전에 볼륨을 제거하려면 제거할 수 있습니다.

. Management * > * Volumes * 를 선택합니다.
. DELETED * 버튼을 클릭합니다.
. 단일 볼륨 또는 여러 볼륨을 제거하는 단계를 수행합니다.
+
[cols="25,75"]
|===
| 옵션을 선택합니다 | 단계 


 a| 
단일 볼륨을 제거합니다
 a| 
.. 제거할 볼륨의 작업 아이콘을 클릭합니다.
.. Purge * 를 클릭합니다.
.. 작업을 확인합니다.




 a| 
여러 볼륨을 제거합니다
 a| 
.. 제거할 볼륨을 선택합니다.
.. 대량 작업 * 을 클릭합니다.
.. 결과 메뉴에서 * Purge * 를 선택합니다.
.. 작업을 확인합니다.


|===




== 볼륨의 클론을 생성합니다

단일 볼륨 또는 여러 볼륨의 클론을 생성하여 데이터의 시점 복사본을 만들 수 있습니다. 볼륨을 클론하면 시스템에서 볼륨의 스냅샷을 생성한 다음 스냅샷이 참조하는 데이터의 복제본을 생성합니다. 비동기식 프로세스이며, 프로세스에 필요한 시간은 클론 생성 중인 볼륨의 크기와 현재 클러스터 로드에 따라 다릅니다.

클러스터는 한 번에 볼륨당 최대 2개의 클론 요청을 실행하고 한 번에 최대 8개의 활성 볼륨 클론 작업을 지원합니다. 이러한 제한을 초과하는 요청은 나중에 처리할 수 있도록 대기열에 추가됩니다.


NOTE: 운영 체제는 복제된 볼륨을 처리하는 방식에 따라 다릅니다. VMware ESXi는 복제된 볼륨을 볼륨 복사본 또는 스냅샷 볼륨으로 처리합니다. 볼륨은 새 데이터 저장소를 생성하는 데 사용할 수 있는 디바이스가 됩니다. 클론 볼륨을 마운트하고 스냅샷 LUN을 처리하는 방법에 대한 자세한 내용은 의 VMware 설명서를 참조하십시오 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["VMFS 데이터 저장소 복제본 마운트"] 및.


IMPORTANT: 작은 크기로 복제하여 복제된 볼륨을 잘라내려면 먼저 작은 볼륨에 맞도록 파티션을 준비해야 합니다.

.단계
. Management * > * Volumes * 를 선택합니다.
. 단일 볼륨을 클론하려면 다음 단계를 수행하십시오.
+
.. Active * 페이지의 볼륨 목록에서 복제할 볼륨의 작업 아이콘을 클릭합니다.
.. 결과 메뉴에서 * Clone * 을 클릭합니다.
.. 클론 볼륨 * 창에서 새로 복제된 볼륨의 볼륨 이름을 입력합니다.
.. 체적 크기 * 스핀 상자 및 목록을 사용하여 체적의 크기와 측정을 선택합니다.
+

NOTE: 기본 볼륨 크기 선택은 GB입니다. GB 또는 GiB 단위로 측정된 크기를 사용하여 볼륨을 생성할 수 있습니다.

+
*** 1GB = 1,000,000바이트
*** 1GiB = 1 073 741 824바이트


.. 새로 복제된 볼륨에 대한 액세스 유형을 선택합니다.
.. 계정 * 목록에서 새로 복제된 볼륨과 연결할 계정을 선택합니다.
+

NOTE: 계정 만들기 * 링크를 클릭하고 계정 이름을 입력한 다음 * 만들기 * 를 클릭하면 이 단계에서 계정을 만들 수 있습니다. 계정을 만든 후에는 시스템에서 자동으로 * 계정 * 목록에 계정을 추가합니다.



. 여러 볼륨을 클론하려면 다음 단계를 수행하십시오.
+
.. Active * 페이지의 볼륨 목록에서 복제할 볼륨 옆의 확인란을 선택합니다.
.. 대량 작업 * 을 클릭합니다.
.. 결과 메뉴에서 * Clone * 을 선택합니다.
.. 여러 볼륨 클론 * 대화 상자의 * 새 볼륨 이름 접두사 * 필드에 복제된 볼륨의 접두사를 입력합니다.
.. Account * 목록에서 복제된 볼륨과 연결할 계정을 선택합니다.
.. 클론 복제된 볼륨에 대한 액세스 유형을 선택합니다.


. 클로닝 시작 * 을 클릭합니다.
+

NOTE: 클론의 볼륨 크기를 늘리면 새 볼륨의 끝에 추가 여유 공간이 있는 새 볼륨이 됩니다. 볼륨 사용 방법에 따라 파티션을 확장하거나 사용 가능한 공간에 새 파티션을 만들어야 사용할 수 있습니다.





== 를 참조하십시오

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

