---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: 스토리지 노드의 노드별 UI를 사용하여 지원 번들을 생성 또는 삭제하고, 드라이브의 구성 설정을 재설정하고, 네트워크 또는 클러스터 서비스를 다시 시작할 수 있습니다. 
---
= 노드별 UI를 사용하여 시스템 유틸리티를 실행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 노드별 UI를 사용하여 지원 번들을 생성 또는 삭제하고, 드라이브의 구성 설정을 재설정하고, 네트워크 또는 클러스터 서비스를 다시 시작할 수 있습니다.

스토리지 노드의 노드별 UI에 로그인했습니다.

. 시스템 유틸리티 * 를 클릭합니다.
. 실행할 시스템 유틸리티의 단추를 클릭합니다.
+
** * 제어 전원 *
+
노드를 재부팅, 전원 사이클 또는 종료합니다.

+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊기게 됩니다.

+
다음 매개 변수를 지정합니다.

+
*** 조치: 옵션에는 재시작 및 중지(전원 끄기)가 포함됩니다.
*** Wakeup Delay(웨이크업 지연): 노드가 다시 온라인 상태로 전환되기 전에 추가 시간


** * 노드 로그 수집 *
+
노드의 /tmp/bunds 디렉토리 아래에 지원 번들을 생성합니다.

+
다음 매개 변수를 지정합니다.

+
*** 번들 이름: 생성된 각 지원 번들의 고유 이름입니다. 이름이 제공되지 않으면 "supportbundle"과 노드 이름이 파일 이름으로 사용됩니다.
*** Extra Args: 이 매개 변수는 sf_make_support_bundle 스크립트에 공급됩니다. 이 매개 변수는 NetApp Support의 요청에만 사용해야 합니다.
*** timeout sec(시간 초과 초): 각 개별 ping 응답을 대기하는 시간(초)을 지정합니다.


** * 노드 로그 삭제 *
+
Create Cluster Support Bundle* 또는 CreateSupportBundle API 메소드를 사용하여 생성된 노드에서 현재 지원 번들을 삭제합니다.

** * 드라이브 재설정 *
+
드라이브를 초기화하고 현재 드라이브에 있는 모든 데이터를 제거합니다. 기존 노드 또는 업그레이드된 노드에서 드라이브를 재사용할 수 있습니다.

+
다음 매개 변수를 지정합니다.

+
*** 드라이브: 재설정할 장치 이름 목록(드라이브 ID 아님).


** * 네트워크 구성 재설정 *
+
개별 노드의 네트워크 구성 문제를 해결하고 개별 노드의 네트워크 구성을 공장 출하시 기본 설정으로 재설정합니다.

** * 노드 재설정 *
+
노드를 공장 초기 설정으로 재설정합니다. 모든 데이터가 제거되지만 이 작업 중에 노드의 네트워크 설정이 유지됩니다. 노드가 클러스터에 할당되지 않고 사용 가능한 상태인 경우에만 재설정할 수 있습니다.

+

IMPORTANT: 이 옵션을 사용하면 모든 데이터, 패키지(소프트웨어 업그레이드), 구성 및 로그 파일이 노드에서 삭제됩니다.

** * 네트워킹 재시작 *
+
노드에서 모든 네트워킹 서비스를 다시 시작합니다.

+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊어질 수 있습니다.

** * 서비스를 다시 시작합니다 *
+
노드에서 Element 소프트웨어 서비스를 다시 시작합니다.

+

IMPORTANT: 이 작업은 일시적인 노드 서비스를 중단시킬 수 있습니다. 이 작업은 NetApp Support의 지시에 따라서만 수행해야 합니다.

+
다음 매개 변수를 지정합니다.

+
*** 서비스: 다시 시작할 서비스 이름입니다.
*** 조치: 서비스에 대해 수행할 조치. 시작, 중지 및 재시작 옵션이 있습니다.





