---
permalink: storage/task_post_deploy_configure_system_options.html 
sidebar: sidebar 
keywords: deployment, post deployment options, credentials, components, FIPS security, passwords, MFA, multifactor authentication, mutli-factor authentication, security, EKM, key management, external key management, FIPS 
summary: 'SolidFire 시스템을 설정한 후 몇 가지 선택적 작업을 수행할 수 있습니다. 또한 다중 요소 인증, 외부 키 관리 및 FIPS(Federal Information Processing Standards) 보안에 대한 설정을 구성할 수 있습니다.' 
---
= 구축 후 SolidFire 시스템 옵션을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 시스템을 설정한 후 몇 가지 선택적 작업을 수행할 수 있습니다.

시스템에서 자격 증명을 변경하는 경우 다른 구성 요소에 미치는 영향을 알고 싶을 수 있습니다.

또한 다중 요소 인증, 외부 키 관리 및 FIPS(Federal Information Processing Standards) 보안에 대한 설정을 구성할 수 있습니다. 필요한 경우 암호 업데이트도 고려해야 합니다.



== 자세한 내용을 확인하십시오

* link:task_post_deploy_credentials.html["NetApp HCI 및 NetApp SolidFire에서 자격 증명을 변경합니다"]
* link:reference_post_deploy_change_default_ssl_certificate.html["Element 소프트웨어 기본 SSL 인증서를 변경합니다"]
* link:task_post_deploy_credential_change_ipmi_password.html["노드의 IPMI 암호를 변경합니다"]
* link:concept_system_manage_mfa_enable_multi_factor_authentication.html["다중 요소 인증을 사용합니다"]
* link:concept_system_manage_key_get_started_with_external_key_management.html["외부 키 관리를 시작합니다"]
* link:task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["FIPS 드라이브를 지원하는 클러스터를 생성합니다"]

