---
permalink: storage/task_replication_plan_cluster_and_volume_pairing.html 
sidebar: sidebar 
keywords: cluster, volume pairing, plan for, real-time replication 
summary: 실시간 원격 복제를 수행하려면 Element 소프트웨어를 실행하는 두 스토리지 클러스터를 페어링하고, 각 클러스터에서 볼륨을 페어링하고, 복제를 확인해야 합니다. 복제가 완료되면 볼륨 관계를 삭제해야 합니다. 
---
= 실시간 복제를 위해 클러스터 및 볼륨 페어링을 계획합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실시간 원격 복제를 수행하려면 Element 소프트웨어를 실행하는 두 스토리지 클러스터를 페어링하고, 각 클러스터에서 볼륨을 페어링하고, 복제를 확인해야 합니다. 복제가 완료되면 볼륨 관계를 삭제해야 합니다.

.필요한 것
* 페어링되는 하나 또는 두 클러스터에 대한 클러스터 관리자 권한이 있어야 합니다.
* 페어링된 클러스터의 관리 및 스토리지 네트워크 모두에 있는 모든 노드 IP 주소는 서로 라우팅됩니다.
* 페어링된 모든 노드의 MTU는 동일해야 하며 클러스터 간 엔드 투 엔드를 지원해야 합니다.
* 두 스토리지 클러스터에는 고유한 클러스터 이름, MVIP, SVIP 및 모든 노드 IP 주소가 있어야 합니다.
* 클러스터의 Element 소프트웨어 버전 간의 차이는 하나의 주요 버전 이상일 수 없습니다. 차이가 크면 클러스터 중 하나를 업그레이드하여 데이터 복제를 수행해야 합니다.



NOTE: NetApp은 데이터 복제 시 WAN 가속기 어플라이언스를 사용하지 않았습니다. 이러한 어플라이언스는 데이터를 복제하는 두 클러스터 간에 구축될 경우 압축 및 중복 제거를 방해할 수 있습니다. 프로덕션 환경에 배포하기 전에 WAN 가속기 어플라이언스의 효과를 완벽하게 검증해야 합니다.



== 자세한 내용을 확인하십시오

* xref:task_replication_pair_clusters.adoc[복제를 위해 클러스터를 쌍으로 설정합니다]
* xref:task_replication_pair_volumes.adoc[볼륨을 페어링합니다]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[복제 소스와 타겟을 페어링된 볼륨에 할당합니다]

