---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: SolidFire 스토리지 시스템에서 테넌트는 계정을 사용하여 클라이언트가 노드의 볼륨에 연결할 수 있도록 설정할 수 있습니다. 계정에는 할당된 볼륨에 액세스하는 데 필요한 CHAP 인증이 포함되어 있습니다. 볼륨을 생성하면 특정 계정에 할당됩니다. 
---
= CHAP를 사용하여 계정 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 스토리지 시스템에서 테넌트는 계정을 사용하여 클라이언트가 클러스터의 볼륨에 연결할 수 있도록 설정할 수 있습니다. 계정에는 할당된 볼륨에 액세스하는 데 필요한 CHAP(Challenge-Handshake Authentication Protocol) 인증이 포함되어 있습니다. 볼륨을 생성하면 특정 계정에 할당됩니다.

계정에는 최대 2천 개의 볼륨이 할당될 수 있지만 볼륨은 하나의 계정에만 속할 수 있습니다.



== CHAP 알고리즘입니다

Element 12.7부터 보안 FIPS 호환 CHAP 알고리즘 SHA1, SHA-256 및 SHA3-256이 지원됩니다. Element 12.7을 사용하는 경우 호스트 iSCSI 이니시에이터가 Element iSCSI 타겟과 함께 iSCSI 세션을 생성하는 경우 사용할 CHAP 알고리즘 목록을 요청합니다. Element iSCSI 대상은 호스트 iSCSI 초기자가 요청한 목록에서 지원하는 첫 번째 알고리즘을 선택합니다. Element iSCSI 타겟이 가장 안전한 알고리즘을 선택하는지 확인하려면 호스트 iSCSI 초기자가 가장 안전한(예: SHA3-256)에서 주문한 알고리즘 목록을 가장 안전한 것으로 보내도록 구성해야 합니다. SHA1 또는 MD5. 호스트 iSCSI 초기자가 SHA 알고리즘을 요청하지 않으면 Element iSCSI 대상이 MD5를 선택하며, 호스트의 제안된 알고리즘 목록에 MD5가 포함되어 있다고 가정합니다. 보안 알고리즘을 지원하려면 호스트 iSCSI 이니시에이터 구성을 업데이트해야 할 수 있습니다.

Element 12.7 업그레이드 중에 스토리지 노드가 재부팅될 때 SHA 알고리즘을 포함하는 목록이 포함된 세션 요청을 보내도록 호스트 iSCSI 이니시에이터 구성을 이미 업데이트한 경우 새로운 보안 알고리즘이 활성화되고 가장 안전한 프로토콜을 사용하여 새 iSCSI 세션 또는 다시 연결된 iSCSI 세션이 설정됩니다. 업그레이드 중에 기존의 모든 iSCSI 세션이 MD5에서 SHA로 전환됩니다. 호스트 iSCSI 이니시에이터 구성을 SHA를 요청하기 위해 업데이트하지 않으면 기존 iSCSI 세션에서 계속 MD5를 사용합니다. 나중에 호스트 iSCSI 이니시에이터 CHAP 알고리즘을 업데이트한 후 iSCSI 세션이 다시 연결되는 유지 보수 작업에 따라 iSCSI 세션이 점차 MD5에서 SHA로 전환되어야 합니다.

예를 들어, RHEL(Red Hat Enterprise Linux) 8.3의 기본 호스트 iSCSI 초기자는 "node.session.auth.chap_algs = SHA3-256, SHA256, SHA1, MD5" 설정이 MD5만 사용하는 iSCSI 초기자에 대한 의견을 남겼습니다. 호스트에서 이 설정의 주석 처리를 해제하고 iSCSI 이니시에이터를 다시 시작하면 해당 호스트에서 iSCSI 세션이 트리거되어 SHA3-256을 사용합니다.

필요한 경우 를 사용할 수 있습니다 https://docs.netapp.com/us-en/element-software/api/reference_element_api_listiscsisessions.html["목록 세션"] 각 세션에 사용 중인 CHAP 알고리즘을 확인하는 API 메소드



== 계정을 만듭니다

볼륨에 대한 액세스를 허용하는 계정을 생성할 수 있습니다.

시스템의 각 계정 이름은 고유해야 합니다.

. Management * > * Accounts * 를 선택합니다.
. 계정 만들기 * 를 클릭합니다.
. 사용자 이름 * 을 입력합니다.
. CHAP 설정 * 섹션에서 다음 정보를 입력합니다.
+

NOTE: 자격 증명 필드를 비워 두면 두 암호를 자동으로 생성할 수 있습니다.

+
** CHAP 노드 세션 인증을 위한 * 초기자 암호 *.
** CHAP 노드 세션 인증을 위한 * Target Secret * 입니다.


. 계정 만들기 * 를 클릭합니다.




== 계정 세부 정보를 봅니다

개별 계정의 성능 활동을 그래픽 형식으로 볼 수 있습니다.

그래프 정보는 계정에 대한 I/O 및 처리량 정보를 제공합니다. 평균 및 최대 활동 수준은 10초 보고 기간 단위로 표시됩니다. 이러한 통계에는 계정에 할당된 모든 볼륨에 대한 활동이 포함됩니다.

. Management * > * Accounts * 를 선택합니다.
. 계정의 작업 아이콘을 클릭합니다.
. 세부 정보 보기 * 를 클릭합니다.


다음은 몇 가지 세부 사항입니다.

* * 상태 *: 계정 상태입니다. 가능한 값:
+
** 활성: 활성 계정.
** 잠김: 잠긴 계정입니다.
** 제거됨: 삭제 및 삭제된 계정입니다.


* * 활성 볼륨 *: 계정에 할당된 활성 볼륨의 수입니다.
* * 압축 *: 계정에 할당된 볼륨의 압축 효율성 점수입니다.
* * 중복 제거 *: 계정에 할당된 볼륨의 중복 제거 효율성 점수입니다.
* * 씬 프로비저닝 *: 계정에 할당된 볼륨의 씬 프로비저닝 효율성 점수입니다.
* * Overall Efficiency *: 계정에 할당된 볼륨의 전체 효율성 점수입니다.




== 계정을 편집합니다

계정을 편집하여 상태를 변경하거나 CHAP 암호를 변경하거나 계정 이름을 수정할 수 있습니다.

계정의 CHAP 설정을 수정하거나 액세스 그룹에서 이니시에이터 또는 볼륨을 제거하면 초기자가 예기치 않게 볼륨에 액세스할 수 없게 될 수 있습니다. 볼륨 액세스가 예기치 않게 손실되지 않는지 확인하려면 계정 또는 액세스 그룹 변경의 영향을 받는 iSCSI 세션을 항상 로그아웃하고 이니시에이터 설정 및 클러스터 설정을 변경한 후 초기자가 볼륨에 다시 연결할 수 있는지 확인합니다.


IMPORTANT: 관리 서비스와 연결된 영구 볼륨은 설치 또는 업그레이드 중에 생성되는 새 계정에 할당됩니다. 영구 볼륨을 사용하는 경우 연결된 계정을 수정하거나 삭제하지 마십시오.

. Management * > * Accounts * 를 선택합니다.
. 계정의 작업 아이콘을 클릭합니다.
. 결과 메뉴에서 * Edit * 를 선택합니다.
. * 선택 사항: * 사용자 이름 * 을 편집합니다.
. * 선택 사항: * 상태 * 드롭다운 목록을 클릭하고 다른 상태를 선택합니다.
+

IMPORTANT: 상태를 * locked * 로 변경하면 계정에 대한 모든 iSCSI 연결이 종료되고 계정에 더 이상 액세스할 수 없습니다. 계정과 연결된 볼륨은 유지되지만 볼륨은 iSCSI를 검색할 수 없습니다.

. * 선택 사항: * CHAP 설정 * 에서 노드 세션 인증에 사용되는 * 초기자 암호 * 및 * 대상 암호 * 자격 증명을 편집합니다.
+

NOTE: CHAP 설정 * 자격 증명을 변경하지 않으면 자격 증명은 그대로 유지됩니다. 자격 증명 필드를 비워 두면 새 암호가 생성됩니다.

. 변경 내용 저장 * 을 클릭합니다.




== 계정을 삭제합니다

더 이상 필요하지 않은 계정은 삭제할 수 있습니다.

계정을 삭제하기 전에 계정과 연결된 모든 볼륨을 삭제하고 삭제하십시오.


IMPORTANT: 관리 서비스와 연결된 영구 볼륨은 설치 또는 업그레이드 중에 생성되는 새 계정에 할당됩니다. 영구 볼륨을 사용하는 경우 연결된 계정을 수정하거나 삭제하지 마십시오.

. Management * > * Accounts * 를 선택합니다.
. 삭제할 계정의 작업 아이콘을 클릭합니다.
. 결과 메뉴에서 * 삭제 * 를 선택합니다.
. 작업을 확인합니다.




== 자세한 내용을 확인하십시오

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 및 요소 리소스 페이지입니다"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

