---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: 지정된 간격으로 볼륨 또는 볼륨의 스냅샷이 자동으로 발생하도록 예약할 수 있습니다. 
---
= 스냅샷 스케줄을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
지정된 간격으로 볼륨 또는 볼륨의 스냅샷이 자동으로 발생하도록 예약할 수 있습니다.

스냅샷 스케줄을 구성할 때 해당 월의 일 또는 일을 기준으로 시간 간격 중에서 선택할 수 있습니다. 또한 반복 스케줄을 생성하고 다음 스냅샷이 발생하기 전 일, 시간 및 분을 지정할 수 있습니다.

5분 동안 나눌 수 없는 기간에 스냅샷을 실행하도록 예약하는 경우 5분 동안 나눌 수 있는 다음 기간에 스냅샷이 실행됩니다. 예를 들어 스냅샷을 12:42:00 UTC에서 실행하도록 예약하는 경우 12:45:00 UTC에서 실행됩니다. 5분 미만의 간격으로 실행되도록 스냅샷을 예약할 수 없습니다.

Element 12.5부터 직렬 생성을 활성화하고 UI에서 선입선출(FIFO) 방식으로 스냅샷을 유지하도록 선택할 수 있습니다.

* 직렬 생성 활성화 * 옵션은 한 번에 하나의 스냅샷만 복제되도록 지정합니다. 이전 스냅샷 복제가 아직 진행 중인 경우 새 스냅샷 생성이 실패합니다. 이 확인란을 선택하지 않으면 다른 스냅샷 복제가 아직 진행 중일 때 스냅샷 생성이 허용됩니다.
* FIFO * 옵션은 일관된 수의 최신 스냅샷을 유지하는 기능을 추가합니다. 이 확인란을 선택하면 FIFO 기준으로 스냅샷이 보존됩니다. FIFO 스냅샷 대기열이 최대 깊이에 도달하면 새 FIFO 스냅샷을 삽입하면 가장 오래된 FIFO 스냅샷이 삭제됩니다.


.단계
. 데이터 보호 * > * 스케줄 * 을 선택합니다.
. Create Schedule * 을 선택합니다.
. 볼륨 ID CSV * 필드에 스냅샷 작업에 포함할 단일 볼륨 ID 또는 쉼표로 구분된 볼륨 ID 목록을 입력합니다.
. 새 일정 이름을 입력합니다.
. 일정 유형을 선택하고 제공된 옵션에서 일정을 설정합니다.
. * 선택 사항: * 반복 일정 * 을 선택하여 스냅샷 일정을 무한정 반복합니다.
. * 선택 사항: * 새 스냅샷 이름 * 필드에 새 스냅샷의 이름을 입력합니다.
+
필드를 비워 두면 스냅샷 생성 날짜와 시간이 이름으로 사용됩니다.

. * 선택 사항: * 부모 볼륨이 페어링될 때 복제에 스냅샷이 캡처되도록 하려면 * 쌍으로 된 경우 복제에 스냅샷 포함 * 확인란을 선택합니다.
. * 선택 사항: * 한 번에 하나의 스냅샷만 복제되도록 하려면 * 직렬 생성 활성화 * 확인란을 선택합니다.
. 스냅샷에 대한 보존을 설정하려면 다음 옵션 중에서 선택합니다.
+
** * 선택 사항: * FIFO(선입선출) * 확인란을 선택하여 일치하는 수의 최신 스냅샷을 유지합니다.
** 시스템에 스냅샷을 무한정 유지하려면 * 영구 보존 * 을 선택합니다.
** 보존 기간 설정 * 을 선택하고 날짜 스핀 상자를 사용하여 시스템에서 스냅샷을 보존할 기간을 선택합니다.


. Create Schedule * 을 선택합니다.

