---
permalink: storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html 
sidebar: sidebar 
keywords: volume pairings, paired volumes, replication source, assign 
summary: 볼륨이 페어링된 후에는 소스 볼륨과 해당 복제 타겟 볼륨을 할당해야 합니다. 복제 소스 또는 타겟은 볼륨 쌍의 볼륨일 수 있습니다. 소스 볼륨을 사용할 수 없는 경우 소스 볼륨으로 전송된 데이터를 원격 타겟 볼륨으로 리디렉션하는 경우에도 이 절차를 사용할 수 있습니다. 
---
= 복제 소스와 타겟을 페어링된 볼륨에 할당합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨이 페어링된 후에는 소스 볼륨과 해당 복제 타겟 볼륨을 할당해야 합니다. 복제 소스 또는 타겟은 볼륨 쌍의 볼륨일 수 있습니다. 소스 볼륨을 사용할 수 없는 경우 소스 볼륨으로 전송된 데이터를 원격 타겟 볼륨으로 리디렉션하는 경우에도 이 절차를 사용할 수 있습니다.

소스 볼륨과 타겟 볼륨이 포함된 클러스터에 액세스할 수 있습니다.

.단계
. 소스 볼륨 준비:
+
.. 소스로 할당할 볼륨이 포함된 클러스터에서 * Management * > * Volumes * 를 선택합니다.
.. 소스로 할당할 볼륨의 * 작업 * 아이콘을 클릭하고 * 편집 * 을 클릭합니다.
.. 액세스 * 드롭다운 목록에서 * 읽기/쓰기 * 를 선택합니다.
+

IMPORTANT: 소스 및 타겟 할당을 반대로 전환하는 경우 이 작업을 수행하면 새 복제 타겟이 할당될 때까지 볼륨 쌍에 다음 메시지가 표시됩니다. "PausedMisconfigured"

+
액세스를 변경하면 볼륨 복제가 일시 중지되고 데이터 전송이 중지됩니다. 두 사이트에서 이러한 변경 내용을 조정했는지 확인합니다.

.. 변경 내용 저장 * 을 클릭합니다.


. 타겟 볼륨 준비:
+
.. 타겟으로 할당할 볼륨이 포함된 클러스터에서 * 관리 * > * 볼륨 * 을 선택합니다.
.. 타겟으로 할당할 볼륨의 작업 아이콘을 클릭하고 * 편집 * 을 클릭합니다.
.. Access * 드롭다운 목록에서 * Replication Target * 을 선택합니다.
+

IMPORTANT: 기존 볼륨을 복제 타겟으로 할당할 경우 해당 볼륨의 데이터를 덮어씁니다. 데이터가 없고 소스 볼륨의 정확한 특성(예: 크기, 512e 설정 및 QoS 구성)이 있는 새 타겟 볼륨을 사용해야 합니다. 타겟 볼륨의 크기는 소스 볼륨과 같거나 더 클 수 있지만 크기는 작을 수 없습니다.

.. 변경 내용 저장 * 을 클릭합니다.






== 자세한 내용을 확인하십시오

* xref:task_replication_pair_volumes_using_a_volume_id.adoc[볼륨 ID를 사용하여 볼륨을 페어링합니다]
* xref:task_replication_pair_volumes_using_a_pairing_key.adoc[페어링 키를 사용하여 볼륨을 페어링합니다]

