---
permalink: storage/task_data_protection_configure_custom_protection_domains.html 
sidebar: sidebar 
keywords:  
summary: 사용자 지정 보호 도메인을 구성하여 클러스터의 복원력을 향상시킬 수 있습니다. 
---
= 사용자 지정 보호 도메인을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
두 개 이상의 스토리지 노드가 포함된 Element 클러스터의 경우 각 노드에 대해 사용자 지정 보호 도메인을 구성할 수 있습니다. 사용자 지정 보호 도메인을 구성할 때는 클러스터의 모든 노드를 도메인에 할당해야 합니다.


TIP: 보호 도메인을 할당하면 노드 간 데이터 동기화가 시작되고 데이터 동기화가 완료될 때까지 일부 클러스터 작업을 사용할 수 없습니다. 클러스터에 대해 사용자 지정 보호 도메인을 구성한 후 새 스토리지 노드를 추가할 때 노드에 대해 보호 도메인을 할당하고 데이터 동기화를 완료할 때까지 새 노드에 대한 드라이브를 추가할 수 없습니다. 를 방문하십시오 link:../concepts/concept_solidfire_concepts_data_protection.html#protection-domains["보호 도메인 설명서"] 보호 도메인에 대해 자세히 알아보십시오.


NOTE: 사용자 지정 보호 도메인 구성표를 클러스터에 사용하려면 각 섀시 내의 모든 스토리지 노드를 동일한 사용자 지정 보호 도메인에 할당해야 합니다. 이를 위해 필요한 만큼 사용자 지정 보호 도메인을 생성해야 합니다(가장 작은 사용자 지정 보호 도메인 구성표는 3개 도메인임). 모범 사례로서 도메인당 동일한 수의 노드를 구성하고 특정 도메인에 할당된 각 노드의 유형이 동일한지 확인합니다.

.단계
. 클러스터 * > * 노드 * 를 클릭합니다.
. 보호 도메인 구성 * 을 클릭합니다.
+
사용자 지정 보호 도메인 구성* 창에서 현재 구성된 보호 도메인(있는 경우)과 개별 노드에 대한 보호 도메인 할당을 볼 수 있습니다.

. 새 사용자 지정 보호 도메인의 이름을 입력하고 * Create * 를 클릭합니다.
+
생성해야 하는 모든 새 보호 도메인에 대해 이 단계를 반복합니다.

. 노드 할당 * 목록의 각 노드에 대해 * 보호 도메인 * 열의 드롭다운을 클릭하고 해당 노드에 할당할 보호 도메인을 선택합니다.
+

CAUTION: 변경 사항을 적용하기 전에 노드 및 섀시 레이아웃, 구성한 사용자 지정 보호 도메인 스키마 및 데이터 보호에 대한 스키마의 영향을 이해해야 합니다. 보호 도메인 구성표를 적용하고 즉시 변경해야 하는 경우 구성이 적용된 후 데이터 동기화가 수행되므로 변경이 가능한 한 시간이 될 수 있습니다.

. 보호 도메인 구성 * 을 클릭합니다.


클러스터 크기에 따라 도메인 간 데이터 동기화 시간이 다소 걸릴 수 있습니다. 데이터 동기화가 완료되면 * Cluster * > * Nodes * 페이지에서 사용자 지정 보호 도메인 할당을 볼 수 있으며, Element 웹 UI 대시보드는 * Custom Protection Domain Health * 창에 클러스터의 보호 상태를 표시합니다.

사용자 지정 보호 도메인 구성을 적용한 후 다음과 같은 오류가 나타날 수 있습니다.

|===


| 오류 | 설명 | 해상도 


| SetProtectionDomainLayout 실패: ProtectionDomainLayout 노드 ID를 {9}사용할 수 없습니다. 기본 이름과 기본 이름이 아닌 이름은 함께 사용할 수 없습니다. | 노드에 보호 도메인이 할당되어 있지 않습니다. | 노드에 보호 도메인을 할당합니다. 


| SetProtectionDomainLayout 실패: 보호 도메인 유형 'custom'이 보호 도메인 유형 'chassis'를 분할합니다. | 다중 노드 섀시의 노드에는 섀시의 다른 노드와 다른 보호 도메인이 할당됩니다. | 섀시의 모든 노드에 동일한 보호 도메인이 할당되었는지 확인합니다. 
|===


== 자세한 내용을 확인하십시오

link:concept_intro_custom_protection_domains.html["사용자 지정 보호 도메인"^]
link:../api/index.html["Element API를 사용하여 스토리지를 관리합니다"^]
