---
permalink: storage/task_data_manage_vol_access_group_create_an_initiator.html 
sidebar: sidebar 
keywords: initiator, create, fc, iscsi, aliases, chap 
summary: iSCSI 또는 파이버 채널 이니시에이터를 생성하고 선택적으로 별칭을 할당할 수 있습니다. 
---
= 이니시에이터를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 또는 파이버 채널 이니시에이터를 생성하고 선택적으로 별칭을 할당할 수 있습니다.

API 호출을 사용하여 이니시에이터 기반 CHAP 특성을 할당할 수도 있습니다. 이니시에이터당 CHAP 계정 이름과 자격 증명을 추가하려면 "CreateInitiator" API 호출을 사용하여 CHAP 액세스 및 특성을 제거하고 추가해야 합니다. "CreateInitiators" 및 "ModifyInitiators" API 호출을 통해 하나 이상의 virtualNetworkID를 지정하여 이니시에이터 액세스를 하나 이상의 VLAN으로 제한할 수 있습니다. 가상 네트워크를 지정하지 않으면 이니시에이터는 모든 네트워크에 액세스할 수 있습니다.

자세한 내용은 API 참조 정보를 참조하십시오.link:../api/index.html["Element API를 사용하여 스토리지를 관리합니다"]

.단계
. 관리 * > * 이니시에이터 * 를 클릭합니다.
. 이니시에이터 생성 * 을 클릭합니다.
. 다음 단계를 수행하여 단일 이니시에이터 또는 여러 이니시에이터를 생성합니다.
+
[cols="25,75"]
|===
| 옵션을 선택합니다 | 단계 


 a| 
단일 이니시에이터를 생성합니다
 a| 
.. Create a Single Initiator * 를 클릭합니다.
.. IQN/WWPN * 필드에 이니시에이터의 IQN 또는 WWPN을 입력합니다.
.. 별칭 * 필드에 초기자의 이름을 입력합니다.
.. 이니시에이터 생성 * 을 클릭합니다.




 a| 
여러 이니시에이터를 생성합니다
 a| 
.. 이니시에이터 대량 생성 * 을 클릭합니다.
.. 텍스트 상자에 IQN 또는 WWPN 목록을 입력합니다.
.. 이니시에이터 추가 * 를 클릭합니다.
.. 결과 목록에서 이니시에이터를 선택하고 * Alias * 열에서 해당하는 추가 아이콘을 클릭하여 이니시에이터의 별칭을 추가합니다.
.. 확인 표시를 클릭하여 새 별칭을 확인합니다.
.. 이니시에이터 생성 * 을 클릭합니다.


|===

