---
permalink: esds/concept_esds_networking_best_practices.html 
sidebar: sidebar 
keywords: solidfire esds, software-defined storage, networks, linux host routing, networking 
summary: SolidFire ESDS를 설치하기 전에 RHEL을 실행하는 스토리지 노드에 필요한 네트워크를 설정해야 합니다. 사용자 환경의 네트워크 라우팅에 대한 책임은 사용자에게 있습니다. 프레임워크로 제공되는 모범 사례를 사용할 수 있습니다. 
---
= 네트워크 구성을 위한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire ESDS를 설치하기 전에 RHEL을 실행하는 스토리지 노드에 필요한 네트워크를 설정해야 합니다. 사용자 환경의 네트워크 라우팅에 대한 책임은 사용자에게 있습니다. 프레임워크로 제공되는 모범 사례를 사용할 수 있습니다.

[IMPORTANT]
====
* 본드 또는 팀 구성 인터페이스를 사용합니다.
* 클러스터의 모든 노드에 대해 동일한 인터페이스 이름을 사용합니다(예: 각 노드의 관리 인터페이스에 대한 팀 관리, 노드의 스토리지 인터페이스에 대한 팀 STG).
* NetworkManager가 실행 중인지 확인합니다.
* 정책 기반 라우팅을 위해 NetworkManager-Dispatcher-routing-rules 패키지가 모든 스토리지 노드에 설치되어 있는지 확인합니다.
* 을 참조하십시오 https://www.netapp.com/us/media/tr-4763.pdf["NetApp SolidFire 스토리지 시스템의 네트워킹 및 네트워크 유지 관리에 대한 모범 사례"].
* 본드 또는 팀 구성을 통해 여러 개의 이중화 물리적 인터페이스를 사용하도록 각 노드의 관리 및 스토리지 네트워크를 구성합니다.


====
네트워크 팀 구성에 대한 자세한 내용은 을 참조하십시오 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-configure_network_teaming["네트워크 팀 구성을 구성합니다"^]. 기본적으로 모든 스토리지 노드 10GbE 인터페이스는 최대 전송 단위(MTU)가 9000바이트로 활성화됩니다. 최적의 성능을 위해 모든 서버측 스토리지 인터페이스를 NetApp SolidFire 스토리지 노드와 동일한 MTU로 구성합니다. 점보 프레임 오버헤드와 네트워크를 통한 적절한 전달을 고려하여 최소 9016바이트 이상의 MTU를 지원하도록 네트워크 스위치를 구성해야 합니다. 더 낮은 MTU 설정을 지원하도록 이 구성을 변경하려면 NetApp 지원에 문의하십시오.

SolidFire ESDS에서 다양한 유형의 트래픽에 필요한 스토리지 및 관리 네트워크에 대한 자세한 내용은 다음 표를 참조하십시오.

[cols="2*"]
|===
| 네트워크 유형입니다 | 설명 


 a| 
스토리지 네트워크
 a| 
* 모든 스토리지/iSCSI 트래픽을 포함합니다.
* 다른 계층 3 네트워크에 있는 호스트에서 마운트하거나 클러스터 간에 데이터를 복제하려는 경우 라우팅할 수 있습니다.
* 동일한 계층 2 브로드캐스트 도메인의 네트워크 인터페이스로 구성되어야 합니다.




 a| 
관리 네트워크
 a| 
* 모든 관리 트래픽을 포함합니다.
* 다른 계층 3 네트워크에서 클러스터 API 또는 UI에 액세스하려는 경우 라우팅될 수 있습니다.
* 동일한 계층 2 브로드캐스트 도메인의 네트워크 인터페이스로 구성되어야 합니다.
* MTU가 1500바이트 이상인 네트워크 인터페이스 카드로 구성해야 합니다.


|===

TIP: 호스트 네트워크 구성에 대한 예제 및 팁은 를 참조하십시오 link:task_esds_configure_the_interface_config_files.adoc["여기"].



== 자세한 내용을 확인하십시오

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 리소스 페이지 를 참조하십시오"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

