---
permalink: esds/reference_esds_containerlogs.html 
sidebar: sidebar 
keywords: element, solidfire esds, get container logs, sds containers 
summary: SolidFire ESDS 컨테이너 및 관련 로그를 얻을 수 있는 위치에 대해 자세히 알아보십시오. 여기에 제공된 정보는 문제 해결을 위한 로그 수집을 시작하는 데 도움이 됩니다. 로그 분석에 정통한 교육 받은 엔지니어가 문제를 해결하는 데 도움이 되는 NetApp Support와 계약을 체결하는 것이 가장 좋습니다. 
---
= 컨테이너 로그를 수집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire ESDS 컨테이너 및 관련 로그를 얻을 수 있는 위치에 대해 자세히 알아보십시오. 여기에 제공된 정보는 문제 해결을 위한 로그 수집을 시작하는 데 도움이 됩니다. 참여하는 것이 가장 좋습니다 https://www.netapp.com/company/contact-us/support/["NetApp 지원"^]로그 분석을 잘 알고 있는 숙련된 엔지니어가 문제를 해결하는 데 도움이 될 수 있습니다.

SolidFire ESDS에는 다음 컨테이너가 포함됩니다.

* 요소 컨테이너('element'): 모든 요소 서비스를 단일 컨테이너에 호스팅합니다.
* 요소 인증 컨테이너('element_auth'): 관리 UI에 대해 다단계 인증(MFA) 및 세션 인증 토큰을 제공합니다.
* Network Watchdog container('fsnetwd'): 로컬 Element 인스턴스의 하트비트 모니터링과 가상 IP(MVIP 및 SVIP)의 페일오버를 제공합니다.


SSH를 통해 ESDS 노드의 컨테이너에 액세스하려면 노드 소유자가 SSH를 활성화하고 로그인 자격 증명을 제공해야 합니다. 호스트 시스템에 대한 SSH 액세스 권한이 있으면 'podman PS' 명령어를 사용해 하나 이상의 컨테이너의 상태를 확인할 수 있다. 아래 예를 참조하십시오.

[listing]
----
# podman ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f6b8817c024a localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 10 seconds ago sfnetwd
c3fed6141259 localhost/solidfire-auth:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 11 seconds ago element_auth
1ffa8289c701 localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 12 seconds ago Up 12 seconds ago element
#
----

IMPORTANT: 컨테이너 중 하나가 가동되거나 실행되고 있지 않은 경우 Podman을 사용하여 컨테이너를 직접 제어(중지 또는 시작)하지 마십시오. Element 소프트웨어는 'SolidFire systemd' 서비스 유닛을 통해 제어됩니다. 이 서비스는 elementctl을 사용하여 세 요소 컨테이너에서 실행되는 소프트웨어를 조정합니다. 호스트에서 SolidFire 서비스를 제어하기 위해 'stemctl'을 사용하는 것이 모든 노드에서 Element 소프트웨어를 시작 및 중지하는 권장 방법이지만, 라이브 클러스터에서는 지원 부서의 지침에 따라 작업을 수행해야 합니다.

SolidFire ESDS와 관련된 모든 로그는 컨테이너 인스턴스 전체에 걸쳐 유지되는 호스트의 '/var/log/solidfire/'에서 찾을 수 있습니다. 이 디렉토리에는 Element 컨테이너의 로그가 들어 있으며, 각각 ELEMENT_AUTH와 Sfnetwd 컨테이너의 로그가 들어 있는 ELEMENT_AUTH/ 및 Sfnetwd/ 하위 디렉토리가 포함되어 있습니다. 컨테이너 내부에서 '/var/log'에서 컨테이너별 로그에 액세스할 수 있습니다.



=== NetApp 하이브리드 클라우드 제어 UI를 사용하여 로그를 수집하십시오

로그를 수집하여 NetApp 지원에 전송하여 SolidFire ESDS 클러스터 관련 문제를 진단하는 데 도움이 되도록 할 수 있습니다.

로그를 수집할 때 다음 사항을 염두에 두십시오.

* 로그를 수집하기 위해 Podman 명령을 사용하지 마십시오.
* NetApp 지원에서는 호스트 로그 수집을 위해 하나의 수집을 사용합니다. 최적의 지원 환경을 위해 Collect를 설치해야 합니다.


.단계
. 웹 브라우저를 열고 관리 노드의 IP 주소를 찾습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
https://[management node IP address]
----
. NetApp 하이브리드 클라우드 제어에 스토리지 클러스터 관리자 자격 증명을 제공하여 로그인하십시오.
. 대시보드 에서 오른쪽 위에 있는 메뉴를 선택합니다.
. 로그 수집 * 을 선택합니다.
. 날짜 범위 * 드롭다운 메뉴에서 날짜 범위를 선택하여 로그에 포함할 날짜를 지정합니다.
+
사용자 지정 시작 날짜를 지정하는 경우 날짜를 선택하여 날짜 범위를 시작할 수 있습니다. 로그는 해당 날짜부터 현재 시간까지 수집됩니다.

. Log Collection * 섹션에서 스토리지 클러스터 또는 특정 스토리지 노드를 선택합니다.
. 로그 수집을 시작하려면 * 로그 수집 * 을 선택합니다.
+
로그 수집은 백그라운드에서 실행되며 페이지에 진행 상황이 표시됩니다.

+

NOTE: 수집한 로그에 따라 진행률 표시줄이 몇 분 동안 특정 비율로 유지되거나 일부 지점에서 매우 느리게 진행될 수 있습니다.

. 로그 패키지를 다운로드하려면 * 로그 다운로드 * 를 선택합니다.
+
로그 패키지는 압축된 UNIX 파일 형식 .tgz입니다.





== 자세한 내용을 확인하십시오

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 리소스 페이지 를 참조하십시오"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

