---
permalink: esds/reference_esds_use_maintenance_mode.html 
sidebar: sidebar 
keywords: element, solidfire esds, maintenance, maintenance mode 
summary: 소프트웨어 업그레이드 또는 호스트 복구 같이 유지보수를 위해 스토리지 노드를 오프라인 상태로 전환해야 하는 경우, 해당 노드에 대한 유지보수 모드를 지원하여 스토리지 클러스터의 나머지 부분에 대한 I/O 영향을 최소화할 수 있습니다. 
---
= SolidFire ESDS 클러스터에서 유지보수 모드를 사용합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
소프트웨어 업그레이드 또는 호스트 복구 같이 유지보수를 위해 스토리지 노드를 오프라인 상태로 전환해야 하는 경우, 해당 노드에 대한 유지보수 모드를 지원하여 스토리지 클러스터의 나머지 부분에 대한 I/O 영향을 최소화할 수 있습니다.


TIP: 노드에서 유지보수 모드의 현재 상태를 확인하려면 를 사용하십시오 link:../api/reference_element_api_listactivenodes.html["'ListActiveNodes"^] API 메소드. 노드 오브젝트에는 노드에 있는 유지보수 모드의 현재 상태를 나타내는 'maintenanceMode' 매개 변수가 포함됩니다.


NOTE: 유지보수 모드가 활성화된 즉시 유지 관리를 수행해야 합니다. 노드를 유지보수 모드로 필요한 시간 이상으로 방치하지 마십시오.

노드가 정상 상태(차단 클러스터 장애가 없음)이고 스토리지 클러스터가 단일 노드 장애를 허용하지 않는 경우에만 스토리지 노드를 유지보수 모드로 전환할 수 있습니다. 정상 및 허용 노드에 대해 유지보수 모드를 활성화하면 노드가 즉시 전환되지 않고 다음 조건이 충족될 때까지 노드가 모니터링됩니다.

* 노드에서 호스팅되는 모든 볼륨이 페일오버되었으며 노드는 더 이상 모든 볼륨의 운영 볼륨으로 호스팅되지 않습니다.
* 페일오버되는 모든 볼륨에 임시 대기 노드가 할당됩니다.


이러한 기준이 충족되면 노드는 유지보수 모드로 전환됩니다. 5분 이내에 이러한 조건이 충족되지 않으면 노드가 유지보수 모드로 전환되지 않습니다.

스토리지 노드에 대해 유지보수 모드를 해제하면 다음 조건이 충족될 때까지 노드가 모니터링됩니다.

* 모든 데이터가 노드에 완전히 복제됩니다.
* 모든 차단 클러스터 장애가 해결되었습니다.
* 노드에서 호스팅되는 볼륨에 대한 모든 임시 대기 노드 할당이 활성화되지 않았습니다.


이러한 기준이 충족되면 노드는 유지보수 모드에서 전환됩니다. 1시간 이내에 이러한 조건이 충족되지 않으면 노드가 유지보수 모드에서 전환되지 않습니다.



== 유지 관리 모드를 사용하는 동안 가능한 시나리오

* 노드가 유지보수 모드에 있지만 아직 재부팅되지 않았거나 유지보수가 발생하지 않았거나 유지보수 작업이 수행되었거나 유지 보수가 수행되었으며 백업 및 상태가 양호했지만 유지보수 모드를 비활성화하지 않은 경우, 또 다른 노드가 다운되면 첫 번째 노드의 유지보수 모드가 자동으로 비활성화됩니다.
* 노드 중 하나가 유지보수 모드이고 다른 노드가 동시에 중단되면 중단이 있습니다. 유지보수 모드에 있는 노드가 다시 온라인 상태가 될 때까지 기다려야 합니다.
* 유지 관리 모드에서 장시간 앙상블의 구성원인 노드를 놓으면 다른 노드를 추가할 수 있는 경우 앙상블에서 자동으로 제거됩니다.




== 유지보수 모드를 활성화합니다

"Enable유지보수모드" API 메소드를 사용하여 유지보수 모드를 활성화할 수 있습니다. 이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

[cols="5*"]
|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
포세언풀베데폭스
 a| 
클러스터 장애 차단이 있는 경우에도 이 노드에 대해 유지 관리 모드를 강제로 사용하도록 설정합니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
'절점'
 a| 
유지보수 모드로 전환할 노드 ID 목록입니다. 한 번에 하나의 노드만 지원됩니다.
 a| 
정수 배열
 a| 
없음
 a| 
예



 a| 
퍼민트프리마라이스파리미트
 a| 
분당 스왑할 기본 슬라이스의 수입니다. 지정하지 않으면 모든 기본 슬라이스가 한 번에 스왑됩니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
'시간 초과'입니다
 a| 
유지 관리 모드가 자동으로 비활성화되기 전까지 활성화 상태를 유지할 기간을 지정합니다. 시간 문자열 형식(예: HH:MM:ss)입니다. 지정하지 않으면 명시적으로 비활성화될 때까지 유지 관리 모드가 활성 상태로 유지됩니다.
 a| 
문자열
 a| 
없음
 a| 
아니요

|===
이 메서드의 반환 값은 다음과 같습니다.

[cols="3*"]
|===
| 이름 | 설명 | 유형 


 a| 
아신핸들
 a| 
"GetAsyncResult" 메서드를 사용하여 이 asyncHandle 을 검색하고 유지 관리 모드 전환이 완료되는 시기를 확인할 수 있습니다.
 a| 
정수



 a| 
'CurrentMode(현재 모드)'
 a| 
노드의 현재 유지보수 모드 상태입니다. 가능한 값:

* Disabled(비활성화): 요청된 유지 관리가 없습니다.
* FailedToRecover: 노드가 유지보수 모드에서 복구되지 못했습니다.
* RecoveringFromMaintenance: 노드가 유지보수 모드에서 복구 중입니다.
* PreparingForMaintenance: 유지 관리를 수행할 노드를 준비하기 위한 작업이 수행됩니다.
* ReadyForMaintenance: 노드를 유지 관리할 준비가 되었습니다.

 a| 
유지 관리 모드(문자열)



 a| 
재취상모드
 a| 
요청된 노드의 유지보수 모드 상태입니다. 가능한 값:

* Disabled(비활성화): 요청된 유지 관리가 없습니다.
* FailedToRecover: 노드가 유지보수 모드에서 복구되지 못했습니다.
* RecoveringFromMaintenance: 노드가 유지보수 모드에서 복구 중입니다.
* PreparingForMaintenance: 유지 관리를 수행할 노드를 준비하기 위한 작업이 수행됩니다.
* ReadyForMaintenance: 노드를 유지 관리할 준비가 되었습니다.

 a| 
유지 관리 모드(문자열)

|===


== 유지보수 모드를 비활성화합니다

Disable유지보수모드 API 메소드를 사용하여 유지보수 모드를 비활성화할 수 있습니다. 이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

[cols="5*"]
|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
'절점'
 a| 
유지보수 모드에서 벗어났을 스토리지 노드 ID 목록입니다.
 a| 
정수 배열
 a| 
없음
 a| 
예

|===
이 메서드의 반환 값은 다음과 같습니다.

[cols="3*"]
|===
| 이름 | 설명 | 유형 


 a| 
아신핸들
 a| 
"GetAsyncResult" 메서드를 사용하여 이 asyncHandle 을 검색하고 유지 관리 모드 전환이 완료되는 시기를 확인할 수 있습니다.
 a| 
정수



 a| 
'CurrentMode(현재 모드)'
 a| 
노드의 현재 유지보수 모드 상태입니다. 가능한 값:

* Disabled(비활성화): 요청된 유지 관리가 없습니다.
* FailedToRecover: 노드가 유지보수 모드에서 복구되지 못했습니다.
* Unexpected: 노드가 오프라인 상태로 발견되었지만 Disabled 모드에 있습니다.
* RecoveringFromMaintenance: 노드가 유지보수 모드에서 복구 중입니다.
* PreparingForMaintenance: 유지 관리를 수행할 노드를 준비하기 위한 작업이 수행됩니다.
* ReadyForMaintenance: 노드를 유지 관리할 준비가 되었습니다.

 a| 
유지 관리 모드(문자열)



 a| 
재취상모드
 a| 
요청된 노드의 유지보수 모드 상태입니다. 가능한 값:

* Disabled(비활성화): 요청된 유지 관리가 없습니다.
* FailedToRecover: 노드가 유지보수 모드에서 복구되지 못했습니다.
* Unexpected: 노드가 오프라인 상태로 발견되었지만 Disabled 모드에 있습니다.
* RecoveringFromMaintenance: 노드가 유지보수 모드에서 복구 중입니다.
* PreparingForMaintenance: 유지 관리를 수행할 노드를 준비하기 위한 작업이 수행됩니다.
* ReadyForMaintenance: 노드를 유지 관리할 준비가 되었습니다.

 a| 
유지 관리 모드(문자열)

|===


== 자세한 내용을 확인하십시오

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 리소스 페이지 를 참조하십시오"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

