---
permalink: esds/reference_esds_sf_sds_config_file.html 
sidebar: sidebar 
keywords: element, solidfire esds, hardware components, configuration file 
summary: 모든 노드에는 SF_SDS_config.YAML 파일이 있으며, 여기에는 SolidFire ESDS 서비스에서 사용하도록 지정한 하드웨어 목록이 포함됩니다. 드라이브를 교체한 후 드라이브를 교체한 노드에 대해 이 파일에 교체 드라이브 정보를 추가해야 합니다. 이 파일은 /opt/sf/에 저장됩니다. 이 파일에는 노드의 드라이브에 대한 모든 정보가 포함됩니다. 새 드라이브를 추가할 때마다 이 파일에 새 드라이브의 세부 정보를 입력해야 합니다. 
---
= SF_SDS_config.YAML 파일의 내용입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 노드에는 SolidFire ESDS 서비스에서 사용하도록 지정한 하드웨어 목록이 포함된 'f_sds_config.yAML' 파일이 있습니다. 드라이브를 교체한 후 드라이브를 교체한 노드에 대해 이 파일에 교체 드라이브 정보를 추가해야 합니다. 이 파일은 '/opt/sf/'에 저장됩니다. 이 파일에는 노드의 드라이브에 대한 모든 정보가 포함됩니다. 새 드라이브를 추가할 때마다 이 파일에 새 드라이브의 세부 정보를 입력해야 합니다.

파일의 * 필수 * 내용은 다음과 같습니다.

[cols="4*"]
|===
| 키 | 기본값 | 유형 | 설명 


 a| 
schemaVersion 을 참조하십시오
 a| 
"2.0"
 a| 
문자열
 a| 
파일의 스키마 버전 번호입니다.



 a| 
네트워크
 a| 
해당 없음
 a| 
목록
 a| 
허용되는 값: 관리 인터페이스, storageInterface



 a| 
관리 인터페이스
 a| 
"team0"
 a| 
문자열
 a| 
관리 및 클러스터 관리 트래픽에 사용할 사전 구성된 중복 호스트 OS 네트워크 인터페이스의 이름입니다.



 a| 
스토리지 인터페이스
 a| 
"Team1"
 a| 
문자열
 a| 
스토리지 네트워크 트래픽(iSCSI 트래픽)에 사용할 사전 구성된 중복 호스트 OS 네트워크 인터페이스의 이름입니다.



 a| 
데이터 드라이브
 a| 
해당 없음
 a| 
목록
 a| 
SolidFire ESDS에서 사용 중인 물리적 스토리지 디바이스에 대한 호스트 OS 경로 목록입니다. 이 경로를 블록 또는 NVMe 장치에 대한 전체 경로로 지정할 수 있습니다. /dev/disk/by-id/WWN-xxxx-xxxx-example, /dev/disk/by-uuuid/NVMe-xxxx-xxxxx-example 및 /dev/sda1과 같은 전체 경로 예제가 지원됩니다



 a| 
캐시 디바이스
 a| 
해당 없음
 a| 
목록
 a| 
SolidFire ESDS에서 캐시 디바이스로 사용 중인 물리적 디바이스에 대한 호스트 OS 경로입니다. 목록 항목으로 지정해야 합니다. 다음은 지원되는 전체 경로의 예입니다. /dev/disk/by-id/NVMe-NVMe.8086-XXXXXXX-XXXXX-XXXXXX - 예

|===


== 자세한 내용을 확인하십시오

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 리소스 페이지 를 참조하십시오"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

