---
permalink: api/concept_element_api_about_the_api.html 
sidebar: sidebar 
keywords: SolidFire,API,overview,about,Element 
summary: Element API는 HTTPS를 통한 JSON-RPC 프로토콜을 기반으로 합니다. JSON-RPC는 경량 JSON 데이터 교환 형식을 기반으로 하는 간단한 텍스트 기반 RPC 프로토콜입니다. 클라이언트 라이브러리는 모든 주요 프로그래밍 언어에 사용할 수 있습니다. 
---
= Element 소프트웨어 API 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element API는 HTTPS를 통한 JSON-RPC 프로토콜을 기반으로 합니다. JSON-RPC는 경량 JSON 데이터 교환 형식을 기반으로 하는 간단한 텍스트 기반 RPC 프로토콜입니다. 클라이언트 라이브러리는 모든 주요 프로그래밍 언어에 사용할 수 있습니다.

API 엔드포인트에 대한 HTTPS POST 요청을 통해 API 요청을 할 수 있습니다. POST 요청의 본문은 JSON-RPC 요청 객체입니다. API는 현재 배치 요청(단일 POST의 여러 요청 객체)을 지원하지 않습니다. API 요청을 제출할 때 요청의 콘텐츠 유형으로 "application/json-rpc"를 사용하고 본문이 형식 인코딩되지 않았는지 확인해야 합니다.


NOTE: Element 웹 UI는 이 문서에 설명된 API 메소드를 사용합니다. API 로그를 활성화하여 UI에서 API 작업을 모니터링할 수 있으며, 이를 통해 시스템에 실행 중인 메서드를 볼 수 있습니다. 요청과 응답을 모두 활성화하여 시스템이 실행된 메서드에 응답하는 방법을 확인할 수 있습니다.

달리 명시되지 않는 한, API 응답의 모든 날짜 문자열은 UTC+0 형식입니다.


NOTE: 스토리지 클러스터에 로드가 많이 있거나 중간 지연 없이 여러 개의 연속된 API 요청을 제출하는 경우 메서드가 실패하고 "xDBVersionMismatch" 오류가 반환될 수 있습니다. 이 경우 메서드 호출을 다시 시도하십시오.

* xref:reference_element_api_request_object_members.adoc[객체 구성원 요청]
* xref:reference_element_api_response_object_members.adoc[응답 객체 멤버]
* xref:concept_element_api_request_endpoints.adoc[엔드포인트 요청]
* xref:concept_element_api_authentication.adoc[API 인증]
* xref:concept_element_api_asynchronous_methods.adoc[비동기 메서드]
* xref:reference_element_api_attributes.adoc[속성]




== 자세한 내용을 확인하십시오

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

