---
permalink: api/reference_element_api_volumepair.html 
sidebar: sidebar 
keywords: object,objects,volumePair 
summary: volumePair 개체에는 다른 클러스터의 다른 볼륨과 페어링된 볼륨에 대한 정보가 들어 있습니다. 볼륨이 페어링되지 않은 경우 이 개체는 비어 있습니다. ListActivePairedVolumes 및 ListActiveVolumes API 메소드를 사용하여 페어링된 볼륨에 대한 정보를 반환할 수 있습니다. 
---
= 볼륨페어가 있습니다
:icons: font
:imagesdir: ../media/


[role="lead"]
volumePair 개체에는 다른 클러스터의 다른 볼륨과 페어링된 볼륨에 대한 정보가 들어 있습니다. 볼륨이 페어링되지 않은 경우 이 개체는 비어 있습니다. 'ListActivePairedVolumes' 및 'ListActiveVolumes' API 메소드를 사용하여 페어링된 볼륨에 대한 정보를 반환할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
클러스터 airID
 a| 
볼륨이 페어링된 클러스터
 a| 
정수



 a| 
원격 복제
 a| 
볼륨 복제에 대한 세부 정보입니다. 구성원:

* Mode: (string) "Async", "Sync" 또는 "SnapshotsOnly" 중 하나입니다.
* pauseLimit: (정수) 내부 전용.
* remoteServiceID: (정수) 원격 슬라이스 서비스 ID입니다.
* resumeDetails: (string) 나중에 사용할 수 있도록 예약되어 있습니다.
* snapshotReplication(JSON 개체)
+
** 상태: (string) 진행 중인 스냅샷 복제의 상태입니다.
** stateDetails: (string) 나중에 사용할 수 있도록 예약되어 있습니다.


* 상태: (string) 볼륨 복제의 상태입니다.
* stateDetails: (string) 나중에 사용할 수 있도록 예약되어 있습니다.

 a| 
JSON 개체



 a| 
remoteSliceID
 a| 
원격 클러스터의 클러스터 정의 슬라이스 ID입니다.
 a| 
정수



 a| 
원격 볼륨 ID
 a| 
로컬 볼륨이 페어링되어 있는 원격 클러스터의 볼륨 ID입니다.
 a| 
정수



 a| 
원격 볼륨 이름
 a| 
원격 볼륨의 이름입니다.
 a| 
문자열



 a| 
볼륨 UUID
 a| 
정식 형식으로 이 페어링에 대해 보편적으로 고유한 클러스터 정의 식별자입니다.
 a| 
문자열

|===


== 자세한 내용을 확인하십시오

* xref:reference_element_api_listactivepairedvolumes.adoc[ListActive유료볼륨]
* xref:reference_element_api_listactivevolumes.adoc[ListActiveVolumes]

