---
permalink: api/reference_element_api_modifykeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,modifying,modify,change,edit 
summary: 'ModifyKeyServerKmip 메서드를 사용하여 기존 키 관리 상호 운용성 프로토콜\(KMIP\) 키 서버를 지정된 특성으로 수정할 수 있습니다. 유일하게 필요한 매개 변수는 keyServerID이지만 keyServerID만 포함하는 요청은 아무런 조치를 취하지 않고 오류가 발생하지 않습니다. 지정하는 다른 모든 매개 변수는 키 서버의 기존 값을 지정된 keyServerID로 바꿉니다. 작동 중에 키 서버가 제대로 작동하는지 확인하기 위해 키 서버에 접촉합니다. kmipKeyServerHostnames 매개 변수를 사용하여 호스트 이름 또는 IP 주소를 여러 개 제공할 수 있지만 키 서버가 클러스터 구성에 있는 경우에만 가능합니다.' 
---
= ModifyKeyServerKmip
:icons: font
:imagesdir: ../media/


[role="lead"]
ModifyKeyServerKmip 방식을 사용하여 기존 KMIP(Key Management Interoperability Protocol) 키 서버를 지정된 속성으로 수정할 수 있습니다. 유일하게 필요한 매개 변수는 keyServerID이지만 keyServerID만 포함하는 요청은 아무런 조치를 취하지 않고 오류가 발생하지 않습니다. 지정하는 다른 모든 매개 변수는 키 서버의 기존 값을 지정된 keyServerID로 바꿉니다. 작동 중에 키 서버가 제대로 작동하는지 확인하기 위해 키 서버에 접촉합니다. kmipKeyServerHostnames 매개 변수를 사용하여 호스트 이름 또는 IP 주소를 여러 개 제공할 수 있지만 키 서버가 클러스터 구성에 있는 경우에만 가능합니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
KeyServerID를 입력합니다
 a| 
수정할 KMIP Key Server의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
KmipCaCertificate입니다
 a| 
외부 키 서버의 루트 CA의 공개 키 인증서입니다. TLS 통신에서 외부 키 서버가 제공하는 인증서를 확인하는 데 사용됩니다. 개별 서버가 서로 다른 CA를 사용하는 키 서버 클러스터의 경우 모든 CA의 루트 인증서가 포함된 연결된 문자열을 제공합니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
kmipClientCertificate를 참조하십시오
 a| 
SolidFire KMIP 클라이언트가 사용하는 PEM 형식 Base64 인코딩된 PKCS #10 X.509 인증서.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
kmipKeyServerHostName입니다
 a| 
이 KMIP 키 서버와 연관된 호스트 이름 또는 IP 주소의 배열입니다. 키 서버가 클러스터 구성에 있는 경우에만 호스트 이름 또는 IP 주소를 여러 개 제공해야 합니다.
 a| 
문자열 배열
 a| 
없음
 a| 
아니요



 a| 
kmipKeyServerName입니다
 a| 
KMIP 키 서버의 이름입니다. 이 이름은 표시 목적으로만 사용되며 고유한 이름은 필요하지 않습니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
kmipKeyServerPort 를 참조하십시오
 a| 
이 KMIP 키 서버와 연관된 포트 번호(일반적으로 5696)
 a| 
정수
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
KmipKeyServer를 참조하십시오
 a| 
새로 수정된 키 서버에 대한 세부 정보가 포함된 개체입니다.
 a| 
link:reference_element_api_keyserverkmip.md#["KeyServerKmip"]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "method": "ModifyKeyServerKmip",
  "params": {
    "keyServerID": 15
    "kmipCaCertificate": "CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "kirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"kirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== 버전 이후 새로운 기능

11.7
