---
permalink: api/reference_element_api_drivestats.html 
sidebar: sidebar 
keywords: object,objects,driveStats 
summary: DRIVeStats 개체에는 단일 드라이브에 대한 높은 수준의 활동 측정이 포함되어 있습니다. API 메서드 GetDriveStats 를 사용하여 측정 정보를 검색할 수 있습니다. 
---
= 드라이브 통계
:icons: font
:imagesdir: ../media/


[role="lead"]
DRIVeStats 개체에는 단일 드라이브에 대한 높은 수준의 활동 측정이 포함되어 있습니다. API 메소드 GetDriveStats를 사용하여 측정 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
활성 세션
 a| 
현재 이 드라이브를 사용하는 iSCSI 세션 수(메타데이터 드라이브에만 있음).
 a| 
정수



 a| 
드라이브 ID입니다
 a| 
클러스터에 있는 드라이브의 고유 ID입니다.
 a| 
정수



 a| 
실패 DieCount
 a| 
실패한 드라이브 하드웨어 요소의 수입니다.
 a| 
정수



 a| 
라이프리메이ingPercent
 a| 
드라이브 미디어 마모 표시등
 a| 
정수



 a| 
lifetimeReadBytes 를 참조하십시오
 a| 
드라이브의 수명 동안 이 드라이브에서 읽은 총 바이트.
 a| 
정수



 a| 
lifetimWriteBytes 를 참조하십시오
 a| 
드라이브의 수명 동안 이 드라이브에 기록된 총 바이트 수입니다.
 a| 
정수



 a| 
파워온후스
 a| 
이 드라이브의 전원이 켜진 시간.
 a| 
정수



 a| 
읽기\바이트
 a| 
클라이언트 작업으로 인해 드라이브에서 읽은 총 바이트 수입니다.
 a| 
정수



 a| 
readOps를 참조하십시오
 a| 
클라이언트 작업으로 인한 드라이브의 총 읽기 작업입니다.
 a| 
정수



 a| 
할당했습니다
 a| 
이 드라이브에서 교체한 불량 섹터 수입니다.
 a| 
정수



 a| 
예비 용량 Percent
 a| 
드라이브의 사용 가능한 예약 용량입니다.
 a| 
정수



 a| 
타임 스탬프입니다
 a| 
UTC + 0 형식의 현재 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
총 용량
 a| 
드라이브의 총 용량(바이트)입니다.
 a| 
정수



 a| 
UncorrectableErrors(교정되지 않은 오류)
 a| 
드라이브의 SMART(Self-Monitoring, Analysis and Reporting Technology) 모니터링 시스템에서 보고된 수정할 수 없는 오류 값입니다.
 a| 
정수



 a| 
사용 용량
 a| 
드라이브의 사용된 용량(바이트)입니다.
 a| 
정수



 a| 
사용메모리
 a| 
이 드라이브를 호스팅하는 노드에서 현재 사용하는 메모리 양입니다.
 a| 
정수



 a| 
쓰기 바이트
 a| 
클라이언트 작업으로 인해 드라이브에 기록된 총 바이트 수입니다.
 a| 
정수



 a| 
쓰기 작업
 a| 
클라이언트 작업으로 인해 드라이브에 대한 총 쓰기 작업입니다.
 a| 
정수

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_getdrivestats.adoc[GetDriveStats 를 참조하십시오]
