---
permalink: api/reference_element_api_node.html 
sidebar: sidebar 
keywords: object,objects,node 
summary: 노드 오브젝트에는 클러스터의 각 노드에 대한 정보가 포함됩니다. ListActiveNodes 및 ListAllNodes 메서드를 사용하여 이 정보를 검색할 수 있습니다. 
---
= 노드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 오브젝트에는 클러스터의 각 노드에 대한 정보가 포함됩니다. 이 정보는 ListActiveNodes 및 ListAllNodes 메서드를 사용하여 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
연관FServiceID입니다
 a| 
노드의 Fibre Channel 서비스 ID입니다. 노드가 Fibre Channel 노드가 아닌 경우 "0"입니다.
 a| 
정수



 a| 
연계한 마스터 서비스 ID입니다
 a| 
노드의 마스터 서비스 ID입니다.
 a| 
정수



 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체



 a| 
섀시 이름
 a| 
섀시를 고유하게 식별하며 단일 섀시의 모든 노드에 대해 동일합니다.
 a| 
문자열



 a| 
CIP
 a| 
노드에 할당된 클러스터 IP 주소입니다.
 a| 
문자열



 a| 
치피
 a| 
클러스터 통신에 사용되는 네트워크 인터페이스입니다.
 a| 
문자열



 a| 
customProtectionDomainName입니다
 a| 
사용자 지정 보호 도메인을 고유하게 식별합니다. 이 이름은 지정된 사용자 지정 보호 도메인의 모든 섀시 내의 모든 스토리지 노드에 대해 동일합니다.
 a| 
문자열



 a| 
광섬유 채널 TargetPortGroup 을 참조하십시오
 a| 
이 노드와 연결된 대상 그룹입니다. 노드가 Fibre Channel 노드가 아닌 경우 "null"입니다.
 a| 
정수



 a| 
유지 관리 모드
 a| 
노드가 유지 관리를 위해 어떤 모드에 있는지 나타냅니다.
 a| 
해당 없음



 a| 
MIP
 a| 
노드 관리에 사용되는 IP 주소입니다.
 a| 
문자열



 a| 
미피
 a| 
노드 관리에 사용되는 네트워크 인터페이스입니다.
 a| 
문자열



 a| 
이름
 a| 
노드의 호스트 이름입니다.
 a| 
문자열



 a| 
노드 ID입니다
 a| 
이 노드의 노드 ID입니다.
 a| 
정수



 a| 
노드 슬롯
 a| 
HCI 플랫폼의 경우 이 노드가 있는 섀시 슬롯("A", "B", "C" 또는 "D")에 해당하는 문자가 있습니다. 스토리지 플랫폼의 경우 이 값은 null입니다.
 a| 
문자열



 a| 
플랫폼 정보
 a| 
노드에 대한 하드웨어 정보입니다. 구성원:

* chassisType: 노드의 하드웨어 플랫폼입니다.
* cpuModel: 하드웨어 플랫폼의 CPU 모델입니다.
* 노드 메모리 GB: 물리적 플랫폼에 설치된 메모리 크기(GB)입니다.
* NodeType: 노드 모델 이름입니다.
* PlatformConfigVersion: 이 노드 하드웨어에 대해 구성된 소프트웨어 버전입니다.

 a| 
JSON 개체



 a| 
역할
 a| 
클러스터에서 노드의 역할입니다. 가능한 값:

* 관리
* 스토리지
* 컴퓨팅
* 증인

 a| 



 a| 
SIP
 a| 
노드에 할당된 스토리지 IP 주소입니다.
 a| 
문자열



 a| 
SIPI
 a| 
스토리지 트래픽에 사용되는 네트워크 인터페이스입니다.
 a| 
문자열



 a| 
소프트웨어 버전
 a| 
노드에서 실행 중인 Element 소프트웨어의 현재 버전을 반환합니다.
 a| 
문자열



 a| 
UUID입니다
 a| 
이 노드와 관련된 범용 고유 식별자입니다.
 a| 
문자열



 a| 
가상네트워크
 a| 
가상 네트워크 IP 주소 및 ID가 포함된 객체입니다.
 a| 
xref:reference_element_api_virtualnetwork.adoc[가상네트워크] 스토리지

|===


== 자세한 내용을 확인하십시오

* xref:reference_element_api_listactivenodes.adoc[ListActiveNodes 를 선택합니다]
* xref:reference_element_api_listallnodes.adoc[목록노드]

