---
permalink: api/reference_element_api_startbulkvolumewrite.html 
sidebar: sidebar 
keywords: volume,bulk,start,starting,write,session,startbulkvolumewrite 
summary: StartBulkVolumeWrite 메서드를 사용하여 지정된 볼륨에서 대량 볼륨 쓰기 세션을 시작할 수 있습니다. 
---
= StartBulkVolumeWrite
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'stBulkVolumeWrite' 메서드를 사용하여 지정된 볼륨에서 대량 볼륨 쓰기 세션을 시작할 수 있습니다.

하나의 볼륨에서 2개의 대량 볼륨 프로세스만 동시에 실행할 수 있습니다. 세션을 초기화하면 외부 백업 소스에서 Element 스토리지 볼륨에 데이터가 기록됩니다. 외부 데이터는 Element 스토리지 노드에서 실행되는 웹 서버에서 액세스합니다. 외부 데이터 액세스에 대한 서버 상호 작용 정보는 스토리지 시스템에서 실행되는 스크립트를 통해 전달됩니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
형식
 a| 
볼륨 데이터의 형식입니다. 다음 중 하나일 수 있습니다.

* '비압축': 볼륨의 모든 바이트는 압축 없이 반환됩니다.
* '네이티브': 불투명한 데이터가 반환되어 더 작고 더 효율적으로 저장되며 이후의 대량 볼륨 쓰기에 기록됩니다.

 a| 
문자열
 a| 
없음
 a| 
예



 a| 
볼륨 ID
 a| 
기록할 볼륨의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
스크립트
 a| 
실행 스크립트의 이름입니다. 스크립트 이름을 제공하지 않으면 Element 스토리지 노드를 액세스하는 데 키와 URL이 필요합니다. 스크립트는 기본 노드에서 실행되며 로컬 웹 서버에 연결할 수 있도록 키와 URL이 스크립트에 반환됩니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
스크립트 매개변수
 a| 
스크립트에 전달할 JSON 매개 변수입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
속성
 a| 
대량 볼륨 작업에 대한 JSON 특성입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
asyncHandle
 a| 
완료 여부를 확인할 비동기 프로세스의 ID입니다.
 a| 
정수



 a| 
키
 a| 
불투명 키는 세션을 고유하게 식별합니다.
 a| 
문자열



 a| 
URL
 a| 
노드의 웹 서버에 액세스하는 URL입니다.
 a| 
문자열

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "StartBulkVolumeWrite",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
   },
   "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== 버전 이후 새로운 기능

9.6
