---
permalink: api/reference_element_api_testconnectsvip.html 
sidebar: sidebar 
keywords: storage,connection,svip,test,testing,testconnectsvip 
summary: TestConnectSvip 메서드를 사용하여 스토리지 클러스터에 대한 스토리지 접속을 테스트할 수 있습니다. 이 테스트에서는 ICMP 패킷을 사용하여 SVIP에 ping을 하고, 성공하면 iSCSI 초기자로 연결합니다. 
---
= 테스트 ConnectSvip
:icons: font
:imagesdir: ../media/


[role="lead"]
"TestConnectSvip" 메서드를 사용하여 스토리지 클러스터에 대한 스토리지 접속을 테스트할 수 있습니다. 이 테스트에서는 ICMP 패킷을 사용하여 SVIP에 ping을 하고, 성공하면 iSCSI 초기자로 연결합니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
비프
 a| 
이 값을 전달하여 다른 SVIP의 관리 연결을 테스트할 수 있습니다. 타겟 클러스터와의 연결을 테스트할 때 이 값을 사용할 필요는 없습니다.
 a| 
문자열
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
세부 정보
 a| 
테스트 작업에 대한 정보(JSON 개체):

* '연결됨': 테스트가 SVIP(부울)에 연결될 수 있는지 여부를 나타냅니다.
* S VIP: SVIP 테스트 대상(string)
* pingBytes: 56바이트 및 9000바이트(object)의 ping 테스트에 대한 세부 정보
+
** '56': 56바이트 ping 테스트 결과(JSON 개체):
+
*** 개별 응답 시간: 각 앙상블 노드의 응답 시간 목록(문자열 배열)
*** 개별 상태: 각 앙상블 노드의 핑 상태 목록(부울 배열)
*** 응답 시간: 평균 Ping 응답 시간(문자열)
*** '성공': Ping 테스트가 성공했는지 여부를 나타냅니다(부울).


** 9000바이트 핑 테스트 결과(JSON 개체):
+
*** 개별 응답 시간: 각 앙상블 노드의 응답 시간 목록(문자열 배열)
*** 개별 상태: 각 앙상블 노드의 핑 상태 목록(부울 배열)
*** 응답 시간: 평균 Ping 응답 시간(문자열)
*** '성공': Ping 테스트가 성공했는지 여부를 나타냅니다(부울).


** 채도: 테스트 실행에 필요한 시간(문자열)
** "결과": 전체 테스트 결과(문자열)



 a| 
문자열

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "TestConnectSvip",
   "params": {
      "svip" : "172.27.62.50"
      },
   "id" : 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "connected": true,
      "pingBytes": {
           "56": {
               "individualResponseTimes": [
                   "00:00:00.000152",
                   "00:00:00.000132",
                   "00:00:00.000119",
                   "00:00:00.000114",
                   "00:00:00.000112"
              ],
              "individualStatus": [
                  true,
                  true,
                  true,
                  true,
                  true
              ],
              "responseTime": "00:00:00.000126",
              "successful": true
           },
          "9000": {
                "individualResponseTimes": [
                    "00:00:00.000295",
                    "00:00:00.000257",
                    "00:00:00.000172",
                    "00:00:00.000172",
                    "00:00:00.000267"
              ],
              "individualStatus": [
                  true,
                  true,
                  true,
                  true,
                  true
             ],
             "responseTime": "00:00:00.000233",
             "successful": true
           }
        },
        "svip": "172.27.62.50"
      },
      "duration": "00:00:00.421907",
      "result": "Passed"
   }
}
----


== 버전 이후 새로운 기능

9.6
