---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: StartVolumePairing 메서드를 사용하여 다른 볼륨과 페어링하는 데 사용되는 볼륨에서 인코딩된 키를 생성할 수 있습니다. 이 메소드가 생성하는 키는 CompleteVolumePairing 메소드에서 볼륨 페어링을 설정하는 데 사용됩니다. 
---
= StartVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'스타볼륨 페어링' 방법을 사용하여 다른 볼륨과 페어링하는 데 사용되는 볼륨에서 인코딩된 키를 생성할 수 있습니다. 이 메소드가 생성하는 키는 볼륨 페어링을 설정하기 위해 'CompleteVolumePairing' 메소드에서 사용됩니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
모드를 선택합니다
 a| 
페어링 프로세스를 시작할 볼륨의 모드입니다. 이 모드는 볼륨이 소스 볼륨인 경우에만 설정할 수 있습니다. 가능한 값:

* 비동기식 쓰기가 로컬에서 완료될 때 인식됩니다. 클러스터는 타겟 클러스터에 쓰기가 복제되기를 기다리지 않습니다. (지정된 모드 매개 변수가 없는 경우 기본값)
* '동기화': Source는 데이터가 로컬과 원격 클러스터에 저장될 때 쓰기를 인식합니다.
* '스냅샷 전용': 소스 클러스터에서 생성된 스냅샷만 복제됩니다. 소스 볼륨의 활성 쓰기는 복제되지 않습니다.

 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
볼륨 ID
 a| 
페어링 프로세스를 시작할 볼륨의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
볼륨 키퍼링키
 a| 
에서 사용하는 문자의 문자열입니다 xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] API 메소드.
 a| 
문자열

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
