---
permalink: api/reference_element_api_initiator.html 
sidebar: sidebar 
keywords: object,objects,initiator 
summary: 이니시에이터 객체에는 iSCSI 또는 파이버 채널 이니시에이터에 대한 정보가 포함되어 있습니다. 이니시에이터 객체에는 IQN 또는 WWPN 식별자가 포함될 수 있습니다. ListInitiators 메서드를 사용하여 시스템에 알려진 모든 이니시에이터의 목록을 가져올 수 있습니다. 이니시에이터 객체를 사용하여 볼륨 액세스 그룹을 통해 볼륨 세트에 대한 SCSI 이니시에이터 액세스를 구성합니다. 이니시에이터는 한 번에 하나의 볼륨 액세스 그룹의 구성원만 될 수 있습니다. CreateInitiators 및 ModifyInitiators 메서드를 사용하여 하나 이상의 virtualNetworkID를 지정하여 하나 이상의 VLAN에 대한 초기자 액세스를 제한할 수 있습니다. 가상 네트워크를 지정하지 않으면 이니시에이터가 모든 네트워크에 액세스할 수 있습니다. 
---
= 이니시에이터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이니시에이터 객체에는 iSCSI 또는 파이버 채널 이니시에이터에 대한 정보가 포함되어 있습니다. 이니시에이터 객체에는 IQN 또는 WWPN 식별자가 포함될 수 있습니다. "ListInitiators" 방법을 사용하여 시스템에 알려진 모든 초기자의 목록을 가져올 수 있습니다. 이니시에이터 객체를 사용하여 볼륨 액세스 그룹을 통해 볼륨 세트에 대한 SCSI 이니시에이터 액세스를 구성합니다. 이니시에이터는 한 번에 하나의 볼륨 액세스 그룹의 구성원만 될 수 있습니다. "CreateInitiators" 및 "ModifyInitiators" 메서드를 사용하여 하나 이상의 virtualNetworkID를 지정하여 하나 이상의 VLAN에 대한 초기자 액세스를 제한할 수 있습니다. 가상 네트워크를 지정하지 않으면 이니시에이터가 모든 네트워크에 액세스할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
별칭
 a| 
이니시에이터에 할당된 알기 쉬운 이름입니다(있는 경우).
 a| 
문자열



 a| 
속성
 a| 
이 이니시에이터에 할당된 JSON 특성 세트입니다. 특성이 할당되지 않으면 비어 있습니다.
 a| 
JSON 개체



 a| 
챕터 사용자 이름
 a| 
이 이니시에이터의 고유한 CHAP 사용자 이름입니다.
 a| 
문자열



 a| 
initiatorID입니다
 a| 
이니시에이터의 숫자 식별자입니다.
 a| 
정수



 a| 
initiatorname입니다
 a| 
IQN 또는 WWPN 형식의 이니시에이터 이름입니다.
 a| 
문자열



 a| 
이니토시크입니다
 a| 
이니시에이터를 인증하는 데 사용되는 CHAP 암호입니다.
 a| 
문자열



 a| 
요구 사항
 a| 
이 이니시에이터에 CHAP가 필요한 경우 true입니다.
 a| 
부울



 a| 
targetSecret
 a| 
대상을 인증하는 데 사용되는 CHAP 암호입니다(상호 CHAP 인증을 사용하는 경우).
 a| 
문자열



 a| 
가상네트워크 ID
 a| 
이 이니시에이터와 연결된 가상 네트워크 식별자 목록입니다. 하나 이상의 가 정의된 경우 이 이니시에이터는 지정된 가상 네트워크에만 로그인할 수 있습니다. 가상 네트워크가 정의되지 않은 경우 이 이니시에이터는 모든 네트워크에 로그인할 수 있습니다.
 a| 
정수



 a| 
볼륨 액세스 그룹
 a| 
이 이니시에이터가 속한 볼륨 액세스 그룹 ID 목록입니다.
 a| 
정수 배열

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_listinitiators.adoc[ListInitiators(목록 초기자]
