---
permalink: api/reference_element_api_cluster_pairing_order_of_operations.html 
sidebar: sidebar 
keywords: cluster,pairing,pair,order,operations,clusters 
summary: 원격 복제를 사용하려면 먼저 Element 소프트웨어를 실행하는 스토리지 클러스터 쌍 간에 접속을 설정해야 합니다. 
---
= 클러스터 페어링 작업 순서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 복제를 사용하려면 먼저 Element 소프트웨어를 실행하는 스토리지 클러스터 쌍 간에 접속을 설정해야 합니다.

다음 API 메소드 세트를 사용하여 클러스터 연결을 설정하십시오.

* xref:reference_element_api_startclusterpairing.adoc[StartClusterPairing을 선택합니다]:
+
이 API 메소드는 클러스터 쌍 생성에 사용되는 페어링 키를 생성하고 반환합니다. 이 키는 암호화되어 클러스터 간의 통신을 설정하는 데 사용되는 정보가 포함되어 있습니다. 단일 클러스터를 최대 4개의 다른 클러스터와 페어링할 수 있습니다. 그러나 각 클러스터 페어링에 대해 새 키를 생성해야 합니다. 를 클릭합니다 xref:reference_element_api_startclusterpairing.adoc[StartClusterPairing을 선택합니다] 메서드는 메서드가 호출될 때마다 새 키를 생성합니다. 에 각 고유 키를 사용합니다 xref:reference_element_api_completeclusterpairing.adoc[CompleteClusterPairing] 각 추가 클러스터를 페어링하는 방법입니다.

+

NOTE: 보안상의 이유로 전자 메일을 통해 다른 사용자에게 페어링 키를 보내면 안 됩니다. 키에 사용자 이름과 암호가 들어 있습니다.

* xref:reference_element_api_completeclusterpairing.adoc[CompleteClusterPairing]:
+
이 방법은 로 만든 페어링 키를 사용합니다 xref:reference_element_api_startclusterpairing.adoc[StartClusterPairing을 선택합니다] API를 사용하여 클러스터 페어를 생성합니다. 를 발행합니다 xref:reference_element_api_completeclusterpairing.adoc[CompleteClusterPairing] 대상에 대한 clusterPairingKey 매개 변수를 사용한 API 메소드 원본 클러스터는 키를 생성한 클러스터입니다.





== 자세한 내용을 확인하십시오

* xref:reference_element_api_startclusterpairing.adoc[StartClusterPairing을 선택합니다]
* xref:reference_element_api_completeclusterpairing.adoc[CompleteClusterPairing]

