---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: ListVolumes 메서드를 사용하여 클러스터에 있는 볼륨 목록을 가져올 수 있습니다. 사용 가능한 매개 변수를 사용하여 목록에서 반환할 볼륨을 지정할 수 있습니다. 
---
= 목록 볼륨
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"ListVolumes" 방법을 사용하여 클러스터에 있는 볼륨 목록을 가져올 수 있습니다. 사용 가능한 매개 변수를 사용하여 목록에서 반환할 볼륨을 지정할 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
계정
 a| 
여기에서 지정한 계정이 소유한 볼륨만 반환됩니다. volumeIDs 매개변수와 함께 사용할 수 없습니다.
 a| 
정수 배열
 a| 
없음
 a| 
아니요



 a| 
여기에는 VirtualVolumes가 포함됩니다
 a| 
가상 볼륨은 기본적으로 응답에 포함됩니다. 가상 볼륨을 제외하려면 FALSE로 설정합니다.
 a| 
부울
 a| 
참
 a| 
아니요



 a| 
isPdis방송입니다
 a| 
페어링되었거나 페어링되지 않은 볼륨을 반환합니다. 가능한 값:

* True: 페어링된 모든 볼륨을 반환합니다.
* False: 페어링되지 않은 모든 볼륨을 반환합니다.

 a| 
부울
 a| 
없음
 a| 
아니요



 a| 
제한
 a| 
반환되는 최대 볼륨 결과 수를 설정할 수 있습니다. volumeIDs 매개변수와 함께 사용할 수 없습니다.
 a| 
정수
 a| 
10000입니다
 a| 
아니요



 a| 
시작 볼륨 ID입니다
 a| 
ID가 이 값보다 크거나 같은 볼륨만 반환됩니다. volumeIDs 매개변수와 함께 사용할 수 없습니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
볼륨 ID
 a| 
볼륨 ID 목록입니다. 이 매개 변수를 지정하면 다른 매개 변수가 이 볼륨 집합에서만 작동합니다. 계정, startVolumeID 및 제한 매개변수와 함께 사용할 수 없습니다.
 a| 
정수 배열
 a| 
아니요
 a| 
아니요



 a| 
볼륨 이름
 a| 
볼륨 이름과 일치하는 볼륨 개체 정보만 반환됩니다.
 a| 
문자열
 a| 
아니요
 a| 
아니요



 a| 
볼륨 상태
 a| 
상태 값과 같은 상태의 볼륨만 반환됩니다. 가능한 값:

* 생성 중
* 스냅샷 생성
* 활성
* 삭제됨

 a| 
문자열
 a| 
아니요
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
볼륨
 a| 
볼륨 목록입니다.
 a| 
xref:reference_element_api_volume.adoc[볼륨] 스토리지

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== 버전 이후 새로운 기능

9.6
