---
permalink: api/reference_element_api_disableencryptionatrest.html 
sidebar: sidebar 
keywords: element, api, encryption, disable, disabling, at rest, rest, DisableEncryptionAtRest 
summary: DisableEncryptionAtRest 메서드를 사용하면 EnableEncryptionAtRest 메서드를 사용하여 이전에 클러스터에 적용된 암호화를 제거할 수 있습니다. 이 비활성화 방법은 비동기식이며 암호화를 비활성화하기 전에 응답을 반환합니다. GetClusterInfo 메서드를 사용하여 프로세스가 완료된 시점을 확인하기 위해 시스템을 폴링할 수 있습니다. 
---
= DisableEncryptionAtRest
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"EnableEncryptionAtRest" 메서드를 사용하여 이전에 클러스터에 적용된 암호화를 제거할 수 있습니다. 이 비활성화 방법은 비동기식이며 암호화를 비활성화하기 전에 응답을 반환합니다. GetClusterInfo 메서드를 사용하면 프로세스가 완료된 시점을 확인하기 위해 시스템을 폴링할 수 있습니다.


TIP: 유휴 상태의 암호화 및/또는 클러스터의 유휴 상태의 소프트웨어 암호화를 확인하려면 를 사용합니다 link:../api/reference_element_api_getclusterinfo.html["클러스터 정보 확인 방법을 참조하십시오"^]. 를 사용할 수 있습니다 `GetSoftwareEncryptionAtRestInfo` link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["클러스터에서 유휴 데이터를 암호화하는 데 사용하는 정보를 가져오는 방법입니다"^].


NOTE: 이 방법을 사용하여 유휴 소프트웨어 암호화를 해제할 수 없습니다. 저장 시 소프트웨어 암호화를 비활성화하려면 다음을 수행해야 합니다 link:reference_element_api_createcluster.html["새 클러스터를 생성합니다"] 소프트웨어 암호화 사용 안 함.



== 매개 변수

이 메서드에는 입력 매개 변수가 없습니다.



== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "DisableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id" : 1,
  "result" : {}
}
----


== 버전 이후 새로운 기능

9.6

[discrete]
== 자세한 내용을 확인하십시오

* link:api/reference_element_api_getclusterinfo.html["GetClusterInfo 를 참조하십시오"]
* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 리소스 페이지 를 참조하십시오"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

