---
permalink: api/reference_element_api_groupsnapshot.html 
sidebar: sidebar 
keywords: object,objects,groupSnapshot 
summary: groupSnapshot 개체에는 볼륨 그룹에 대한 스냅샷에 대한 정보가 포함되어 있습니다. ListGroupSnapshots API 메서드를 사용하여 그룹 스냅샷 정보를 검색할 수 있습니다. 
---
= 그룹 스냅샷
:icons: font
:imagesdir: ../media/


[role="lead"]
groupSnapshot 개체에는 볼륨 그룹에 대한 스냅샷에 대한 정보가 포함되어 있습니다. "ListGroupSnapshots" API 메소드를 사용하여 그룹 스냅샷 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체



 a| 
createTime(createTime)
 a| 
그룹 스냅샷이 생성된 UTC+0 형식의 날짜 및 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
enableRemoteReplication
 a| 
스냅샷이 원격 복제에 대해 설정되었는지 여부를 나타냅니다.
 a| 
부울



 a| 
groupSnapshotID입니다
 a| 
그룹 스냅샷의 고유 ID입니다.
 a| 
정수



 a| 
groupSnapshotUUID입니다
 a| 
그룹 스냅샷의 UUID입니다.
 a| 
문자열



 a| 
구성원
 a| 
그룹 스냅샷의 각 구성원에 대한 정보를 포함하는 객체 배열입니다.
 a| 
xref:reference_element_api_snapshot.adoc[스냅샷] 스토리지



 a| 
이름
 a| 
그룹 스냅샷의 이름 또는 지정된 항목이 없으면 스냅샷이 생성된 UTC 형식의 날짜 및 시간입니다.
 a| 
문자열 또는 ISO 8601 날짜 문자열



 a| 
원격 상태
 a| 
소스 클러스터에서 볼 수 있는 것처럼 타겟 클러스터에 있는 각 원격 스냅샷의 범용 식별자 및 복제 상태를 포함하는 스토리지
 a| 
xref:reference_element_api_remoteclustersnapshotstatus.adoc[원격 클러스터 스냅샷상태] 스토리지



 a| 
상태
 a| 
스냅샷의 현재 상태입니다. 가능한 값:

* 알 수 없음: 스냅샷 상태를 가져오는 동안 오류가 발생했습니다.
* 준비: 이 스냅샷은 사용 준비가 되어 있으며 아직 쓸 수 없습니다.
* RemoteSyncing(원격 Syncing): 이 스냅샷이 원격 클러스터에서 복제되고 있습니다.
* 완료: 이 스냅샷은 준비 또는 복제를 완료했으며 이제 사용할 수 있습니다.
* Active(활성): 이 스냅샷은 활성 분기입니다.
* 클론 생성: 이 스냅샷은 CopyVolume 작업과 관련되어 있습니다.

 a| 
문자열

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_listgroupsnapshots.adoc[ListGroupSnapshots을 선택합니다]
