---
permalink: api/reference_element_api_removeinitiatorsfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: initiators,initiator,volume,access,group,remove,removing,removeinitiatorsfromvolumeaccessgroup 
summary: RemoveInitialatorsFromVolumeAccessGroup 메서드를 사용하여 지정된 볼륨 액세스 그룹에서 이니시에이터를 제거할 수 있습니다. 
---
= RemoveInitialatorsFromVolumeAccessGroup 을 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"RemoveInitialatorsFromVolumeAccessGroup" 메서드를 사용하여 지정된 볼륨 액세스 그룹에서 이니시에이터를 제거할 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
볼륨 액세스 그룹 ID입니다
 a| 
이니시에이터가 제거된 볼륨 액세스 그룹의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
이니시에이터
 a| 
볼륨 액세스 그룹에 포함할 이니시에이터 ID 또는 이름(IQN 및 WWPN) 목록입니다. 이니시에이터 이름 목록을 전달하는 경우 이니시에이터가 없으면 이니시에이터가 생성됩니다. 이니시에이터 ID 목록을 전달하는 경우 초기자가 없으면 오류가 반환됩니다. 이니시에이터 이름 전달은 더 이상 사용되지 않으므로 가능하면 이니시에이터 ID를 사용해야 합니다.
 a| 
정수 배열(권장) 또는 문자열 배열(사용되지 않음)
 a| 
없음
 a| 
아니요



 a| 
보육원 이니시에이터
 a| 
이니시에이터 객체를 볼륨 액세스 그룹에서 제거한 후 삭제할 것인지 여부를 지정합니다. 가능한 값:

* 참: 이니시에이터 객체가 볼륨 액세스 그룹에서 제거된 후 삭제합니다.
* False: 이니시에이터 객체가 볼륨 액세스 그룹에서 제거된 후에는 삭제하지 마십시오. 이것이 기본값입니다.

 a| 
부울
 a| 
거짓
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
볼륨 액세스 그룹
 a| 
새로 수정된 볼륨 액세스 그룹에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[볼륨 액세스 그룹]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "id": 13171,
  "method": "RemoveInitiatorsFromVolumeAccessGroup",
  "params": {
    "initiators": [114,115],
    "volumeAccessGroupID": 96
  }
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 13171,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [],
      "initiators": [],
      "name": "test",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== 버전 이후 새로운 기능

9.6
