---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: ModifyVirtualNetwork 메서드를 사용하여 기존 가상 네트워크의 특성을 변경할 수 있습니다. 
---
= ModifyVirtualNetwork의 약어입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ModifyVirtualNetwork 메서드를 사용하여 기존 가상 네트워크의 특성을 변경할 수 있습니다.

이 방법을 사용하면 주소 블록을 추가하거나 제거하거나, 넷마스크를 변경하거나, 가상 네트워크의 이름 또는 설명을 수정할 수 있습니다. 또한 네임스페이스를 사용하거나 사용하지 않도록 설정할 수 있으며, 가상 네트워크에 네임스페이스가 설정되어 있는 경우 게이트웨이를 추가하거나 제거할 수도 있습니다.


NOTE: 이 메서드를 사용하려면 virtualNetworkID 또는 virtualNetworkTag가 매개 변수로 필요하지만 둘 다 필요하지 않습니다.

주의:

네임스페이스 매개 변수를 변경하여 기존 가상 네트워크에 라우팅 가능한 스토리지 VLAN 기능을 설정하거나 해제하면 가상 네트워크에서 처리되는 트래픽이 모두 중단됩니다. 예약된 유지 관리 창에서 네임스페이스 매개 변수를 변경하는 것이 가장 좋습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
가상네트워크 ID
 a| 
수정할 가상 네트워크의 고유 식별자입니다. 이것은 클러스터에서 할당한 가상 네트워크 ID입니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
가상네트워크 태그
 a| 
수정할 가상 네트워크를 식별하는 네트워크 태그입니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
주소 블록
 a| 
이 가상 네트워크에 설정할 새 주소 블록입니다. 여기에는 기존 개체에 추가할 새 주소 블록이나 제거해야 하는 사용하지 않는 주소 블록을 생략할 수 있습니다. 또는 기존 주소 블록의 크기를 늘리거나 줄일 수 있습니다. 가상 네트워크 개체의 시작 주소 블록 크기만 늘릴 수 있으며 줄일 수는 없습니다. 이 개체에 필요한 멤버:

* 시작: IP 주소 범위의 시작. (문자열)
* 크기: 블록에 포함할 IP 주소의 수입니다. (정수)

 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
게이트웨이
 a| 
가상 네트워크 게이트웨이의 IP 주소입니다. 이 매개 변수는 namespace 매개 변수가 true 로 설정된 경우에만 유효합니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
이름
 a| 
가상 네트워크의 새 이름입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
네임스페이스
 a| 
true로 설정하면 가상 네트워크를 다시 생성하고 네임스페이스를 구성하여 라우팅할 수 있는 스토리지 VLAN 기능을 활성화합니다. false로 설정하면 가상 네트워크에 대한 VRF 기능이 비활성화됩니다. 이러한 가치를 변경하면 이 가상 네트워크를 통해 실행되는 트래픽이 중단됩니다.
 a| 
부울
 a| 
없음
 a| 
아니요



 a| 
넷마스크
 a| 
이 가상 네트워크에 대한 새 네트워크 마스크입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
비프
 a| 
이 가상 네트워크의 스토리지 가상 IP 주소입니다. 가상 네트워크의 SVIP는 변경할 수 없습니다. 다른 SVIP 주소를 사용하려면 새 가상 네트워크를 만들어야 합니다.
 a| 
문자열
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== 버전 이후 새로운 기능

9.6
