---
permalink: api/reference_element_api_listsnapmirrorrelationships.html 
sidebar: sidebar 
keywords: snapmirror,endpoints,endpoint,list,listing,listsnapmirrorrelationships 
summary: Element 소프트웨어 웹 UI에서는 ListSnapMirrorRelationships 메서드를 사용하여 Element 스토리지 클러스터의 SnapMirror 관계를 하나 또는 모두 나열합니다. 
---
= ListSnapMirror 관계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element 소프트웨어 웹 UI에서는 'ListSnapMirrorRelationships' 메서드를 사용하여 Element 스토리지 클러스터의 SnapMirror 관계를 하나 이상 나열합니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
snapMirrorEndpointID입니다
 a| 
지정된 끝점 ID와 연결된 관계만 나열합니다. 제공된 끝점 ID가 없으면 알려진 모든 SnapMirror 끝점의 관계가 표시됩니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
디스테이징 볼륨
 a| 
지정된 대상 볼륨과 연결된 관계를 나열합니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
없음
 a| 
아니요



 a| 
소스 볼륨
 a| 
지정된 소스 볼륨과 연결된 관계를 나열합니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
없음
 a| 
아니요



 a| 
SVM
 a| 
지정된 SVM의 관계를 표시합니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
관계 ID
 a| 
지정된 관계 ID와 연결된 관계를 나열합니다.
 a| 
문자열
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
snapMirrorRelationships
 a| 
SnapMirror 관계에 대한 정보가 포함된 개체 목록입니다.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship] 스토리지

|===


== 버전 이후 새로운 기능

10.1
