---
permalink: api/reference_element_api_modifyschedule.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapshot,schedule,scheduled,delete,pause,modifyschedule 
summary: ModifySchedule 을 사용하여 예약된 스냅샷이 발생하는 간격을 변경할 수 있습니다. 이 방법을 사용하여 일정을 삭제하거나 일시 중지할 수도 있습니다. 
---
= ModifySchedule 을 선택합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ModifySchedule을 사용하여 예약된 스냅샷이 발생하는 간격을 변경할 수 있습니다. 이 방법을 사용하여 일정을 삭제하거나 일시 중지할 수도 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
속성
 a| 
스냅샷 발생 빈도를 변경하는 데 사용합니다. 가능한 값:

* 금주의 날
* 달의 일
* 시간 간격

 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
시간
 a| 
스냅샷이 주별 또는 월 일 모드에서 발생하는 시간 또는 스냅샷 사이의 시간. 유효한 값은 0 ~ 24입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
이름
 a| 
스냅샷의 이름입니다. 이름을 입력하지 않으면 그룹 스냅샷이 생성된 날짜 및 시간이 사용됩니다. 허용되는 최대 이름 길이는 244자입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
분
 a| 
스냅샷이 주별 또는 월 일 모드에서 발생하는 시간(분)이나 스냅샷 사이의 시간(분)입니다. 유효한 값은 0에서 59 사이입니다.
 a| 
정수
 a| 
없음
 a| 
아니요



| 마지막 실행 상태 | 마지막으로 예약된 스냅샷 생성 결과 또는 상태입니다. | 문자열 | 없음 | 아니요 


 a| 
일시 중지되었습니다
 a| 
스케줄이 일시 중지되어야 하는지 여부를 나타냅니다. 유효한 값:

* "참"입니다
* 거짓입니다

 a| 
부울
 a| 
없음
 a| 
아니요



 a| 
반복
 a| 
일정이 반복되는지 여부를 나타냅니다. 유효한 값은 다음과 같습니다.

* "참"입니다
* 거짓입니다

 a| 
부울
 a| 
없음
 a| 
아니요



 a| 
RunNextInterval 을 선택합니다
 a| 
다음에 스케줄러가 활성화될 때 스냅샷을 실행할지 여부를 선택하는 데 사용합니다. 유효한 값:

* "참"입니다
* 거짓입니다


true로 설정하면 다음에 스케줄러가 활성화될 때 예약된 스냅샷이 실행된 다음 다시 false로 재설정됩니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
예약 ID입니다
 a| 
스케줄의 고유 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
예약 이름
 a| 
스케줄의 고유 이름입니다. 허용되는 최대 스케줄 이름 길이는 244자입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
일정 유형
 a| 
생성할 스케줄의 유형을 나타냅니다. 유일하게 지원되는 값은 '스냅샷'입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
'ScheduleInfo'입니다
 a| 
스케줄에 지정된 고유 이름, 생성된 스냅샷의 보존 기간 및 스냅샷이 생성된 볼륨의 볼륨 ID입니다. 유효한 값:

* 'volumeID': 스냅샷에 포함될 볼륨의 ID입니다. (정수)
* '볼륨': 그룹 스냅샷에 포함될 볼륨 ID 목록입니다. (정수 배열)
* 이름: 사용할 스냅샷 이름입니다. (문자열)
* enableRemoteReplication: 스냅샷이 원격 복제에 포함되어야 하는지 여부를 나타냅니다. (부울)
* 다시 보존: 스냅샷이 보존되는 시간(HH:MM:ss)입니다. 비어 있으면 스냅샷이 영구적으로 유지됩니다. (문자열)
* fifo: 선입선출(FIFO) 방식으로 스냅샷이 보존됩니다. (문자열)
* ensuSerialCreation: 이전 스냅샷 복제가 진행 중인 경우 새 스냅샷 생성이 허용되는지 여부를 지정합니다. (부울)

 a| 
link:reference_element_api_schedule.html["스케줄"^]
 a| 
없음
 a| 
아니요



 a| 
snapMirrorLabel
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트에 대한 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
삭제
 a| 
스케줄이 삭제되도록 표시되었는지 여부를 나타냅니다. 유효한 값:

* "참"입니다
* 거짓입니다

 a| 
부울
 a| 
없음
 a| 
아니요



 a| 
시작 날짜
 a| 
일정이 처음 시작되거나 시작될 날짜를 나타냅니다.
 a| 
ISO 8601 날짜 문자열
 a| 
없음
 a| 
아니요



 a| 
몬트데이즈입니다
 a| 
스냅샷이 생성되는 월의 일. 유효한 값은 1부터 31까지입니다.
 a| 
정수 배열
 a| 
없음
 a| 
예



 a| 
평일
 a| 
스냅샷이 생성되는 요일. 요일은 일요일부터 0의 값과 1의 오프셋으로 시작됩니다.
 a| 
문자열
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
스케줄
 a| 
수정된 일정 특성이 포함된 개체입니다.
 a| 
xref:reference_element_api_schedule.adoc[스케줄]

|===


== 요청 예

[listing]
----
{
  "method": "ModifySchedule",
  "params": {
    "scheduleName" : "Chicago",
    "scheduleID" : 3
    },
  "id": 1
}
----


== 응답 예

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Week"
            },
      "hasError": false,
      "hours": 5,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 0,
      "monthdays": [],
      "paused": false,
      "recurring": true,
      "runNextInterval": false,
      "scheduleID": 3,
      "scheduleInfo": {
        "volumeID": "2"
            },
      "scheduleName": "Chicago",
      "scheduleType": "Snapshot",
      "startingDate": null,
      "toBeDeleted": false,
      "weekdays": [
        {
          "day": 2,
          "offset": 1
      }
      ]
    }
  }
}
----


== 버전 이후 새로운 기능

9.6
