---
permalink: api/reference_element_api_listasyncresults.html 
sidebar: sidebar 
keywords: async,asynchronous,result,results,get,list,listing,listasyncresults 
summary: ListAsyncResults 를 사용하여 시스템에서 현재 실행 중이거나 완료된 모든 비동기 메서드의 결과를 나열할 수 있습니다. ListAsyncResults 를 사용하여 비동기 결과를 쿼리하면 완료된 asyncHandles 가 만료되지 않습니다. GetAsyncResult 를 사용하여 ListAsyncResults 에서 반환된 asyncHandles 중 하나를 쿼리할 수 있습니다. 
---
= ListAsyncResults 를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"ListAsyncResults"를 사용하면 시스템에서 현재 실행 중이거나 완료된 모든 비동기 메서드의 결과를 나열할 수 있습니다. ListAsyncResults로 비동기 결과를 쿼리하면 완성된 asyncHandles가 만료되지 않습니다. GetAsyncResult를 사용하여 ListAsyncResults에서 반환된 asyncHandles 중 하나를 쿼리할 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
asyncResultTypes를 참조하십시오
 a| 
결과 유형의 선택적 목록입니다. 이 목록을 사용하여 결과를 이러한 유형의 작업으로만 제한할 수 있습니다. 가능한 값:

* DriveAdd: 클러스터에 드라이브를 추가하는 시스템과 관련된 작업.
* BulkVolume: 백업 또는 복구와 같은 볼륨 간 복제 작업
* 클론:볼륨 클론 생성 작업
* DriveRemoval: 클러스터에서 데이터를 제거하기 위해 시스템에서 드라이브에서 데이터를 복사하는 작업.
* RtfiPendingNode: 클러스터에 추가하기 전에 시스템에 호환되는 소프트웨어를 설치하는 작업이 필요합니다.

 a| 
문자열 배열
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
인두 핸들
 a| 
serialize된 비동기 메서드 결과의 배열입니다.
 a| 
JSON 개체 어레이

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "ListAsyncResults",
   "params": {
   },
   "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result": {
     "asyncHandles": [
       {
         "asyncResultID": 47,
         "completed": true,
         "createTime": "2016-01-01T22:29:19Z",
         "data": {
           "cloneID": 26,
           "message": "Clone complete.",
           "volumeID": 48
         },
         "lastUpdateTime": "2016-01-01T22:45:43Z",
         "resultType": "Clone",
         "success": true
      },
      ...]
   }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

xref:reference_element_api_getasyncresult.adoc[GetAsyncResult 를 참조하십시오]
