---
permalink: api/reference_element_api_modifyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,access,group,modify,modifying,updating,changing,change,update,edit,editing,modifyvolumeaccessgroup 
summary: ModifyVolumeAccessGroup 메서드를 사용하여 초기자를 업데이트하고 볼륨 액세스 그룹에서 볼륨을 추가 또는 제거할 수 있습니다. 
---
= ModifyVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ModifyVolumeAccessGroup의 방법을 사용하여 초기자를 업데이트하고 볼륨 액세스 그룹에서 볼륨을 추가 또는 제거할 수 있습니다.

지정된 이니시에이터 또는 볼륨이 현재 존재하는 이니시에이터 또는 볼륨과 중복될 경우 볼륨 액세스 그룹은 있는 그대로 유지됩니다. 볼륨 또는 이니시에이터에 대한 값을 지정하지 않으면 현재 이니시에이터 및 볼륨 목록이 변경되지 않습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
볼륨 액세스 그룹 ID입니다
 a| 
수정할 볼륨 액세스 그룹의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
이름
 a| 
이 볼륨 액세스 그룹의 새 이름입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
이니시에이터
 a| 
볼륨 액세스 그룹에 포함할 이니시에이터 ID 또는 이름(IQN 및 WWPN) 목록입니다. 이니시에이터 이름 목록을 전달하는 경우 이니시에이터가 없으면 이니시에이터가 생성됩니다. 이니시에이터 ID 목록을 전달하는 경우 초기자가 없으면 오류가 반환됩니다. 이니시에이터 이름 전달은 더 이상 사용되지 않으므로 가능하면 이니시에이터 ID를 사용해야 합니다.
 a| 
정수 배열(권장) 또는 문자열 배열(사용되지 않음)
 a| 
없음
 a| 
아니요



 a| 
보육원 이니시에이터
 a| 
이니시에이터 객체를 볼륨 액세스 그룹에서 제거한 후 삭제할 것인지 여부를 지정합니다. 가능한 값:

* 참: 이니시에이터 객체가 볼륨 액세스 그룹에서 제거된 후 삭제합니다.
* False: 이니시에이터 객체가 볼륨 액세스 그룹에서 제거된 후에는 삭제하지 마십시오. 이것이 기본값입니다.

 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
볼륨
 a| 
수정할 볼륨의 볼륨 ID 목록입니다.
 a| 
정수 배열
 a| 
없음
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[볼륨 액세스 그룹]

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
볼륨 액세스 그룹
 a| 
새로 수정된 볼륨 액세스 그룹에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[볼륨 액세스 그룹]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "ModifyVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "name": "accessgrouptest",
      "initiators": [115,114],
      "volumes": [
         346
    ],
      "attributes": {}
   }
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": null,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [
        114,
        115
      ],
      "initiators": [
        "iqn.1998-01.com.vmware:desk1-esx1-577b283a",
        "iqn.1998-01.com.vmware:donesq-esx1-421b281b"
      ],
      "name": "accessgrouptest",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

* xref:reference_element_api_addinitiatorstovolumeaccessgroup.adoc[AddInitialatorsToVolumeAccessGroup 을 참조하십시오]
* xref:reference_element_api_addvolumestovolumeaccessgroup.adoc[AddVolumesToVolumeAccessGroup]
* xref:reference_element_api_removeinitiatorsfromvolumeaccessgroup.adoc[RemoveInitialatorsFromVolumeAccessGroup 을 참조하십시오]
* xref:reference_element_api_removevolumesfromvolumeaccessgroup.adoc[RemoveVolumesFromVolumeAccessGroup]

