---
permalink: api/reference_element_api_ldapconfiguration.html 
sidebar: sidebar 
keywords: object,objects,ldapConfiguration 
summary: ldapConfiguration 개체에는 스토리지 시스템의 LDAP 구성에 대한 정보가 포함되어 있습니다. GetLdapConfiguration API 메서드를 사용하여 LDAP 정보를 검색할 수 있습니다. 
---
= ldapConfiguration 을 선택합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ldapConfiguration 개체에는 스토리지 시스템의 LDAP 구성에 대한 정보가 포함되어 있습니다. GetLdapConfiguration API 메서드를 사용하여 LDAP 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
AuthType
 a| 
사용할 사용자 인증 방법을 식별합니다. 가능한 값:

* DirectBind
* 검색 안바인드

 a| 
문자열



 a| 
활성화됨
 a| 
시스템이 LDAP에 대해 구성되었는지 여부를 식별합니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
groupSearchBaseDN
 a| 
그룹 검색을 시작할 트리의 기본 DN(시스템에서 여기에서 하위 트리 검색을 수행합니다).
 a| 
문자열



 a| 
groupSearchCustomFilter를 선택합니다
 a| 
사용된 사용자 정의 검색 필터.
 a| 
문자열



 a| 
그룹 검색 유형
 a| 
사용되는 기본 그룹 검색 필터를 제어합니다. 가능한 값:

* NoGroups(참고 그룹): 그룹 지원이 없습니다.
* ActiveDirectory: 사용자의 모든 AD 그룹의 중첩된 구성원
* MemberDN: MemberDN 스타일 그룹(단일 수준).

 a| 
문자열



 a| 
searchBindDN
 a| 
사용자에 대한 LDAP 검색을 수행하기 위해 로그인할 정규화된 DN입니다(LDAP 디렉토리에 대한 읽기 액세스 필요).
 a| 
문자열



 a| 
서버 URI입니다
 a| 
LDAP 서버 URI의 쉼표로 구분된 목록(예: LDAP://1.2.3.4 및 LDAPS://1.2.3.4:123)
 a| 
문자열



 a| 
사용자 NTemplate
 a| 
정규화된 사용자 DN을 구성하는 데 사용되는 문자열입니다.
 a| 
문자열



 a| 
userSearchBaseDN입니다
 a| 
검색을 시작하는 데 사용되는 트리의 기본 DN(여기에서 하위 트리 검색 수행)입니다.
 a| 
문자열



 a| 
userSearchFilter 를 선택합니다
 a| 
사용된 LDAP 필터입니다.
 a| 
문자열

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_getldapconfiguration.adoc[GetLdapConfiguration 을 참조하십시오]
