---
permalink: api/reference_element_api_addvirtualnetwork.html 
sidebar: sidebar 
keywords: addvirtualnetwork,cluster,add,adding,virtual,network 
summary: AddVirtualNetwork 메서드를 사용하여 새 가상 네트워크를 클러스터 구성에 추가할 수 있습니다. 
---
= AddVirtualNetwork 를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AddVirtualNetwork 메서드를 사용하여 새 가상 네트워크를 클러스터 구성에 추가할 수 있습니다.

가상 네트워크를 추가하면 각 노드에 대한 인터페이스가 생성되고 각 인터페이스에 가상 네트워크 IP 주소가 필요합니다. 이 API 메소드에 대해 매개 변수로 지정한 IP 주소의 수는 클러스터의 노드 수보다 크거나 같아야 합니다. 시스템은 가상 네트워크 주소를 대량 프로비저닝하고 개별 노드에 자동으로 할당합니다. 가상 네트워크 주소를 노드에 수동으로 할당할 필요는 없습니다.


NOTE: AddVirtualNetwork 메서드는 새 가상 네트워크를 만드는 데만 사용됩니다. 기존 가상 네트워크를 변경하려면 를 사용합니다 xref:reference_element_api_modifyvirtualnetwork.adoc[ModifyVirtualNetwork의 약어입니다] 방법.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
주소 블록
 a| 
가상 네트워크에 포함할 고유한 IP 주소 범위 개체에 필요한 멤버:

* 시작: IP 주소 범위의 시작. (문자열)
* 크기: 블록에 포함할 IP 주소의 수입니다. (정수)

 a| 
JSON 개체 어레이
 a| 
없음
 a| 
예



 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
게이트웨이
 a| 
가상 네트워크 게이트웨이의 IP 주소입니다. 이 매개 변수는 namespace 매개 변수가 true 로 설정된 경우에만 유효합니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
이름
 a| 
새 가상 네트워크에 대한 사용자 정의 이름입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
네임스페이스
 a| 
TRUE로 설정하면 네임스페이스와 여기에 포함된 가상 네트워크를 생성하고 구성하여 라우팅할 수 있는 스토리지 VLAN 기능을 활성화합니다.
 a| 
부울
 a| 
없음
 a| 
아니요



 a| 
넷마스크
 a| 
생성 중인 가상 네트워크에 대한 고유한 네트워크 마스크입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
비프
 a| 
생성 중인 가상 네트워크의 고유한 스토리지 IP 주소입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
가상네트워크 태그
 a| 
고유한 VLAN(가상 네트워크) 태그 지원되는 값은 1 - 4094입니다.
 a| 
정수
 a| 
없음
 a| 
예

|===
* 참고: * 가상 네트워크 매개변수는 네임스페이스를 false로 설정할 때 각 가상 네트워크마다 고유해야 합니다.



== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
가상네트워크 ID
 a| 
새 가상 네트워크의 가상 네트워크 ID입니다.
 a| 
정수

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "method": "AddVirtualNetwork",
  "params": {
    "virtualNetworkTag": 2010,
    "name": "network1",
    "addressBlocks" : [
        { "start": "192.86.5.1", "size": 10 },
        { "start": "192.86.5.50", "size": 20 }
    ],
    "netmask" : "255.255.192.0",
    "gateway" : "10.0.1.254",
    "svip" : "192.86.5.200",
    "attributes" : {}
    "namespace" : true
  },
"id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result":
      {
        "virtualNetworkID": 5
   }
}
----


== 버전 이후 새로운 기능

9.6
