---
permalink: api/reference_element_api_setsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,info,setting,set,setsnmpinfo 
summary: SetSnmpInfo 메서드를 사용하여 클러스터 노드에서 SNMP 버전 2 및 버전 3을 구성할 수 있습니다. 이 인터페이스를 사용하여 설정한 값은 클러스터의 모든 노드에 적용되며 전달된 값은 SetSnmpInfo 를 이전에 호출할 때 설정된 모든 값을 대체합니다. 
---
= SetSnmpInfo 를 선택합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
'snmpInfo' 방법을 사용하여 클러스터 노드에서 SNMP 버전 2 및 버전 3을 구성할 수 있습니다. 이 인터페이스로 설정한 값은 클러스터의 모든 노드에 적용되며 전달된 값은 이전 호출에서 설정한 'DetSnmpInfo'를 모두 대체합니다.



== 매개 변수


NOTE: SetSnmpInfo 는 Element 버전 6.0 이상에서 더 이상 사용되지 않습니다. 를 사용합니다 xref:reference_element_api_enablesnmp.adoc[EnableSnmp] 및 xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] 대신 메서드를 사용합니다.

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
네트워크
 a| 
클러스터 노드에서 실행 중인 SNMP 서버에 대한 네트워크 및 액세스 유형 목록입니다. SNMP를 참조하십시오 xref:reference_element_api_network_snmp.adoc[네트워크] 가능한 값을 나타내는 개체입니다. 이 매개 변수는 SNMP v2에만 필요합니다.
 a| 
xref:reference_element_api_network_snmp.adoc[네트워크] 스토리지
 a| 
없음
 a| 
아니요



 a| 
활성화됨
 a| 
true로 설정하면 클러스터의 각 노드에서 SNMP가 설정됩니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
snmpV3이 활성화되었습니다
 a| 
TRUE로 설정하면 클러스터의 각 노드에서 SNMP v3이 활성화됩니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
usmUsers(사용자)
 a| 
SNMP v3이 활성화된 경우 이 값은 networks 매개 변수 대신 전달되어야 합니다. 이 매개변수는 SNMP v3에만 필요합니다.
 a| 
xref:reference_element_api_usmuser.adoc[usmUser(사용자)]
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== SNMP v3이 활성화된 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":true,
    "usmUsers":[
      {
        "name":"user1",
        "access":"rouser",
        "secLevel":"auth",
        "password":"namex1",
        "passphrase":"yourpassphrase"
      }
    ]
  },
 "id":1
}
----


== SNMP v2가 활성화된 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":false,
    "networks":[
      {
        "community":"public",
        "access":"ro",
        "network":"localhost",
      }
    ]
  },
  "id":1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id" : 1
  "result" :{
  }
}
----


== 버전 이후 새로운 기능

9.6
