---
permalink: api/reference_element_api_hardwareinfo.html 
sidebar: sidebar 
keywords: object,objects,hardwareInfo 
summary: 하드웨어 정보 객체에는 클러스터에 있는 각 노드의 하드웨어 및 상태에 대한 자세한 정보가 들어 있습니다. GetHardwareInfo API 메서드를 사용하여 이 정보를 검색할 수 있습니다. 
---
= 하드웨어 정보
:icons: font
:imagesdir: ../media/


[role="lead"]
하드웨어 정보 객체에는 클러스터에 있는 각 노드의 하드웨어 및 상태에 대한 자세한 정보가 들어 있습니다. GetHardwareInfo API 메서드를 사용하여 이 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
보드직렬
 a| 
DMI 보드 일련 번호입니다.
 a| 
문자열



 a| 
버스
 a| 
마더보드 미디어 버스 정보.
 a| 
JSON 개체



 a| 
섀시 일련 번호
 a| 
섀시의 일련 번호입니다.
 a| 
문자열



 a| 
드라이브하드웨어
 a| 
노드의 각 드라이브에 대한 정보 목록입니다.
 a| 
JSON 개체 어레이



 a| 
광섬유 채널 포트
 a| 
노드의 Fibre Channel 포트 목록입니다.
 a| 
정수 배열



 a| 
하드웨어 구성
 a| 
마더보드 주변 장치 구성 정보
 a| 
JSON 개체



 a| 
kernelCrashDumpState를 참조하십시오
 a| 
운영 체제 커널의 크래시 덤프 구성.
 a| 
문자열



 a| 
메모리
 a| 
펌웨어 및 시스템 메모리 하드웨어 정보
 a| 
JSON 개체



 a| 
네트워크
 a| 
노드의 각 네트워크 인터페이스에 대한 설명입니다.
 a| 
JSON 개체



 a| 
네트워크 인터페이스
 a| 
노드의 네트워크 인터페이스 상태입니다.
 a| 
JSON 개체



 a| 
노드 슬롯
 a| 
HCI 플랫폼의 경우 이 노드가 있는 섀시 슬롯("A", "B", "C" 또는 "D")에 해당하는 문자가 있습니다. 스토리지 플랫폼의 경우 이 값은 null입니다.
 a| 
문자열



 a| 
NVRAM
 a| 
노드의 NVRAM 통계.
 a| 
JSON 개체



 a| 
원점
 a| 
마더보드 공급업체.
 a| 
문자열



 a| 
플랫폼
 a| 
섀시 플랫폼에 대한 설명입니다.
 a| 
JSON 개체



 a| 
일련 번호
 a| 
제품의 일련 번호입니다.
 a| 
문자열



 a| 
스토리지
 a| 
스토리지 컨트롤러 정보입니다.
 a| 
JSON 개체



 a| 
시스템 메모리
 a| 
운영 체제 메모리 사용 및 성능 정보
 a| 
JSON 개체



 a| 
시스템
 a| 
노드 섀시의 유형입니다.
 a| 
JSON 개체



 a| 
UUID입니다
 a| 
노드의 고유 ID입니다.
 a| 
UUID입니다

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_gethardwareinfo.adoc[GetHardwareInfo 를 참조하십시오]
