---
permalink: api/reference_element_api_rollbacktosnapshot.html 
sidebar: sidebar 
keywords: rollbacktosnapshot,snapshot,creating,create,roll,back,rollback,roll back,existing 
summary: RollbackToSnapshot 메서드를 사용하여 활성 볼륨 이미지의 기존 스냅샷을 만들 수 있습니다. 이 방법은 기존 스냅샷에서 새 스냅샷을 생성합니다. 
---
= RollbackToSnapshot 을 클릭합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"RollbackToSnapshot" 방법을 사용하여 활성 볼륨 이미지의 기존 스냅샷을 만들 수 있습니다. 이 방법은 기존 스냅샷에서 새 스냅샷을 생성합니다.

새 스냅샷이 활성화되고 기존 스냅샷은 수동으로 삭제될 때까지 보존됩니다. saveCurrentState 매개 변수를 true로 설정하지 않으면 이전에 활성화된 스냅샷이 삭제됩니다.

* cluster_fullness * 를 선택합니다


NOTE: 클러스터 충만도가 1단계, 2단계 또는 3단계에 있는 경우 스냅샷을 생성할 수 있습니다. 클러스터 충만도가 4단계 또는 5단계에 도달하면 스냅샷을 생성할 수 없습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
볼륨 ID
 a| 
볼륨의 VolumeID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 특성
 a| 
없음
 a| 
아니요



 a| 
이름
 a| 
스냅샷의 이름입니다. 이름을 제공하지 않으면 롤백되는 스냅샷의 이름이 이름 끝에 "-copy"가 추가되어 사용됩니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
스냅샷 ID입니다
 a| 
지정된 볼륨에서 이전에 생성된 스냅샷의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
SaveCurrentState를 선택합니다
 a| 
이전 활성 볼륨 이미지를 저장할지 여부를 지정합니다. 유효한 값:

* 참: 이전 활성 볼륨 이미지가 유지됩니다.
* False: 이전 활성 볼륨 이미지가 삭제됩니다.

 a| 
부울
 a| 
거짓
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
체크섬
 a| 
저장된 스냅샷에 있는 데이터의 작은 문자열 표현입니다.
 a| 
문자열



 a| 
스냅샷 ID입니다
 a| 
saveCurrentState 가 false 로 설정된 경우 이 값은 null입니다.

saveCurrentState 가 true 로 설정된 경우 새로 생성된 스냅샷의 고유 ID입니다.
 a| 
정수



 a| 
스냅샷
 a| 
saveCurrentState 가 false 로 설정된 경우 이 값은 null입니다.

saveCurrentState 가 true 로 설정된 경우 새로 생성된 스냅샷에 대한 정보가 포함된 개체입니다.
 a| 
xref:reference_element_api_snapshot.adoc[스냅샷]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
 "method": "RollbackToSnapshot",
 "params": {
    "volumeID": 1,
    "snapshotID": 3114,
    "saveCurrentState": true
  },
  "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "checksum": "0x0",
    "snapshot": {
      "attributes": {},
      "checksum": "0x0",
      "createTime": "2016-04-04T17:27:32Z",
      "enableRemoteReplication": false,
      "expirationReason": "None",
      "expirationTime": null,
      "groupID": 0,
      "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
      "name": "test1-copy",
      "snapshotID": 1,
      "snapshotUUID": "30d7e3fe-0570-4d94-a8d5-3cc8097a6bfb",
      "status": "done",
      "totalSize": 5000658944,
      "virtualVolumeID": null,
      "volumeID": 1
    },
    "snapshotID": 1
  }
}
----


== 버전 이후 새로운 기능

9.6
