---
permalink: api/reference_element_api_createschedule.html 
sidebar: sidebar 
keywords: CreateSchedule,create,creating,schedule,schedules,snapshot,snapshots,scheduling,automatic,volume,volumes 
summary: CreateSchedule 을 사용하여 정의된 간격으로 볼륨의 자동 스냅샷을 예약할 수 있습니다. 
---
= 생성 일정 을 클릭합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'CreateSchedule'을 사용하여 정의된 간격으로 볼륨의 자동 스냅샷을 예약할 수 있습니다.

나중에 생성된 스냅샷을 백업 또는 롤백으로 사용하여 볼륨 또는 볼륨 그룹의 데이터가 스냅샷이 생성된 시점의 정합성이 보장되도록 할 수 있습니다. 5분 동안 나눌 수 없는 기간에 스냅샷을 실행하도록 예약하는 경우 5분 동안 나눌 수 있는 다음 기간에 스냅샷이 실행됩니다. 예를 들어 스냅샷을 12:42:00 UTC에서 실행하도록 예약하는 경우 12:45:00 UTC에서 실행됩니다. 5분 미만의 간격으로 실행되도록 스냅샷을 예약할 수 없습니다.


NOTE: 클러스터 충만도가 1단계, 2단계 또는 3단계에 있는 경우 스냅샷을 생성할 수 있습니다. 클러스터 충만도가 4단계 또는 5단계에 도달하면 스냅샷을 생성할 수 없습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
'속성'
 a| 
""frequency"" 문자열을 사용하여 스냅샷의 빈도를 나타냅니다. 가능한 값:

* 금주의 날
* 달의 일
* 시간 간격

 a| 
JSON 개체
 a| 
없음
 a| 
아니요



| 'haserror'입니다 | * 설명이 필요한 도움말 * | 부울 | 거짓입니다 | 아니요 


 a| 
"시간"
 a| 
반복 스냅샷 간 시간 또는 스냅샷이 요일 또는 월 모드에서 실행되는 GMT 시간 사이의 시간입니다. 유효한 값은 0 ~ 23입니다.
 a| 
정수
 a| 
없음
 a| 
아니요



| '마지막 기록 상태' | 마지막으로 예약된 스냅샷 생성 결과 또는 상태입니다. | 문자열 | 없음 | 아니요 


 a| 
이름
 a| 
스냅샷의 이름입니다. 이름을 입력하지 않으면 그룹 스냅샷이 생성된 날짜 및 시간이 사용됩니다. 허용되는 최대 이름 길이는 244자입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
'분'
 a| 
반복 스냅샷 간 시간(분) 또는 스냅샷이 요일 또는 월 모드에서 발생할 분(GMT 시간)입니다. 유효한 값은 5 - 59입니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
"일시 정지"
 a| 
스케줄이 일시 중지되어야 하는지 여부를 나타냅니다. 유효한 값:

* "참"입니다
* 거짓입니다

 a| 
부울
 a| 
없음
 a| 
아니요



 a| 
반복
 a| 
일정이 반복되는지 여부를 나타냅니다. 유효한 값은 다음과 같습니다.

* "참"입니다
* 거짓입니다

 a| 
부울
 a| 
없음
 a| 
아니요



| 'runNextInterval'  a| 
다음에 스케줄러가 활성화될 때 스냅샷을 실행할지 여부를 지정합니다. true로 설정하면 다음에 스케줄러가 활성화될 때 예약된 스냅샷이 실행되고 다시 false로 재설정됩니다. 유효한 값은 다음과 같습니다.

* "참"입니다
* 거짓입니다

| 부울 | 거짓입니다 | 아니요 


 a| 
'ScheduleName'입니다
 a| 
스케줄의 고유 이름입니다. 허용되는 최대 스케줄 이름 길이는 244자입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
'ScheduleType'입니다
 a| 
생성할 스케줄의 유형을 나타냅니다. 유효한 값은 스냅샷입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
'ScheduleInfo'입니다
 a| 
스케줄에 지정된 고유 이름, 생성된 스냅샷의 보존 기간 및 스냅샷이 생성된 볼륨의 볼륨 ID입니다. 유효한 값:

* 'volumeID': 스냅샷에 포함될 볼륨의 ID입니다. (정수)
* '볼륨': 그룹 스냅샷에 포함될 볼륨 ID 목록입니다. (정수 배열)
* 이름: 사용할 스냅샷 이름입니다. (문자열)
* enableRemoteReplication: 스냅샷이 원격 복제에 포함되어야 하는지 여부를 나타냅니다. (부울)
* 다시 보존: 스냅샷이 보존되는 시간(HH:MM:ss)입니다. 비어 있으면 스냅샷이 영구적으로 유지됩니다. (문자열)
* fifo: 선입선출(FIFO) 방식으로 스냅샷이 보존됩니다. (문자열)
* ensuSerialCreation: 이전 스냅샷 복제가 진행 중인 경우 새 스냅샷 생성이 허용되는지 여부를 지정합니다. (부울)

 a| 
JSON 개체
 a| 
없음
 a| 
예



 a| 
'스냅샷 레이블'
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트에 대한 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
'시작 날짜'
 a| 
일정이 실행되는 시간입니다. 설정하지 않으면 일정이 즉시 시작됩니다. UTC 시간으로 서식이 지정되었습니다.
 a| 
ISO 8601 날짜 문자열
 a| 
없음
 a| 
아니요



| "토베델eted" | 스냅샷 생성이 완료된 후 이 스냅샷 스케줄을 삭제하도록 지정합니다. | 부울 | 거짓입니다 | 아니요 


 a| 
몬트데이즈다
 a| 
스냅샷이 생성되는 월의 일. 유효한 값은 1부터 31까지입니다.
 a| 
정수 배열
 a| 
없음
 a| 
예(해당 월의 일수를 예약하는 경우)



 a| 
평일
 a| 
스냅샷이 생성되는 요일. 필요한 값(사용된 경우):

* 데이: 0 ~ 6(일요일 ~ 토요일)
* 상계: 한 달 동안 1-6주(1보다 크면 1일, 1일 이내에 Nth-1일에만 매치됩니다. 예를 들어 일요일의 경우 offset:3은 달의 세 번째 일요일을, 수요일의 경우 offset:4는 월의 네 번째 수요일을 의미합니다. 오프셋:0은 아무 작업도 수행되지 않음을 의미합니다. 오프셋:1(기본값)은 해당 월의 어느 위치에 해당하든 해당 요일에 대해 스냅샷이 생성됨을 의미합니다.

 a| 
JSON 개체 어레이
 a| 
없음
 a| 
예(해당 주의 일수를 예약할 경우)

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
예약 ID입니다
 a| 
생성된 스케줄의 ID입니다.
 a| 
정수



 a| 
스케줄
 a| 
새로 생성된 스케줄에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_schedule.adoc[스케줄]

|===


== 요청 예 1

다음 예제 스케줄에는 다음과 같은 매개 변수가 있습니다.

* 시작 시간이나 분을 지정하지 않아 일정이 가능한 한 자정까지 가깝게 시작됩니다(00:00:00Z).
* 반복되지 않습니다(한 번만 실행).
* 2015년 6월 1일, UTC 19:17:15z(어느 날이든 관계없이)에 이어 첫 번째 일요일 또는 수요일에 한 번 실행됩니다.
* 볼륨 한 개만 포함됩니다(볼륨 ID = 1).


[listing]
----
{
  "method":"CreateSchedule",
  "params":{
    "hours":0,
    "minutes":0,
    "paused":false,
    "recurring":false,
    "scheduleName":"MCAsnapshot1",
    "scheduleType":"snapshot",
    "attributes":{
      "frequency":"Days Of Week"
    },
    "scheduleInfo":{
      "volumeID":"1",
      "name":"MCA1"
    },
    "monthdays":[],
    "weekdays":[
      {
        "day":0,
        "offset":1
      },
      {
        "day":3,
        "offset":1
      }
    ],
    "startingDate":"2015-06-01T19:17:54Z"
  },
   "id":1
}
}
}
----


== 응답 예 1

위의 요청은 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Week"
      },
      "hasError": false,
      "hours": 0,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 0,
      "monthdays": [],
      "paused": false,
      "recurring": false,
      "runNextInterval": false,
      "scheduleID": 4,
      "scheduleInfo": {
        "name": "MCA1",
        "volumeID": "1"
      },
      "scheduleName": "MCAsnapshot1",
      "scheduleType": "Snapshot",
      "startingDate": "2015-06-01T19:17:54Z",
      "toBeDeleted": false,
      "weekdays": [
        {
          "day": 0,
          "offset": 1
        },
        {
          "day": 3,
          "offset": 1
        }
      ]
    },
    "scheduleID": 4
  }
}
----


== 요청 예 2

다음 예제 스케줄에는 다음과 같은 매개 변수가 있습니다.

* 반복됨(지정된 시간에 매월 예약된 간격으로 실행됨).
* 이는 시작일자에 이어 매달 1일 10일 15일30일.
* 매일 오후 12시 15분에 실행됩니다.
* 볼륨 한 개만 포함됩니다(볼륨 ID = 1).


[listing]
----
{
  "method":"CreateSchedule",
    "params":{
      "hours":12,
      "minutes":15,
      "paused":false,
      "recurring":true,
      "scheduleName":"MCASnapshot1",
      "scheduleType":"snapshot",
      "attributes":{
        "frequency":"Days Of Month"
      },
      "scheduleInfo":{
        "volumeID":"1"
      },
      "weekdays":[
      ],
      "monthdays":[
        1,
        10,
        15,
        30
      ],
      "startingDate":"2015-04-02T18:03:15Z"
    },
    "id":1
}
----


== 응답 예 2

위의 요청은 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Month"
      },
      "hasError": false,
      "hours": 12,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 15,
      "monthdays": [
        1,
        10,
        15,
        30
      ],
      "paused": false,
      "recurring": true,
      "runNextInterval": false,
      "scheduleID": 5,
      "scheduleInfo": {
        "volumeID": "1"
      },
      "scheduleName": "MCASnapshot1",
      "scheduleType": "Snapshot",
      "startingDate": "2015-04-02T18:03:15Z",
      "toBeDeleted": false,
      "weekdays": []
    },
      "scheduleID": 5
  }
}
----


== 요청 예 3

다음 예제 스케줄에는 다음과 같은 매개 변수가 있습니다.

* 2015년 4월 2일부터 예정된 주기로부터 5분 이내에 시작됩니다.
* 반복됨(지정된 시간에 매월 예약된 간격으로 실행됨).
* 시작 날짜 이후 매달 두 번째, 세 번째, 네 번째 에 실행됩니다.
* 매일 오후 14:45에 실행됩니다.
* 여기에는 볼륨 그룹(볼륨 = 1 및 2)이 포함됩니다.


[listing]
----
{
  "method":"CreateSchedule",
  "params":{
    "hours":14,
    "minutes":45,
    "paused":false,
    "recurring":true,
    "scheduleName":"MCASnapUser1",
    "scheduleType":"snapshot",
    "attributes":{
      "frequency":"Days Of Month"
    },
    "scheduleInfo":{
      "volumes":[1,2]
    },
    "weekdays":[],
    "monthdays":[2,3,4],
    "startingDate":"2015-04-02T20:38:23Z"
  },
  "id":1
}
----


== 응답 예 3

위의 요청은 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Month"
      },
      "hasError": false,
      "hours": 14,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 45,
      "monthdays": [
        2,
        3,
        4
      ],
      "paused": false,
      "recurring": true,
      "runNextInterval": false,
      "scheduleID": 6,
      "scheduleInfo": {
        "volumes": [
          1,
          2
        ]
      },
      "scheduleName": "MCASnapUser1",
      "scheduleType": "Snapshot",
      "startingDate": "2015-04-02T20:38:23Z",
      "toBeDeleted": false,
      "weekdays": []
    },
    "scheduleID": 6
  }
}
----


== 버전 이후 새로운 기능

9.6
