---
permalink: api/reference_element_api_app_a_cluster_fault_codes.html 
sidebar: sidebar 
keywords: cluster,fault,codes,code,message,alert,error 
summary: 스토리지 클러스터에서 관리자에게 이익이 될 수 있는 오류 또는 상태가 발생하면 클러스터 장애가 발생합니다. ListClusterFats 메서드를 사용하여 스토리지 클러스터에서 해결된 장애 및 해결되지 않은 장애의 현재 목록을 검색할 수 있습니다. 
---
= 클러스터 고장 코드
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 클러스터에서 관리자에게 이익이 될 수 있는 오류 또는 상태가 발생하면 클러스터 장애가 발생합니다. "ListClusterFats" 메서드를 사용하여 스토리지 클러스터에서 해결된 장애 및 해결되지 않은 장애의 현재 목록을 검색할 수 있습니다.

다음 목록에는 NetApp Element 스토리지 클러스터 장애에 대한 자세한 내용과 가능한 솔루션이 나와 있습니다.

* * authenticationServiceFault *
+
하나 이상의 클러스터 노드에서 인증 서비스가 예상대로 작동하지 않습니다.

+
NetApp 지원 팀에 문의하십시오.

* * 가용한 VirtualNetworkIPAddressLow *
+
IP 주소 블록의 가상 네트워크 주소 수가 적습니다.

+
이 오류를 해결하려면 가상 네트워크 주소 블록에 더 많은 IP 주소를 추가하십시오.

* * 블록클러스터풀 *
+
단일 노드 손실을 지원하기에 충분한 여유 블록 스토리지 공간이 없습니다. 클러스터 충만 수준에 대한 자세한 내용은 GetClusterFullThreshold API 메서드를 참조하십시오. 이 클러스터 고장은 다음 상태 중 하나를 나타냅니다.

+
** stage3Low(경고): 사용자 정의 임계값이 초과되었습니다. Cluster Full(클러스터 전체) 설정을 조정하거나 노드를 더 추가합니다.
** stage4Critical(오류): 1노드 장애를 복구할 수 있는 공간이 부족합니다. 볼륨, 스냅샷 및 클론을 생성할 수 없습니다.
** stage5CompletyConsumered (Critical) 1; 쓰기 또는 새 iSCSI 연결이 허용되지 않습니다. 현재 iSCSI 연결이 유지됩니다. 클러스터에 용량을 더 추가할 때까지 쓰기에 실패합니다. 이 오류를 해결하려면 볼륨을 제거 또는 삭제하거나 스토리지 클러스터에 다른 스토리지 노드를 추가하십시오.


* * 블록성능이 저하됨 *
+
장애로 인해 블록 데이터가 더 이상 완전히 복제되지 않습니다.

+
|===
| 심각도입니다 | 설명 


 a| 
경고
 a| 
블록 데이터의 전체 복사본을 두 개만 액세스할 수 있습니다.



 a| 
오류
 a| 
블록 데이터의 전체 복사본을 하나만 액세스할 수 있습니다.



 a| 
심각
 a| 
블록 데이터의 전체 복사본을 액세스할 수 없습니다.

|===
+
* 참고: * 경고 상태는 Triple Helix 시스템에서만 발생할 수 있습니다.

+
이 오류를 해결하려면 오프라인 노드 또는 블록 서비스를 복원하거나 NetApp Support에 지원을 문의하십시오.

* * BLOCKServiceTooFull *
+
블록 서비스가 너무 많은 공간을 사용하고 있습니다.

+
이 오류를 해결하려면 볼륨을 제거 또는 삭제하거나 스토리지 클러스터에 다른 스토리지 노드를 추가하십시오.

* * ClockSkewExceedsFaultThreshold *
+
클러스터 마스터와 토큰을 제공하는 노드 간의 시간 차이가 권장 임계값을 초과합니다.

+
스토리지 클러스터는 노드 간의 시간 차이를 자동으로 수정할 수 없습니다. 이 오류를 해결하려면 설치 기본값이 아닌 네트워크 내부의 NTP 서버를 사용하십시오. 이미 내부 NTP 서버를 사용하고 있는 경우 NetApp 지원 팀에 지원을 문의하십시오.

* * 클러스터 동기화 *
+
클러스터 블록 데이터가 성능 저하 상태이고 전체 블록 데이터 이중화를 복원하기 위한 자동 복구 프로세스가 진행될 수 없습니다. 너무 많은 노드나 블록 서비스가 오프라인 상태이거나 클러스터 블록 서비스가 너무 가득 찼습니다.

+
이 오류를 해결하려면 블록 용량을 더 추가하거나 NetApp Support에 문의하십시오.

* * 클러스터풀 *
+
스토리지 클러스터에 사용 가능한 스토리지 공간이 더 이상 없습니다.

+
이 오류를 해결하려면 스토리지를 더 추가하십시오.

* * 클러스터로IOPSARREOverProvisioned *
+
스토리지 클러스터 IOPS가 초과 프로비저닝됩니다. 모든 최소 QoS IOPS의 합이 클러스터의 예상 IOPS보다 큽니다. 시스템에서 모든 볼륨에 대해 최소 QoS를 동시에 유지할 수 없습니다.

+
이 오류를 해결하려면 볼륨에 대한 최소 QoS IOPS 설정을 낮추십시오.

* * disableDriveSecurityFailed *
+
저장된 데이터 암호화 기능이 꺼져 있을 때 드라이브를 안전하게 비활성화할 수 없습니다. 드라이브에 여전히 드라이브 보안이 활성화되어 있습니다.

+
드라이브 보안을 비활성화할 수 없는 이유가 고장 세부 정보에 표시됩니다. 이유를 기준으로 문제를 조사해야 할 수도 있습니다. 보안이 비활성화되지 않은 디스크를 복구해야 하는 경우 다음 단계를 수행하십시오.

+
.. 드라이브를 "사용 가능" 상태로 이동하여 드라이브를 논리적으로 분리합니다.
.. 드라이브에서 보안 삭제를 수행합니다.
.. 드라이브를 "활성" 상태로 이동합니다. 이 단계를 수행해도 문제가 해결되지 않으면 드라이브를 교체합니다.


* * 연결 해제 클러스터 쌍 *
+
클러스터 쌍의 연결이 끊어지거나 잘못 구성되었습니다.

+
클러스터의 네트워크 연결을 확인합니다.

* * 연결 해제 RemoteNode *
+
원격 노드의 연결이 끊겼거나 잘못 구성되었습니다. 노드 간 네트워크 연결을 확인합니다.

* * 연결 해제 SnapMirror 엔드포인트 *
+
원격 SnapMirror 엔드포인트의 연결이 끊어지거나 잘못 구성되었습니다. 클러스터와 원격 SnapMirrorEndpoint 간의 네트워크 연결을 확인합니다.

* * 드라이브 사용 가능 *
+
하나 이상의 드라이브를 스토리지 클러스터에 추가할 수 있습니다. 일반적으로 모든 스토리지 클러스터에는 모든 드라이브가 추가되어야 하며 사용 가능한 상태에서는 없어야 합니다. 이 오류가 예기치 않게 나타날 경우 NetApp 지원 팀에 문의하십시오.

+
이 오류를 해결하려면 사용 가능한 드라이브를 스토리지 클러스터에 추가하십시오.

* * 드라이브 실패 *
+
하나 이상의 드라이브에 장애가 발생하면 클러스터가 이 오류를 반환하고 다음 조건 중 하나를 표시합니다.

+
** 드라이브 관리자가 드라이브에 액세스할 수 없습니다.
** 슬라이스 또는 블록 서비스가 너무 많은 번 실패했으며, 이는 아마도 드라이브 읽기 또는 쓰기 오류로 인해 발생할 수 있으며 다시 시작할 수 없습니다.
** 드라이브가 없습니다.
** 노드의 마스터 서비스에 액세스할 수 없습니다(노드의 모든 드라이브가 누락/실패로 간주됨).
** 드라이브가 잠겨 있고 드라이브의 인증 키를 가져올 수 없습니다.
** 드라이브가 잠겨 있고 잠금 해제 작업이 실패합니다. 이 문제를 해결하려면:
** 노드의 네트워크 연결을 확인합니다.
** 드라이브를 교체합니다.
** 인증 키를 사용할 수 있는지 확인합니다.


* * 드라이브 상태 결함 *
+
드라이브가 SMART 상태 점검에 실패하여 드라이브의 기능이 저하되었습니다. 이 결함의 심각도는 다음과 같습니다.

+
** 슬롯 <node slot><drive slot>에 일련 번호 <serial number>이(가) 있는 드라이브가 SMART Overall 상태 검사에 실패했습니다. 이 고장을 해결하려면 드라이브를 교체하십시오.


* * driveWearFault *
+
드라이브의 남은 수명이 임계값 아래로 떨어졌지만 여전히 작동하고 있습니다. 이 결함에는 위험 및 경고라는 두 가지 심각도 수준이 있을 수 있습니다.

+
** 슬롯이 <node slot><drive slot>인 일련 번호가 <serial number>인 드라이브의 마모 수준이 매우 중요합니다.
** 슬롯이 <node slot><drive slot>인 슬롯에 일련 번호 <serial number>가 있는 드라이브의 마모 예비량이 적습니다. 이 고장을 해결하려면 드라이브를 곧 교체하십시오.


* * duplicateClusterMasterCandidate *
+
스토리지 클러스터 마스터 후보가 두 개 이상 있습니다.

+
NetApp 지원 팀에 문의하십시오.

* * enableDriveSecurityFailed *
+
저장된 데이터 암호화 기능이 켜져 있을 때 드라이브를 안전하게 사용할 수 없습니다.

+
보안을 활성화하기 위해 올바른 키를 사용하고 있는지 확인합니다. 보안이 설정되지 않은 디스크를 복구해야 하는 경우 다음 단계를 수행하십시오.

+
.. 드라이브를 "사용 가능" 상태로 이동하여 드라이브를 논리적으로 분리합니다.
.. 드라이브에서 보안 삭제를 수행합니다.
.. 드라이브를 "활성" 상태로 이동합니다. 이 단계를 수행해도 문제가 해결되지 않으면 드라이브를 교체합니다.


* * EnembleDegraded *
+
앙상블 노드 중 하나에 네트워크 연결 또는 전원이 손실되었습니다.

+
이 오류를 해결하려면 영향을 받는 노드에 대한 네트워크 연결 또는 전원을 복원하십시오.

* * 예외 *
+
비정상적인 고장이 발생했습니다. 이러한 고장은 오류 대기열에서 자동으로 삭제되지 않습니다.

+
NetApp 지원 팀에 문의하십시오.

* * failedSpaceTooFull *
+
블록 서비스가 데이터 쓰기 요청에 응답하지 않습니다. 이로 인해 슬라이스 서비스의 공간이 부족하여 실패한 쓰기를 저장할 수 없습니다.

+
NetApp 지원 팀에 문의하십시오.

* * 팬센서 *
+
팬 센서가 고장났거나 없습니다.

+
노드에서 장애가 발생한 하드웨어를 교체합니다. 그래도 문제가 해결되지 않으면 NetApp Support에 문의하십시오.

* * 광섬유 채널 액세스 저하됨 *
+
Fibre Channel 노드가 스토리지 IP 주소를 통해 스토리지 클러스터의 다른 노드에 응답하지 않습니다.

+
클러스터의 네트워크 연결을 확인합니다.

* * 광섬유 채널 액세스사용할 수 없음 *
+
모든 Fibre Channel 노드가 응답하지 않습니다. 노드 ID가 표시됩니다.

+
클러스터의 네트워크 연결을 확인합니다.

* * 광섬유 채널 ActiveIxL *
+
IxL Nexus 수가 Fibre Channel 노드당 지원되는 활성 세션 8000개 한도에 근접하고 있습니다.

+
** 모범 사례 제한은 5500입니다.
** 경고 한계는 7500입니다.
** 최대 제한(시행되지 않음)은 8192입니다. 이 고장을 해결하려면 IxL Nexus 수를 Best Practice Limit 인 5500 미만으로 줄이십시오.


* * 광섬유 채널 구성 *
+
이 클러스터 고장은 다음 상태 중 하나를 나타냅니다.

+
** PCI 슬롯에 예기치 않은 Fibre Channel 포트가 있습니다.
** 예기치 않은 Fibre Channel HBA 모델이 있습니다.
** Fibre Channel HBA의 펌웨어에 문제가 있습니다.
** Fibre Channel 포트가 온라인 상태가 아닙니다.
** Fibre Channel 패스스루 구성에 지속적인 문제가 있습니다. NetApp 지원 팀에 문의하십시오.


* * 광섬유 채널 IOPS *
+
총 IOPS 수가 클러스터의 파이버 채널 노드에 대한 IOPS 제한에 근접하고 있습니다. 제한 사항은 다음과 같습니다.

+
** FC0025:450K IOPS는 파이버 채널 노드당 4K 블록 크기로 제한됩니다.
** FCN001:625K OPS는 파이버 채널 노드당 4K 블록 크기에서 제한됩니다. 이 오류를 해결하려면 사용 가능한 모든 Fibre Channel 노드에서 로드 밸런싱을 조정합니다.


* * 광섬유 채널 StaticIxL *
+
IxL Nexus 수가 Fibre Channel 노드당 지원되는 16000개의 정적 세션 제한에 근접하고 있습니다.

+
** 모범 사례 제한은 11000입니다.
** 경고 한계는 15000입니다.
** 최대 제한(강제 적용)은 16384입니다. 이 고장을 해결하려면 IxL Nexus 개수를 11000의 모범 사례 한도 미만으로 줄이십시오.


* 파일시스템 용량 낮음*
+
파일 시스템 중 하나에 공간이 부족합니다.

+
이 오류를 해결하려면 파일 시스템에 용량을 더 추가하십시오.

* * fipsDrivesMismatch *
+
FIPS가 아닌 드라이브가 FIPS 스토리지 노드에 삽입되었거나 FIPS 드라이브가 아닌 스토리지 노드에 삽입되었습니다.

+
문제가 있는 드라이브를 분리하거나 교체합니다.

* * fipsDrivesOutOfCompliance * 를 참조하십시오
+
시스템에서 저장된 데이터 암호화가 해제되었거나 스토리지 클러스터에 FIPS 이외의 하드웨어가 있음을 감지했습니다.

+
저장 시 암호화를 설정하거나 스토리지 클러스터에서 비 FIPS 하드웨어를 제거합니다.

* * fipsSelfTestFailure *
+
FIPS 자체 테스트 중에 시스템에서 장애가 감지되었습니다.

+
NetApp 지원 팀에 문의하십시오.

* * 하드웨어 구성 불일치 *
+
이 클러스터 고장은 다음 상태 중 하나를 나타냅니다.

+
** 구성이 노드 정의와 일치하지 않습니다.
** 이 노드 유형에 잘못된 드라이브 크기가 있습니다.
** 노드가 지원되지 않는 드라이브를 사용하고 있습니다.
** 드라이브 펌웨어가 일치하지 않습니다.
** 드라이브의 암호화 가능 상태가 상위 노드와 일치하지 않습니다. NetApp 지원 팀에 문의하십시오.


* * idPCertificateExpiration *
+
타사 ID 공급자와 함께 사용할 클러스터의 서비스 공급자 SSL 인증서가 만료되었거나 이미 만료되었습니다. 이 결함은 긴급도에 따라 다음과 같은 심각도를 사용합니다.

+
|===
| 심각도입니다 | 설명 


 a| 
경고
 a| 
인증서가 30일 이내에 만료됩니다.



 a| 
오류
 a| 
인증서가 7일 이내에 만료됩니다.



 a| 
심각
 a| 
인증서가 3일 이내에 만료되거나 이미 만료되었습니다.

|===
+
이 오류를 해결하려면 SSL 인증서가 만료되기 전에 업데이트하십시오. 업데이트된 SSL 인증서를 제공하려면 UpdateIdpConfiguration 메서드와 RefreshCertificateExpirationTime = true 를 사용합니다.

* * 비일관성 모델 *
+
VLAN 장치의 연결 모드가 누락되었습니다. 이 고장은 예상 본드 모드와 현재 사용 중인 본드 모드를 표시합니다.

+
이 오류를 해결하려면 노드별 웹 UI에서 연결 모드를 수정합니다.

* * 비일관성 InterfaceConfiguration *
+
인터페이스 구성이 일치하지 않습니다.

+
이 오류를 해결하려면 스토리지 클러스터의 노드 인터페이스가 일관되게 구성되어 있는지 확인합니다.

* * 불일치 *
+
이 클러스터 고장은 다음 상태 중 하나를 나타냅니다.

+
** Bond1G 불일치: Bond1G 인터페이스에서 일치하지 않는 MTU가 감지되었습니다.
** Bond10G 불일치: Bond10G 인터페이스에서 일치하지 않는 MTU가 감지되었습니다. 이 장애는 관련된 MTU 값과 함께 문제의 노드나 노드를 표시합니다.


+
이 오류를 해결하려면 노드별 웹 UI에서 MTU 설정을 수정합니다.

* * 비일관성 RoutingRules *
+
이 인터페이스의 라우팅 규칙이 일치하지 않습니다.

* * 불일관된 SubnetMasks *
+
VLAN 장치의 네트워크 마스크가 VLAN에 대해 내부적으로 기록된 네트워크 마스크와 일치하지 않습니다. 이 고장은 예상 네트워크 마스크와 현재 사용 중인 네트워크 마스크를 표시합니다.

+
이 오류를 해결하려면 Element(스토리지 클러스터) 웹 UI에서 서브넷 마스크를 수정합니다.

* * incorrectBondPortCount *
+
연결 포트 수가 올바르지 않습니다.

* * invalidConfiguredFiberChannelNodeCount * 입니다
+
두 예상 Fibre Channel 노드 연결 중 하나의 성능이 저하되었습니다. 이 오류는 하나의 Fibre Channel 노드만 연결되어 있을 때 나타납니다.

+
이 오류를 해결하려면 클러스터 네트워크 연결 및 네트워크 케이블을 확인하고 실패한 서비스가 있는지 확인합니다. 네트워크 또는 서비스 문제가 없는 경우 NetApp Support에서 파이버 채널 노드 교체를 문의하십시오.

* * irqBalancepFailed *
+
인터럽트의 균형을 맞추는 동안 예외가 발생했습니다.

+
NetApp 지원 팀에 문의하십시오.

* *kmipCertificateFault(루트 인증 기관(CA) 인증서의 만료 시기가 임박했습니다.*
+
루트 CA(인증 기관) 인증서의 만료 시기가 다가오고 있습니다. 이 결함은 긴급도에 따라 다음과 같은 심각도를 사용합니다.

+
|===
| 심각도입니다 | 설명 


 a| 
경고
 a| 
인증서가 30일 이내에 만료됩니다.



 a| 
오류
 a| 
인증서가 7일 이내에 만료됩니다.



 a| 
심각
 a| 
인증서가 3일 이내에 만료됩니다.

|===
+
이 오류를 해결하려면 인증서가 만료되기 전에 업데이트하십시오. 만료 날짜가 30일 이상인 루트 CA에서 새 인증서를 취득합니다. ModifyKeyServerKmip API 메서드를 사용하여 업데이트된 루트 CA 인증서를 제공합니다.

* * kmipCertificateFault(클라이언트 인증서 만료 임박) *
+
클라이언트 인증서의 만료 시기가 다가오고 있습니다. 이 결함은 긴급도에 따라 다음과 같은 심각도를 사용합니다.

+
|===
| 심각도입니다 | 설명 


 a| 
경고
 a| 
인증서가 30일 이내에 만료됩니다.



 a| 
오류
 a| 
인증서가 7일 이내에 만료됩니다.



 a| 
심각
 a| 
인증서가 3일 이내에 만료됩니다.

|===
+
이 오류를 해결하려면 GetClientCertificateSigningRequest 메서드를 사용하여 새 CSR을 만듭니다. CSR이 30일 이상 만료되도록 서명한 후 ModifyKeyServerKmip API 메소드를 사용하여 만료되는 클라이언트 인증서를 새 인증서로 대체하십시오.

* * kmipCertificateFault(루트 인증 기관(CA) 인증서 만료) *
+
루트 CA 인증서가 만료되었습니다.

+
만료 날짜가 30일 이상인 루트 CA에서 새 인증서를 취득합니다. ModifyKeyServerKmip API 메서드를 사용하여 업데이트된 루트 CA 인증서를 제공합니다.

* * kmipCertificateFault(클라이언트 인증서 만료) *
+
클라이언트 인증서가 만료되었습니다.

+
GetClientCertificateSigningRequest API 메서드를 사용하여 새 CSR을 만들고 새 만료 날짜가 향후 30일 이상이 되도록 서명하도록 합니다. 만료된 클라이언트 인증서를 새 인증서로 바꾸려면 ModifyKeyServerKmip API 메서드를 사용합니다.

* * kmipCertificateFault(잘못된 루트 인증 기관(CA) 인증서) *
+
루트 CA 인증서가 잘못되었습니다.

+
올바른 인증서가 제공되었는지 확인하십시오. 필요한 경우 루트 CA에서 인증서를 다시 가져옵니다. ModifyKeyServerKmip API 메서드를 사용하여 올바른 인증서를 설치합니다.

* * kmipCertificateFault(잘못된 클라이언트 인증서) *
+
클라이언트 인증서가 유효하지 않습니다.

+
올바른 KMIP 클라이언트 인증서가 설치되었는지 확인하십시오. 클라이언트 인증서의 루트 CA가 외부 키 관리 서버에 설치되어 있어야 합니다. 클라이언트 인증서를 업데이트해야 하는 경우 ModifyKeyServerKmip API 메서드를 사용하여 업데이트합니다.

* * kmipServerFault(연결 실패) *
+
하나 이상의 노드가 외부 키 관리 서버에 액세스할 수 없습니다.

+
주요 서버 ID는 장애 세부 정보에 제공됩니다. 서버가 작동하고 관리 네트워크를 통해 연결할 수 있는지 확인합니다. 일부 노드만 외부 키 관리 서버에 액세스할 수 없는 경우 키 서버에 연결할 수 없는 노드가 오류 세부 정보에 나열됩니다. 네트워크 또는 특정 노드 수준에서 문제 해결을 수행하여 일부 노드만 외부 키 관리 서버에 액세스할 수 있는 이유를 확인합니다.

* * kmipServerFault(인증 실패) *
+
하나 이상의 노드가 외부 키 관리 서버로 인증할 수 없습니다.

+
올바른 루트 CA 및 KMIP 클라이언트 인증서를 사용 중인지 확인합니다. 인증서를 업데이트해야 하는 경우 ModifyKeyServerKmip 메서드를 사용하여 올바른 인증서를 설치합니다.

* * kmipServerFault(서버 오류) *
+
외부 키 관리 서버에 오류가 있습니다.

+
오류 세부 정보는 고장 세부 정보에 나와 있습니다. 오류에 따라 외부 키 관리 서버의 문제를 해결해야 할 수 있습니다.

* * 암기편임계값 *
+
수정 가능 또는 수정할 수 없는 많은 ECC 오류가 감지되었습니다. 이 결함은 긴급도에 따라 다음과 같은 심각도를 사용합니다.

+
|===
| 이벤트 | 심각도입니다 | 설명 


 a| 
단일 DIMM cErrorCount는 cDimmCorrectableErrWarnThreshold에 도달합니다.
 a| 
경고
 a| 
DIMM:<프로세서><DIMM 슬롯>에서 수정 가능한 ECC 메모리 오류가 임계값보다 높습니다



 a| 
단일 DIMM cErrorCount는 cErrorFaultTimer 가 DIMM에 대해 만료될 때까지 immCorrectableErrWarnThreshold 를 유지합니다.
 a| 
오류
 a| 
DIMM:<프로세서><DIMM>에서 수정 가능한 ECC 메모리 오류가 임계값보다 높습니다



 a| 
메모리 컨트롤러는 cErrorCount above cMemCtlCorrectableErrWarnThreshold 를 보고하고 cMemCtlrCorrectableErrWarnDuration 을 지정합니다.
 a| 
경고
 a| 
수정 가능한 ECC 메모리 오류가 메모리 컨트롤러의 임계값보다 높음:<프로세서><메모리 컨트롤러>



 a| 
메모리 컨트롤러는 메모리 컨트롤러에 대해 cErrorFaultTimer 가 만료될 때까지 cErrorCount 를 cMemCtlCorrectableErrWarnThreshold 보다 높게 보고합니다.
 a| 
오류
 a| 
DIMM:<프로세서><DIMM>에서 수정 가능한 ECC 메모리 오류가 임계값보다 높습니다



 a| 
단일 DIMM은 0보다 큰 uErrorCount를 보고하지만 cDimmUncorrectableErrFaultThreshold보다 작습니다.
 a| 
경고
 a| 
DIMM:<프로세서><DIMM 슬롯>에서 수정할 수 없는 ECC 메모리 오류가 감지되었습니다



 a| 
단일 DIMM은 적어도 cDimmUncorrectableErrFaultThreshold의 uErrorCount를 보고합니다.
 a| 
오류
 a| 
DIMM:<프로세서><DIMM 슬롯>에서 수정할 수 없는 ECC 메모리 오류가 감지되었습니다



 a| 
메모리 컨트롤러는 uErrorCount 가 0보다 크지만 cMemCtlrUncorrectableErrFaultThreshold 보다 작다는 것을 보고합니다.
 a| 
경고
 a| 
메모리 컨트롤러 <Processor><Memory Controller>에서 수정할 수 없는 ECC 메모리 오류가 감지되었습니다



 a| 
메모리 컨트롤러는 cMemCtlrUncorrectableErrFaultThreshold의 uErrorCount를 보고합니다.
 a| 
오류
 a| 
메모리 컨트롤러 <Processor><Memory Controller>에서 수정할 수 없는 ECC 메모리 오류가 감지되었습니다

|===
+
이 고장을 해결하려면 NetApp 지원에 문의하여 지원을 받으십시오.

* * 메모리 사용 임계값 *
+
메모리 사용량이 정상보다 높습니다. 이 결함은 긴급도에 따라 다음과 같은 심각도를 사용합니다.

+

NOTE: 고장 유형에 대한 자세한 내용은 * 세부 정보 * 표제를 참조하십시오.

+
|===


| 심각도입니다 | 설명 


 a| 
경고
 a| 
시스템 메모리가 부족합니다.



 a| 
오류
 a| 
시스템 메모리가 매우 부족합니다.



 a| 
심각
 a| 
시스템 메모리가 완전히 소모되었습니다.

|===
+
이 고장을 해결하려면 NetApp 지원에 문의하여 지원을 받으십시오.

* * 메타 클러스터풀 *
+
단일 노드 손실을 지원하기에 충분한 여유 메타데이터 스토리지 공간이 없습니다. 클러스터 충만 수준에 대한 자세한 내용은 GetClusterFullThreshold API 메서드를 참조하십시오. 이 클러스터 고장은 다음 상태 중 하나를 나타냅니다.

+
** stage3Low(경고): 사용자 정의 임계값이 초과되었습니다. Cluster Full(클러스터 전체) 설정을 조정하거나 노드를 더 추가합니다.
** stage4Critical(오류): 1노드 장애를 복구할 수 있는 공간이 부족합니다. 볼륨, 스냅샷 및 클론을 생성할 수 없습니다.
** stage5CompletyConsumered (Critical) 1; 쓰기 또는 새 iSCSI 연결이 허용되지 않습니다. 현재 iSCSI 연결이 유지됩니다. 클러스터에 용량을 더 추가할 때까지 쓰기에 실패합니다. 데이터를 삭제 또는 삭제하거나 노드를 더 추가합니다. 자세한 내용은 _클러스터 충만 수준 이해_를 참조하십시오.


+
이 오류를 해결하려면 볼륨을 제거 또는 삭제하거나 스토리지 클러스터에 다른 스토리지 노드를 추가하십시오.

* * mbuCheckFailure *
+
네트워크 디바이스가 적절한 MTU 크기로 구성되지 않았습니다.

+
이 고장을 해결하려면 모든 네트워크 인터페이스 및 스위치 포트가 점보 프레임(최대 9000바이트 크기)에 맞게 구성되었는지 확인하십시오.

* * 네트워크 구성 *
+
이 클러스터 고장은 다음 상태 중 하나를 나타냅니다.

+
** 예상된 네트워크 인터페이스가 존재하지 않습니다.
** 중복된 네트워크 인터페이스가 있습니다.
** 네트워크 인터페이스가 구성되었지만 다운되었습니다.
** 네트워크 인터페이스를 다시 시작해야 합니다. NetApp 지원 팀에 문의하십시오.


* * nobaableVirtualNetworkIPAddresses *
+
IP 주소 블록에 사용 가능한 가상 네트워크 주소가 없습니다.

+
** virtualNetworkID# 태그(###)에 사용 가능한 스토리지 IP 주소가 없습니다. 클러스터에 노드를 추가할 수 없습니다. 이 오류를 해결하려면 가상 네트워크 주소 블록에 더 많은 IP 주소를 추가하십시오.


* * nodeHardwareFault(네트워크 인터페이스 <name>이(가) 다운되었거나 케이블이 뽑혀 있음) *
+
네트워크 인터페이스가 다운되었거나 케이블이 분리되었습니다.

+
이 고장을 해결하려면 노드나 노드의 네트워크 연결을 확인하십시오.

* * nodeHardwareFault(드라이브 암호화 가능 상태가 슬롯 <node slot><drive slot>) * 의 드라이브에 대한 노드의 암호화 가능 상태와 일치하지 않습니다
+
드라이브가 설치된 스토리지 노드의 암호화 기능과 일치하지 않습니다.

* * nodeHardwareFault(이 노드 유형에 대해 슬롯 <node slot><drive slot>의 드라이브에 대해 <드라이브 유형> 드라이브 크기 <실제 크기>가 올바르지 않음 - 예상 크기>) *
+
스토리지 노드에는 이 노드의 크기가 잘못된 드라이브가 포함되어 있습니다.

* * nodeHardwareFault(슬롯 <node slot><drive slot>에서 지원되지 않는 드라이브가 감지되었습니다. 드라이브 통계 및 상태 정보를 사용할 수 없습니다.) *
+
스토리지 노드에 지원되지 않는 드라이브가 포함되어 있습니다.

* * nodeHardwareFault(슬롯 <node slot><드라이브 슬롯>의 드라이브가 펌웨어 버전 <예상 버전>을(를) 사용해야 하지만 지원되지 않는 버전 <실제 버전>을(를) 사용하고 있음) *
+
스토리지 노드에는 지원되지 않는 펌웨어 버전을 실행하는 드라이브가 포함되어 있습니다.

* * 노드 유지보수모드 *
+
노드가 유지보수 모드로 전환되었습니다. 이 결함은 긴급도에 따라 다음과 같은 심각도를 사용합니다.

+
|===
| 심각도입니다 | 설명 


 a| 
경고
 a| 
노드가 아직 유지보수 모드에 있음을 나타냅니다.



 a| 
오류
 a| 
장애 발생 또는 활성 스탠바이로 인해 유지보수 모드가 비활성화되지 않았음을 나타냅니다.

|===
+
이 고장을 해결하려면 유지보수가 완료된 후 유지보수 모드를 비활성화하십시오. 오류 수준 고장이 지속될 경우 NetApp 지원에 지원을 문의하십시오.

* * 노드 오프라인 *
+
Element 소프트웨어가 지정된 노드와 통신할 수 없습니다.

+
이 오류를 해결하려면 클러스터의 네트워크 연결 및 네트워크 케이블 연결을 확인하십시오. 네트워크 문제가 없는 경우 NetApp Support에서 노드 교체를 문의하십시오.

* * notUsingLCPBondMode *
+
LACP 결합 모드가 구성되지 않았습니다.

+
이 오류를 해결하려면 스토리지 노드를 구축할 때 LACP 결합을 사용합니다. LACP가 활성화되어 있지 않고 올바르게 구성되지 않은 경우 클라이언트에서 성능 문제를 겪을 수 있습니다.

* * ntpServerUnreachable *
+
스토리지 클러스터가 지정된 NTP 서버 또는 서버와 통신할 수 없습니다.

+
이 오류를 해결하려면 NTP 서버 구성, 네트워크 및 방화벽을 확인하십시오.

* * ntpTimeNotInSync * 를 선택합니다
+
스토리지 클러스터 시간과 지정된 NTP 서버 시간 간의 차이가 너무 큽니다. 스토리지 클러스터가 자동으로 차이를 수정할 수 없습니다.

+
이 오류를 해결하려면 설치 기본값이 아닌 네트워크 내부의 NTP 서버를 사용하십시오. 내부 NTP 서버를 사용하고 있고 문제가 지속되면 NetApp 지원 팀에 지원을 문의하십시오.

* nvramDeviceStatus *
+
NVRAM 장치에 오류가 있거나, 오류가 발생했거나, 오류가 발생했습니다. 이 결함에는 다음과 같은 심각도가 있습니다.

+
|===
| 심각도입니다 | 설명 


 a| 
경고
 a| 
하드웨어에 의해 경고가 감지되었습니다. 이 조건은 온도 경고와 같이 일시적인 것일 수 있습니다.

** nvmLifetimeError 를 참조하십시오
** nvmLifetimeStatus를 참조하십시오
** energySourceLifetimeStatus를 참조하십시오
** energySourceTemperatureStatus를 참조하십시오
** WarningThresholdExceeded(경고 임계홀더제외)




 a| 
오류
 a| 
하드웨어에서 오류 또는 위험 상태가 감지되었습니다. 클러스터 마스터가 슬라이스 드라이브를 작업에서 제거하려고 합니다. 이렇게 하면 드라이브 제거 이벤트가 생성됩니다. 보조 슬라이스 서비스를 사용할 수 없는 경우 드라이브가 제거되지 않습니다. 경고 수준 오류와 함께 반환된 오류:

** NVRAM 디바이스 마운트 지점이 없습니다.
** NVRAM 장치 파티션이 존재하지 않습니다.
** NVRAM 장치 파티션이 있지만 마운트되지 않았습니다.




 a| 
심각
 a| 
하드웨어에서 오류 또는 위험 상태가 감지되었습니다. 클러스터 마스터가 슬라이스 드라이브를 작업에서 제거하려고 합니다. 이렇게 하면 드라이브 제거 이벤트가 생성됩니다. 보조 슬라이스 서비스를 사용할 수 없는 경우 드라이브가 제거되지 않습니다.

** 지속
** 팔StatusSaveNArmed 를 선택합니다
** csaveStatusError입니다


|===
+
노드에서 장애가 발생한 하드웨어를 교체합니다. 그래도 문제가 해결되지 않으면 NetApp Support에 문의하십시오.

* *전원 공급 장치 오류*
+
이 클러스터 고장은 다음 상태 중 하나를 나타냅니다.

+
** 전원 공급 장치가 없습니다.
** 전원 공급 장치에 장애가 발생했습니다.
** 전원 공급 장치에 입력이 없거나 입력이 범위를 벗어났습니다. 이 오류를 해결하려면 중복 전원이 모든 노드에 공급되는지 확인합니다. 문제가 지속되면 NetApp 지원 팀에 문의하십시오.


* * 프로비저닝됨 스페이스투풀 *
+
스토리지 클러스터의 전체 프로비저닝 용량이 너무 가득 찼습니다.

+
이 오류를 해결하려면 프로비저닝된 공간을 더 추가하거나 볼륨 또는 스냅샷을 삭제 및 퍼지합니다.

* * remoteRepAsyncDelayExceeded *
+
복제에 대해 구성된 비동기 지연을 초과했습니다.

* * remoteRepClusterFull *
+
타겟 스토리지 클러스터가 너무 가득 차 볼륨이 원격 복제를 일시 중지했습니다.

+
이 오류를 해결하려면 타겟 스토리지 클러스터에서 공간을 확보하십시오.

* * remoteRepSnapshotClusterFull *
+
타겟 스토리지 클러스터가 너무 가득 차 있어 볼륨이 스냅샷의 원격 복제를 일시 중지했습니다.

+
이 오류를 해결하려면 타겟 스토리지 클러스터에서 공간을 확보하십시오.

* * remoteRepSnapshotsExcedLimit *
+
타겟 스토리지 클러스터 볼륨이 스냅샷 제한을 초과했기 때문에 볼륨이 스냅샷의 원격 복제를 일시 중지했습니다.

+
이 오류를 해결하려면 원격 클러스터에서 일부 스냅샷을 제거하십시오.

* 별표(* scheduleActionError*)
+
하나 이상의 예약된 작업이 실행되었지만 실패했습니다.

+
예약된 활동이 다시 실행되고 성공하거나, 예약된 활동이 삭제되거나, 활동이 일시 중지되어 재개되면 결함이 지워집니다.

* * sensorReadingFailed *
+
베이스보드 관리 컨트롤러(BMC) 자체 테스트에 실패했거나 센서가 BMC와 통신할 수 없습니다.

+
NetApp 지원 팀에 문의하십시오.

* * serviceNotRunning *
+
필요한 서비스가 실행되고 있지 않습니다.

+
NetApp 지원 팀에 문의하십시오.

* * 슬라이서 서비스전체 *
+
슬라이스 서비스에 할당된 프로비저닝 용량이 너무 적습니다.

+
이 오류를 해결하려면 스토리지 노드를 더 추가하거나 NetApp Support에 문의하십시오.

* * 슬라이슬리서비스건강하지 않음 *
+
시스템에서 슬라이스 서비스가 정상 상태가 아닌 것을 감지하여 자동으로 서비스 해제를 합니다.

+
** 심각도 = 경고: 작업이 수행되지 않습니다. 이 경고 기간은 6분 후에 만료됩니다.
** 심각도 = 오류: 시스템이 자동으로 데이터를 사용 중지하여 다른 정상 드라이브로 데이터를 재복제합니다. 네트워크 연결 문제 및 하드웨어 오류를 확인합니다. 특정 하드웨어 구성 요소에 장애가 발생한 경우 다른 장애가 발생할 수 있습니다. 슬라이스 서비스에 액세스할 수 있거나 서비스가 해체되면 결함이 지워집니다.


* * sshEnabled *
+
SSH 서비스는 스토리지 클러스터의 하나 이상의 노드에서 설정됩니다.

+
이 장애를 해결하려면 노드나 노드에서 SSH 서비스를 사용하지 않도록 설정합니다.

* * sslCertificateExpiration *
+
이 노드와 연결된 SSL 인증서가 만료되었거나 만료되었습니다. 이 결함은 긴급도에 따라 다음과 같은 심각도를 사용합니다.

+
|===


| 심각도입니다 | 설명 


 a| 
경고
 a| 
인증서가 30일 이내에 만료됩니다.



 a| 
오류
 a| 
인증서가 7일 이내에 만료됩니다.



 a| 
심각
 a| 
인증서가 3일 이내에 만료되거나 이미 만료되었습니다.

|===
+
이 고장을 해결하려면 SSL 인증서를 갱신하십시오. 필요한 경우 NetApp Support에 지원을 요청하십시오.

* * 용량 *
+
단일 노드는 스토리지 클러스터 용량의 절반 이상을 차지합니다.

+
시스템은 데이터 이중화를 유지하기 위해 최대 노드의 용량을 줄여 일부 블록 용량이 고립되도록 합니다(미사용). 이 오류를 해결하려면 기존 스토리지 노드에 드라이브를 추가하거나 클러스터에 스토리지 노드를 추가합니다.

* * tempSensor *
+
온도 센서가 정상 온도보다 높은 온도를 보고하고 있습니다. 이 고장은 전원 공급 장치 오류 또는 팬센서 오류와 함께 발생할 수 있습니다.

+
이 고장을 해결하려면 저장소 클러스터 근처의 공기 흐름을 방해하는 물체가 있는지 확인하십시오. 필요한 경우 NetApp Support에 지원을 요청하십시오.

* * 업그레이드 *
+
24시간 이상 업그레이드가 진행 중입니다.

+
이 고장을 해결하려면 업그레이드를 재개하거나 NetApp 지원에 지원을 문의하십시오.

* * 언발란시믹스노드 *
+
단일 노드는 스토리지 클러스터 용량의 3분의 1 이상을 차지합니다.

+
NetApp 지원 팀에 문의하십시오.

* * 무응답 서비스 *
+
시스템 서비스가 응답하지 않습니다.

+
NetApp 지원 팀에 문의하십시오.

* * virtualNetworkConfig *
+
이 클러스터 고장은 다음 상태 중 하나를 나타냅니다.

+
** 인터페이스가 없습니다.
** 인터페이스에 잘못된 네임스페이스가 있습니다.
** 잘못된 네트워크 마스크가 있습니다.
** 잘못된 IP 주소가 있습니다.
** 인터페이스가 실행되고 있지 않습니다.
** 노드에 불필요한 인터페이스가 있습니다. NetApp 지원 팀에 문의하십시오.


* * 볼륨이 저하됨 *
+
2차 볼륨이 아직 완전히 복제 및 동기화되지 않았습니다.

+
동기화가 완료되면 이 고장이 삭제됩니다.

+
고장이 지속될 경우 네트워크 연결 문제 및 하드웨어 오류를 확인하십시오.

* * volumesOffline *
+
스토리지 클러스터에 있는 하나 이상의 볼륨이 오프라인 상태입니다.

+
NetApp 지원 팀에 문의하십시오.





== 자세한 내용을 확인하십시오

* xref:reference_element_api_getclusterfullthreshold.adoc[GetClusterFullThreshold 를 참조하십시오]
* xref:reference_element_api_listclusterfaults.adoc[ListClusterFats]

