---
permalink: api/reference_element_api_clusterstats.html 
sidebar: sidebar 
keywords: objects,clusterStats 
summary: 클러스터 통계 개체에는 클러스터에 대한 통계 데이터가 포함되어 있습니다. 객체에 포함된 볼륨 관련 통계 중 다수는 클러스터의 모든 볼륨에 대해 평균화됩니다. GetClusterStats 메서드를 사용하여 클러스터에 대한 이 정보를 검색할 수 있습니다. 
---
= 클러스터 통계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 통계 개체에는 클러스터에 대한 통계 데이터가 포함되어 있습니다. 객체에 포함된 볼륨 관련 통계 중 다수는 클러스터의 모든 볼륨에 대해 평균화됩니다. GetClusterStats 메서드를 사용하여 클러스터에 대한 이 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 계산 | 유형 


 a| 
실제 IOPS
 a| 
지난 500밀리초 동안 전체 클러스터의 현재 실제 IOPS
 a| 
특정 시점
 a| 
정수



 a| 
averageIOPSize를 클릭합니다
 a| 
지난 500밀리초 동안 클러스터에 대한 최근 입출력의 평균 크기(바이트)입니다.
 a| 
특정 시점
 a| 
정수



 a| 
클라이언트 대기열 깊이
 a| 
클러스터에 대한 미해결 읽기 및 쓰기 작업 수입니다.
 a| 
해당 없음
 a| 
정수



 a| 
클러스터 활용률
 a| 
현재 사용되고 있는 클러스터의 최대 IOPS의 비율입니다. 이 값은 clusterUtilization=normalizedIOPS/maxIOPS(GetClusterCapacity에서)로 계산됩니다.
 a| 
해당 없음
 a| 
부동



 a| 
지연 시간 USec
 a| 
마지막 500밀리초 내에 클러스터에 대한 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다.
 a| 
특정 시점
 a| 
정수



 a| 
정규화 IOPS
 a| 
지난 500밀리초 동안 전체 클러스터의 평균 IOPS 수입니다.
 a| 
특정 시점
 a| 
정수



 a| 
읽기\바이트
 a| 
클러스터를 생성한 후 클러스터에서 읽은 총 누적 바이트 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
ReadBytesLastSample 을 참조하십시오
 a| 
마지막 샘플 기간 동안 클러스터에서 읽은 총 바이트 수입니다.
 a| 
특정 시점
 a| 
정수



 a| 
readLatencyUSec을 참조하십시오
 a| 
마지막 500밀리초 내에 클러스터에 대한 읽기 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다.
 a| 
특정 시점
 a| 
정수



 a| 
ReadLatencyUSecTotal 을 참조하십시오
 a| 
클러스터를 생성한 후 읽기 작업을 수행하는 데 소요된 총 시간입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
readOps를 참조하십시오
 a| 
클러스터를 생성한 후 클러스터에 대한 총 누적 읽기 작업 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
ReadOpsLastSample 을 참조하십시오
 a| 
마지막 샘플 기간 동안의 총 읽기 작업 수입니다.
 a| 
특정 시점
 a| 
정수



 a| 
SamplePeriodMSec
 a| 
샘플 기간의 길이(밀리초).
 a| 
해당 없음
 a| 
정수



 a| 
서비스 수
 a| 
클러스터에서 실행 중인 서비스 수입니다. servicesTotal과 같을 경우 모든 노드에서 유효한 통계가 수집되었음을 나타냅니다.
 a| 
특정 시점
 a| 
정수



 a| 
서비스합계
 a| 
클러스터에서 실행 중인 총 예상 서비스 수입니다.
 a| 
해당 없음
 a| 
정수



 a| 
타임 스탬프입니다
 a| 
UTC + 0 형식의 현재 시간입니다.
 a| 
해당 없음
 a| 
ISO 8601 날짜 문자열



 a| 
unalignedReads입니다
 a| 
클러스터가 생성된 후 클러스터에 대한 정렬되지 않은 총 읽기 작업입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
UnalignedWrites를 참조하십시오
 a| 
클러스터가 생성된 후 클러스터에 대한 정렬되지 않은 총 쓰기 작업 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
쓰기 바이트
 a| 
클러스터를 생성한 후 클러스터에 기록된 총 누적 바이트 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
WriteBytesLastSample 을 참조하십시오
 a| 
마지막 샘플 기간 동안 클러스터에 기록된 총 바이트 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
writeLatencyUSec입니다
 a| 
마지막 500밀리초 내에 클러스터에 대한 쓰기 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다.
 a| 
특정 시점
 a| 
정수



 a| 
쓰기 LatencyUSecTotal
 a| 
클러스터를 생성한 후 쓰기 작업을 수행하는 데 소요된 총 시간입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
쓰기 작업
 a| 
클러스터를 생성한 후 클러스터에 대한 총 누적 쓰기 작업 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
WriteOpsLastSample 을 참조하십시오
 a| 
마지막 샘플 기간 동안의 총 쓰기 작업 수입니다.
 a| 
특정 시점
 a| 
정수

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_getclusterstats.adoc[GetClusterStats 를 참조하십시오]
