---
permalink: api/reference_element_api_creategroupsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,snapshot,snapshots,CreateGroupSnapshot,group,create,creating 
summary: CreateGroupSnapshot 을 사용하여 볼륨 그룹의 시점 복사본을 만들 수 있습니다. 
---
= CreateGroupSnapshot 을 클릭합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
CreateGroupSnapshot을 사용하여 볼륨 그룹의 시점 복사본을 만들 수 있습니다.

나중에 이 스냅샷을 백업 또는 롤백으로 사용하여 볼륨 그룹의 데이터가 스냅샷을 생성한 시점의 정합성이 보장되도록 할 수 있습니다.

* cluster_fullness * 를 선택합니다


NOTE: 클러스터 충만도가 1단계, 2단계 또는 3단계에 있는 경우 스냅샷을 생성할 수 있습니다. 클러스터 충만도가 4단계 또는 5단계에 도달하면 스냅샷을 생성할 수 없습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
'속성'
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
enableRemoteReplication
 a| 
스냅샷을 원격 스토리지에 복제할지 여부를 지정합니다. 가능한 값:

* "참": 스냅샷이 원격 스토리지에 복제됩니다.
* "거짓": 스냅샷은 원격 스토리지에 복제되지 않습니다.

 a| 
부울
 a| 
거짓
 a| 
아니요



| 엔수에SerialCreation  a| 
이전 스냅샷 복제가 진행 중인 경우 스냅샷을 생성하지 않도록 지정합니다. 가능한 값은 다음과 같습니다.

* "참": 이는 한 번에 하나의 스냅샷만 복제되도록 합니다. 이전 스냅샷 복제가 아직 진행 중인 경우 새 스냅샷 생성이 실패합니다.
* 거짓: 기본값. 다른 스냅샷 복제가 아직 진행 중인 경우 이 스냅샷 생성이 허용됩니다.

| 부울 | 거짓입니다 | 아니요 


 a| 
만료를 위한 시간
 a| 
스냅샷을 제거할 수 있는 시간을 지정합니다. '연장'과 함께 사용할 수 없습니다. 만료 시간 또는 보존 중 어느 것도 지정하지 않으면 스냅샷이 만료되지 않습니다. 시간 형식은 시간 기반 만료에 대한 ISO 8601 날짜 문자열이며, 그렇지 않으면 만료되지 않습니다. 값이 "null"이면 스냅샷이 영구적으로 보존됩니다. 'fifo' 값을 사용하면 볼륨의 다른 FIFO 스냅숏과 비교하여 선입선출(FIFO) 기준으로 스냅샷이 보존됩니다. 사용할 수 있는 FIFO 공간이 없으면 API가 실패합니다.
 a| 
ISO 8601 날짜 문자열
 a| 
없음
 a| 
아니요



 a| 
이름
 a| 
그룹 스냅샷의 이름입니다. 이름을 입력하지 않으면 그룹 스냅샷이 생성된 날짜 및 시간이 사용됩니다. 허용되는 최대 이름 길이는 255자입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
'연장'
 a| 
시간 형식이 HH:MM:ss인 점을 제외하고 이 매개 변수는 'expirationTime' 매개 변수와 동일합니다. 만료 시간 또는 재연이 지정되지 않으면 스냅샷이 만료되지 않습니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
'스냅샷 레이블'
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트에 대한 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
'볼륨'
 a| 
복사할 볼륨 이미지의 고유 ID입니다.
 a| 
볼륨 ID 스토리지
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
구성원
 a| 
그룹의 각 구성원에 대한 체크섬, 볼륨 ID 및 스냅샷 ID 목록입니다. 유효한 값:

* 체크섬: 저장된 스냅샷에 있는 데이터의 작은 문자열 표현입니다. 이 체크섬은 나중에 다른 스냅샷을 비교하여 데이터의 오류를 감지하는 데 사용할 수 있습니다. (문자열)
* snapshotID: 새 스냅샷이 생성된 스냅샷의 고유 ID입니다. snapshotID는 지정된 볼륨의 스냅숏에서 가져온 것이어야 합니다. (정수)
* volumeID: 스냅샷의 소스 볼륨 ID입니다. (정수)

 a| 
JSON 개체 어레이



 a| 
groupSnapshotID입니다
 a| 
새 그룹 스냅샷의 고유 ID입니다.
 a| 
그룹 스냅샷 ID입니다



 a| 
그룹 스냅샷
 a| 
새로 생성된 그룹 스냅샷에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_groupsnapshot.adoc[그룹 스냅샷]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "CreateGroupSnapshot",
   "params": {
      "volumes": [1,2]
   },
   "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-04T22:43:29Z",
      "groupSnapshotID": 45,
      "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3323,
          "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
          "status": "done",
          "totalSize": 5000658944,
          "virtualVolumeID": null,
          "volumeID": 1
        },
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3324,
          "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
          "status": "done",
          "totalSize": 6001000448,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "2016-04-04T22:43:29Z",
      "status": "done"
    },
    "groupSnapshotID": 45,
    "members": [
      {
        "checksum": "0x0",
        "snapshotID": 3323,
        "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
        "volumeID": 1
      },
      {
        "checksum": "0x0",
        "snapshotID": 3324,
        "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
        "volumeID": 2
      }
    ]
  }
}
----


== 버전 이후 새로운 기능

9.6
