---
permalink: api/reference_element_api_syncjob.html 
sidebar: sidebar 
keywords: object,objects,syncjob 
summary: syncJob 개체에는 클러스터에서 실행 중인 클론, 원격 복제 또는 슬라이스 동기화 작업에 대한 정보가 들어 있습니다. 
---
= 동기화 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
syncJob 개체에는 클러스터에서 실행 중인 클론, 원격 복제 또는 슬라이스 동기화 작업에 대한 정보가 들어 있습니다.

'ListSyncJobs' API 메소드를 사용하여 동기화 정보를 조회할 수 있다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
BlocksPerSecond
 a| 
소스 클러스터에서 타겟 클러스터로 전송되는 초당 데이터 블록 수입니다. 형식 멤버가 remote 로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
분기 유형
 a| 
원격 복제 동기화 작업에 대해서만 반환됩니다. 가능한 값:

* 스냅샷
* 볼륨

 a| 
문자열



 a| 
바이테페르세컨드
 a| 
클론이 초당 처리하는 바이트 수입니다. 유형 구성원이 클론 또는 슬라이스로 설정된 경우에만 표시됩니다.
 a| 
부동



 a| 
cloneid(클론 ID)
 a| 
진행 중인 클론 작업의 식별자입니다. 형식 구성원이 클론으로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
currentBytes를 나타냅니다
 a| 
클론이 소스 볼륨에서 처리한 바이트 수입니다. 유형 구성원이 클론 또는 슬라이스로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
dstServiceID입니다
 a| 
볼륨의 기본 복제본을 호스팅하는 서비스 식별자입니다. 형식 멤버가 remote 로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
dstVolumeID
 a| 
대상 볼륨 ID입니다. 형식 구성원이 클론 또는 원격 으로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
경과 시간
 a| 
동기화 작업이 시작된 이후 경과된 시간(초)입니다.
 a| 
동기화 작업 유형에 따라 부동 또는 정수



 a| 
그룹 CloneID입니다
 a| 
진행 중인 그룹 클론 작업의 ID입니다.
 a| 
정수



 a| 
노드 ID입니다
 a| 
클론이 발생하는 노드를 지정합니다. 형식 구성원이 클론으로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
완료입니다
 a| 
동기화 작업 완료율입니다.
 a| 
동기화 작업 유형에 따라 부동 또는 정수



 a| 
남은 시간
 a| 
작업을 완료하는 데 필요한 예상 시간(초)입니다.
 a| 
부동



 a| 
슬라이스 ID
 a| 
동기화되는 슬라이스 드라이브의 ID입니다.
 a| 
정수



 a| 
단계
 a| 
형식 구성원이 원격 또는 클론으로 설정된 경우에만 표시됩니다. 가능한 값:

* 메타데이터: 복제는 원격 클러스터로 전송해야 하는 데이터를 결정하는 프로세스입니다. 이 복제 프로세스 단계에 대한 상태가 보고되지 않습니다.
* 데이터: 복제는 대량의 데이터를 원격 클러스터로 전송하는 중입니다.
* Whole(전체): 슬라이스 동기화 작업에 대한 슬라이스의 역호환성을 나타냅니다.

 a| 
문자열



 a| 
스냅샷 ID입니다
 a| 
클론이 생성된 스냅샷의 ID입니다. 형식 구성원이 클론으로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
srcServiceID입니다
 a| 
소스 서비스 ID입니다.
 a| 
정수



 a| 
srcVolumeID
 a| 
소스 볼륨 ID입니다.
 a| 
정수



 a| 
TotalBytes를 나타냅니다
 a| 
클론의 총 바이트 수입니다. 유형 구성원이 클론 또는 슬라이스로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
유형
 a| 
동기화 작업의 유형입니다. 가능한 값:

* 복제
* Slice(슬라이스)
* 블록
* 원격

 a| 
문자열

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs 를 선택합니다]
