---
permalink: api/reference_element_api_createvolume.html 
sidebar: sidebar 
keywords: create,volume,volumes,creating,CreateVolume 
summary: CreateVolume 메서드를 사용하여 클러스터에 빈 새 볼륨을 만들 수 있습니다. 볼륨 생성이 완료되면 iSCSI를 통해 볼륨을 연결할 수 있습니다. 
---
= CreateVolume(생성 볼륨)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"CreateVolume" 방법을 사용하여 클러스터에 빈 새 볼륨을 생성할 수 있습니다. 볼륨이 생성되는 즉시 iSCSI를 통해 볼륨을 연결할 수 있습니다.

지정된 QoS 값 없이 생성된 볼륨은 기본값을 사용합니다. 'GetDefaultQoS' 메서드를 사용하여 볼륨의 기본값을 볼 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


| "접근" | 볼륨에 대한 액세스 모드입니다. 이 매개 변수가 포함되면 지원되는 유일한 값은 'napMirrorTarget'입니다. | 문자열 | 없음 | 아니요 


| 계정 ID | 이 볼륨을 소유한 계정의 ID입니다. | 정수 | 없음 | 예 


| 'associateWithQoSPolicy'  a| 
볼륨을 지정된 QoS 정책에 연결합니다. 가능한 값:

* "true": QoSPolicyID 매개 변수에 지정된 QoS 정책과 볼륨을 연결합니다.
* "false": QoSPolicyID 매개 변수에 지정된 QoS 정책과 볼륨을 연결하지 마십시오. false 이면 QoSPolicy 매개 변수에 QoS 정책을 지정했는지 여부에 관계없이 기존 정책 연결이 제거됩니다.

| 부울 | 참 | 아니요 


| '속성' | JSON 개체 형식의 이름-값 쌍 목록입니다. JSON 형식 문자를 포함하여 총 속성 크기는 1000B 또는 1KB 미만이어야 합니다. | JSON 개체 | 없음 | 아니요 


| enable512e  a| 
512바이트 섹터 에뮬레이션을 활성화합니다. 가능한 값:

* "참": 볼륨이 512바이트 섹터 에뮬레이션을 제공합니다.
* "거짓": 512e 에뮬레이션이 활성화되지 않았습니다.

| 부울 | 없음 | 예 


| "enableSnapMirrorReplication"을 참조하십시오  a| 
SnapMirror 엔드포인트에서 복제를 위해 볼륨을 사용할 수 있는지 여부를 결정합니다. 가능한 값:

* "참"입니다
* 거짓입니다

| 부울 | 거짓 | 아니요 


| 'fifoSize'입니다 | 볼륨이 지원하는 FIFO(First In First Out) 스냅샷의 최대 수를 지정합니다. FIFO 및 FIFO 외 스냅샷은 모두 볼륨에서 사용 가능한 스냅샷 슬롯의 동일한 풀을 사용합니다. 이 옵션을 사용하여 사용 가능한 스냅샷 슬롯의 FIFO 스냅샷 소비를 제한할 수 있습니다. 이 인수를 생략하면 기본적으로 24가 사용됩니다. | 정수 | 24 | 아니요 


| '민차피오사이즈' | 볼륨이 예약한 FIFO(First In First Out) 스냅샷 슬롯의 최소 수를 지정합니다. 이렇게 하면 FIFO 스냅샷이 아닌 볼륨에서 FIFO 스냅샷과 FIFO 외 스냅샷을 모두 사용할 경우 FIFO 슬롯이 너무 많이 사용되지 않습니다. 또한 적어도 여러 FIFO 스냅샷을 항상 사용할 수 있도록 합니다. FIFO와 FIFO 이외 스냅샷은 동일한 풀을 공유하기 때문에, 'min다섯obsize'는 FIFO가 아닌 스냅샷의 총 수를 동일한 양으로 줄입니다. 이 인수를 생략하면 기본적으로 0이 됩니다. | 정수 | 0 | 아니요 


| 이름 | 볼륨 액세스 그룹의 이름입니다(사용자가 지정할 수 있음). 고유하지 않아도 되지만 권장됨. 길이는 1-64자여야 합니다. | 문자열 | 없음 | 예 


| QoS  a| 
이 볼륨에 대한 초기 서비스 품질 설정. 기본값이 지정되지 않은 경우 사용됩니다. 가능한 값:

* minIOPS
* 'maxIOPS'입니다
* 버스트IOPS

| QoS 개체 | 없음 | 아니요 


| "qosPolicyID"입니다 | QoS 설정을 지정된 볼륨에 적용해야 하는 정책의 ID입니다. QoS 파라미터와 함께 사용할 수 없는 파라미터이다. | 정수 | 없음 | 아니요 


| "TotalSize"입니다 | 볼륨의 총 크기(바이트)입니다. 크기는 가장 가까운 메가바이트 단위로 반올림됩니다. | 정수 | 없음 | 예 
|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
볼륨
 a| 
새로 생성된 볼륨에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_volume.adoc[볼륨]



 a| 
볼륨 ID
 a| 
새로 생성된 볼륨의 볼륨 ID입니다.
 a| 
정수



 a| 
곡선
 a| 
곡선은 키 값 쌍의 집합입니다. 키는 입출력 크기(바이트)입니다. 이 값은 특정 입출력 크기에서 IOP를 수행하는 비용을 나타냅니다. 곡선은 100 IOPS로 설정된 4096바이트 작업을 기준으로 계산됩니다.
 a| 
JSON 개체

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "CreateVolume",
   "params": {
      "name": "mysqldata",
      "accountID": 1,
      "totalSize": 107374182400,
      "enable512e": false,
      "attributes": {
         "name1": "value1",
         "name2": "value2",
         "name3": "value3"
      },
      "qos": {
         "minIOPS": 50,
         "maxIOPS": 500,
         "burstIOPS": 1500,
         "burstTime": 60
      }
   },
   "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
    "id": 1,
    "result": {
        "curve": {
            "4096": 100,
            "8192": 160,
            "16384": 270,
            "32768": 500,
            "65536": 1000,
            "131072": 1950,
            "262144": 3900,
            "524288": 7600,
            "1048576": 15000
        },
        "volume": {
            "access": "readWrite",
            "accountID": 1,
            "attributes": {
                "name1": "value1",
                "name2": "value2",
                "name3": "value3"
            },
            "blockSize": 4096,
            "createTime": "2016-03-31T22:20:22Z",
            "deleteTime": "",
            "enable512e": false,
            "iqn": "iqn.2010-01.com.solidfire:mysqldata.677",
            "name": "mysqldata",
            "purgeTime": "",
            "qos": {
                "burstIOPS": 1500,
                "burstTime": 60,
                "curve": {
                    "4096": 100,
                    "8192": 160,
                    "16384": 270,
                    "32768": 500,
                    "65536": 1000,
                    "131072": 1950,
                    "262144": 3900,
                    "524288": 7600,
                    "1048576": 15000
                },
                "maxIOPS": 500,
                "minIOPS": 50
            },
            "scsiEUIDeviceID": "6a796179000002a5f47acc0100000000",
            "scsiNAADeviceID": "6f47acc1000000006a796179000002a5",
            "sliceCount": 0,
            "status": "active",
            "totalSize": 107374182400,
            "virtualVolumeID": null,
            "volumeAccessGroups": [],
            "volumeID": 677,
            "volumePairs": []
        },
        "volumeID": 677
    }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS를 참조하십시오]
