---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: ListAuthSessionsByUsername 메서드를 사용하여 지정된 사용자에 대한 모든 인증 세션을 나열할 수 있습니다. AccessGroup ClusterAdmins/Administrator 권한이 없는 호출자는 자신의 세션만 나열할 수 있습니다. ClusterAdmins/Administrator 권한이 있는 호출자는 모든 사용자에 속하는 세션을 나열할 수 있습니다. 
---
= ListAuthSessionsByUsername입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
"ListAuthSessionsByUsername" 메서드를 사용하여 지정된 사용자에 대한 모든 인증 세션을 나열할 수 있습니다. AccessGroup ClusterAdmins/Administrator 권한이 없는 호출자는 자신의 세션만 나열할 수 있습니다. ClusterAdmins/Administrator 권한이 있는 호출자는 모든 사용자에 속하는 세션을 나열할 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
AuthMethod
 a| 
나열되는 사용자 세션의 인증 방법입니다. ClusterAdmins/Administrator AccessGroup의 호출자만 이 매개 변수를 제공할 수 있습니다. 가능한 값은 다음과 같습니다.

* * AuthMethod = Cluster * 는 ClusterAdmin 사용자 이름을 지정합니다.
* * AuthMethod = LDAP * 는 사용자의 LDAP DN을 지정합니다.
* * AuthMethod = IDP * 는 사용자의 IDP UUID 또는 NameID를 지정합니다. IDP가 두 옵션을 반환하도록 구성되지 않은 경우 세션이 생성될 때 발급된 임의 UUID를 지정합니다.

 a| 
AuthMethod
 a| 
없음
 a| 
예



 a| 
사용자 이름
 a| 
사용자의 고유 식별자입니다.
 a| 
문자열
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
세션
 a| 
인증 세션에 대한 세션 정보 목록입니다.
 a| 
link:reference_element_api_authsessioninfo.md#GUID-FF0CE38C-8F99-4F23-8A6F-F6EA4487E808["AuthSessionInfo 를 참조하십시오"]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== 버전 이후 새로운 기능

12.0
