---
permalink: api/reference_element_api_enablemaintenancemode.html 
sidebar: sidebar 
keywords: maintenance,enable,mode 
summary: EnableMaintenanceMode 메서드를 사용하여 유지 관리를 위한 스토리지 노드를 준비할 수 있습니다. 유지보수 시나리오에는 노드의 전원을 끄거나 다시 시작해야 하는 작업이 포함됩니다. 
---
= Enable유지보수모드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"EnableMaintenanceMode" 메서드를 사용하여 유지 관리를 위한 스토리지 노드를 준비할 수 있습니다. 유지보수 시나리오에는 노드의 전원을 끄거나 다시 시작해야 하는 작업이 포함됩니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
포세WithUnresolvedFats
 a| 
클러스터 장애 차단이 있는 경우에도 이 노드에 대해 유지 관리 모드를 강제로 사용하도록 설정합니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
노드
 a| 
유지보수 모드로 전환할 노드 ID 목록입니다. 한 번에 하나의 노드만 지원됩니다.
 a| 
정수 배열
 a| 
없음
 a| 
예



 a| 
PerMinutePrimarySwapLimit
 a| 
분당 스왑할 기본 슬라이스의 수입니다. 지정하지 않으면 모든 기본 슬라이스가 한 번에 스왑됩니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
시간 초과
 a| 
유지 관리 모드가 자동으로 비활성화되기 전까지 활성화 상태를 유지할 기간을 지정합니다. 시간 문자열 형식(예: HH:MM:ss)입니다. 지정하지 않으면 명시적으로 비활성화될 때까지 유지 관리 모드가 활성 상태로 유지됩니다.
 a| 
문자열
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
asyncHandle
 a| 
GetAsyncResult 메서드를 사용하여 이 asyncHandle 을 검색하고 유지 관리 모드 전환이 완료되는 시기를 결정할 수 있습니다.
 a| 
정수



 a| 
CurrentMode(현재 모드)
 a| 
노드의 현재 유지보수 모드 상태입니다. 가능한 값:

* Disabled(비활성화): 요청된 유지 관리가 없습니다.
* FailedToRecover: 노드가 유지보수 모드에서 복구되지 못했습니다.
* RecoveringFromMaintenance: 노드가 유지보수 모드에서 복구 중입니다.
* PreparingForMaintenance: 유지 관리를 수행할 노드를 준비하기 위한 작업이 수행됩니다.
* ReadyForMaintenance: 노드를 유지 관리할 준비가 되었습니다.

 a| 
유지 관리 모드(문자열)



 a| 
requestedMode를 선택합니다
 a| 
요청된 노드의 유지보수 모드 상태입니다. 가능한 값:

* Disabled(비활성화): 요청된 유지 관리가 없습니다.
* FailedToRecover: 노드가 유지보수 모드에서 복구되지 못했습니다.
* RecoveringFromMaintenance: 노드가 유지보수 모드에서 복구 중입니다.
* PreparingForMaintenance: 유지 관리를 수행할 노드를 준비하기 위한 작업이 수행됩니다.
* ReadyForMaintenance: 노드를 유지 관리할 준비가 되었습니다.

 a| 
유지 관리 모드(문자열)

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "method": "EnableMaintenanceMode",
  "params": {
    "forceWithUnresolvedFaults": False,
    "nodes": [6],
    "perMinutePrimarySwapLimit" : 40,
    "timeout" : "01:00:05"
  },
"id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "ReadyForMaintenance",
        "asyncHandle": 1,
        "currentMode": "Disabled"
    }
}
----


== 버전 이후 새로운 기능

12.2



== 자세한 내용을 확인하십시오

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["NetApp HCI 스토리지 유지보수 모드의 개념"^]
