---
permalink: api/reference_element_api_startbulkvolumeread.html 
sidebar: sidebar 
keywords: volume,read,session,start,starting,bulk,startbulkvolumeread 
summary: StartBulkVolumeRead 메서드를 사용하여 지정된 볼륨에서 대량 볼륨 읽기 세션을 시작할 수 있습니다. 
---
= StartBulkVolumeRead
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'stBulkVolumeRead' 방법을 사용하여 지정된 볼륨에서 대량 볼륨 읽기 세션을 시작할 수 있습니다.

하나의 볼륨에서 2개의 대량 볼륨 프로세스만 동시에 실행할 수 있습니다. 세션을 초기화하면 외부 백업 소스에 저장할 SolidFire 스토리지 볼륨에서 데이터가 읽힙니다. 외부 데이터는 Element 스토리지 노드에서 실행되는 웹 서버에서 액세스합니다. 외부 데이터 액세스에 대한 서버 상호 작용 정보는 스토리지 시스템에서 실행되는 스크립트를 통해 전달됩니다.

대량 볼륨 읽기 작업이 시작되면 볼륨의 스냅샷이 작성되고 읽기가 완료되면 스냅샷이 삭제됩니다. 스냅샷의 ID를 매개 변수로 입력하여 볼륨의 스냅샷을 읽을 수도 있습니다. 이전 스냅샷을 읽는 경우 시스템은 볼륨의 새 스냅샷을 생성하지 않으며 읽기 완료 시 이전 스냅샷을 삭제하지 않습니다.


NOTE: 이 프로세스는 기존 스냅샷의 ID가 제공되지 않은 경우 새 스냅샷을 생성합니다. 클러스터 충만도가 2단계 또는 3단계에 있는 경우 스냅샷을 생성할 수 있습니다. 클러스터 충만도가 4 또는 5단계에 있으면 스냅샷이 생성되지 않습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
형식
 a| 
볼륨 데이터의 형식입니다. 다음 중 하나일 수 있습니다.

* '비압축': 볼륨의 모든 바이트는 압축 없이 반환됩니다.
* '네이티브': 불투명한 데이터가 반환되어 더 작고 더 효율적으로 저장되며 이후의 대량 볼륨 쓰기에 기록됩니다.

 a| 
문자열
 a| 
없음
 a| 
예



 a| 
볼륨 ID
 a| 
읽을 볼륨의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
스냅샷 ID입니다
 a| 
대량 볼륨 읽기에 사용된 이전에 생성된 스냅샷의 ID입니다. ID를 입력하지 않으면 현재 활성 볼륨 이미지의 스냅샷이 생성됩니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
스크립트
 a| 
실행 스크립트의 이름입니다. 스크립트 이름을 제공하지 않으면 Element 스토리지 노드를 액세스하는 데 키와 URL이 필요합니다. 스크립트는 기본 노드에서 실행되며 로컬 웹 서버에 연결할 수 있도록 키와 URL이 스크립트에 반환됩니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
스크립트 매개변수
 a| 
스크립트에 전달할 JSON 매개 변수입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다. link:reference_element_api_attributes.html["자세한 정보"].
 a| 
JSON 개체
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
asyncHandle
 a| 
완료 여부를 확인할 비동기 프로세스의 ID입니다.
 a| 
정수



 a| 
키
 a| 
불투명 키는 세션을 고유하게 식별합니다.
 a| 
문자열



 a| 
URL
 a| 
노드의 웹 서버에 액세스하는 URL입니다.
 a| 
문자열

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "StartBulkVolumeRead",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
      "snapshotID" : 2
   },
   "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
      "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== 버전 이후 새로운 기능

9.6
