---
permalink: api/reference_element_api_clonemultiplevolumes.html 
sidebar: sidebar 
keywords: volume,volumes,clone,cloning,multiple,CloneMultipleVolumes 
summary: CloneMultipleVolumes 메서드를 사용하여 지정된 볼륨 그룹의 클론을 생성할 수 있습니다. 여러 볼륨의 클론을 함께 생성할 때 일관성 있는 특성 세트를 여러 볼륨의 그룹에 할당할 수 있습니다. 
---
= CloneMultipleVolumes
:icons: font
:imagesdir: ../media/


[role="lead"]
"CloneMultipleVolumes" 방법을 사용하여 지정된 볼륨 그룹의 클론을 생성할 수 있습니다. 여러 볼륨의 클론을 함께 생성할 때 일관성 있는 특성 세트를 여러 볼륨의 그룹에 할당할 수 있습니다.

groupSnapshotID 매개 변수를 사용하여 그룹 스냅샷의 볼륨을 클론 복제하기 전에 먼저 을 사용하여 그룹 스냅샷을 생성해야 합니다 xref:reference_element_api_creategroupsnapshot.adoc[CreateGroupSnapshot 을 클릭합니다] API 메소드 또는 웹 UI. 여러 볼륨을 클론 생성할 때는 groupSnapshotID를 사용하는 것이 선택 사항입니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
액세스
 a| 
볼륨의 배열에 전달된 정보에 의해 재정의되지 않은 경우 새 볼륨에 대한 새로운 기본 액세스 방법입니다.
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
enableSnapMirrorReplication
 a| 
SnapMirror 엔드포인트에서 복제를 위해 볼륨을 사용할 수 있는지 여부를 결정합니다. 가능한 값:

* 참
* 거짓

 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
groupSnapshotID입니다
 a| 
클론의 기반으로 사용할 그룹 스냅샷의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
새 계정 ID
 a| 
볼륨 배열에 전달된 정보에 의해 재정의되지 않은 경우 볼륨에 대한 새 계정 ID입니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
볼륨
 a| 
새 볼륨에 대해 지정하는 구성원의 컬렉션입니다. 구성원:

* 볼륨 ID: (필수)
* 액세스: (선택 사항) ReadOnly , ReadWrite , Locked 또는 ReplicationTarget 중 하나일 수 있습니다.
* 특성: (선택 사항) JSON 개체 형식의 이름 값 쌍 목록입니다.
* 이름: (선택 사항) 클론의 새 이름입니다.
* newAccountID: (선택 사항) 새 볼륨의 계정 ID입니다.
* newSize: (선택 사항) 볼륨의 총 크기(바이트)입니다. 크기는 가장 가까운 메가바이트 단위로 반올림됩니다.


선택적 멤버를 지정하지 않으면 소스 볼륨에서 값이 상속됩니다.
 a| 
JSON 개체 어레이
 a| 
없음
 a| 
예(볼륨 ID)

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
asyncHandle
 a| 
비동기 메서드 호출에서 반환된 값입니다.
 a| 
정수



 a| 
그룹 CloneID입니다
 a| 
새 그룹 클론의 고유 ID입니다.
 a| 
정수



 a| 
구성원
 a| 
소스 및 대상 볼륨 쌍의 볼륨 ID 목록입니다.
 a| 
JSON 개체 어레이

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "CloneMultipleVolumes",
   "params": {
       "volumes": [
           {
              "volumeID": 5
              "name":"foxhill",
              "access":"readOnly"
              },
           {
              "volumeID": 18
              },
           {
             "volumeID": 20
              }
     ]
   },
   "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "asyncHandle": 12,
    "groupCloneID": 4,
    "members": [
     {
      "srcVolumeID": 5,
      "volumeID": 29
     },
     {
      "srcVolumeID": 18,
      "volumeID": 30
     },
     {
      "srcVolumeID": 20,
      "volumeID": 31
      }
    ]
  }
}
----


== 버전 이후 새로운 기능

9.6
