---
permalink: api/reference_element_api_getclustercapacity.html 
sidebar: sidebar 
keywords: cluster,capacity,getting,get,measurements,measure,deduplication,GetClusterCapacity 
summary: GetClusterCapacity 를 사용하면 전체 스토리지 클러스터에 대해 높은 수준의 용량 측정을 반환할 수 있습니다. 이 메서드는 Element 웹 UI에 표시된 효율성 비율을 계산하는 데 사용할 수 있는 필드를 반환합니다. 스크립트의 효율성 계산을 사용하여 씬 프로비저닝, 중복제거, 압축 및 전체 효율성에 대한 효율성 비율을 반환할 수 있습니다. 
---
= GetClusterCapacity 를 선택합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'GetClusterCapacity'를 사용하면 전체 스토리지 클러스터에 대해 높은 수준의 용량 측정을 반환할 수 있습니다. 이 메서드는 Element 웹 UI에 표시된 효율성 비율을 계산하는 데 사용할 수 있는 필드를 반환합니다. 스크립트의 효율성 계산을 사용하여 씬 프로비저닝, 중복제거, 압축 및 전체 효율성에 대한 효율성 비율을 반환할 수 있습니다.



== 효율성 계산

다음 수식을 사용하여 씬 프로비저닝, 중복 제거 및 압축을 계산합니다. 이러한 수식은 Element 8.2 이상에 적용됩니다.

* thinProvisioningFactor=(ZeroBlocks + zeroBlocks)/nonZeroBlocks
* DeDuplicationFactor = (ZeroBlocks + snapshotNonZeroBlocks)/uniqueBlocks
* 압축 계수 = (uniqueBlock * 4096) / (uniqueBlocksUsedSpace * 0.93)




== 전체 효율성 비율 계산

다음 수식을 사용하여 씬 프로비저닝, 중복제거 및 압축 효율성 계산의 결과를 사용하여 전체 클러스터 효율성을 계산합니다.

* efficiencyFactor = thinProvisioningFactor * deDuplicationFactor * 압축 계수




== 매개 변수

이 메서드에는 입력 매개 변수가 없습니다.



== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
클러스터 용량
 a| 
스토리지 클러스터의 용량 측정입니다.
 a| 
xref:reference_element_api_clustercapacity.adoc[클러스터 용량]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "GetClusterCapacity",
   "params": {},
   "id" : 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "clusterCapacity": {
      "activeBlockSpace": 236015557096,
      "activeSessions": 20,
      "averageIOPS": 0,
      "clusterRecentIOSize": 0,
      "currentIOPS": 0,
      "maxIOPS": 150000,
      "maxOverProvisionableSpace": 259189767127040,
      "maxProvisionedSpace": 51837953425408,
      "maxUsedMetadataSpace": 404984011161,
      "maxUsedSpace": 12002762096640,
      "nonZeroBlocks": 310080350,
      "peakActiveSessions": 20,
      "peakIOPS": 0,
      "provisionedSpace": 1357931085824,
      "snapshotNonZeroBlocks": 0,
      "timestamp": "2016-10-17T21:24:36Z",
      "totalOps": 1027407650,
      "uniqueBlocks": 108180156,
      "uniqueBlocksUsedSpace": 244572686901,
      "usedMetadataSpace": 8745762816,
      "usedMetadataSpaceInSnapshots": 8745762816,
      "usedSpace": 244572686901,
      "zeroBlocks": 352971938
    }
  }
}
----


== 버전 이후 새로운 기능

9.6
