---
permalink: api/reference_element_api_modifyvolumeaccessgrouplunassignments.html 
sidebar: sidebar 
keywords: volumes,volume,defining,define,modify,modifying,edit,editing,change,changing,modifyvolumeaccessgrouplunassignments,access,group,lun,assignment 
summary: ModifyVolumeAccessGroupLunAssignments 메서드를 사용하여 특정 볼륨에 대한 사용자 지정 LUN 할당을 정의할 수 있습니다. 
---
= ModifyVolumeAccessGroupLunAssignments 를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ModifyVolumeAccessGroupLunAssignments 메서드를 사용하여 특정 볼륨에 대한 사용자 지정 LUN 할당을 정의할 수 있습니다.

이 방법은 볼륨 액세스 그룹의 lunAssignments 매개변수에 설정된 LUN 값만 변경합니다. 다른 모든 LUN 할당은 변경되지 않습니다.

LUN 할당 값은 볼륨 액세스 그룹의 볼륨에 대해 고유해야 합니다. 볼륨 액세스 그룹 내에서는 중복 LUN 값을 정의할 수 없습니다. 하지만 다른 볼륨 액세스 그룹에서 동일한 LUN 값을 다시 사용할 수 있습니다.


NOTE: 유효한 LUN 값은 0 - 16383입니다. 이 범위를 벗어나는 LUN 값을 전달하는 경우 시스템에서 예외가 생성됩니다. 예외가 있을 경우 지정된 LUN 할당이 수정되지 않습니다.

주의:

활성 I/O가 있는 볼륨의 LUN 할당을 변경하는 경우 I/O를 중단할 수 있습니다. 볼륨 LUN 할당을 변경하기 전에 서버 구성을 변경해야 합니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
볼륨 액세스 그룹 ID입니다
 a| 
LUN 할당을 수정할 고유한 볼륨 액세스 그룹 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
점심 배정
 a| 
할당된 새 LUN 값이 있는 볼륨 ID입니다.
 a| 
정수 배열
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
볼륨 그룹 루네팅
 a| 
수정된 볼륨 액세스 그룹 LUN 할당의 세부 정보가 포함된 객체입니다.
 a| 
JSON 개체

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "ModifyVolumeAccessGroupLunAssignments",
   "params": {
       "volumeAccessGroupID" : 218,
       "lunAssignments" : [
           {"volumeID" : 832, "lun" : 0},
           {"volumeID" : 834, "lun" : 1}
        ]
    },
    "id" : 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroupLunAssignments": {
      "deletedLunAssignments": [],
      "lunAssignments": [
        {
          "lun": 0,
          "volumeID": 832
        },
        {
          "lun": 1,
          "volumeID": 834
        }
      ],
      "volumeAccessGroupID": 218
    }
  }
}
----


== 버전 이후 새로운 기능

9.6
