---
permalink: api/reference_element_api_createinitiators.html 
sidebar: sidebar 
keywords: create,creating,initiator,CreateInitiators,WWPN,IQN,initiators 
summary: 'CreateInitiators 를 사용하여 여러 개의 새 이니시에이터 IQN 또는 WWPN(World Wide Port Name\)을 생성하고 선택적으로 별칭 및 속성을 할당할 수 있습니다. CreateInitiators 를 사용하여 새 이니시에이터를 생성할 때 볼륨 액세스 그룹에 추가할 수도 있습니다.' 
---
= CreateInitiators(초기자)
:icons: font
:imagesdir: ../media/


[role="lead"]
'CreateInitiators'를 사용하여 여러 개의 새 이니시에이터 IQN 또는 WWPN(World Wide Port Name)을 생성하고 별칭 및 속성을 선택적으로 할당할 수 있습니다. 'CreateInitiators'를 사용하여 새 이니시에이터를 생성할 때 볼륨 액세스 그룹에 추가할 수도 있습니다.

작업에서 매개 변수에 제공된 이니시에이터 중 하나를 생성하지 못할 경우 메소드는 오류를 반환하며 이니시에이터를 생성하지 않습니다(부분 완료는 불가능).



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
이니시에이터
 a| 
각 새 이니시에이터의 특성을 포함하는 객체 목록입니다. 개체:

* "alias": (선택 사항) 이 초기자에 할당할 친숙한 이름입니다. (문자열)
* 'attributes': (선택 사항) 이 초기자에 할당할 JSON 특성 세트입니다. (JSON 개체)
* 'chapUsername': (선택 사항) 이 이니시에이터의 고유한 CHAP 사용자 이름입니다. 생성시 지정하지 않고 requireChp가 TRUE인 경우 기본적으로 이니시에이터 이름(IQN)이 지정됩니다. (문자열)
* initiatorSecret: (선택 사항) 초기자를 인증하는 데 사용되는 CHAP 암호입니다. 생성시 지정하지 않고 requireChp 가 true 이면 기본적으로 임의로 생성된 암호가 사용됩니다. (문자열)
* '이름': (필수) 생성할 초기자(IQN 또는 WWPN)의 이름입니다. (문자열)
* RequirChap(RequireChap): (선택 사항) 이 초기자에 대한 세션 로그인 중에 CHAP가 필요한 경우 True입니다. (부울)
* targetSecret: (선택 사항) 대상을 인증하는 데 사용되는 CHAP 암호(상호 CHAP 인증 사용 시) 생성시 지정하지 않고 requireChp 가 true 이면 기본적으로 임의로 생성된 암호가 사용됩니다. (문자열)
* 'virtualNetworkIDs': (선택 사항) 이 이니시에이터와 연결된 가상 네트워크 식별자 목록입니다. 하나 이상의 가상 네트워크를 정의하는 경우 이 이니시에이터는 해당 가상 네트워크에만 로그인할 수 있습니다. 가상 네트워크를 정의하지 않으면 이 이니시에이터가 모든 네트워크에 로그인할 수 있습니다.
* 'volumeAccessGroupID': (선택 사항) 새로 생성된 이 이니시에이터가 추가될 볼륨 액세스 그룹의 ID입니다. (정수)

 a| 
JSON 개체 어레이
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
이니시에이터
 a| 
새로 생성된 이니시에이터를 설명하는 객체 목록입니다.
 a| 
xref:reference_element_api_initiator.adoc[이니시에이터] 스토리지

|===


== 오류

이 메서드는 다음 오류를 반환할 수 있습니다.

|===


| 이름 | 설명 


 a| 
xInitialatorExists
 a| 
선택한 이니시에이터 이름이 이미 있는 경우 반환됩니다.

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "id": 3291,
  "method": "CreateInitiators",
  "params": {
    "initiators": [
      {
        "name": "iqn.1993-08.org.debian:01:288170452",
        "alias": "example1"
      },
      {
        "name": "iqn.1993-08.org.debian:01:297817012",
        "alias": "example2"
      }
    ]
  }
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 3291,
  "result": {
    "initiators": [
      {
        "alias": "example1",
        "attributes": {},
        "initiatorID": 145,
        "initiatorName": "iqn.1993-08.org.debian:01:288170452",
        "volumeAccessGroups": []
      },
      {
        "alias": "example2",
        "attributes": {},
        "initiatorID": 146,
        "initiatorName": "iqn.1993-08.org.debian:01:297817012",
        "volumeAccessGroups": []
      }
    ]
  }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

xref:reference_element_api_listinitiators.adoc[ListInitiators(목록 초기자]
