---
permalink: api/reference_element_api_addclusteradmin.html 
sidebar: sidebar 
keywords: addclusteradmin,cluster,admin,administrator,adding,add 
summary: AddClusterAdmin 메서드를 사용하여 새 클러스터 관리자 계정을 추가할 수 있습니다. 클러스터 관리자는 API 및 관리 툴을 통해 클러스터를 관리할 수 있습니다. 클러스터 관리자는 완전히 분리되어 있으며 표준 테넌트 계정과 관련이 없습니다. 
---
= 추가\n\n새 관리자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'AddClusterAdmin' 메서드를 사용하여 새 클러스터 관리자 계정을 추가할 수 있습니다. 클러스터 관리자는 API 및 관리 툴을 통해 클러스터를 관리할 수 있습니다. 클러스터 관리자는 완전히 분리되어 있으며 표준 테넌트 계정과 관련이 없습니다.

각 클러스터 관리자는 API의 서브셋으로 제한할 수 있습니다. 서로 다른 사용자 및 애플리케이션에 여러 클러스터 관리자 계정을 사용해야 합니다. 가장 좋은 방법은 각 클러스터 관리자에게 필요한 최소한의 권한을 부여하는 것입니다. 이렇게 하면 자격 증명 유출이 발생할 수 있는 영향을 줄일 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
액세스
 a| 
클러스터 관리자가 사용할 수 있는 방법을 제어합니다.
 a| 
문자열 배열
 a| 
없음
 a| 
예



 a| 
허용 가능한 샛길
 a| 
최종 사용자 사용권 계약에 동의합니다. 시스템에 클러스터 관리자 계정을 추가하려면 true로 설정합니다. 생략하거나 false 로 설정하면 메서드 호출이 실패합니다.
 a| 
부울
 a| 
없음
 a| 
예



 a| 
속성
 a| 
JSON 개체 형식의 이름/값 쌍 목록입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
암호
 a| 
이 클러스터 관리자를 인증하는 데 사용되는 암호입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
사용자 이름
 a| 
이 클러스터 관리자의 고유한 사용자 이름입니다. 길이는 1자에서 1024자 사이여야 합니다.
 a| 
문자열
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
클러스터 관리자 ID
 a| 
새로 생성된 클러스터 관리자에 대한 ClusterAdminID입니다.
 a| 
정수

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "method": "AddClusterAdmin",
  "params": {
    "username": "joeadmin",
    "password": "68!5Aru268)$",
    "attributes": {},
    "acceptEula": true,
    "access": ["volumes", "reporting", "read"]
  },
  "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id":1,
  "result" : {
    "clusterAdminID": 2
   }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

xref:reference_element_api_app_b_access_control.adoc[액세스 제어]
