---
permalink: api/reference_element_api_snapmirrorrelationship.html 
sidebar: sidebar 
keywords: object,objects,snapMirrorRelationship 
summary: snapMirrorRelationship 개체에는 Element 볼륨과 ONTAP 볼륨 간의 SnapMirror 관계에 대한 정보가 들어 있습니다. 
---
= snapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
snapMirrorRelationship 개체에는 Element 볼륨과 ONTAP 볼륨 간의 SnapMirror 관계에 대한 정보가 들어 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
snapMirrorEndpointID입니다
 a| 
대상 ONTAP 시스템의 ID입니다.
 a| 
정수



 a| 
snapMirrorRelationshipID입니다
 a| 
ListSnapMirrorRelationships에 반환되는 것과 같이 배열의 각 snapMirrorRelationship 개체에 대한 고유 식별자입니다. 이 UUID는 ONTAP 시스템에서 생성 및 반환됩니다.
 a| 
문자열



 a| 
소스 볼륨
 a| 
소스 볼륨을 설명하는 개체입니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]



 a| 
디스테이징 볼륨
 a| 
대상 볼륨을 설명하는 개체입니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]



 a| 
currentMaxTransferRate(현재 최대 전송 속도)
 a| 
소스 볼륨과 대상 볼륨 간의 현재 최대 전송 속도(KB/초)입니다.
 a| 
정수



 a| 
힐리네
 a| 
관계가 정상인지 아닌지 여부 가능한 값:

* 참: 관계가 양호합니다.
* False: 관계가 정상이 아닙니다. 이 문제는 수동 또는 예약된 업데이트가 실패했거나 중단되었거나 마지막으로 예약된 업데이트가 지연되어 발생할 수 있습니다.

 a| 
부울



 a| 
라그타임
 a| 
대상 볼륨의 데이터가 소스 볼륨의 데이터 뒤에 걸리는 시간(초)입니다.
 a| 
정수



 a| 
마지막 전송 기간
 a| 
마지막 전송을 완료하는 데 걸린 시간(초)입니다.
 a| 
정수



 a| 
마지막 전송 오류
 a| 
마지막 전송 실패의 원인을 설명하는 메시지입니다.
 a| 
문자열



 a| 
마지막 전송 크기
 a| 
마지막 전송 중에 전송된 총 바이트 수입니다.
 a| 
정수



 a| 
lastTransferEndTimestamp.(마지막 전송 종료 타임스탬프
 a| 
마지막 전송 종료의 타임 스탬프입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
마지막 전송 유형
 a| 
관계의 이전 전송 유형입니다.
 a| 
문자열



 a| 
최대 전송 속도
 a| 
볼륨 간 최대 데이터 전송 속도(KB/초)를 지정합니다. 기본값 0은 무제한이며 SnapMirror 관계가 사용 가능한 네트워크 대역폭을 완전히 활용할 수 있도록 허용합니다.
 a| 
정수



 a| 
미러스테이트
 a| 
SnapMirror 관계의 미러 상태입니다. 가능한 값:

* 초기화되지 않음: 대상 볼륨이 초기화되지 않았습니다.
* snapmirred: 대상 볼륨이 초기화되었으며 SnapMirror 업데이트를 받을 준비가 되었습니다.
* 부분 해제: 대상 볼륨이 읽기/쓰기이고 스냅샷이 있습니다.

 a| 
문자열



 a| 
새 스냅숏
 a| 
타겟 볼륨에 있는 최신 스냅샷 복사본의 이름입니다.
 a| 
문자열



 a| 
정책 이름
 a| 
관계에 대한 ONTAP SnapMirror 정책의 이름을 지정합니다. 사용 가능한 정책 목록은 ListSnapMirrorPolicies 를 사용하여 검색할 수 있습니다. 예제 값은 "MirorLatest"와 "MirorAndVault"입니다.
 a| 
문자열



 a| 
정책 유형
 a| 
관계에 대한 ONTAP SnapMirror 정책의 유형입니다. ListSnapMirrorPolicies 를 참조하십시오. 예를 들면 ""async_mirror"" 또는 "Mirror_vault" 등이 있습니다.
 a| 
문자열



 a| 
관계 진척도
 a| 
현재 관계 활동에 대해 지금까지 처리된 총 바이트 수로, relationship-status에서 반환된 것입니다. "relationshipStatus" 멤버가 활동이 진행 중임을 나타내는 경우에만 설정됩니다.
 a| 
정수



 a| 
관계 상태
 a| 
SnapMirror 관계의 상태입니다. 가능한 값:

* 유휴
* 전송 중입니다
* 확인 중입니다
* 정지 중
* 정지되었습니다
* 대기열에 있습니다
* 준비 중
* 마무리 중입니다
* 중단 중
* 끊는 중

 a| 
문자열



 a| 
관계 유형
 a| 
SnapMirror 관계의 유형입니다. Element 소프트웨어를 실행하는 스토리지 클러스터에서 이 값은 항상 ""extended_data_protection""입니다.
 a| 
문자열



 a| 
예약 이름
 a| 
ONTAP 시스템에서 SnapMirror 관계를 업데이트하는 데 사용되는 기존 cron 일정 이름입니다. ListSnapMirrorSchedules를 사용하여 사용 가능한 일정 목록을 검색할 수 있습니다.
 a| 
문자열



 a| 
비healthyReason
 a| 
관계가 정상이 아닌 이유.
 a| 
문자열

|===