---
permalink: api/reference_element_api_keyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,keys 
summary: 'keyServerKmip 객체는 키 관리 상호 운용성 프로토콜\(KMIP\) 키 서버를 설명합니다. KMIP는 저장된 암호화 등의 클러스터 기능에 사용할 인증 키를 검색하는 위치입니다.' 
---
= KeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
keyServerKmip 객체는 KMIP(Key Management Interoperability Protocol) 키 서버를 설명합니다. KMIP(Key Management Interoperability Protocol) 키 서버는 저장된 암호화 등의 클러스터 기능에 사용할 인증 키를 검색하는 위치입니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
KeyProviderID를 입력합니다
 a| 
이 KMIP 키 서버가 공급자에 할당된 경우 이 멤버는 KMIP 키 공급자가 할당한 ID를 포함합니다. 그렇지 않으면 이 멤버는 null입니다.
 a| 
정수



 a| 
KeyServerID를 입력합니다
 a| 
KMIP 키 서버의 ID입니다. 이 값은 주요 서버 생성 중에 클러스터에서 할당한 고유한 값입니다. 이 값은 변경할 수 없습니다.
 a| 
정수



 a| 
KmipAssignedProviderIsActive 를 참조하십시오
 a| 
이 KMIP 키 서버가 공급자에 할당된 경우(keyProviderID가 null이 아님), 이 멤버는 해당 공급자가 활성 상태인지(현재 사용 중인 키를 제공) 여부를 나타냅니다. 그렇지 않으면 이 멤버는 null입니다.
 a| 
부울



 a| 
KmipCaCertificate입니다
 a| 
외부 키 서버의 루트 CA의 공개 키 인증서입니다. TLS 통신에서 외부 키 서버가 제공하는 인증서를 확인하는 데 사용됩니다. 개별 서버가 서로 다른 CA를 사용하는 키 서버 클러스터의 경우 이 구성원에는 모든 CA의 루트 인증서의 연결된 문자열이 포함됩니다.
 a| 
문자열



 a| 
kmipClientCertificate를 참조하십시오
 a| 
Element 스토리지 KMIP 클라이언트가 사용하는 PEM 형식 Base64 인코딩된 PKCS #10 X.509 인증서.
 a| 
문자열



 a| 
kmipKeyServerHostName입니다
 a| 
이 KMIP 키 서버와 연결된 호스트 이름 또는 IP 주소입니다.
 a| 
문자열 배열



 a| 
kmipKeyServerName입니다
 a| 
KMIP 키 서버의 이름입니다. 이 이름은 표시 목적으로만 사용되며 고유한 이름은 필요하지 않습니다.
 a| 
문자열



 a| 
kmipKeyServerPort 를 참조하십시오
 a| 
이 KMIP 키 서버와 연관된 포트 번호(일반적으로 5696)
 a| 
정수

|===