---
permalink: api/reference_element_api_session_iscsi.html 
sidebar: sidebar 
keywords: object,objects,session 
summary: '세션 \(iSCSI\) 개체에는 각 볼륨의 iSCSI 세션에 대한 자세한 정보가 들어 있습니다. ListIS세션 API 메소드를 사용하여 iSCSI 세션 정보를 검색할 수 있습니다.' 
---
= 세션(iSCSI)
:icons: font
:imagesdir: ../media/


[role="lead"]
세션(iSCSI) 개체에는 각 볼륨의 iSCSI 세션에 대한 자세한 정보가 들어 있습니다. 'ListISSisions' API 메소드를 사용하여 iSCSI 세션 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
계정 ID입니다
 a| 
CHAP 인증에 사용되는 계정의 계정 ID(있는 경우)입니다.
 a| 
정수



 a| 
계정 이름
 a| 
CHAP 인증에 사용되는 계정의 이름입니다(있는 경우).
 a| 
문자열



 a| 
createTime(createTime)
 a| 
UTC + 0 형식으로 iSCSI 세션을 생성한 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
드라이브 ID입니다
 a| 
세션을 호스팅하는 전송 서비스와 연결된 드라이브 ID입니다.
 a| 
정수



 a| 
드라이브 ID입니다
 a| 
오류를 보고하는 드라이브의 드라이브 ID 목록입니다. 해당되지 않는 경우 빈 목록입니다.
 a| 
정수 배열



 a| 
이니시에이터
 a| 
이 iSCSI 세션의 서버 이니시에이터에 대한 정보입니다. 구성원:

* 별칭: 이니시에이터에 할당된 대화명입니다.
* 특성: 이 이니시에이터의 특성입니다.
* initiatorID: 이 이니시에이터의 ID입니다.
* initiatorname: 이 이니시에이터의 이름입니다.
* volumeAccessGroups: 이 이니시에이터와 연결된 볼륨 액세스 그룹 목록입니다.

 a| 
JSON 개체



 a| 
initiatorIP입니다
 a| 
iSCSI 서버 이니시에이터의 IP 주소 및 포트 번호입니다.
 a| 
문자열



 a| 
initiatorname입니다
 a| 
iSCSI 서버 이니시에이터의 IQN(iSCSI 정규화된 이름)입니다.
 a| 
문자열



 a| 
initiatorPortName입니다
 a| 
initiatorSessionID와 결합된 initiatorname은 이니시에이터 포트를 식별합니다.
 a| 
문자열



 a| 
initiatorSessionID입니다
 a| 
이니시에이터에서 iSCSI 세션을 해당 이니시에이터에 속하는 것으로 식별하는 48비트 ID입니다.
 a| 
정수



 a| 
msSinceLastIsiPDU를 참조하십시오
 a| 
이 세션에 대해 마지막 iSCSI PDU를 수신한 후 시간(밀리초)입니다.
 a| 
정수



 a| 
msSinceLastScsiCommand 를 참조하십시오
 a| 
이 세션에 대해 마지막 SCSI 명령을 수신한 이후의 시간(밀리초)입니다.
 a| 
정수



 a| 
노드 ID입니다
 a| 
세션을 호스팅하는 전송 서비스와 연결된 노드 ID입니다.
 a| 
정수



 a| 
서비스 ID입니다
 a| 
세션을 호스팅하는 전송 서비스의 ServiceID입니다.
 a| 
정수



 a| 
세션 ID입니다
 a| 
iSCSI 세션 ID입니다.
 a| 
정수



 a| 
targetIP를 선택합니다
 a| 
iSCSI 스토리지 타겟의 IP 주소 및 포트 번호입니다.
 a| 
문자열



 a| 
TARGETNAME(이름)
 a| 
iSCSI 타겟의 IQN입니다.
 a| 
문자열



 a| 
targetPortName입니다
 a| 
대상 포털 그룹 태그와 결합된 targetName은 대상 포트를 식별합니다.
 a| 
문자열



 a| 
가상네트워크 ID
 a| 
세션과 연결된 가상 네트워크 ID입니다.
 a| 
정수



 a| 
볼륨 ID
 a| 
세션에 연결된 볼륨의 볼륨 ID(있는 경우)입니다.
 a| 
정수



 a| 
볼륨 인스턴스
 a| 
iSCSI 세션과 연결된 볼륨 객체를 식별합니다(있는 경우).
 a| 
정수

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_listiscsisessions.adoc[목록 세션]
