---
permalink: api/reference_element_api_setconfig.html 
sidebar: sidebar 
keywords: config,configuration,set,setting,node,setconfig,network,cluster 
summary: SetConfig 메서드를 사용하여 노드의 네트워크 및 클러스터 정보를 설정할 수 있습니다. 이 메서드는 SetClusterConfig 및 SetNetworkConfig 메서드를 모두 사용하여 사용할 수 있는 단일 API 메서드에 동일한 설정을 포함합니다. 변경할 필드만 이 메서드에 포함되어야 합니다. 
---
= 설정 구성
:icons: font
:imagesdir: ../media/


[role="lead"]
'설정 구성' 방법을 사용하여 노드에 대한 네트워크 및 클러스터 정보를 설정할 수 있습니다. 이 방법은 단일 API 메소드에서 'etClusterConfig' 및 'etNetworkConfig' 메서드를 모두 사용하여 사용할 수 있는 동일한 설정을 포함합니다. 변경할 필드만 이 메서드에 포함되어야 합니다.


NOTE: SolidFire 엔터프라이즈 SDS는 이 방법을 지원하지 않습니다. SolidFire ESDS 시스템에서 이 메서드를 사용하면 메서드가 오류를 반환합니다.



== 매개 변수

주의:

노드에서 연결 모드를 변경하면 네트워크 연결이 일시적으로 끊어질 수 있습니다.

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
클러스터
 a| 
스토리지 노드가 연결된 스토리지 클러스터와 통신하는 방법을 식별하는 클러스터 정보입니다.
 a| 
xref:reference_element_api_cluster.adoc[클러스터]
 a| 
없음
 a| 
아니요



 a| 
네트워크
 a| 
노드의 각 네트워크 인터페이스에 대한 네트워크 연결 유형 및 현재 설정입니다.
 a| 
xref:reference_element_api_network_all_interfaces.adoc[네트워크(모든 인터페이스)]
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
구성
 a| 
노드의 새 구성과 현재 구성입니다. 이 개체에는 다음이 포함됩니다.

* xref:reference_element_api_cluster.adoc[클러스터]: 스토리지 노드가 연결된 스토리지 클러스터와 통신하는 방법을 식별하는 클러스터 정보입니다.
* xref:reference_element_api_network_all_interfaces.adoc[네트워크(모든 인터페이스)]: 노드의 각 네트워크 인터페이스에 대한 네트워크 연결 유형 및 현재 설정입니다.

 a| 
JSON 개체

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
	"method": "SetConfig",
	"params": {
		"cluster": {
			"name": "MyHostname"
		},
		"network": {
			"Bond10G": {
				"bond-mode": "ALB"
			}
		}
	}
}
----


== 응답 예

이 메소드의 응답은 getconfig 메소드의 반환과 동일합니다. SetConfig를 사용하면 개체 표시 및 업데이트된 값에 대한 모든 필드가 표시됩니다.



== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

* xref:reference_element_api_setclusterconfig.adoc[SetClusterConfig]
* xref:reference_element_api_setnetworkconfig.adoc[SetNetworkConfig]
* xref:reference_element_api_response_example_getconfig.adoc[getconfig를 참조하십시오]

