---
permalink: api/reference_element_api_network_local_interfaces.html 
sidebar: sidebar 
keywords: object,objects,network 
summary: 'network\(local interfaces\) 객체에는 스토리지 노드의 루프백 인터페이스와 같은 로컬 네트워크 인터페이스에 대한 구성 정보가 포함되어 있습니다. getconfig 및 GetNetworkConfig 메서드를 사용하여 스토리지 노드에 대한 이 정보를 가져올 수 있습니다.' 
---
= 네트워크(로컬 인터페이스)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크(로컬 인터페이스) 객체에는 스토리지 노드의 루프백 인터페이스와 같은 로컬 네트워크 인터페이스에 대한 구성 정보가 포함되어 있습니다. "getconfig" 및 "GetNetworkConfig" 메서드를 사용하여 스토리지 노드에 대한 정보를 가져올 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===


| 이름 | 설명 | 유형 


 a| 
가족
 a| 
인터페이스가 사용하도록 구성된 주소 제품군입니다. 현재 IPv4에 대해 "inet"이 지원됩니다.
 a| 
문자열



 a| 
MacAddress(MacAddress)
 a| 
인터페이스에 할당되고 네트워크에서 관찰되는 실제 MAC 주소입니다.
 a| 
문자열



 a| 
MacAddressPermanent를 참조하십시오
 a| 
제조업체가 인터페이스에 할당한 불변 MAC 주소입니다.
 a| 
문자열



 a| 
방법
 a| 
인터페이스를 구성하는 데 사용되는 방법입니다. 가능한 값:

* Loopback: IPv4 루프백 인터페이스를 정의하는 데 사용됩니다.
* Manual(수동): 자동으로 구성되지 않은 인터페이스를 정의하는 데 사용됩니다.
* DHCP: DHCP를 통해 IP 주소를 가져오는 데 사용할 수 있습니다.
* 정적: 정적으로 할당된 IPv4 주소를 사용하여 이더넷 인터페이스를 정의하는 데 사용됩니다.

 a| 
문자열



 a| 
상태
 a| 
인터페이스의 상태입니다. 가능한 값:

* Down(아래로): 인터페이스가 비활성 상태입니다.
* UP: 인터페이스가 준비되었지만 링크가 없습니다.
* UpAndRunning: 인터페이스가 준비되고 링크가 설정됩니다.

 a| 
문자열



 a| 
업안닝
 a| 
인터페이스가 준비되었고 링크가 있는지 여부를 나타냅니다.
 a| 
부울

|===


== 멤버 수정 가능성 및 노드 상태

이 표는 가능한 각 노드 상태에서 개체 매개 변수를 수정할 수 있는지 여부를 나타냅니다.

|===


| 매개 변수 이름입니다 | 사용 가능 상태입니다 | 보류 중 상태입니다 | 활성 상태입니다 


 a| 
가족
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
MacAddress(MacAddress)
 a| 
시스템에 의해 구성됩니다
 a| 
해당 없음
 a| 
해당 없음



 a| 
MacAddressPermanent를 참조하십시오
 a| 
시스템에 의해 구성됩니다
 a| 
해당 없음
 a| 
해당 없음



 a| 
방법
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
상태
 a| 
예
 a| 
예
 a| 
예



 a| 
업안닝
 a| 
시스템에 의해 구성됩니다
 a| 
해당 없음
 a| 
해당 없음

|===


== 자세한 내용을 확인하십시오

* xref:reference_element_api_getconfig.adoc[getconfig를 참조하십시오]
* xref:reference_element_api_getnetworkconfig.adoc[GetNetworkConfig 를 참조하십시오]

