---
permalink: api/reference_element_api_snapshot.html 
sidebar: sidebar 
keywords: object,objects,snapshot 
summary: 스냅샷 개체에는 볼륨에 대해 생성된 스냅샷에 대한 정보가 포함되어 있습니다. ListSnapshots API 메소드를 사용하여 볼륨 또는 모든 볼륨에 대한 스냅샷 정보 목록을 검색할 수 있습니다. 객체에는 활성 스냅샷에 대한 정보와 볼륨에 대해 생성된 각 스냅샷에 대한 정보가 포함됩니다. 
---
= 스냅샷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 개체에는 볼륨에 대해 생성된 스냅샷에 대한 정보가 포함되어 있습니다. "ListSnapshots" API 메소드를 사용하여 볼륨 또는 모든 볼륨에 대한 스냅샷 정보 목록을 검색할 수 있습니다. 객체에는 활성 스냅샷에 대한 정보와 볼륨에 대해 생성된 각 스냅샷에 대한 정보가 포함됩니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체



 a| 
체크섬
 a| 
저장된 스냅샷에 있는 데이터의 작은 문자열 표현입니다. 이 체크섬은 나중에 다른 스냅샷을 비교하여 데이터의 오류를 감지하는 데 사용할 수 있습니다.
 a| 
문자열



 a| 
createTime(createTime)
 a| 
스냅샷이 생성된 UTC+0 형식 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
enableRemoteReplication
 a| 
원격 복제에 대해 스냅샷이 설정되어 있는지 여부를 나타냅니다.
 a| 
부울



 a| 
만료 Reason입니다
 a| 
스냅샷 만료가 설정되는 방법을 나타냅니다. 가능한 값:

* API: 만료 시간은 API를 사용하여 설정합니다.
* 없음: 만료 시간이 설정되지 않았습니다.
* Test(테스트): 만료 시간이 테스트용으로 설정됩니다.
* FIFO: 만료 작업은 선입선출 방식으로 이루어집니다.

 a| 
문자열



 a| 
만료 시간
 a| 
이 스냅샷이 만료되어 클러스터에서 제거되는 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
그룹 ID입니다
 a| 
스냅샷이 그룹 스냅샷의 구성원인 경우 그룹 ID입니다.
 a| 
정수



 a| 
groupsnapshotUUID입니다
 a| 
그룹의 각 스냅샷에 대한 정보가 포함되어 있습니다. 이러한 각 구성원은 스냅샷의 UUID 매개 변수를 갖습니다.
 a| 
문자열



 a| 
인스턴스 생성시간
 a| 
로컬 클러스터에서 스냅샷이 생성된 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
instanceSnapshotUUID입니다
 a| 
로컬 클러스터에 있는 스냅샷의 범용 고유 ID입니다. 이 ID는 다른 클러스터에 복제되지 않습니다.
 a| 
문자열



 a| 
이름
 a| 
스냅샷에 할당된 고유한 이름입니다. 이름을 지정하지 않으면 스냅샷이 생성된 시점의 UTC + 0 형식 타임 스탬프가 됩니다.
 a| 
문자열



 a| 
원격 상태
 a| 
소스 클러스터에서 볼 수 있는 것처럼 타겟 클러스터에 있는 각 원격 스냅샷의 범용 식별자 및 복제 상태를 포함하는 스토리지
 a| 
xref:reference_element_api_remoteclustersnapshotstatus.adoc[원격 클러스터 스냅샷상태] 스토리지



 a| 
snapMirrorLabel
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트에 대한 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다. 설정되지 않은 경우 이 값은 null입니다.
 a| 
문자열



 a| 
스냅샷 ID입니다
 a| 
기존 스냅샷의 고유 ID입니다.
 a| 
문자열



 a| 
스냅샷 UUID입니다
 a| 
기존 스냅샷의 범용 고유 ID입니다. 스냅샷이 여러 클러스터에 복제되면 이 ID가 함께 복제되고 클러스터 전체에서 스냅샷을 식별하는 데 사용됩니다.
 a| 
문자열



 a| 
상태
 a| 
스냅샷의 현재 상태입니다. 가능한 값:

* 알 수 없음: 스냅샷 상태를 가져오는 동안 오류가 발생했습니다.
* 준비: 이 스냅샷은 사용 준비가 되어 있으며 아직 쓸 수 없습니다.
* RemoteSyncing(원격 Syncing): 이 스냅샷이 원격 클러스터에서 복제되고 있습니다.
* 완료: 이 스냅샷은 준비 또는 복제를 완료했으며 이제 사용할 수 있습니다.
* Active(활성): 이 스냅샷은 활성 분기입니다.
* 클론 생성: 이 스냅샷은 CopyVolume 작업과 관련되어 있습니다.

 a| 
문자열



 a| 
총 크기
 a| 
스냅샷의 총 크기(바이트)입니다.
 a| 
정수



 a| 
가상볼륨 ID
 a| 
이 스냅샷과 연결된 가상 볼륨의 ID입니다.
 a| 
UUID입니다



 a| 
볼륨 ID
 a| 
스냅샷이 생성된 볼륨의 ID입니다.
 a| 
정수



 a| 
볼륨 이름
 a| 
스냅샷이 생성된 시점의 볼륨 이름입니다.
 a| 
문자열

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_listsnapshots.adoc[목록\n\n 스냅샷]
