---
permalink: api/reference_element_api_pendingnode.html 
sidebar: sidebar 
keywords: object,objects,pendingNode 
summary: 펜딩노드 개체에는 클러스터에 추가할 수 있는 노드에 대한 정보가 포함되어 있습니다. ListPendingNodes API 메서드를 사용하여 보류 중인 모든 노드에 대해 이 정보 목록을 반환합니다. AddNodes API 메서드를 사용하여 나열된 노드를 클러스터에 추가할 수 있습니다. 
---
= 펜던트 노드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
펜딩노드 개체에는 클러스터에 추가할 수 있는 노드에 대한 정보가 포함되어 있습니다. ListPendingNodes API 메소드를 사용하여 보류 중인 모든 노드에 대해 이 정보 목록을 반환합니다. AddNodes API 메소드를 사용하여 나열된 노드를 클러스터에 추가할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
치피
 a| 
노드에 할당된 클러스터 IP 주소입니다.
 a| 
문자열



 a| 
활성 NodeKey
 a| 
소프트웨어를 성공적으로 설치한 후 노드가 자동으로 클러스터에 참여할 수 있도록 하는 고유한 키입니다.
 a| 
문자열



 a| 
AssignedNodeID입니다
 a| 
노드에 할당된 노드 ID입니다.
 a| 
문자열



 a| 
asyncHandle
 a| 
작업의 상태를 쿼리하는 데 사용할 수 있는 비동기 메서드 핸들입니다.
 a| 
정수



 a| 
섀시 이름
 a| 
섀시를 고유하게 식별하며 단일 섀시의 모든 노드에 대해 동일합니다.
 a| 
문자열



 a| 
CIP
 a| 
노드에 할당된 클러스터 IP 주소입니다.
 a| 
문자열



 a| 
MIP
 a| 
노드에 할당된 관리 IP 주소입니다.
 a| 
문자열



 a| 
노드 슬롯
 a| 
HCI 플랫폼의 경우 이 노드가 있는 섀시 슬롯("A", "B", "C" 또는 "D")에 해당하는 문자가 있습니다. 스토리지 플랫폼의 경우 이 값은 null입니다.
 a| 
문자열



 a| 
활성 노드 ID입니다
 a| 
노드의 보류 중인 노드 ID입니다.
 a| 
정수



 a| 
플랫폼 정보
 a| 
노드에 대한 하드웨어 정보입니다. 구성원:

* chassisType: 노드의 하드웨어 플랫폼입니다.
* cpuModel: 하드웨어 플랫폼의 CPU 모델입니다.
* 노드 메모리 GB: 물리적 플랫폼에 설치된 메모리 크기(GB)입니다.
* NodeType: 노드 모델 이름입니다.
* PlatformConfigVersion: 이 노드 하드웨어에 대해 구성된 소프트웨어 버전입니다.

 a| 
JSON 개체



 a| 
역할
 a| 
클러스터에서 노드의 역할입니다. 가능한 값:

* 관리
* 스토리지
* 컴퓨팅
* 증인

 a| 



 a| 
SIP
 a| 
노드에 할당된 스토리지(iSCSI) IP 주소입니다.
 a| 
문자열



 a| 
소프트웨어 버전
 a| 
노드에서 실행 중인 Element 소프트웨어의 현재 버전입니다.
 a| 
문자열

|===


== 자세한 내용을 확인하십시오

* xref:reference_element_api_addnodes.adoc[추가 노드]
* xref:reference_element_api_listpendingnodes.adoc[ListPendingNodes 를 참조하십시오]

