---
permalink: api/reference_element_api_volumestats.html 
sidebar: sidebar 
keywords: object,objects,volumeStats 
summary: volumeStats 개체에는 개별 볼륨에 대한 통계 데이터가 포함되어 있습니다. 
---
= 볼륨 통계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
volumeStats 개체에는 개별 볼륨에 대한 통계 데이터가 포함되어 있습니다.



== 개체 멤버

다음 방법을 사용하여 일부 또는 모든 볼륨에 대한 volumeStats 개체를 가져올 수 있습니다.

* xref:reference_element_api_getvolumestats.adoc[GetVolumeStats 를 참조하십시오]
* xref:reference_element_api_listvolumestatsbyaccount.adoc[ListVolumeStatsByAccount]
* xref:reference_element_api_listvolumestatsbyvolume.adoc[ListVolumeStatsByVolume]
* xref:reference_element_api_listvolumestatsbyvolumeaccessgroup.adoc[ListVolumeStatsByVolumeAccessGroup]


이 개체에는 다음 멤버가 포함되어 있습니다.

[cols="20,50,15,15"]
|===
| 이름 | 설명 | 계산 | 유형 


 a| 
계정 ID입니다
 a| 
볼륨 소유자 계정의 ID입니다.
 a| 
해당 없음
 a| 
정수



 a| 
실제 IOPS
 a| 
마지막 500밀리초 동안 볼륨에 대한 현재 실제 IOPS입니다.
 a| 
특정 시점
 a| 
정수



 a| 
asyncDelay를 선택합니다
 a| 
볼륨이 원격 클러스터와 마지막으로 동기화된 이후의 시간입니다. 볼륨이 페어링되지 않은 경우 null입니다. * 참고: * 활성 복제 상태의 타겟 볼륨은 항상 0의 asyncDelay를 가집니다. 타겟 볼륨은 복제 중에 시스템을 인식하며, asyncDelay가 항상 정확하다고 가정합니다.
 a| 
해당 없음
 a| 
ISO 8601 기간 문자열 또는 null



 a| 
averageIOPSize를 클릭합니다
 a| 
최근 500밀리초 동안 볼륨에 대한 최근 I/O의 평균 크기(바이트)입니다.
 a| 
특정 시점
 a| 
정수



 a| 
burstIOPSCredit
 a| 
사용자가 사용할 수 있는 총 IOP 크레딧 수입니다. 볼륨이 구성된 최대 maxIOPS를 사용하지 않으면 크레딧이 계산됩니다.
 a| 
해당 없음
 a| 
정수



 a| 
클라이언트 대기열 깊이
 a| 
볼륨에 대한 미해결 읽기 및 쓰기 작업 수입니다.
 a| 
해당 없음
 a| 
정수



 a| 
DesiredMetadataHosts 를 선택합니다
 a| 
볼륨 메타데이터가 메타데이터 서비스 간에 마이그레이션되는 경우 마이그레이션 중인 메타데이터(슬라이스) 서비스입니다. "null" 값은 볼륨이 마이그레이션되지 않음을 의미합니다.
 a| 
해당 없음
 a| 
JSON 개체



 a| 
지연 시간 USec
 a| 
마지막 500밀리초 내에 볼륨에 대한 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다. "0"(0) 값은 볼륨에 대한 I/O가 없음을 의미합니다.
 a| 
특정 시점
 a| 
정수



 a| 
메타 호스트가 있습니다
 a| 
볼륨 메타데이터가 상주하는 메타데이터(슬라이스) 서비스입니다. 가능한 값:

* Primary: 볼륨을 호스팅하는 기본 메타데이터 서비스입니다.
* liveSecondaries: 현재 "라이브" 상태에 있는 보조 메타데이터 서비스입니다.
* DeadSecondaries: 비활성 상태의 보조 메타데이터 서비스입니다.

 a| 
해당 없음
 a| 
JSON 개체



 a| 
정규화 IOPS
 a| 
지난 500밀리초 동안 전체 클러스터의 평균 IOPS 수입니다.
 a| 
특정 시점
 a| 
정수



 a| 
ZeroBlocks가 아닙니다
 a| 
마지막 가비지 수집 작업이 완료된 후 데이터가 포함된 총 4KiB 블록 수입니다.
 a| 
해당 없음
 a| 
정수



 a| 
읽기\바이트
 a| 
볼륨 생성 이후 볼륨에서 읽은 총 누적 바이트 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
ReadBytesLastSample 을 참조하십시오
 a| 
마지막 샘플 기간 동안 볼륨에서 읽은 총 바이트 수입니다.
 a| 
특정 시점
 a| 
정수



 a| 
readLatencyUSec을 참조하십시오
 a| 
마지막 500밀리초 동안 볼륨에 대한 읽기 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다.
 a| 
특정 시점
 a| 
정수



 a| 
ReadLatencyUSecTotal 을 참조하십시오
 a| 
볼륨에서 읽기 작업을 수행하는 데 소요된 총 시간입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
readOps를 참조하십시오
 a| 
볼륨을 생성한 후 볼륨에 대한 총 읽기 작업입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
ReadOpsLastSample 을 참조하십시오
 a| 
마지막 샘플 기간 동안의 총 읽기 작업 수입니다.
 a| 
특정 시점
 a| 
정수



 a| 
SamplePeriodMSec
 a| 
샘플 기간의 길이(밀리초).
 a| 
해당 없음
 a| 
정수



 a| 
슬라이서 IopsStats
 a| 
볼륨의 I/O 사용량 통계입니다. Element 12.8부터 사용 가능. 가능한 슬라이서 IopsStats 값:

* LargeStatistics: 일반적으로 최근 24시간 동안 측정된 볼륨의 I/O 통계입니다.
* smallStatistics: 일반적으로 마지막 시간 동안 측정된 볼륨의 I/O 통계입니다.


가능한 largeStatistics 및 smallStatistics 값:

* averageReadIops: 볼륨에 대한 평균 읽기 IOPS입니다.
* AverageTotalIops: 볼륨에 대한 평균 총(읽기 + 쓰기) IOPS입니다.
* averageWriteIops: 볼륨에 대한 평균 쓰기 IOPS입니다.
* nSamples: 통계 계산에 포함된 샘플 수입니다.
* PeakReadIops: 통계 간격 동안 관찰된 최대 읽기 IOPS입니다.
* PeakTotalIops: 통계 간격 동안 관찰된 최대 총 IOPS입니다.
* PeakWriteIops: 통계 간격 동안 관찰된 최대 쓰기 IOPS입니다.
* 슬라이서 ID: 볼륨 ID 또는 슬라이스 ID입니다

 a| 
특정 시점
 a| 
JSON 개체



 a| 
스로틀
 a| 
데이터 재복제, 일시적 오류 및 생성된 스냅샷으로 인해 시스템이 최대 IOPS보다 클라이언트를 제한하는 양을 나타내는 0에서 1 사이의 부동 값입니다.
 a| 
해당 없음
 a| 
부동



 a| 
타임 스탬프입니다
 a| 
UTC + 0 형식의 현재 시간입니다.
 a| 
해당 없음
 a| 
ISO 8601 날짜 문자열



 a| 
unalignedReads입니다
 a| 
볼륨을 생성한 후 볼륨에 대한 정렬되지 않은 총 읽기 작업입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
UnalignedWrites를 참조하십시오
 a| 
볼륨이 생성된 후 볼륨에 대한 정렬되지 않은 총 쓰기 작업 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
볼륨 액세스 그룹
 a| 
볼륨이 속한 볼륨 액세스 그룹의 ID 목록입니다.
 a| 
해당 없음
 a| 
정수 배열



 a| 
볼륨 ID
 a| 
볼륨의 ID입니다.
 a| 
해당 없음
 a| 
정수



 a| 
볼륨 크기
 a| 
프로비저닝된 총 용량(바이트)
 a| 
해당 없음
 a| 
정수



 a| 
볼륨 활용률입니다
 a| 
클라이언트가 해당 볼륨에 대한 maxIOPS QoS 설정과 비교하여 볼륨의 입력/출력 기능을 완전히 사용하는 방법을 설명하는 부동 소수점 값입니다. 가능한 값:

* 0: 클라이언트가 볼륨을 사용하고 있지 않습니다.
* 0.01 ~ 0.99: 클라이언트가 볼륨의 IOPS 기능을 완전히 활용하지 않습니다.
* 1.00: 클라이언트가 maxIOPS 설정에 의해 설정된 IOPS 한도까지 볼륨을 완전히 활용하고 있습니다.
* > 1.00: 클라이언트가 maxIOPS로 설정된 제한 이상을 사용하고 있습니다. burstIOPS QoS 설정이 maxIOPS보다 높게 설정되어 있을 때 발생할 수 있습니다. 예를 들어, maxIOPS가 1000으로 설정되고 burstIOPS가 2000으로 설정된 경우 클라이언트가 볼륨을 완전히 사용하면 'volumeUtilization' 값은 2.00이 됩니다.

 a| 
해당 없음
 a| 
부동



 a| 
쓰기 바이트
 a| 
볼륨 생성 이후 볼륨에 기록된 총 누적 바이트 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
WriteBytesLastSample 을 참조하십시오
 a| 
마지막 샘플 기간 동안 볼륨에 쓴 총 바이트 수입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
writeLatencyUSec입니다
 a| 
마지막 500밀리초 동안 볼륨에 대한 쓰기 작업을 완료하는 데 걸리는 평균 시간(마이크로초)입니다.
 a| 
특정 시점
 a| 
정수



 a| 
쓰기 LatencyUSecTotal
 a| 
볼륨에 대한 쓰기 작업을 수행하는 데 소요된 총 시간입니다.
 a| 
단조적으로 증가
 a| 
정수



 a| 
쓰기 작업
 a| 
볼륨 생성 이후 볼륨에 대한 총 누적 쓰기 작업.
 a| 
단조적으로 증가
 a| 
정수



 a| 
WriteOpsLastSample 을 참조하십시오
 a| 
마지막 샘플 기간 동안의 총 쓰기 작업 수입니다.
 a| 
특정 시점
 a| 
정수



 a| 
ZeroBlocks입니다
 a| 
마지막 가비지 수집 작업이 완료된 후 데이터가 없는 총 4KiB 블록 수입니다.
 a| 
특정 시점
 a| 
정수

|===