---
permalink: api/reference_element_api_createclustersupportbundle.html 
sidebar: sidebar 
keywords: CreateClusterSupportBundle,create,cluster,support,bundle,creating 
summary: 관리 노드에서 CreateClusterSupportBundle 을 사용하여 클러스터의 모든 노드에서 지원 번들을 수집할 수 있습니다. 번들이 생성되면 이 번들은 노드에 .tar.gz 파일로 저장됩니다. 이 메서드는 관리 노드에서만 실행할 수 있으며 스토리지 노드에서 실행될 때는 작동하지 않습니다. 
---
= CreateClusterSupportBundle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드에서 'CreateClusterSupportBundle'을 사용하여 클러스터의 모든 노드에서 지원 번들을 수집할 수 있습니다. 개별 노드 지원 번들은 tar.gz 파일로 압축됩니다. 클러스터 지원 번들은 노드 지원 번들을 포함하는 tar 파일입니다. 이 메서드는 관리 노드에서만 실행할 수 있으며 스토리지 노드에서 실행될 때는 작동하지 않습니다.



== 매개 변수


NOTE: 관리 노드에 대해 이 메서드를 호출해야 합니다. 예를 들면 다음과 같습니다.

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
allowIncomplete.(
 a| 
하나 이상의 노드에서 번들을 수집할 수 없는 경우 스크립트를 계속 실행할 수 있습니다.
 a| 
부울
 a| 
없음
 a| 
아니요



 a| 
번집니다
 a| 
생성된 각 지원 번들의 고유 이름입니다. 이름이 제공되지 않으면 "supportbundle"과 노드 이름이 파일 이름으로 사용됩니다
 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
진동
 a| 
클러스터의 MVIP입니다. 번들은 클러스터의 모든 노드에서 수집됩니다. nodes 매개 변수를 지정하지 않은 경우 이 매개 변수가 필요합니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
노드
 a| 
번들을 수집할 노드의 IP 주소입니다. 노드 또는 mvip 중 하나만 사용하여 번들을 수집할 노드를 지정합니다. mvip을 지정하지 않은 경우 이 매개 변수가 필요합니다.
 a| 
문자열 배열
 a| 
없음
 a| 
예



 a| 
암호
 a| 
클러스터 관리자 암호입니다. * 참고: * 이 암호는 입력 시 텍스트로 표시됩니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
사용자 이름
 a| 
클러스터 관리자 사용자 이름입니다.
 a| 
문자열
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
"method": "CreateClusterSupportBundle",
"params": {
          "bundlename": "clusterbundle",
          "mvip": "132.119.120.100"
     }
   },
 "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id":1,
  "result":{
   "details":{
      "bundleName":"clusterbundle",
      "extraArgs":"",
      "files":[
          "/tmp/supportbundles/clusterbundle.cl-4SD5.tar"
      ],
      "output":"timeout -s KILL 1790s /usr/local/bin/sfclustersupportbundle --quiet --name=\"clusterbundle\" --target-directory=\"/tmp/solidfire-dtemp.MM7f0m\" --user=\"admin\" --pass=\"admin\" --mvip=132.119.120.100"
       },
       "duration":"00:00:24.938127",
       "result":"Passed"
    }
}
----


== 버전 이후 새로운 기능

9.6
