---
permalink: api/reference_element_api_drive.html 
sidebar: sidebar 
keywords: objects,object,drive 
summary: 드라이브 개체에는 클러스터의 활성 노드에 있는 개별 드라이브에 대한 정보가 들어 있습니다. 이 오브젝트에는 볼륨 메타데이터 또는 블록 드라이브로 추가된 드라이브에 대한 세부 정보와 아직 추가되지 않았으며 사용 가능한 드라이브가 포함되어 있습니다. ListDrives API 메서드를 사용하여 이 정보를 검색할 수 있습니다. 
---
= 드라이브
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브 개체에는 클러스터의 활성 노드에 있는 개별 드라이브에 대한 정보가 들어 있습니다. 이 오브젝트에는 볼륨 메타데이터 또는 블록 드라이브로 추가된 드라이브에 대한 세부 정보와 아직 추가되지 않았으며 사용 가능한 드라이브가 포함되어 있습니다. ListDrives API 메소드를 사용하여 이 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다. 이 개체는 항상 null이며 수정할 수 없습니다.
 a| 
JSON 개체



 a| 
용량
 a| 
드라이브의 총 용량(바이트)입니다.
 a| 
정수



 a| 
섀시 슬롯
 a| 
HCI 플랫폼의 경우 이 값은 이 드라이브가 있는 서버 섀시의 노드 문자 및 슬롯 번호입니다. 스토리지 플랫폼의 경우 슬롯 번호는 "슬롯" 정수의 문자열 표현입니다.
 a| 
문자열



 a| 
DRiveFailureDetail 을 선택합니다
 a| 
드라이브의 상태가 "Failed(실패)"인 경우 이 필드는 드라이브가 실패로 표시된 이유에 대한 자세한 정보를 제공합니다.
 a| 
문자열



 a| 
드라이브 ID입니다
 a| 
이 드라이브의 ID입니다.
 a| 
정수



 a| 
DRiveSecurityFaultReason 을 참조하십시오
 a| 
드라이브 보안을 활성화 또는 비활성화하지 못한 경우, 실패한 이유입니다. 값이 "없음"이면 오류가 없는 것입니다.
 a| 
문자열



 a| 
키 ID입니다
 a| 
키 공급자가 이 드라이브의 잠금을 해제하기 위한 인증 키를 획득하기 위해 사용하는 키 ID입니다.
 a| 
UUID입니다



 a| 
KeyProviderID를 입력합니다
 a| 
이 드라이브의 잠금을 해제하기 위한 인증 키의 공급자를 식별합니다.
 a| 
정수



 a| 
노드 ID입니다
 a| 
이 드라이브를 포함하는 노드의 ID입니다.
 a| 
정수



 a| 
세그먼트 파일 크기입니다
 a| 
드라이브의 세그먼트 파일 크기(바이트)입니다.
 a| 
정수



 a| 
일련 번호
 a| 
드라이브 일련 번호입니다.
 a| 
문자열



 a| 
슬롯
 a| 
이 드라이브가 있는 서버 섀시의 슬롯 번호 또는 내부 메타데이터 드라이브에 SATADimm 장치를 사용하는 경우 -1입니다.
 a| 
정수



 a| 
상태
 a| 
드라이브의 상태입니다. 가능한 값:

* 사용 가능: 사용 가능한 드라이브.
* 활성: 활성 드라이브.
* 지우기: 드라이브가 안전하게 지워지고 있습니다. 해당 드라이브의 모든 데이터가 영구적으로 제거됩니다.
* 실패: 실패한 드라이브입니다. 이전에 드라이브에 있던 모든 데이터가 클러스터의 다른 드라이브로 마이그레이션되었습니다.
* 분리: 드라이브를 분리하는 중입니다. 이전에 드라이브에 있던 모든 데이터가 클러스터의 다른 드라이브로 마이그레이션되고 있습니다.

 a| 
문자열



 a| 
유형
 a| 
드라이브 유형입니다. 가능한 값:

* Volume(볼륨): 볼륨 메타데이터를 저장합니다.
* 블록: 블록 데이터를 저장합니다.
* 알 수 없음: 드라이브 유형이 아직 활성 상태가 아니며 아직 결정되지 않았습니다.

 a| 
문자열



 a| 
사용 가능 용량
 a| 
드라이브의 가용 용량(바이트)
 a| 
정수

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_listdrives.adoc[ListDrives를 선택합니다]
