---
permalink: api/reference_element_api_removedrives.html 
sidebar: sidebar 
keywords: cluster,drive,drives,remove,removing,removedrives 
summary: RemoveDrives 메서드를 사용하여 클러스터의 일부인 드라이브를 사전에 제거할 수 있습니다. 이 방법은 클러스터 용량을 줄이거나 사용 수명이 거의 다 된 드라이브를 교체할 준비를 하는 데 사용할 수 있습니다. 드라이브에서 데이터가 모두 제거되며 클러스터에서 드라이브가 제거되기 전에 클러스터의 다른 드라이브로 마이그레이션됩니다. 
---
= 드라이브 제거
:icons: font
:imagesdir: ../media/


[role="lead"]
"RemoveDrives" 방법을 사용하여 클러스터의 일부인 드라이브를 사전에 제거할 수 있습니다. 이 방법은 클러스터 용량을 줄이거나 사용 수명이 거의 다 된 드라이브를 교체할 준비를 하는 데 사용할 수 있습니다. 드라이브에서 데이터가 모두 제거되며 클러스터에서 드라이브가 제거되기 전에 클러스터의 다른 드라이브로 마이그레이션됩니다.

RemoveDrives는 비동기 방법입니다. 제거하는 드라이브의 총 용량에 따라 모든 데이터를 마이그레이션하는 데 몇 분이 걸릴 수 있습니다.

여러 드라이브를 제거할 때는 각각 하나의 드라이브를 가진 여러 개의 개별 메서드가 아니라 하나의 "RemoveDrives" 메서드 호출을 사용합니다. 이렇게 하면 클러스터의 스토리지 부하를 균등하게 안정화하기 위해 발생하는 데이터 밸런싱의 양이 줄어듭니다.

"RemoveDrives"를 사용하여 "failed" 상태의 드라이브를 제거할 수도 있습니다. "실패" 상태의 드라이브를 제거하면 드라이브가 "사용 가능" 또는 "활성" 상태로 복귀되지 않습니다. 클러스터에서 드라이브를 사용할 수 없습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
드라이브
 a| 
클러스터에서 제거할 드라이브 ID 목록입니다.
 a| 
정수 배열
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
asyncHandle
 a| 
작업 결과를 얻는 데 사용되는 Handle 값입니다.
 a| 
정수

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "RemoveDrives",
   "params": {
      "drives"  : [3, 4, 5]
   },
   "id" : 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result" : {
     "asyncHandle": 1
   }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult 를 참조하십시오]
* xref:reference_element_api_listdrives.adoc[ListDrives를 선택합니다]

