---
permalink: api/reference_element_api_task_virtual_volumes.html 
sidebar: sidebar 
keywords: object,objects,task 
summary: 작업 객체에는 시스템에서 현재 실행 중이거나 완료된 가상 볼륨 작업에 대한 정보가 들어 있습니다. ListVirtualVolumeTasks 메서드를 사용하여 모든 가상 볼륨 작업에 대한 이 정보를 검색할 수 있습니다. 
---
= 작업(가상 볼륨)
:icons: font
:imagesdir: ../media/


[role="lead"]
작업 객체에는 시스템에서 현재 실행 중이거나 완료된 가상 볼륨 작업에 대한 정보가 들어 있습니다. 'ListVirtualVolumeTasks' 메서드를 사용하여 모든 가상 볼륨 작업에 대한 이 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
취소됨
 a| 
작업이 취소되었는지 여부를 나타냅니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
CLoneVirtualVolumeID
 a| 
클론 생성 중인 가상 볼륨의 고유한 가상 볼륨 ID(클론 작업용)입니다.
 a| 
UUID입니다



 a| 
ParentMetadata
 a| 
가상 볼륨의 스냅샷을 클론 생성하거나 생성하는 작업에 대한 상위 볼륨의 메타데이터를 포함하는 객체입니다.
 a| 
JSON 개체



 a| 
ParentTotalSize를 선택합니다
 a| 
클론 또는 스냅샷 작업을 위해 상위 항목에서 사용 가능한 총 공간(바이트)입니다.
 a| 
정수



 a| 
ParentUsedSize(매개 변수 크기)
 a| 
클론 또는 스냅샷 작업에 대해 상위 항목의 사용된 공간(바이트)입니다.
 a| 
정수



 a| 
작동
 a| 
작업이 수행 중인 작업의 유형입니다. 가능한 값:

* 알 수 없음: 작업 작업을 알 수 없습니다.
* Prepare(준비): 작업이 가상 볼륨을 준비하는 중입니다.
* 스냅샷: 작업이 가상 볼륨의 스냅샷을 생성하는 중입니다.
* 롤백: 작업이 가상 볼륨을 스냅샷으로 롤백하고 있습니다.
* 클론: 작업이 가상 볼륨의 클론을 생성하는 중입니다.
* FastClone: 작업이 가상 볼륨의 고속 클론을 생성하는 중입니다.
* copyDiffs: 작업이 다른 블록을 가상 볼륨으로 복사하는 중입니다.

 a| 
문자열



 a| 
상태
 a| 
가상 볼륨 작업의 현재 상태입니다. 가능한 값:

* 오류: 작업이 실패하여 오류를 반환했습니다.
* Queued(대기): 작업이 실행 대기 중입니다.
* 실행 중: 작업이 현재 실행 중입니다.
* 성공: 작업이 성공적으로 완료되었습니다.

 a| 
문자열



 a| 
가상볼륨 호스트 ID
 a| 
작업을 시작한 호스트의 고유 ID입니다.
 a| 
UUID입니다



 a| 
가상볼륨 ID
 a| 
새로운 고유 가상 볼륨 ID(새 가상 볼륨을 생성하는 작업에 해당).
 a| 
UUID입니다



 a| 
가상볼륨 작업 ID
 a| 
작업의 고유 ID입니다.
 a| 
UUID입니다

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_listvirtualvolumetasks.adoc[ListVirtualVolumeTasks를 참조하십시오]
