---
permalink: api/reference_element_api_getsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,information,info,get,getting 
summary: 'GetSnmpInfo 메서드를 사용하여 현재 단순 네트워크 관리 프로토콜\(SNMP\) 구성 정보를 가져올 수 있습니다.' 
---
= GetSnmpInfo 를 참조하십시오
:icons: font
:imagesdir: ../media/


[role="lead"]
"GetSnmpInfo" 메서드를 사용하여 현재 SNMP(Simple Network Management Protocol) 구성 정보를 가져올 수 있습니다.



== 매개 변수


NOTE: GetSnmpInfo 는 Element 버전 8.0 이후 버전에서 사용되지 않습니다. 를 클릭합니다 xref:reference_element_api_getsnmpstate.adoc[GetSnmpState 를 선택합니다] 및 xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] 메서드는 GetSnmpInfo 메서드를 대체합니다.

이 메서드에는 입력 매개 변수가 없습니다.



== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
네트워크
 a| 
SNMP에 대해 활성화된 네트워크 및 액세스 유형 목록입니다. * 참고: * SNMP v3이 비활성화된 경우에만 네트워크가 표시됩니다.
 a| 
xref:reference_element_api_network_snmp.adoc[네트워크]



 a| 
활성화됨
 a| 
클러스터의 노드가 SNMP에 대해 구성되어 있는지 여부를 나타냅니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
snmpV3이 활성화되었습니다
 a| 
클러스터의 노드가 SNMP v3에 대해 구성된 경우 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
usmUsers(사용자)
 a| 
SNMP v3이 활성화된 경우 SNMP에 대한 사용자 액세스 매개 변수 목록이 클러스터에서 반환됩니다. 이 매개 변수는 networks 매개 변수 대신 반환됩니다.
 a| 
xref:reference_element_api_usmuser.adoc[usmUser(사용자)]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "GetSnmpInfo",
   "params": {},
   "id" : 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
   "id" : 1,
   "result" : {
      "enabled" : true,
      "networks" : [
         {
            "access" : "rosys",
            "cidr" : 0,
            "community" : "public",
            "network" : "localhost"
         }
      ]
   }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

* xref:reference_element_api_getsnmpstate.adoc[GetSnmpState 를 선택합니다]
* xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL]

