---
permalink: api/reference_element_api_fault.html 
sidebar: sidebar 
keywords: object,objects,fault 
summary: 장애 객체에는 클러스터에서 감지된 고장에 대한 정보가 포함되어 있습니다. ListClusterFats 메서드는 클러스터 오류 정보를 반환합니다. 
---
= 오류
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
장애 객체에는 클러스터에서 감지된 고장에 대한 정보가 포함되어 있습니다. ListClusterFats 메서드는 클러스터 오류 정보를 반환합니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
클러스터 오류 ID
 a| 
각 클러스터 장애와 관련된 고유 ID입니다.
 a| 
정수



 a| 
코드
 a| 
감지된 특정 고장에 대한 고장 코드입니다. 자세한 내용은 클러스터 오류 코드 를 참조하십시오.
 a| 
문자열



 a| 
데이터
 a| 
추가 고장 관련 정보
 a| 
JSON 개체



 a| 
날짜
 a| 
UTC + 0 형식의 현재 시간입니다.
 a| 
ISO 8601 문자열



 a| 
세부 정보
 a| 
고장에 대한 설명과 추가 세부 정보
 a| 
문자열



 a| 
드라이브 ID입니다
 a| 
드라이브 ID 목록의 첫 번째 드라이브 ID입니다. 드라이브 ID 목록이 비어 있는 경우(즉, 드라이브를 처리하는 장애가 반환되지 않은 경우) 이 값은 0입니다.
 a| 
정수



 a| 
드라이브 ID입니다
 a| 
이 결함이 참조하는 드라이브의 드라이브 ID 값 목록입니다. 드라이브 고장 시 포함됩니다. 없는 경우 빈 배열입니다.
 a| 
정수 배열



 a| 
노드 하드wareFaultID
 a| 
클러스터의 하드웨어 장애에 할당된 식별자입니다.
 a| 
정수



 a| 
노드 ID입니다
 a| 
이 장애가 참조하는 노드의 노드 ID입니다. 노드 및 드라이브 장애에 대해 포함되며, 그렇지 않으면 0으로 설정됩니다.
 a| 
정수



 a| 
간략 해제
 a| 
고장의 해결됨 상태. 가능한 값:

* 참: 고장이 더 이상 감지되지 않습니다.
* 거짓: 고장이 여전히 존재합니다.

 a| 
부울



 a| 
확인 날짜
 a| 
고장이 해결된 날짜 및 시간입니다.
 a| 
ISO 8601 문자열



 a| 
서비스 ID입니다
 a| 
오류와 관련된 서비스입니다. 장애가 서비스와 연결되지 않은 경우 이 값은 "0"(영)입니다.
 a| 
정수



 a| 
심각도입니다
 a| 
고장의 심각도입니다. 가능한 값:

* 경고: 경미한 문제 클러스터가 작동 중이고 이 심각도 수준에서 업그레이드가 허용됩니다.
* 오류: 일반적으로 서비스에 영향을 주지 않아야 하는 장애입니다(가능한 성능 저하 또는 HA 손실 제외). 일부 기능이 비활성화되었을 수 있습니다.
* 위험: 서비스에 영향을 주는 심각한 장애입니다. 시스템에서 API 요청 또는 클라이언트 I/O를 처리할 수 없으며 데이터가 손실될 위험이 있습니다.
* 모범 사례: 최적화되지 않은 시스템 구성으로 인해 발생한 고장

 a| 
문자열



 a| 
유형
 a| 
고장의 유형입니다. 가능한 값:

* 노드: 전체 노드에 영향을 주는 장애.
* 드라이브: 개별 드라이브에 영향을 주는 고장.
* 클러스터: 전체 클러스터에 영향을 주는 장애.
* 서비스: 클러스터의 서비스에 영향을 주는 장애.
* 볼륨: 개별 볼륨에 영향을 주는 장애.

 a| 
문자열

|===


== 자세한 내용을 확인하십시오

* xref:reference_element_api_listclusterfaults.adoc[ListClusterFats]
* link:../storage/reference_monitor_cluster_fault_codes.html["클러스터 고장 코드"]

