---
permalink: api/reference_element_api_clonevolume.html 
sidebar: sidebar 
keywords: volumes,volume,cloning,clone,CloneVolume 
summary: CloneVolume 메서드를 사용하여 볼륨의 복사본을 만들 수 있습니다. 이 메서드는 비동기식이며 완료하는 데 시간이 걸릴 수 있습니다. 
---
= CloneVolume(볼륨)
:icons: font
:imagesdir: ../media/


[role="lead"]
"CloneVolume" 방법을 사용하여 볼륨의 복사본을 만들 수 있습니다. 이 메서드는 비동기식이며 완료하는 데 시간이 걸릴 수 있습니다.

클론 생성 프로세스는 "CloneVolume" 요청을 할 때 즉시 시작되며 API 메소드가 실행될 때 볼륨의 상태를 나타냅니다. 를 사용할 수 있습니다 xref:reference_element_api_getasyncresult.adoc[GetAsyncResult 를 참조하십시오] 클론 생성 프로세스가 완료되고 새 볼륨을 연결에 사용할 수 있는 시기를 결정하는 방법입니다. 을 사용할 수 있습니다 xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs 를 선택합니다] 를 클릭하여 클론 생성 진행률을 표시합니다. 볼륨에 대한 초기 속성 및 서비스 품질 설정은 클론 생성 중인 볼륨에서 상속됩니다. 에서 이러한 설정을 변경할 수 있습니다 xref:reference_element_api_modifyvolume.adoc[ModifyVolume(수정 볼륨)].


NOTE: 클론 복제된 볼륨은 소스 볼륨에서 볼륨 액세스 그룹 구성원 자격을 상속하지 않습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
액세스
 a| 
새 볼륨에 대한 액세스가 허용됩니다. 값을 지정하지 않으면 액세스 값이 변경되지 않습니다. 가능한 값:

* "REadOnly": (선택 사항) 읽기 작업만 허용됩니다.
* 다시 쓰기: (선택 사항) 읽기와 쓰기가 허용됩니다.
* locked: (선택 사항) 읽기와 쓰기가 허용되지 않습니다. 지정하지 않으면 클론 생성 중인 볼륨의 액세스 값이 사용됩니다.
* "replicationTarget": (선택 사항) 페어링된 볼륨 세트의 타겟 볼륨으로 볼륨을 식별합니다. 볼륨이 페어링되지 않은 경우 액세스 상태가 잠깁니다.

 a| 
문자열
 a| 
없음
 a| 
아니요



 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
enable512e
 a| 
새 볼륨에서 512바이트 섹터 에뮬레이션을 사용할지 여부를 지정합니다. 지정하지 않으면 클론 생성 중인 볼륨의 설정이 사용됩니다.
 a| 
부울
 a| 
원래 볼륨의 설정
 a| 
아니요



 a| 
enableSnapMirrorReplication
 a| 
SnapMirror 엔드포인트에서 복제를 위해 볼륨을 사용할 수 있는지 여부를 결정합니다. 가능한 값:

* 참
* 거짓

 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
이름
 a| 
복제된 새 볼륨의 이름입니다. 길이는 1-64자여야 합니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
새 계정 ID
 a| 
새 볼륨의 소유자에 대한 계정 ID입니다. 지정되지 않은 경우 복제되는 볼륨의 소유자 계정 ID가 사용됩니다.
 a| 
정수
 a| 
원래 볼륨 소유자의 계정 ID입니다
 a| 
아니요



 a| 
새 크기
 a| 
볼륨의 새 크기(바이트)입니다. 복제되는 볼륨의 크기보다 크거나 작을 수 있습니다. 지정하지 않으면 볼륨 크기가 변경되지 않습니다. 크기는 가장 가까운 1MB로 반올림됩니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
스냅샷 ID입니다
 a| 
클론의 소스로 사용되는 스냅샷의 ID입니다. ID가 제공되지 않으면 현재 활성 볼륨이 사용됩니다.
 a| 
정수
 a| 
없음
 a| 
아니요



 a| 
볼륨 ID
 a| 
복제할 볼륨의 VolumeID입니다.
 a| 
정수
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
asyncHandle
 a| 
작업 결과를 얻는 데 사용되는 핸들 값입니다.
 a| 
정수



 a| 
cloneid(클론 ID)
 a| 
새로 복제된 볼륨의 cloneid입니다.
 a| 
정수



 a| 
곡선
 a| 
클론에 적용된 QoS 곡선 값입니다.
 a| 
JSON 개체



 a| 
볼륨
 a| 
새로 복제된 볼륨에 대한 정보가 포함된 개체입니다.
 a| 
xref:reference_element_api_volume.adoc[볼륨]



 a| 
볼륨 ID
 a| 
새로 복제된 볼륨의 VolumeID입니다.
 a| 
정수

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "CloneVolume",
   "params": {
      "volumeID" : 5,
      "name"  : "mysqldata-snapshot1",
      "access" : "readOnly"
   },
   "id" : 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
      "asyncHandle": 42,
      "cloneID": 37,
      "volume": {
          "access": "readOnly",
          "accountID": 1,
          "attributes": {},
          "blockSize": 4096,
          "createTime": "2016-03-31T22:26:03Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.mysqldata-snapshot1.680",
          "name": "mysqldata-snapshot1",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 100,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 50
          },
          "scsiEUIDeviceID": "6a796179000002a8f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a796179000002a8",
          "sliceCount": 0,
          "status": "init",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [],
          "volumeID": 680,
          "volumePairs": []
      },
      "volumeID": 680
  }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult 를 참조하십시오]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs 를 선택합니다]
* xref:reference_element_api_modifyvolume.adoc[ModifyVolume(수정 볼륨)]

