---
permalink: api/reference_element_api_breaksnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,volume,volumes,break,breaking,relationship,ONTAP 
summary: Element 웹 UI에서는 BreakSnapMirrorRelationship 메서드를 사용하여 SnapMirror 관계를 중단합니다. SnapMirror 관계가 손상되면 타겟 볼륨이 읽기/쓰기로 전환되어 소스에서 이탈할 수 있습니다. ResyncSnapMirrorRelationship API 메서드를 사용하여 관계를 다시 설정할 수 있습니다. 이 방법을 사용하려면 ONTAP 클러스터를 사용할 수 있어야 합니다. 
---
= BreakSnapMirrorRelationship을 참조하십시오
:icons: font
:imagesdir: ../media/


[role="lead"]
Element 웹 UI에서는 'BreakSnapMirrorRelationship' 메서드를 사용하여 SnapMirror 관계를 끊습니다. SnapMirror 관계가 손상되면 타겟 볼륨이 읽기/쓰기로 전환되어 소스에서 이탈할 수 있습니다. 'ResyncSnapMirrorRelationship' API 메소드를 사용하여 관계를 다시 설정할 수 있습니다. 이 방법을 사용하려면 ONTAP 클러스터를 사용할 수 있어야 합니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
snapMirrorEndpointID입니다
 a| 
Element 스토리지 클러스터와 통신하는 원격 ONTAP 스토리지 시스템의 끝점 ID입니다.
 a| 
정수
 a| 
없음
 a| 
예



 a| 
디스테이징 볼륨
 a| 
SnapMirror 관계의 대상 볼륨입니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===


| 이름 | 설명 | 유형 


 a| 
snapMirrorRelationship
 a| 
손상된 SnapMirror 관계에 대한 정보가 포함된 개체입니다.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== 버전 이후 새로운 기능

10.1



== 자세한 내용을 확인하십시오

xref:reference_element_api_breaksnapmirrorvolume.adoc[BreakSnapMirrorVolume을 참조하십시오]
