---
permalink: api/reference_element_api_getnodehardwareinfo.html 
sidebar: sidebar 
keywords: node,hardware,info,get,getting,getnodehardwareinfo 
summary: GetNodeHardwareInfo 메서드를 사용하여 지정된 노드의 모든 하드웨어 정보 및 상태를 반환할 수 있습니다. 여기에는 일반적으로 제조업체, 공급업체, 버전 및 기타 관련 하드웨어 식별 정보가 포함됩니다. 
---
= GetNodeHardwareInfo 를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
GetNodeHardwareInfo 메서드를 사용하면 지정된 노드의 모든 하드웨어 정보와 상태를 반환할 수 있습니다. 여기에는 일반적으로 제조업체, 공급업체, 버전 및 기타 관련 하드웨어 식별 정보가 포함됩니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
노드 ID입니다
 a| 
하드웨어 정보를 요청하는 노드의 ID입니다. Fibre Channel 노드를 지정하면 Fibre Channel 노드에 대한 정보가 반환됩니다.
 a| 
정수
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
노드 하드웨어 정보
 a| 
지정된 노드 ID에 대한 하드웨어 정보입니다. 이 출력의 각 개체는 지정된 노드의 노드 ID로 레이블이 지정됩니다.
 a| 
xref:reference_element_api_hardwareinfo.adoc[하드웨어 정보]

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "GetNodeHardwareInfo",
   "params": {
     "nodeID": 1
   },
"id" : 1
}
----


== 응답 예

이 응답 예제의 길이로 인해 보충 토픽에 문서화됩니다.



== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

xref:reference_element_api_response_example_getnodehardwareinfo_fibre_channel.adoc[GetNodeHardwareInfo(Fibre Channel 노드의 출력)]

xref:reference_element_api_response_example_getnodehardwareinfo.adoc[GetNodeHardwareInfo(iSCSI 출력)]
