---
permalink: api/reference_element_api_schedule.html 
sidebar: sidebar 
keywords: object,objects,schedule 
summary: 일정 오브젝트에는 볼륨의 스냅샷을 자율적으로 만들기 위해 생성된 스케줄에 대한 정보가 포함되어 있습니다. ListSchedules API 메서드를 사용하여 모든 스케줄에 대한 스케줄 정보를 검색할 수 있습니다. 
---
= 스케줄
:icons: font
:imagesdir: ../media/


[role="lead"]
일정 오브젝트에는 볼륨의 스냅샷을 자율적으로 만들기 위해 생성된 스케줄에 대한 정보가 포함되어 있습니다. 'ListSchedules' API 메소드를 사용하여 모든 스케줄에 대한 스케줄 정보를 검색할 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
일정 발생 빈도를 나타냅니다. 가능한 값:

* 요일
* 월 일
* 시간 간격

 a| 
JSON 개체



 a| 
haserror입니다
 a| 
일정에 오류가 있는지 여부를 나타냅니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
시간
 a| 
다음 스냅샷이 생성되기 전에 경과되는 시간을 표시합니다. 가능한 값은 0 ~ 24입니다.
 a| 
정수



 a| 
마지막 실행 상태
 a| 
마지막으로 예약된 스냅샷의 상태를 나타냅니다. 가능한 값:

* 성공
* 실패했습니다

 a| 
문자열



 a| 
마지막 실행 시간 시작
 a| 
스케줄이 마지막으로 시작된 시간을 나타냅니다.
 a| 
ISO 8601 날짜 문자열



 a| 
분
 a| 
다음 스냅샷이 생성되기 전에 경과되는 분을 표시합니다. 가능한 값은 0에서 59 사이입니다.
 a| 
정수



 a| 
몬트데이즈입니다
 a| 
스냅샷이 생성될 월을 나타냅니다.
 a| 
스토리지



 a| 
일시 중지되었습니다
 a| 
스케줄이 일시 중지되었는지 여부를 나타냅니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
반복
 a| 
일정이 반복되는지 여부를 나타냅니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
RunNextInterval 을 선택합니다
 a| 
스케줄러가 다음에 활성화될 때 스케줄이 실행될지 여부를 나타냅니다. true이면 스케줄러가 다음에 활성화될 때 스케줄이 실행된 다음 이 값이 false로 다시 설정됩니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
예약 ID입니다
 a| 
스케줄의 고유 ID입니다.
 a| 
정수



 a| 
예약 정보
 a| 
스케줄에 지정된 고유한 이름, 생성된 스냅샷의 보존 기간 및 스냅샷이 생성된 볼륨의 볼륨 ID가 포함됩니다.
 a| 
JSON 개체



 a| 
예약 이름
 a| 
일정에 할당된 고유한 이름입니다.
 a| 
문자열



 a| 
일정 유형
 a| 
현재 스냅샷의 스케줄 유형만 지원됩니다.
 a| 
문자열



 a| 
snapMirrorLabel
 a| 
예약 정보에 포함된 생성된 스냅숏 또는 그룹 스냅숏에 적용할 스냅 대칭 레이블입니다. 설정되지 않은 경우 이 값은 null입니다.
 a| 
문자열



 a| 
시작 날짜
 a| 
일정이 처음 시작되거나 시작될 날짜를 나타냅니다(UTC 시간 형식).
 a| 
ISO 8601 날짜 문자열



 a| 
삭제
 a| 
스케줄이 삭제되도록 표시되었는지 여부를 나타냅니다. 가능한 값:

* 참
* 거짓

 a| 
부울



 a| 
평일
 a| 
스냅샷이 생성될 요일을 나타냅니다.
 a| 
스토리지

|===


== 자세한 내용을 확인하십시오

xref:reference_element_api_listschedules.adoc[ListSchedules(일정 목록]
