---
permalink: api/reference_element_api_testnetworkconfig.html 
sidebar: sidebar 
keywords: test,testing,network,config,configuration,testnetworkconfig 
summary: TestNetworkConfig 메서드를 사용하여 구성된 네트워크 설정이 시스템에서 사용 중인 네트워크 설정과 일치하는지 테스트할 수 있습니다. 
---
= TestNetworkConfig를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
TestNetworkConfig 메서드를 사용하면 구성된 네트워크 설정이 시스템에서 사용 중인 네트워크 설정과 일치하는지 테스트할 수 있습니다.



== 매개 변수

SetNetworkConfig 메서드를 사용하여 노드를 구성하면 UI 또는 TUI에서 구성이 검증되고 저장됩니다. TestNetworkConfig API 테스트에서는 유효성 검사 후 로직에 저장된 구성을 사용합니다. 예를 들어 정전이 발생하거나 네트워크에 장애가 발생한 경우 이 API 메서드를 사용하여 노드가 가장 현재 저장된 네트워크 구성으로 실행되고 있는지 확인할 수 있습니다. 이렇게 하면 구성에 오류가 없고 현재 구성이 사용 중인 것을 확인할 수 있습니다.

이 테스트는 응답 출력에 실패만 표시하도록 설계되었습니다. 오류가 없으면 이 테스트에서는 출력을 반환하지 않습니다. 다음 응답 예를 참조하십시오.

이 메서드에는 입력 매개 변수가 없습니다.



== 반환 값

이 메서드의 반환 값은 다음과 같습니다.

|===
| 이름 | 설명 | 유형 


 a| 
세부 정보
 a| 
실행 중인 네트워크 구성을 사용하여 현재 저장된 네트워크 설정을 검증할 때 발견된 오류가 포함되어 있습니다.
 a| 
JSON 개체

|===


== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "TestNetworkConfig",
   "params": {},
   "id" : 1
}
----


== 응답 예 1

오류가 발견되지 않으면 응답이 반환되지 않습니다.

[listing]
----
{
   "id" : 1,
   "result": {
   "details": {
   "network": {...}
  },
   "duration": "00:00:00.144514",
   "result": "Passed"
  }
}
----


== 응답 예 2

MTU 불일치 예

[listing]
----
{
  "id" : 1,
  "result":
  {
	 "details" :
	 {
		"error":
		{
		   "message" : "Network configuration mismatch on Bond10G: Incorrect MTU expectedMTU=[1500]  actualMTU=[9600]", name: "xAssertionFailure"
		}
	 },
	 "duration": "0.125213sec",
	 "result": "Failed"
  }
}
----


== 응답 예 3

누락된 정적 라우트의 예

[listing]
----
{
  "id": 1,
  "result":
  {
	 "details" :
	 {
	 "error":
		{
		"message" : "Network configuration mismatch on Bond1G: Routing table missing route=[192.168.137.2 via 192.168.159.254 dev Bond1G]", name: "xAssertionFailure"
		}
	 },
	 "duration" : "0.128547sec",
	 "result" : "Failed"
  }
}
----


== 버전 이후 새로운 기능

9.6



== 자세한 내용을 확인하십시오

xref:reference_element_api_setnetworkconfig.adoc[SetNetworkConfig]
