---
permalink: api/reference_element_api_clusterinfo.html 
sidebar: sidebar 
keywords: element, api, object, objects, clusterInfo 
summary: clusterInfo 객체에는 노드가 클러스터와 통신하는 데 사용하는 정보가 포함되어 있습니다. GetClusterInfo API 메서드를 사용하면 이 정보를 얻을 수 있습니다. 
---
= 클러스터 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clusterInfo 객체에는 노드가 클러스터와 통신하는 데 사용하는 정보가 포함되어 있습니다. GetClusterInfo API 메서드를 사용하면 이 정보를 얻을 수 있습니다.



== 개체 멤버

이 개체에는 다음 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체



 a| 
defaultProtectionScheme 을 참조하십시오
 a| 
에 보호 체계가 제공되지 않은 경우 새 볼륨에 기본적으로 사용되는 보호 스키마입니다 xref:reference_element_api_createvolume.adoc[CreateVolume(생성 볼륨)] 메서드 호출. 이 보호 스키마는 항상 설정된 보호 체계 세트에 있어야 합니다.
 a| 
문자열



 a| 
enabledProtectionSchemes 를 참조하십시오
 a| 
이 스토리지 클러스터에서 사용하도록 설정된 모든 보호 구성 목록
 a| 
문자열 배열



 a| 
encryptionAtRestState 를 참조하십시오
 a| 
저장된 암호화 기능의 상태입니다. 가능한 값:

* 활성화: 저장된 암호화 사용 중입니다.
* Enabled(활성화): 저장된 데이터 암호화가 활성화됩니다.
* 해제: 저장된 암호화 사용 안 함.
* Disabled(비활성화): 저장된 데이터 암호화가 비활성화됩니다.

 a| 
문자열



 a| 
앙상블
 a| 
클러스터에 사용되는 노드입니다.
 a| 
문자열 배열



 a| 
진동
 a| 
관리 네트워크에서 클러스터의 부동(가상) IP 주소입니다.
 a| 
문자열



 a| 
mvipInterface를 참조하십시오
 a| 
MVIP 주소와 연결된 물리적 인터페이스입니다.
 a| 
문자열



 a| 
mvipNodeID입니다
 a| 
마스터 MVIP 주소가 있는 노드입니다.
 a| 
정수



 a| 
mvipVlanTag
 a| 
MVIP 주소에 대한 VLAN 식별자입니다.
 a| 
문자열



 a| 
이름
 a| 
고유한 클러스터 이름입니다.
 a| 
문자열



 a| 
repCount
 a| 
클러스터에 저장할 각 데이터의 복제본 수입니다. 유효한 값은 "2"입니다.
 a| 
정수



 a| 
소프트웨어암호화 아트레이스상태
 a| 
유휴 상태의 소프트웨어 기반 암호화.
 a| 
문자열



 a| 
supportedProtectionSchemes 를 참조하십시오
 a| 
이 스토리지 클러스터에서 지원되는 모든 보호 구성 목록
 a| 
문자열 배열



 a| 
비프
 a| 
스토리지(iSCSI) 네트워크에서 클러스터의 부동(가상) IP 주소입니다.
 a| 
문자열



 a| 
SvipInterface 를 참조하십시오
 a| 
마스터 SVIP 주소와 연결된 물리적 인터페이스입니다.
 a| 
문자열



 a| 
비노드 ID입니다
 a| 
마스터 SVIP 주소가 있는 노드입니다.
 a| 
정수



 a| 
SvipVlanTag를 참조하십시오
 a| 
마스터 SVIP 주소의 VLAN 식별자입니다.
 a| 
문자열



 a| 
UniqueID를 선택합니다
 a| 
클러스터의 고유 ID입니다.
 a| 
문자열



 a| 
UUID입니다
 a| 
클러스터의 고유 식별자입니다.
 a| 
UUID입니다

|===
[discrete]
== 자세한 내용을 확인하십시오

* link:../api/reference_element_api_getclusterinfo.html["GetClusterInfo 를 참조하십시오"]
* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 리소스 페이지 를 참조하십시오"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

