---
permalink: api/reference_element_api_removenodes.html 
sidebar: sidebar 
keywords: node,nodes,cluster,remove,removing,removenodes 
summary: RemoveNodes를 사용하여 더 이상 클러스터에 참여하지 않아야 하는 노드를 하나 이상 제거할 수 있습니다. 
---
= 노드 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RemoveNodes를 사용하여 더 이상 클러스터에 참여하지 않아야 하는 노드를 하나 이상 제거할 수 있습니다.

노드를 제거하기 전에 "RemoveDrives" 메서드를 사용하여 노드에 포함된 모든 드라이브를 제거해야 합니다. 'RemoveDrives' 프로세스가 완료되고 모든 데이터가 노드에서 마이그레이션될 때까지 노드를 제거할 수 없습니다. 노드를 제거하면 해당 노드가 보류 중인 노드로 등록됩니다. 노드를 다시 추가하거나 종료할 수 있습니다. 노드를 종료하면 보류 중인 노드 목록에서 제거됩니다.



== 클러스터 마스터 노드 제거

'RemoveNodes'를 사용하여 클러스터 마스터 노드를 제거하면 응답을 반환하기 전에 메서드가 시간 초과될 수 있습니다. 메서드 호출이 노드를 제거하지 못한 경우 메서드를 다시 호출합니다. 다른 노드와 함께 클러스터 마스터 노드를 제거하는 경우 별도의 호출을 사용하여 클러스터 마스터 노드를 직접 제거해야 합니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
IgnorEnsembleToleranceChange 를 참조하십시오
 a| 
노드를 제거할 때 앙상블의 노드 오류 허용치 변경 내용을 무시합니다.

스토리지 클러스터에서 다중 노드 장애를 허용하는 데이터 보호 체계를 사용하고 노드를 제거하면 앙상블의 노드 장애 허용 범위가 감소하지만 일반적으로 노드 제거는 오류와 함께 실패합니다. 이 매개 변수를 true 로 설정하면 노드를 제거할 수 있도록 앙상블 공차 검사를 비활성화할 수 있습니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
노드
 a| 
제거할 노드의 NodeID 목록입니다.
 a| 
정수 배열
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "RemoveNodes",
   "params": {
     "nodes"  : [3,4,5]
   },
   "id" : 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
  "id" : 1
  "result" : {},
}
----


== 버전 이후 새로운 기능

9.6
