---
permalink: api/reference_element_api_createcluster.html 
sidebar: sidebar 
keywords: CreateCluster,cluster,create,creating,initialize,initializing 
summary: 'CreateCluster 메서드를 사용하여 "mvip" 및 "svip" 주소의 소유권이 있는 클러스터의 노드를 초기화할 수 있습니다. 각 새 클러스터는 클러스터의 첫 번째 노드의 관리 IP\(MIP\)를 사용하여 초기화됩니다. 이 방법은 또한 클러스터에 구성되어 있는 모든 노드를 자동으로 추가합니다. 새 클러스터가 초기화될 때마다 이 방법을 한 번만 사용하면 됩니다.' 
---
= 클러스터 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"CreateCluster" 메서드를 사용하여 "mvip" 및 "svip" 주소의 소유권이 있는 클러스터의 노드를 초기화할 수 있습니다. 각 새 클러스터는 클러스터의 첫 번째 노드의 MIP(관리 IP)를 사용하여 초기화됩니다. 이 방법은 또한 클러스터에 구성되어 있는 모든 노드를 자동으로 추가합니다. 새 클러스터가 초기화될 때마다 이 방법을 한 번만 사용하면 됩니다.


NOTE: 클러스터의 마스터 노드에 로그인하고 를 실행한 후 xref:reference_element_api_getbootstrapconfig.adoc[GetBootStrapConfig 를 참조하십시오] 방법 클러스터에 포함할 나머지 노드의 IP 주소를 가져오려면 클러스터의 마스터 노드에 대해 CreateCluster 메서드를 실행할 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
허용 가능한 샛길
 a| 
이 클러스터를 생성할 때 최종 사용자 라이센스 계약에 동의함을 표시하십시오. EULA에 동의하려면 이 매개변수를 TRUE로 설정하십시오.
 a| 
부울
 a| 
없음
 a| 
예



 a| 
속성
 a| 
JSON 개체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 개체
 a| 
없음
 a| 
아니요



 a| 
enableSoftwareEncryptionAtRest
 a| 
이 매개 변수를 사용하여 유휴 상태의 소프트웨어 기반 암호화를 사용합니다. 모든 클러스터에서 기본값은 false 입니다. 유휴 소프트웨어 암호화가 활성화된 후에는 클러스터에서 비활성화할 수 없습니다.
 a| 
부울
 a| 
참
 a| 
아니요



 a| 
진동
 a| 
관리 네트워크의 클러스터에 대한 유동(가상) IP 주소입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
노드
 a| 
클러스터를 구성하는 초기 노드 집합의 CIP/SIP 주소입니다. 이 노드의 IP가 목록에 있어야 합니다.
 a| 
문자열 배열
 a| 
없음
 a| 
예



 a| 
주문 번호
 a| 
영숫자 판매 주문 번호입니다. 소프트웨어 기반 플랫폼에 필요
 a| 
문자열
 a| 
없음
 a| 
아니요(하드웨어 기반 플랫폼)

지원(소프트웨어 기반 플랫폼)



 a| 
암호
 a| 
클러스터 admin 계정의 초기 암호입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
일련 번호
 a| 
9자리 영숫자 일련 번호입니다. 소프트웨어 기반 플랫폼에 필요할 수 있습니다.
 a| 
문자열
 a| 
없음
 a| 
아니요(하드웨어 기반 플랫폼)

지원(소프트웨어 기반 플랫폼)



 a| 
비프
 a| 
스토리지(iSCSI) 네트워크에서 클러스터의 부동(가상) IP 주소입니다.
 a| 
문자열
 a| 
없음
 a| 
예



 a| 
사용자 이름
 a| 
클러스터 관리자의 사용자 이름입니다.
 a| 
문자열
 a| 
없음
 a| 
예

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
  "method": "CreateCluster",
  "params": {
    "acceptEula": true,
    "mvip": "10.0.3.1",
    "svip": "10.0.4.1",
    "username": "Admin1",
    "password": "9R7ka4rEPa2uREtE",
    "attributes": {
      "clusteraccountnumber": "axdf323456"
    },
    "nodes": [
      "10.0.2.1",
      "10.0.2.2",
      "10.0.2.3",
      "10.0.2.4"
    ]
  },
  "id": 1
}
----


== 응답 예

이 메서드는 다음 예제와 유사한 응답을 반환합니다.

[listing]
----
{
"id" : 1,
"result" : {}
}
----


== 버전 이후 새로운 기능

9.6

[discrete]
== 자세한 내용을 확인하십시오

* link:reference_element_api_getbootstrapconfig.html["GetBootstrapConfig 를 참조하십시오"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

