---
permalink: api/reference_element_api_enableencryptionatrest.html 
sidebar: sidebar 
keywords: encryption,enable,enabling,EnableEncryptionAtRest 
summary: 'EnableEncryptionAtRest 메서드를 사용하면 클러스터의 유휴 데이터에 AES(Advanced Encryption Standard) 256비트 암호화를 설정하여 클러스터에서 각 노드의 드라이브에 사용되는 암호화 키를 관리할 수 있습니다. 이 기능은 기본적으로 사용되지 않습니다.' 
---
= EnableEncryptionAtRest 를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터에서 각 노드의 드라이브에 사용되는 암호화 키를 관리할 수 있도록 "EnableEncryptionAtRest" 방법을 사용하여 클러스터의 유휴 상태에서 AES(Advanced Encryption Standard) 256비트 암호화를 활성화할 수 있습니다. 이 기능은 기본적으로 사용되지 않습니다.


TIP: 유휴 상태의 암호화 및/또는 클러스터의 유휴 상태의 소프트웨어 암호화를 확인하려면 를 사용합니다 link:../api/reference_element_api_getclusterinfo["클러스터 정보 확인 방법을 참조하십시오"^]. 'GetSoftwareEncryptionAtRestInfo'를 사용할 수 있습니다 link:../api/reference_element_api_getsoftwareencryptionatrestinfo["클러스터에서 유휴 데이터를 암호화하는 데 사용하는 정보를 가져오는 방법입니다"^].


NOTE: 이 방법은 저장된 소프트웨어 암호화를 사용하지 않습니다. 이 작업은 를 통해서만 수행할 수 있습니다 link:../api/reference_element_api_createcluster.html["클러스터 생성 방법"^] enableSoftwareEncryptionAtRest가 true로 설정되어 있습니다.

유휴 데이터 암호화를 설정하면 클러스터에서 각 노드의 드라이브에 대한 암호화 키가 내부적으로 자동으로 관리됩니다.

keyProviderID 를 지정하면 키 공급자 유형에 따라 암호가 생성되고 검색됩니다. 이는 일반적으로 KMIP 키 공급자의 경우 KMIP(Key Management Interoperability Protocol) 키 서버를 사용하여 수행됩니다. 이 작업 후에는 지정된 공급자가 활성화된 것으로 간주되므로 "disableEncryptionAtRest" 메서드를 사용하여 저장된 암호화 기능을 해제할 때까지 삭제할 수 없습니다.


NOTE: 모델 번호가 "-NE"로 끝나는 노드 형식이 있는 경우 "EnableEncryptionAtRest" 메서드 호출이 실패하고 "Encryption not allowed"라는 응답이 표시됩니다. 클러스터에서 암호화할 수 없는 노드가 감지되었습니다."


NOTE: 클러스터가 실행 중이고 양호한 상태인 경우에만 암호화를 사용하거나 사용하지 않도록 설정해야 합니다. 필요에 따라 원하는 빈도로 암호화를 활성화 또는 비활성화할 수 있습니다.


NOTE: 이 프로세스는 비동기식이며 암호화를 사용하기 전에 응답을 반환합니다. GetClusterInfo 메서드를 사용하면 프로세스가 완료된 시점을 확인하기 위해 시스템을 폴링할 수 있습니다.



== 매개 변수

이 메서드에는 다음과 같은 입력 매개 변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수 요소입니다 


 a| 
KeyProviderID를 입력합니다
 a| 
KMIP 키 공급자의 ID입니다.
 a| 
정수
 a| 
없음
 a| 
아니요

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예

이 메서드에 대한 요청은 다음 예제와 비슷합니다.

[listing]
----
{
   "method": "EnableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== 답변 예

이 메서드는 EnableEncryptionAtRest 메서드에서 다음 예제와 유사한 응답을 반환합니다. 보고할 결과가 없습니다.

[listing]
----
{
   "id": 1,
   "result": {}
}
----
클러스터에서 저장된 암호화 기능을 사용하는 동안 GetClusterInfo 는 저장된 암호화("encryptionAtRestState") 상태를 "enabled"로 설명하는 결과를 반환합니다. 저장된 데이터 암호화가 완전히 활성화되면 반환된 상태가 "활성화됨"으로 변경됩니다.

[listing]
----
{
   "id": 1,
      "result": {
         "clusterInfo": {
            "attributes": { },
               "encryptionAtRestState": "enabling",
            "ensemble": [
               "10.10.5.94",
               "10.10.5.107",
               "10.10.5.108"
            ],
            "mvip": "192.168.138.209",
            "mvipNodeID": 1,
            "name": "Marshall",
            "repCount": 2,
            "svip": "10.10.7.209",
            "svipNodeID": 1,
            "uniqueID": "91dt"
      }
   }
}
----


== 버전 이후 새로운 기능

9.6

[discrete]
== 자세한 내용을 확인하십시오

* link:reference_element_api_secureerasedrives.html["SecureEraseDrives"]
* link:reference_element_api_getclusterinfo.html["GetClusterInfo 를 참조하십시오"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 설명서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["이전 버전의 NetApp SolidFire 및 Element 제품에 대한 문서"^]

